// GENERATED by lamella-bsp-gen from csp/rp2040/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Rp2040Instances
    {
        private Rp2040Instances() { }

        public const uint XOSC_BASE = 0x40024000;
        public const uint CLOCKS_BASE = 0x40008000;
        public const uint RESETS_BASE = 0x4000C000;
        public const uint RESETS_CLR_BASE = 0x4000F000;
        public const uint IO_BANK0_BASE = 0x40014000;
        public const uint IO_BANK0_RESET_BIT = 5;
        public const uint IO_BANK0_RESET_MASK = 0x20;
        public const uint PADS_BANK0_BASE = 0x4001C000;
        public const uint PADS_BANK0_RESET_BIT = 8;
        public const uint PADS_BANK0_RESET_MASK = 0x100;
        public const uint PLL_SYS_BASE = 0x40028000;
        public const uint PLL_SYS_RESET_BIT = 12;
        public const uint PLL_SYS_RESET_MASK = 0x1000;
        public const uint PLL_USB_BASE = 0x4002C000;
        public const uint PLL_USB_RESET_BIT = 13;
        public const uint PLL_USB_RESET_MASK = 0x2000;
        public const uint UART0_BASE = 0x40034000;
        public const uint UART0_RESET_BIT = 22;
        public const uint UART0_RESET_MASK = 0x400000;
        public const uint SIO_BASE = 0xD0000000;
    }
}
