// GENERATED by lamella-bsp-gen from bsp/mkr1000/board.toml + csp/atsamw25/module.toml + csp/samd21/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Mkr1000Bindings
    {
        private Mkr1000Bindings() { }

        public const int BOARD_MODEL = 9;

        public const uint WINC_RESET_N_PORT_BASE = 0x41004400;
        public const uint WINC_RESET_N_PIN = 27;
        public const uint WINC_RESET_N_MASK = 0x8000000;
        public const uint WINC_RESET_N_ACTIVE_LOW = 1;
        public const uint WINC_CHIP_EN_PORT_BASE = 0x41004400;
        public const uint WINC_CHIP_EN_PIN = 28;
        public const uint WINC_CHIP_EN_MASK = 0x10000000;
        public const uint WINC_CHIP_EN_ACTIVE_LOW = 0;
        public const uint WINC_IRQN_PORT_BASE = 0x41004480;
        public const uint WINC_IRQN_PIN = 9;
        public const uint WINC_IRQN_MASK = 0x200;
        public const uint WINC_IRQN_ACTIVE_LOW = 1;
    }
}
