# GENERATED by lamella-bsp-gen from bsp/nucleo-f091rc/board.toml + csp/stm32f091/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32f091

BOARD = "nucleo-f091rc"
BOARD_MODEL = 7
BOARD_VENDOR = "St"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
VCP = "vcp"

CARRIER = {
    "kind": "stlink-vcp",
    "role": "vcp",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
    "vcp": {
        "kind": "uart",
        "driver_family": "stm32f091-usart",
        "instance": "usart2",
        "base": 0x40004400,
        "rcc_en_reg": 0x4002101C,
        "rcc_en_mask": 0x20000,
        "pclk_hz": 8000000,
        "tx_port_rcc_en_reg": 0x40021014,
        "tx_port_rcc_en_mask": 0x20000,
        "tx_moder_reg": 0x48000000,
        "tx_moder_mask": 0x30,
        "tx_moder_value": 0x20,
        "tx_afr_reg": 0x48000020,
        "tx_afr_mask": 0xF00,
        "tx_afr_value": 0x100,
        "rx_port_rcc_en_reg": 0x40021014,
        "rx_port_rcc_en_mask": 0x20000,
        "rx_moder_reg": 0x48000000,
        "rx_moder_mask": 0xC0,
        "rx_moder_value": 0x80,
        "rx_afr_reg": 0x48000020,
        "rx_afr_mask": 0xF000,
        "rx_afr_value": 0x1000,
        "brr_115200_hsi_8mhz": 0x45,
    },
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Bases only: register offsets and bit encodings belong to the driver that knows the block.
INSTANCES = {
    "usart2": {"block": "usart", "base": 0x40004400, "rcc_en_off": 0x1C, "rcc_en_bit": 0x11},
    "gpioa": {"block": "gpio", "base": 0x48000000, "rcc_en_off": 0x14, "rcc_en_bit": 0x11},
    "rcc": {"block": "rcc", "base": 0x40021000},
    "gpioc": {"block": "gpio", "base": 0x48000800, "rcc_en_off": 0x14, "rcc_en_bit": 0x13},
    "gpiod": {"block": "gpio", "base": 0x48000C00, "rcc_en_off": 0x14, "rcc_en_bit": 0x14},
    "gpioe": {"block": "gpio", "base": 0x48001000, "rcc_en_off": 0x14, "rcc_en_bit": 0x15},
    "gpiof": {"block": "gpio", "base": 0x48001400, "rcc_en_off": 0x14, "rcc_en_bit": 0x16},
}

PLANS = {
    "hsi-8mhz": {"default": True, "source": "hsi", "hsi_hz": 8000000, "pclk_hz": 8000000},
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
}
