// GENERATED by lamella-bsp-gen from bsp/muselab-nano-ch32v003/board.toml + csp/ch32v003/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ch32v003
//
// The muselab-nano-ch32v003 board bindings (resolved against the ch32v003 chip strata): every value below is a
// generation-time literal derived from the strata -- role descriptors, module control
// lines, and the carrier identity. The board's facts are stated in board.toml.
namespace Lamella.Generated
{
    public sealed class MuselabNanoCh32v003Bindings
    {
        private MuselabNanoCh32v003Bindings() { }

        // -- identity --
        public const int BOARD_MODEL = 23;
        public const string BOARD_VENDOR = "Muselab";
        public const uint DEVICE_COUNT = 1;

        // -- on-board devices: PORT group base + pin index + mask --
        public const uint LED_PORT_BASE = 0x40011400;
        public const uint LED_PIN = 6;
        public const uint LED_BANK = 0;
        public const uint LED_MASK = 0x40;
        public const uint LED_ACTIVE_LOW = 0;
    }
}
