// GENERATED by lamella-bsp-gen from ext/atwinc1500-xpro/extension.toml + ext/standards/xplained-pro.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Atwinc1500XproExtension
    {
        private Atwinc1500XproExtension() { }
        public const string EXTENSION = "atwinc1500-xpro";
        public const string VENDOR = "microchip";
        public const string STANDARD = "xplained-pro";

        /// -- the kit identifier its identification chip carries, as the `nnnn` field of an
        /// `nnnnrrssssssssss` serial. It is how a FITTED extension can be told from an assumed
        /// one -- but on a kit with an embedded debugger the identification line reaches the
        /// DEBUGGER rather than an MCU pad, so this is a host tool's reading and not a
        /// program's --
        public const uint KIT_IDENTIFIER = 2442;

        /// -- what this board needs a host socket to bring out. Each POSITION is the connector
        /// standard's own name for a hole, never a pad: this file cannot name a pad, because it does
        /// not know which host it is plugged into. A host's `CONNECTOR_<socket>_<POSITION>_*`
        /// constants carry the pad behind each one, and the two are joined on the position name --
        public const uint POSITION_COUNT = 10;
        public const uint POSITION_SPI_SS_A_PIN = 15;
        public const uint POSITION_SPI_MOSI_PIN = 16;
        public const uint POSITION_SPI_MISO_PIN = 17;
        public const uint POSITION_SPI_SCK_PIN = 18;
        public const uint POSITION_I2C_SDA_PIN = 11;
        public const uint POSITION_I2C_SCL_PIN = 12;
        public const uint POSITION_GPIO1_PIN = 5;
        public const uint POSITION_GPIO2_PIN = 6;
        public const uint POSITION_SPI_SS_B_PIN = 10;
        public const uint POSITION_IRQ_PIN = 9;

        /// -- the buses this board presents, each naming the socket positions it rides. A host
        /// resolves them through the same socket constants; which of its controllers is behind
        /// them is the HOST's fact and appears nowhere here --
        public const uint BUS_COUNT = 2;
        public const string BUS_WINC_SPI_KIND = "spi";
        public const string BUS_WINC_SPI_SS = "spi_ss_a";
        public const string BUS_WINC_SPI_MOSI = "spi_mosi";
        public const string BUS_WINC_SPI_MISO = "spi_miso";
        public const string BUS_WINC_SPI_SCK = "spi_sck";
        public const string BUS_WINC_DEBUG_I2C_KIND = "i2c";
        public const string BUS_WINC_DEBUG_I2C_SDA = "i2c_sda";
        public const string BUS_WINC_DEBUG_I2C_SCL = "i2c_scl";

        /// -- the devices a host reaches. A LINE-wired device names the socket position it sits on
        /// and its active level; a BUS-wired one names the bus and, where a document states one, its
        /// address. An active level of `unknown` is a document that does not say, recorded as such:
        /// no polarity constant is emitted for it, so a program that assumed one fails to compile --
        public const uint DEVICE_COUNT = 6;
        public const string DEVICE_RESET_N_KIND = "gpio-out";
        public const string DEVICE_RESET_N_POSITION = "gpio1";
        public const uint DEVICE_RESET_N_ACTIVE_LOW = 1;
        public const string DEVICE_WAKE_KIND = "gpio-out";
        public const string DEVICE_WAKE_POSITION = "gpio2";
        public const uint DEVICE_WAKE_ACTIVE_LOW = 0;
        public const string DEVICE_CHIP_EN_KIND = "gpio-out";
        public const string DEVICE_CHIP_EN_POSITION = "spi_ss_b";
        public const uint DEVICE_CHIP_EN_ACTIVE_LOW = 0;
        public const string DEVICE_IRQ_N_KIND = "gpio-in";
        public const string DEVICE_IRQ_N_POSITION = "irq";
        public const string DEVICE_RADIO_KIND = "spi-device";
        public const string DEVICE_RADIO_BUS = "winc-spi";
        public const string DEVICE_RADIO_PART = "atwinc15x0-mr210xb";
        public const string DEVICE_CRYPTO_KIND = "i2c-device";
        public const string DEVICE_CRYPTO_BUS = "winc-debug-i2c";
        public const string DEVICE_CRYPTO_PART = "atecc508a";
        public const uint DEVICE_CRYPTO_ADDRESS = 0x60;
    }
}
