// GENERATED by lamella-bsp-gen from bsp/rpi-pico2-w/board.toml + csp/rp2350/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//
// The rpi-pico2-w board bindings as Swift constants: every value below is a generation-time literal
// derived from the strata. The board's facts are stated in board.toml.

public enum RpiPico2WBindings {
    // -- identity --
    public static let BOARD_MODEL: UInt16 = 10
    public static let BOARD_VENDOR: String = "RaspberryPi"

    /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
    /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
    /// peripherals of the same kind can share no register at all, so a consumer that selects a
    /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
    /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
    /// name a driver; and a uart is a different register map on every family, so the kind does
    /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
    public static let UART0_DRIVER_FAMILY: String = "rp2350-uart"
    public static let SPI0_DRIVER_FAMILY: String = "rp2350-spi"
    public static let I2C0_DRIVER_FAMILY: String = "rp2350-i2c"
    public static let ADC_DRIVER_FAMILY: String = "rp2350-adc"
    public static let PWM1_DRIVER_FAMILY: String = "rp2350-pwm"
    public static let PWM2_DRIVER_FAMILY: String = "rp2350-pwm"
    public static let PWM3_DRIVER_FAMILY: String = "rp2350-pwm"
    public static let PWM4_DRIVER_FAMILY: String = "rp2350-pwm"
    public static let PWM5_DRIVER_FAMILY: String = "rp2350-pwm"
    public static let PWM6_DRIVER_FAMILY: String = "rp2350-pwm"
    public static let PWM7_DRIVER_FAMILY: String = "rp2350-pwm"

    // -- UART0: a pl011 uart binding descriptor --
    public static let UART0_BASE: UInt32 = 0x40070000
    public static let UART0_RESET_MASK: UInt32 = 0x4000240
    public static let UART0_IO_TX_CTRL: UInt32 = 0x40028004
    public static let UART0_IO_RX_CTRL: UInt32 = 0x4002800C
    public static let UART0_PADS_TX: UInt32 = 0x40038004
    public static let UART0_PADS_RX: UInt32 = 0x40038008
    public static let UART0_FUNCSEL: UInt32 = 2
    public static let UART0_CLK_PERI_HZ: UInt32 = 12000000
    public static let UART0_IBRD_115200_PLL_150_48: UInt32 = 6
    public static let UART0_FBRD_115200_PLL_150_48: UInt32 = 33

    // -- SPI0: a pl022 spi binding descriptor (rate = a runtime configuration
    // choice from SSPCLK -- no divisor emits) --
    public static let SPI0_BASE: UInt32 = 0x40080000
    public static let SPI0_RESET_MASK: UInt32 = 0x40240
    public static let SPI0_IO_MISO_CTRL: UInt32 = 0x40028084
    public static let SPI0_PADS_MISO: UInt32 = 0x40038044
    public static let SPI0_IO_CS_CTRL: UInt32 = 0x4002808C
    public static let SPI0_PADS_CS: UInt32 = 0x40038048
    public static let SPI0_IO_SCK_CTRL: UInt32 = 0x40028094
    public static let SPI0_PADS_SCK: UInt32 = 0x4003804C
    public static let SPI0_IO_MOSI_CTRL: UInt32 = 0x4002809C
    public static let SPI0_PADS_MOSI: UInt32 = 0x40038050
    public static let SPI0_FUNCSEL: UInt32 = 1
    public static let SPI0_SSPCLK_HZ: UInt32 = 12000000

    // -- I2C0: a dw-i2c binding descriptor (ic_clk = clk_sys on this chip; the
    // SCL count formulas stay driver math per the official pico-sdk driver) --
    public static let I2C0_BASE: UInt32 = 0x40090000
    public static let I2C0_RESET_MASK: UInt32 = 0x250
    public static let I2C0_IO_SDA_CTRL: UInt32 = 0x40028024
    public static let I2C0_IO_SCL_CTRL: UInt32 = 0x4002802C
    public static let I2C0_PADS_SDA: UInt32 = 0x40038014
    public static let I2C0_PADS_SCL: UInt32 = 0x40038018
    public static let I2C0_FUNCSEL: UInt32 = 3
    public static let I2C0_IC_CLK_HZ: UInt32 = 150000000

    // -- PWM1: an rp2350 pwm binding descriptor: one slice of the pwm block, counting on
    // clk_sys, and each output the board routes -- its index in the slice (0 = A, 1 = B)
    // and its pad --
    public static let PWM1_BASE: UInt32 = 0x400A8000
    public static let PWM1_RESET_MASK: UInt32 = 0x10240
    public static let PWM1_SLICE: UInt32 = 1
    public static let PWM1_FUNCSEL: UInt32 = 4
    public static let PWM1_CLK_SYS_HZ: UInt32 = 150000000
    public static let PWM1_OUTPUT_A: UInt32 = 0
    public static let PWM1_IO_A_CTRL: UInt32 = 0x40028014
    public static let PWM1_PADS_A: UInt32 = 0x4003800C
    public static let PWM1_OUTPUT_B: UInt32 = 1
    public static let PWM1_IO_B_CTRL: UInt32 = 0x4002801C
    public static let PWM1_PADS_B: UInt32 = 0x40038010

    // -- PWM2: an rp2350 pwm binding descriptor: one slice of the pwm block, counting on
    // clk_sys, and each output the board routes -- its index in the slice (0 = A, 1 = B)
    // and its pad --
    public static let PWM2_BASE: UInt32 = 0x400A8000
    public static let PWM2_RESET_MASK: UInt32 = 0x10240
    public static let PWM2_SLICE: UInt32 = 2
    public static let PWM2_FUNCSEL: UInt32 = 4
    public static let PWM2_CLK_SYS_HZ: UInt32 = 150000000
    public static let PWM2_OUTPUT_A: UInt32 = 0
    public static let PWM2_IO_A_CTRL: UInt32 = 0x400280A4
    public static let PWM2_PADS_A: UInt32 = 0x40038054
    public static let PWM2_OUTPUT_B: UInt32 = 1
    public static let PWM2_IO_B_CTRL: UInt32 = 0x400280AC
    public static let PWM2_PADS_B: UInt32 = 0x40038058

    // -- PWM3: an rp2350 pwm binding descriptor: one slice of the pwm block, counting on
    // clk_sys, and each output the board routes -- its index in the slice (0 = A, 1 = B)
    // and its pad --
    public static let PWM3_BASE: UInt32 = 0x400A8000
    public static let PWM3_RESET_MASK: UInt32 = 0x10240
    public static let PWM3_SLICE: UInt32 = 3
    public static let PWM3_FUNCSEL: UInt32 = 4
    public static let PWM3_CLK_SYS_HZ: UInt32 = 150000000
    public static let PWM3_OUTPUT_A: UInt32 = 0
    public static let PWM3_IO_A_CTRL: UInt32 = 0x40028034
    public static let PWM3_PADS_A: UInt32 = 0x4003801C
    public static let PWM3_OUTPUT_B: UInt32 = 1
    public static let PWM3_IO_B_CTRL: UInt32 = 0x4002803C
    public static let PWM3_PADS_B: UInt32 = 0x40038020

    // -- PWM4: an rp2350 pwm binding descriptor: one slice of the pwm block, counting on
    // clk_sys, and each output the board routes -- its index in the slice (0 = A, 1 = B)
    // and its pad --
    public static let PWM4_BASE: UInt32 = 0x400A8000
    public static let PWM4_RESET_MASK: UInt32 = 0x10240
    public static let PWM4_SLICE: UInt32 = 4
    public static let PWM4_FUNCSEL: UInt32 = 4
    public static let PWM4_CLK_SYS_HZ: UInt32 = 150000000
    public static let PWM4_OUTPUT_A: UInt32 = 0
    public static let PWM4_IO_A_CTRL: UInt32 = 0x40028044
    public static let PWM4_PADS_A: UInt32 = 0x40038024
    public static let PWM4_OUTPUT_B: UInt32 = 1
    public static let PWM4_IO_B_CTRL: UInt32 = 0x4002804C
    public static let PWM4_PADS_B: UInt32 = 0x40038028

    // -- PWM5: an rp2350 pwm binding descriptor: one slice of the pwm block, counting on
    // clk_sys, and each output the board routes -- its index in the slice (0 = A, 1 = B)
    // and its pad --
    public static let PWM5_BASE: UInt32 = 0x400A8000
    public static let PWM5_RESET_MASK: UInt32 = 0x10240
    public static let PWM5_SLICE: UInt32 = 5
    public static let PWM5_FUNCSEL: UInt32 = 4
    public static let PWM5_CLK_SYS_HZ: UInt32 = 150000000
    public static let PWM5_OUTPUT_A: UInt32 = 0
    public static let PWM5_IO_A_CTRL: UInt32 = 0x40028054
    public static let PWM5_PADS_A: UInt32 = 0x4003802C
    public static let PWM5_OUTPUT_B: UInt32 = 1
    public static let PWM5_IO_B_CTRL: UInt32 = 0x4002805C
    public static let PWM5_PADS_B: UInt32 = 0x40038030

    // -- PWM6: an rp2350 pwm binding descriptor: one slice of the pwm block, counting on
    // clk_sys, and each output the board routes -- its index in the slice (0 = A, 1 = B)
    // and its pad --
    public static let PWM6_BASE: UInt32 = 0x400A8000
    public static let PWM6_RESET_MASK: UInt32 = 0x10240
    public static let PWM6_SLICE: UInt32 = 6
    public static let PWM6_FUNCSEL: UInt32 = 4
    public static let PWM6_CLK_SYS_HZ: UInt32 = 150000000
    public static let PWM6_OUTPUT_A: UInt32 = 0
    public static let PWM6_IO_A_CTRL: UInt32 = 0x40028064
    public static let PWM6_PADS_A: UInt32 = 0x40038034
    public static let PWM6_OUTPUT_B: UInt32 = 1
    public static let PWM6_IO_B_CTRL: UInt32 = 0x4002806C
    public static let PWM6_PADS_B: UInt32 = 0x40038038

    // -- PWM7: an rp2350 pwm binding descriptor: one slice of the pwm block, counting on
    // clk_sys, and each output the board routes -- its index in the slice (0 = A, 1 = B)
    // and its pad --
    public static let PWM7_BASE: UInt32 = 0x400A8000
    public static let PWM7_RESET_MASK: UInt32 = 0x10240
    public static let PWM7_SLICE: UInt32 = 7
    public static let PWM7_FUNCSEL: UInt32 = 4
    public static let PWM7_CLK_SYS_HZ: UInt32 = 150000000
    public static let PWM7_OUTPUT_A: UInt32 = 0
    public static let PWM7_IO_A_CTRL: UInt32 = 0x40028074
    public static let PWM7_PADS_A: UInt32 = 0x4003803C
    public static let PWM7_OUTPUT_B: UInt32 = 1
    public static let PWM7_IO_B_CTRL: UInt32 = 0x4002807C
    public static let PWM7_PADS_B: UInt32 = 0x40038040

    // -- ADC: an rp-adc binding descriptor: the converter, the board's reference rail, and
    // the channel map of this part's package -- each pin-fed channel's GPIO, the channels
    // whose pad the board gives to another line or binding (RESERVED_CHANNELS, and what
    // has each), and the twin: a second pad the board ties to a channel's own net. The
    // calibration records are chip truth in the adc layout --
    public static let ADC_BASE: UInt32 = 0x400A0000
    public static let ADC_RESET_MASK: UInt32 = 0x1
    public static let ADC_REFERENCE_UV: UInt32 = 3300000
    public static let ADC_CHANNEL_COUNT: UInt32 = 5
    public static let ADC_TEMPERATURE_CHANNEL: UInt32 = 4
    public static let ADC_RESERVED_CHANNELS: UInt32 = 0x8
    public static let ADC_CHANNEL0_PIN: UInt32 = 26
    public static let ADC_GPIO26_CHANNEL: UInt32 = 0
    public static let ADC_CHANNEL1_PIN: UInt32 = 27
    public static let ADC_GPIO27_CHANNEL: UInt32 = 1
    public static let ADC_CHANNEL2_PIN: UInt32 = 28
    public static let ADC_GPIO28_CHANNEL: UInt32 = 2
    public static let ADC_CHANNEL3_PIN: UInt32 = 29
    public static let ADC_GPIO29_CHANNEL: UInt32 = 3
    public static let ADC_CHANNEL3_RESERVED_BY: StaticString = "line 'cyw43439-clk'"

    // -- the clock plan (state-and-verify: the plan states the chosen PLL
    // values AND the resulting rates; generation verified hz == xosc * fbdiv /
    // (postdiv1 * postdiv2) and composed each PRIM word from the pll block fields).
    // Every const carries the plan name as a suffix, the default plan included, so a
    // name states which operating point it means -- a board may declare several --
    public static let XOSC_HZ_PLL_150_48: UInt32 = 12000000
    public static let CLK_SYS_HZ_PLL_150_48: UInt32 = 150000000
    public static let CLK_USB_HZ_PLL_150_48: UInt32 = 48000000
    public static let CLK_ADC_HZ_PLL_150_48: UInt32 = 48000000
    public static let PLL_SYS_FBDIV_PLL_150_48: UInt32 = 125
    public static let PLL_SYS_PRIM_PLL_150_48: UInt32 = 0x52000
    public static let PLL_USB_FBDIV_PLL_150_48: UInt32 = 100
    public static let PLL_USB_PRIM_PLL_150_48: UInt32 = 0x55000
    public static let DEVICE_COUNT: UInt32 = 4

    // -- on-board devices: PORT group base + pin index + mask --
    public static let CYW43439_WL_REG_ON_PORT_BASE: UInt32 = 0xD0000000
    public static let CYW43439_WL_REG_ON_PIN: UInt32 = 23
    public static let CYW43439_WL_REG_ON_BANK: UInt32 = 0
    public static let CYW43439_WL_REG_ON_MASK: UInt32 = 0x800000
    public static let CYW43439_WL_REG_ON_ACTIVE_LOW: UInt32 = 0
    public static let CYW43439_DATA_PORT_BASE: UInt32 = 0xD0000000
    public static let CYW43439_DATA_PIN: UInt32 = 24
    public static let CYW43439_DATA_BANK: UInt32 = 0
    public static let CYW43439_DATA_MASK: UInt32 = 0x1000000
    public static let CYW43439_CS_PORT_BASE: UInt32 = 0xD0000000
    public static let CYW43439_CS_PIN: UInt32 = 25
    public static let CYW43439_CS_BANK: UInt32 = 0
    public static let CYW43439_CS_MASK: UInt32 = 0x2000000
    public static let CYW43439_CS_ACTIVE_LOW: UInt32 = 1
    public static let CYW43439_CLK_PORT_BASE: UInt32 = 0xD0000000
    public static let CYW43439_CLK_PIN: UInt32 = 29
    public static let CYW43439_CLK_BANK: UInt32 = 0
    public static let CYW43439_CLK_MASK: UInt32 = 0x20000000

    // -- memory regions the board fits: SIZE is what a program may reach, which a device's own
    // size may exceed; a region with a CONTROLLER does not exist until that instance is brought
    // up, and touching it first is a bus fault rather than a wrong value --
    public static let MEMORY_REGION_COUNT: UInt32 = 1
    public static let MEMORY_FLASH_KIND: StaticString = "flash"
    public static let MEMORY_FLASH_SIZE: UInt32 = 0x400000
    public static let MEMORY_FLASH_OPTIONAL: UInt32 = 0

    // -- connectors: the sockets a removable module plugs into. The socket is board truth --
    // it is on the schematic and identical on every unit -- and what is plugged into it is not,
    // so no row here names a module. A socket brings out whole BUSES, each named by the binding
    // role that serves it, and single LINES, each named by the standard's own name for that
    // position and carrying the port wiring a driver needs to drive it. Which of a socket's
    // protocols an attached module speaks is a property of the module, so a board that offers
    // several states all of them and chooses none --
    public static let CONNECTOR_COUNT: UInt32 = 1
    public static let CONNECTOR_HEADER_STANDARD: StaticString = "pico-header"
    public static let CONNECTOR_HEADER_GP0_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP0_PIN: UInt32 = 0
    public static let CONNECTOR_HEADER_GP0_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP0_MASK: UInt32 = 0x1
    public static let CONNECTOR_HEADER_GP1_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP1_PIN: UInt32 = 1
    public static let CONNECTOR_HEADER_GP1_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP1_MASK: UInt32 = 0x2
    public static let CONNECTOR_HEADER_GP2_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP2_PIN: UInt32 = 2
    public static let CONNECTOR_HEADER_GP2_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP2_MASK: UInt32 = 0x4
    public static let CONNECTOR_HEADER_GP3_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP3_PIN: UInt32 = 3
    public static let CONNECTOR_HEADER_GP3_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP3_MASK: UInt32 = 0x8
    public static let CONNECTOR_HEADER_GP4_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP4_PIN: UInt32 = 4
    public static let CONNECTOR_HEADER_GP4_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP4_MASK: UInt32 = 0x10
    public static let CONNECTOR_HEADER_GP5_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP5_PIN: UInt32 = 5
    public static let CONNECTOR_HEADER_GP5_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP5_MASK: UInt32 = 0x20
    public static let CONNECTOR_HEADER_GP6_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP6_PIN: UInt32 = 6
    public static let CONNECTOR_HEADER_GP6_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP6_MASK: UInt32 = 0x40
    public static let CONNECTOR_HEADER_GP7_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP7_PIN: UInt32 = 7
    public static let CONNECTOR_HEADER_GP7_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP7_MASK: UInt32 = 0x80
    public static let CONNECTOR_HEADER_GP8_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP8_PIN: UInt32 = 8
    public static let CONNECTOR_HEADER_GP8_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP8_MASK: UInt32 = 0x100
    public static let CONNECTOR_HEADER_GP9_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP9_PIN: UInt32 = 9
    public static let CONNECTOR_HEADER_GP9_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP9_MASK: UInt32 = 0x200
    public static let CONNECTOR_HEADER_GP10_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP10_PIN: UInt32 = 10
    public static let CONNECTOR_HEADER_GP10_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP10_MASK: UInt32 = 0x400
    public static let CONNECTOR_HEADER_GP11_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP11_PIN: UInt32 = 11
    public static let CONNECTOR_HEADER_GP11_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP11_MASK: UInt32 = 0x800
    public static let CONNECTOR_HEADER_GP12_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP12_PIN: UInt32 = 12
    public static let CONNECTOR_HEADER_GP12_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP12_MASK: UInt32 = 0x1000
    public static let CONNECTOR_HEADER_GP13_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP13_PIN: UInt32 = 13
    public static let CONNECTOR_HEADER_GP13_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP13_MASK: UInt32 = 0x2000
    public static let CONNECTOR_HEADER_GP14_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP14_PIN: UInt32 = 14
    public static let CONNECTOR_HEADER_GP14_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP14_MASK: UInt32 = 0x4000
    public static let CONNECTOR_HEADER_GP15_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP15_PIN: UInt32 = 15
    public static let CONNECTOR_HEADER_GP15_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP15_MASK: UInt32 = 0x8000
    public static let CONNECTOR_HEADER_GP16_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP16_PIN: UInt32 = 16
    public static let CONNECTOR_HEADER_GP16_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP16_MASK: UInt32 = 0x10000
    public static let CONNECTOR_HEADER_GP17_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP17_PIN: UInt32 = 17
    public static let CONNECTOR_HEADER_GP17_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP17_MASK: UInt32 = 0x20000
    public static let CONNECTOR_HEADER_GP18_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP18_PIN: UInt32 = 18
    public static let CONNECTOR_HEADER_GP18_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP18_MASK: UInt32 = 0x40000
    public static let CONNECTOR_HEADER_GP19_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP19_PIN: UInt32 = 19
    public static let CONNECTOR_HEADER_GP19_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP19_MASK: UInt32 = 0x80000
    public static let CONNECTOR_HEADER_GP20_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP20_PIN: UInt32 = 20
    public static let CONNECTOR_HEADER_GP20_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP20_MASK: UInt32 = 0x100000
    public static let CONNECTOR_HEADER_GP21_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP21_PIN: UInt32 = 21
    public static let CONNECTOR_HEADER_GP21_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP21_MASK: UInt32 = 0x200000
    public static let CONNECTOR_HEADER_GP22_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP22_PIN: UInt32 = 22
    public static let CONNECTOR_HEADER_GP22_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP22_MASK: UInt32 = 0x400000
    public static let CONNECTOR_HEADER_GP26_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP26_PIN: UInt32 = 26
    public static let CONNECTOR_HEADER_GP26_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP26_MASK: UInt32 = 0x4000000
    public static let CONNECTOR_HEADER_GP27_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP27_PIN: UInt32 = 27
    public static let CONNECTOR_HEADER_GP27_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP27_MASK: UInt32 = 0x8000000
    public static let CONNECTOR_HEADER_GP28_PORT_BASE: UInt32 = 0xD0000000
    public static let CONNECTOR_HEADER_GP28_PIN: UInt32 = 28
    public static let CONNECTOR_HEADER_GP28_BANK: UInt32 = 0
    public static let CONNECTOR_HEADER_GP28_MASK: UInt32 = 0x10000000
}
