# GENERATED by lamella-bsp-gen from bsp/arduino-uno-r4-minima/board.toml + csp/ra4m1/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ra4m1

BOARD = "arduino-uno-r4-minima"
BOARD_MODEL = 34
BOARD_VENDOR = "Arduino"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.

CARRIER = {
    "kind": "native-usb",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Bases only: register offsets and bit encodings belong to the driver that knows the block.
INSTANCES = {
    "port0": {"block": "port", "base": 0x40040000},
    "port1": {"block": "port", "base": 0x40040020},
}

PLANS = {
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
    "led0": {"kind": "gpio-out", "port_base": 0x40040020, "pin": 11, "mask": 0x800, "active_low": False},
    "led_tx": {"kind": "gpio-out", "port_base": 0x40040000, "pin": 12, "mask": 0x1000, "active_low": True},
    "led_rx": {"kind": "gpio-out", "port_base": 0x40040000, "pin": 13, "mask": 0x2000, "active_low": True},
}
