// GENERATED by lamella-bsp-gen from csp/stm32l053/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32l053
//
// The stm32l053 instance map as Swift constants, name/value-identical to Stm32l053Instances.g.cs:
// where each block copy sits and its per-instance ids. Block-register offsets are not
// emitted for Swift: a firmware project states its block constants and reads this file
// for every placed-instance fact.

public enum Stm32l053Instances {
    public static let GPIOA_BASE: UInt32 = 0x50000000
    public static let GPIOA_RCC_EN_OFF: UInt32 = 44
    public static let GPIOA_RCC_EN_BIT: UInt32 = 0
    public static let GPIOA_RCC_EN_MASK: UInt32 = 0x1
    public static let GPIOB_BASE: UInt32 = 0x50000400
    public static let GPIOB_RCC_EN_OFF: UInt32 = 44
    public static let GPIOB_RCC_EN_BIT: UInt32 = 1
    public static let GPIOB_RCC_EN_MASK: UInt32 = 0x2
    public static let GPIOC_BASE: UInt32 = 0x50000800
    public static let GPIOC_RCC_EN_OFF: UInt32 = 44
    public static let GPIOC_RCC_EN_BIT: UInt32 = 2
    public static let GPIOC_RCC_EN_MASK: UInt32 = 0x4
    public static let GPIOD_BASE: UInt32 = 0x50000C00
    public static let GPIOD_RCC_EN_OFF: UInt32 = 44
    public static let GPIOD_RCC_EN_BIT: UInt32 = 3
    public static let GPIOD_RCC_EN_MASK: UInt32 = 0x8
    public static let GPIOH_BASE: UInt32 = 0x50001C00
    public static let GPIOH_RCC_EN_OFF: UInt32 = 44
    public static let GPIOH_RCC_EN_BIT: UInt32 = 7
    public static let GPIOH_RCC_EN_MASK: UInt32 = 0x80
    public static let USART1_BASE: UInt32 = 0x40013800
    public static let USART1_RCC_EN_OFF: UInt32 = 52
    public static let USART1_RCC_EN_BIT: UInt32 = 14
    public static let USART1_RCC_EN_MASK: UInt32 = 0x4000
    public static let USART2_BASE: UInt32 = 0x40004400
    public static let USART2_RCC_EN_OFF: UInt32 = 56
    public static let USART2_RCC_EN_BIT: UInt32 = 17
    public static let USART2_RCC_EN_MASK: UInt32 = 0x20000
    public static let SPI1_BASE: UInt32 = 0x40013000
    public static let SPI1_RCC_EN_OFF: UInt32 = 52
    public static let SPI1_RCC_EN_BIT: UInt32 = 12
    public static let SPI1_RCC_EN_MASK: UInt32 = 0x1000
    public static let EXTI_BASE: UInt32 = 0x40010400
    public static let SYSCFG_BASE: UInt32 = 0x40010000
    public static let SYSCFG_RCC_EN_OFF: UInt32 = 52
    public static let SYSCFG_RCC_EN_BIT: UInt32 = 0
    public static let SYSCFG_RCC_EN_MASK: UInt32 = 0x1
    public static let RCC_BASE: UInt32 = 0x40021000
}
