//! GENERATED by lamella-bsp-gen from csp/esp32c6/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . esp32c6

pub const UART0_BASE: u32 = 0x60000000;
pub const PCR_BASE: u32 = 0x60096000;
pub const IO_MUX_BASE: u32 = 0x60090000;
