//! GENERATED by lamella-bsp-gen from csp/rp2040/blocks/pads-bank0.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040

/// -- register offsets (block-relative) + access widths --
pub const GPIO0_OFF: u32 = 0x4;
pub const GPIO0_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const GPIO0_SLEWFAST: u32 = 0x1;
pub const GPIO0_SLEWFAST_LSB: u32 = 0;
pub const GPIO0_SCHMITT: u32 = 0x2;
pub const GPIO0_SCHMITT_LSB: u32 = 1;
pub const GPIO0_PDE: u32 = 0x4;
pub const GPIO0_PDE_LSB: u32 = 2;
pub const GPIO0_PUE: u32 = 0x8;
pub const GPIO0_PUE_LSB: u32 = 3;
pub const GPIO0_DRIVE: u32 = 0x30;
pub const GPIO0_DRIVE_LSB: u32 = 4;
pub const GPIO0_IE: u32 = 0x40;
pub const GPIO0_IE_LSB: u32 = 6;
pub const GPIO0_OD: u32 = 0x80;
pub const GPIO0_OD_LSB: u32 = 7;

/// -- block constants --
pub const GPIO_STRIDE: u32 = 4;
