//! GENERATED by lamella-bsp-gen from csp/rp2040/blocks/sio.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040

/// -- register offsets (block-relative) + access widths --
pub const GPIO_IN_OFF: u32 = 0x4;
pub const GPIO_IN_WIDTH: i32 = 32;
pub const GPIO_OUT_OFF: u32 = 0x10;
pub const GPIO_OUT_WIDTH: i32 = 32;
pub const GPIO_OUT_SET_OFF: u32 = 0x14;
pub const GPIO_OUT_SET_WIDTH: i32 = 32;
pub const GPIO_OUT_CLR_OFF: u32 = 0x18;
pub const GPIO_OUT_CLR_WIDTH: i32 = 32;
pub const GPIO_OUT_XOR_OFF: u32 = 0x1C;
pub const GPIO_OUT_XOR_WIDTH: i32 = 32;
pub const GPIO_OE_OFF: u32 = 0x20;
pub const GPIO_OE_WIDTH: i32 = 32;
pub const GPIO_OE_SET_OFF: u32 = 0x24;
pub const GPIO_OE_SET_WIDTH: i32 = 32;
pub const GPIO_OE_CLR_OFF: u32 = 0x28;
pub const GPIO_OE_CLR_WIDTH: i32 = 32;
