//! GENERATED by lamella-bsp-gen from csp/saml22/blocks/gclk.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . saml22

/// -- register offsets (block-relative) + access widths --
pub const PCHCTRL0_OFF: u32 = 0x80;
pub const PCHCTRL0_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const PCHCTRL0_GEN: u32 = 0xF;
pub const PCHCTRL0_GEN_LSB: u32 = 0;
pub const PCHCTRL0_CHEN: u32 = 0x40;
pub const PCHCTRL0_CHEN_LSB: u32 = 6;
pub const PCHCTRL0_WRTLOCK: u32 = 0x80;
pub const PCHCTRL0_WRTLOCK_LSB: u32 = 7;
