//! GENERATED by lamella-bsp-gen from csp/saml22/blocks/mclk.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . saml22

/// -- register offsets (block-relative) + access widths --
pub const AHBMASK_OFF: u32 = 0x10;
pub const AHBMASK_WIDTH: i32 = 32;
pub const APBAMASK_OFF: u32 = 0x14;
pub const APBAMASK_WIDTH: i32 = 32;
pub const APBBMASK_OFF: u32 = 0x18;
pub const APBBMASK_WIDTH: i32 = 32;
pub const APBCMASK_OFF: u32 = 0x1C;
pub const APBCMASK_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const APBBMASK_PORT: u32 = 0x8;
pub const APBBMASK_PORT_LSB: u32 = 3;
pub const APBCMASK_SERCOM0: u32 = 0x2;
pub const APBCMASK_SERCOM0_LSB: u32 = 1;
pub const APBCMASK_SERCOM1: u32 = 0x4;
pub const APBCMASK_SERCOM1_LSB: u32 = 2;
pub const APBCMASK_SERCOM2: u32 = 0x8;
pub const APBCMASK_SERCOM2_LSB: u32 = 3;
pub const APBCMASK_SERCOM3: u32 = 0x10;
pub const APBCMASK_SERCOM3_LSB: u32 = 4;
pub const APBCMASK_SERCOM4: u32 = 0x20;
pub const APBCMASK_SERCOM4_LSB: u32 = 5;
pub const APBCMASK_SERCOM5: u32 = 0x40;
pub const APBCMASK_SERCOM5_LSB: u32 = 6;
