// GENERATED by lamella-bsp-gen from bsp/samd21-cnano/board.toml + csp/samd21/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Samd21CnanoBindings
    {
        private Samd21CnanoBindings() { }

        public const int BOARD_MODEL = 46;
        public const string BOARD_VENDOR = "Microchip";

        public const uint LED0_PORT_BASE = 0x41004480;
        public const uint LED0_PIN = 10;
        public const uint LED0_MASK = 0x400;
        public const uint LED0_ACTIVE_LOW = 1;
        public const uint BUTTON0_PORT_BASE = 0x41004480;
        public const uint BUTTON0_PIN = 11;
        public const uint BUTTON0_MASK = 0x800;
        public const uint BUTTON0_ACTIVE_LOW = 1;
    }
}
