# GENERATED by lamella-bsp-gen from bsp/samr30-xpro/board.toml + csp/samr30/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samr30

BOARD = "samr30-xpro"
BOARD_MODEL = 57
BOARD_VENDOR = "Microchip"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
VCP = "vcp"

CARRIER = {
    "kind": "edbg-vcp",
    "usb_vid": 0x03EB,
    "role": "vcp",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
    "vcp": {
        "driver_family": "samr30-sercom",
        "instance": sercom0,
        "sercom_base": 0x42000000,
        "irq": 8,
        "gclk_pchctrl_reg": 0x400018C8,
        "gclk_pchctrl_value": 0x40,
        "apb_mask_reg": 0x4000041C,
        "apb_mask": 0x1,
        "pmux_reg": 0x40002832,
        "pmux_pair": 0x33,
        "pmux_tx_reg": 0x40002832,
        "pmux_tx_mask": 0xF,
        "pmux_tx_value": 0x3,
        "pmux_rx_reg": 0x40002832,
        "pmux_rx_mask": 0xF0,
        "pmux_rx_value": 0x30,
        "pincfg_tx_reg": 0x40002844,
        "pincfg_rx_reg": 0x40002845,
        "txpo": 0,
        "rxpo": 1,
        "baud_115200_osc16m_4mhz": 0x8A0A,
    },
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Each row carries whatever this family's record declares -- a base always, and per-instance
# facts like a clock channel or a bus-enable bit where the family states them. Register offsets
# and bit encodings belong to the driver that knows the block, not here.
INSTANCES = {
    "sercom0": {"block": "sercom", "base": 0x42000000, "gclk_core_id": 0x12, "apb_mask_offset": 0x1C, "apb_bit": 0x0, "irq": 0x8},
    "sercom1": {"block": "sercom", "base": 0x42000400, "gclk_core_id": 0x13, "apb_mask_offset": 0x1C, "apb_bit": 0x1, "irq": 0x9},
    "sercom2": {"block": "sercom", "base": 0x42000800, "gclk_core_id": 0x14, "apb_mask_offset": 0x1C, "apb_bit": 0x2, "irq": 0xA},
    "sercom3": {"block": "sercom", "base": 0x42000C00, "gclk_core_id": 0x15, "apb_mask_offset": 0x1C, "apb_bit": 0x3, "irq": 0xB},
    "sercom4": {"block": "sercom", "base": 0x42001000, "gclk_core_id": 0x16, "apb_mask_offset": 0x1C, "apb_bit": 0x4, "irq": 0xC},
    "sercom5": {"block": "sercom", "base": 0x43000400, "gclk_core_id": 0x18, "apb_mask_offset": 0x20, "apb_bit": 0x1, "irq": 0xD},
    "mclk": {"block": "mclk", "base": 0x40000400},
    "gclk": {"block": "gclk", "base": 0x40001800},
    "porta": {"block": "port", "base": 0x40002800, "apb_mask_offset": 0x14, "apb_bit": 0xA},
    "portb": {"block": "port", "base": 0x40002880, "apb_mask_offset": 0x14, "apb_bit": 0xA},
    "portc": {"block": "port", "base": 0x40002900, "apb_mask_offset": 0x14, "apb_bit": 0xA},
}

PLANS = {
    "osc16m-4mhz": {"default": True, "source": "osc16m", "gclk0_hz": 4000000},
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
    "led0": {"kind": "gpio-out", "port_base": 0x40002800, "pin": 19, "mask": 0x80000, "active_low": True},
    "led1": {"kind": "gpio-out", "port_base": 0x40002800, "pin": 18, "mask": 0x40000, "active_low": True},
    "button0": {"kind": "gpio-in", "port_base": 0x40002800, "pin": 28, "mask": 0x10000000, "active_low": True},
}
