// GENERATED by lamella-bsp-gen from bsp/saml21-xpro/board.toml + csp/saml21/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . saml21
//
// The saml21-xpro board bindings as Swift constants, name/value-identical to Saml21XproBindings.g.cs:
// every value below is a generation-time literal derived from the strata. Board truth
// lives in board.toml, never here.

public enum Saml21XproBindings {
    // -- identity --
    public static let BOARD_MODEL: UInt16 = 55
    public static let BOARD_VENDOR: String = "Microchip"
    public static let CARRIER_USB_VID: UInt16 = 0x03EB

    /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
    /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
    /// peripherals of the same kind can share no register at all, so a consumer that selects a
    /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
    /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
    /// name a driver; and a uart is a different register map on every family, so the kind does
    /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
    public static let VCP_DRIVER_FAMILY: String = "saml21-sercom"

        // -- VCP: a sercom-usart binding descriptor on the PCHCTRL clock architecture.
        // The peripheral channel is an ADDRESS here rather than a field -- PCHCTRL[m] --
        // and WHICH APB mask register gates the instance is per-instance --
    public static let VCP_SERCOM_BASE: UInt32 = 0x42000C00
    public static let VCP_IRQ: UInt32 = 11
    public static let VCP_GCLK_PCHCTRL_REG: UInt32 = 0x400018D4
    public static let VCP_GCLK_PCHCTRL_VALUE: UInt32 = 0x40
    public static let VCP_APB_MASK_REG: UInt32 = 0x4000041C
    public static let VCP_APB_MASK: UInt32 = 0x8
    public static let VCP_PMUX_REG: UInt32 = 0x4000283B
    public static let VCP_PMUX_PAIR: UInt32 = 0x22
    public static let VCP_PMUX_TX_REG: UInt32 = 0x4000283B
    public static let VCP_PMUX_TX_MASK: UInt32 = 0xF
    public static let VCP_PMUX_TX_VALUE: UInt32 = 0x2
    public static let VCP_PMUX_RX_REG: UInt32 = 0x4000283B
    public static let VCP_PMUX_RX_MASK: UInt32 = 0xF0
    public static let VCP_PMUX_RX_VALUE: UInt32 = 0x20
    public static let VCP_PINCFG_TX_REG: UInt32 = 0x40002856
    public static let VCP_PINCFG_RX_REG: UInt32 = 0x40002857
    public static let VCP_TXPO: UInt32 = 0
    public static let VCP_RXPO: UInt32 = 1
    public static let VCP_BAUD_115200_OSC16M_4MHZ: UInt32 = 0x8A0A

    // -- on-board devices: PORT group base + pin index + mask --
    public static let LED0_PORT_BASE: UInt32 = 0x40002880
    public static let LED0_PIN: UInt32 = 10
    public static let LED0_MASK: UInt32 = 0x400
    public static let LED0_ACTIVE_LOW: UInt32 = 1
    public static let BUTTON0_PORT_BASE: UInt32 = 0x40002800
    public static let BUTTON0_PIN: UInt32 = 2
    public static let BUTTON0_MASK: UInt32 = 0x4
    public static let BUTTON0_ACTIVE_LOW: UInt32 = 1
}
