//! GENERATED by lamella-bsp-gen from bsp/sam4e-xpro/board.toml + csp/sam4e/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4e

pub const BOARD_MODEL: u16 = 26;
pub const BOARD_VENDOR: &str = "Atmel";
pub const CARRIER_USB_VID: u16 = 0x03EB;
pub const CARRIER_USB_PID: u16 = 0x2111;

pub const LED0_PORT_BASE: u32 = 0x400E1400;
pub const LED0_PIN: u32 = 22;
pub const LED0_MASK: u32 = 0x400000;
pub const LED0_ACTIVE_LOW: u32 = 1;
pub const BUTTON0_PORT_BASE: u32 = 0x400E0E00;
pub const BUTTON0_PIN: u32 = 2;
pub const BUTTON0_MASK: u32 = 0x4;
pub const BUTTON0_ACTIVE_LOW: u32 = 1;
