//! The Unicode names a `\N{NAME}` string escape resolves, for the common names that appear in real
//! Python source (typographic marks, currency, math, arrows, Greek letters, a few emoji). Not the
//! full Unicode name database (144 of ~30k names) -- an unknown name is a clear lex error pointing
//! at `\u`/`\U`. The code points were taken from CPython's `unicodedata` (Unicode 16.0.0), the
//! same version [`lamella_unicode::UNICODE_VERSION`] tracks.

/// `(name, char)` pairs, sorted by name for a binary search.
const NAMED_CHARS: &[(&str, char)] = &[
    ("ALMOST EQUAL TO", '\u{2248}'),
    ("ASTERISK OPERATOR", '\u{2217}'),
    ("BALLOT BOX WITH CHECK", '\u{2611}'),
    ("BALLOT X", '\u{2717}'),
    ("BLACK CIRCLE", '\u{25CF}'),
    ("BLACK HEART SUIT", '\u{2665}'),
    ("BLACK RIGHT-POINTING TRIANGLE", '\u{25B6}'),
    ("BLACK SQUARE", '\u{25A0}'),
    ("BLACK STAR", '\u{2605}'),
    ("BLACK SUN WITH RAYS", '\u{2600}'),
    ("BULLET", '\u{2022}'),
    ("CENT SIGN", '\u{A2}'),
    ("CHECK MARK", '\u{2713}'),
    ("COPYRIGHT SIGN", '\u{A9}'),
    ("CURRENCY SIGN", '\u{A4}'),
    ("DAGGER", '\u{2020}'),
    ("DEGREE CELSIUS", '\u{2103}'),
    ("DEGREE FAHRENHEIT", '\u{2109}'),
    ("DEGREE SIGN", '\u{B0}'),
    ("DIVISION SIGN", '\u{F7}'),
    ("DIVISION SLASH", '\u{2215}'),
    ("DOT OPERATOR", '\u{22C5}'),
    ("DOUBLE DAGGER", '\u{2021}'),
    ("DOWNWARDS ARROW", '\u{2193}'),
    ("ELEMENT OF", '\u{2208}'),
    ("EM DASH", '\u{2014}'),
    ("EMPTY SET", '\u{2205}'),
    ("EN DASH", '\u{2013}'),
    ("ESTIMATED SYMBOL", '\u{212E}'),
    ("EURO SIGN", '\u{20AC}'),
    ("FACE WITH TEARS OF JOY", '\u{1F602}'),
    ("FIRE", '\u{1F525}'),
    ("FOR ALL", '\u{2200}'),
    ("GREATER-THAN OR EQUAL TO", '\u{2265}'),
    ("GREEK CAPITAL LETTER ALPHA", '\u{391}'),
    ("GREEK CAPITAL LETTER BETA", '\u{392}'),
    ("GREEK CAPITAL LETTER DELTA", '\u{394}'),
    ("GREEK CAPITAL LETTER GAMMA", '\u{393}'),
    ("GREEK CAPITAL LETTER LAMDA", '\u{39B}'),
    ("GREEK CAPITAL LETTER OMEGA", '\u{3A9}'),
    ("GREEK CAPITAL LETTER PHI", '\u{3A6}'),
    ("GREEK CAPITAL LETTER PI", '\u{3A0}'),
    ("GREEK CAPITAL LETTER PSI", '\u{3A8}'),
    ("GREEK CAPITAL LETTER SIGMA", '\u{3A3}'),
    ("GREEK CAPITAL LETTER THETA", '\u{398}'),
    ("GREEK SMALL LETTER ALPHA", '\u{3B1}'),
    ("GREEK SMALL LETTER BETA", '\u{3B2}'),
    ("GREEK SMALL LETTER CHI", '\u{3C7}'),
    ("GREEK SMALL LETTER DELTA", '\u{3B4}'),
    ("GREEK SMALL LETTER EPSILON", '\u{3B5}'),
    ("GREEK SMALL LETTER ETA", '\u{3B7}'),
    ("GREEK SMALL LETTER GAMMA", '\u{3B3}'),
    ("GREEK SMALL LETTER IOTA", '\u{3B9}'),
    ("GREEK SMALL LETTER KAPPA", '\u{3BA}'),
    ("GREEK SMALL LETTER LAMDA", '\u{3BB}'),
    ("GREEK SMALL LETTER MU", '\u{3BC}'),
    ("GREEK SMALL LETTER NU", '\u{3BD}'),
    ("GREEK SMALL LETTER OMEGA", '\u{3C9}'),
    ("GREEK SMALL LETTER OMICRON", '\u{3BF}'),
    ("GREEK SMALL LETTER PHI", '\u{3C6}'),
    ("GREEK SMALL LETTER PI", '\u{3C0}'),
    ("GREEK SMALL LETTER PSI", '\u{3C8}'),
    ("GREEK SMALL LETTER RHO", '\u{3C1}'),
    ("GREEK SMALL LETTER SIGMA", '\u{3C3}'),
    ("GREEK SMALL LETTER TAU", '\u{3C4}'),
    ("GREEK SMALL LETTER THETA", '\u{3B8}'),
    ("GREEK SMALL LETTER UPSILON", '\u{3C5}'),
    ("GREEK SMALL LETTER XI", '\u{3BE}'),
    ("GREEK SMALL LETTER ZETA", '\u{3B6}'),
    ("GRINNING FACE", '\u{1F600}'),
    ("HEAVY BLACK HEART", '\u{2764}'),
    ("HEAVY CHECK MARK", '\u{2714}'),
    ("HEAVY MULTIPLICATION X", '\u{2716}'),
    ("HORIZONTAL BAR", '\u{2015}'),
    ("HORIZONTAL ELLIPSIS", '\u{2026}'),
    ("HUNDRED POINTS SYMBOL", '\u{1F4AF}'),
    ("IDENTICAL TO", '\u{2261}'),
    ("INFINITY", '\u{221E}'),
    ("INTEGRAL", '\u{222B}'),
    ("INTERSECTION", '\u{2229}'),
    ("LEFT DOUBLE QUOTATION MARK", '\u{201C}'),
    ("LEFT RIGHT ARROW", '\u{2194}'),
    ("LEFT SINGLE QUOTATION MARK", '\u{2018}'),
    ("LEFTWARDS ARROW", '\u{2190}'),
    ("LEFTWARDS DOUBLE ARROW", '\u{21D0}'),
    ("LESS-THAN OR EQUAL TO", '\u{2264}'),
    ("LOGICAL AND", '\u{2227}'),
    ("LOGICAL OR", '\u{2228}'),
    ("MICRO SIGN", '\u{B5}'),
    ("MIDDLE DOT", '\u{B7}'),
    ("MINUS SIGN", '\u{2212}'),
    ("MULTIPLICATION SIGN", '\u{D7}'),
    ("MULTIPLICATION X", '\u{2715}'),
    ("N-ARY PRODUCT", '\u{220F}'),
    ("N-ARY SUMMATION", '\u{2211}'),
    ("NABLA", '\u{2207}'),
    ("NO-BREAK SPACE", '\u{A0}'),
    ("NON-BREAKING HYPHEN", '\u{2011}'),
    ("NOT AN ELEMENT OF", '\u{2209}'),
    ("NOT EQUAL TO", '\u{2260}'),
    ("NUMERO SIGN", '\u{2116}'),
    ("OHM SIGN", '\u{2126}'),
    ("PARTIAL DIFFERENTIAL", '\u{2202}'),
    ("PARTY POPPER", '\u{1F389}'),
    ("PER MILLE SIGN", '\u{2030}'),
    ("PILCROW SIGN", '\u{B6}'),
    ("PLUS-MINUS SIGN", '\u{B1}'),
    ("POUND SIGN", '\u{A3}'),
    ("PROPORTIONAL TO", '\u{221D}'),
    ("REGISTERED SIGN", '\u{AE}'),
    ("RIGHT DOUBLE QUOTATION MARK", '\u{201D}'),
    ("RIGHT SINGLE QUOTATION MARK", '\u{2019}'),
    ("RIGHTWARDS ARROW", '\u{2192}'),
    ("RIGHTWARDS DOUBLE ARROW", '\u{21D2}'),
    ("ROCKET", '\u{1F680}'),
    ("RUPEE SIGN", '\u{20A8}'),
    ("SECTION SIGN", '\u{A7}'),
    ("SNOWFLAKE", '\u{2744}'),
    ("SNOWMAN", '\u{2603}'),
    ("SOFT HYPHEN", '\u{AD}'),
    ("SPARKLES", '\u{2728}'),
    ("SQUARE ROOT", '\u{221A}'),
    ("SUPERSCRIPT ONE", '\u{B9}'),
    ("SUPERSCRIPT THREE", '\u{B3}'),
    ("SUPERSCRIPT TWO", '\u{B2}'),
    ("THERE EXISTS", '\u{2203}'),
    ("THUMBS DOWN SIGN", '\u{1F44E}'),
    ("THUMBS UP SIGN", '\u{1F44D}'),
    ("TRADE MARK SIGN", '\u{2122}'),
    ("UNION", '\u{222A}'),
    ("UPWARDS ARROW", '\u{2191}'),
    ("VULGAR FRACTION ONE HALF", '\u{BD}'),
    ("VULGAR FRACTION ONE QUARTER", '\u{BC}'),
    ("VULGAR FRACTION ONE THIRD", '\u{2153}'),
    ("VULGAR FRACTION THREE QUARTERS", '\u{BE}'),
    ("VULGAR FRACTION TWO THIRDS", '\u{2154}'),
    ("WARNING SIGN", '\u{26A0}'),
    ("WHITE CIRCLE", '\u{25CB}'),
    ("WHITE SMILING FACE", '\u{263A}'),
    ("WHITE SQUARE", '\u{25A1}'),
    ("WHITE STAR", '\u{2606}'),
    ("YEN SIGN", '\u{A5}'),
    ("ZERO WIDTH JOINER", '\u{200D}'),
    ("ZERO WIDTH SPACE", '\u{200B}'),
];

/// The character named `name` (`\N{name}`), or `None` if it is not one of the supported names.
pub(crate) fn char_from_name(name: &str) -> Option<char> {
    NAMED_CHARS
        .binary_search_by_key(&name, |(n, _)| n)
        .ok()
        .map(|i| NAMED_CHARS[i].1)
}

#[cfg(test)]
mod tests {
    use super::{char_from_name, NAMED_CHARS};

    #[test]
    fn table_is_sorted_and_looks_up() {
        assert!(NAMED_CHARS.windows(2).all(|w| w[0].0 < w[1].0), "sorted + no duplicate names");
        assert_eq!(char_from_name("BULLET"), Some('\u{2022}'));
        assert_eq!(char_from_name("GREEK SMALL LETTER PI"), Some('\u{3C0}'));
        assert_eq!(char_from_name("EURO SIGN"), Some('\u{20AC}'));
        assert_eq!(char_from_name("NO SUCH NAME"), None);
    }
}
