// GENERATED by lamella-bsp-gen from ext/atethernet1-xpro/extension.toml + ext/standards/xplained-pro.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Atethernet1XproExtension
    {
        private Atethernet1XproExtension() { }
        public const string EXTENSION = "atethernet1-xpro";
        public const string VENDOR = "microchip";
        public const string STANDARD = "xplained-pro";

        /// -- the kit identifier its identification chip carries, as the `nnnn` field of an
        /// `nnnnrrssssssssss` serial. It is how a FITTED extension can be told from an assumed
        /// one -- but on a kit with an embedded debugger the identification line reaches the
        /// DEBUGGER rather than an MCU pad, so this is a host tool's reading and not a
        /// program's --
        public const uint KIT_IDENTIFIER = 2258;

        /// -- what this board needs a host socket to bring out. Each POSITION is the connector
        /// standard's own name for a hole, never a pad: this file cannot name a pad, because it does
        /// not know which host it is plugged into. A host's `CONNECTOR_<socket>_<POSITION>_*`
        /// constants carry the pad behind each one, and the two are joined on the position name --
        public const uint POSITION_COUNT = 7;
        public const uint POSITION_SPI_SS_A_PIN = 15;
        public const uint POSITION_SPI_MOSI_PIN = 16;
        public const uint POSITION_SPI_MISO_PIN = 17;
        public const uint POSITION_SPI_SCK_PIN = 18;
        public const uint POSITION_GPIO2_PIN = 6;
        public const uint POSITION_IRQ_PIN = 9;
        public const uint POSITION_GPIO1_PIN = 5;

        /// -- the buses this board presents, each naming the socket positions it rides. A host
        /// resolves them through the same socket constants; which of its controllers is behind
        /// them is the HOST's fact and appears nowhere here --
        public const uint BUS_COUNT = 1;
        public const string BUS_ETH_SPI_KIND = "spi";
        public const string BUS_ETH_SPI_SS = "spi_ss_a";
        public const string BUS_ETH_SPI_MOSI = "spi_mosi";
        public const string BUS_ETH_SPI_MISO = "spi_miso";
        public const string BUS_ETH_SPI_SCK = "spi_sck";

        /// -- the devices a host reaches. A LINE-wired device names the socket position it sits on
        /// and its active level; a BUS-wired one names the bus and, where a document states one, its
        /// address. An active level of `unknown` is a document that does not say, recorded as such:
        /// no polarity constant is emitted for it, so a program that assumed one fails to compile --
        public const uint DEVICE_COUNT = 4;
        public const string DEVICE_NRST_KIND = "gpio-out";
        public const string DEVICE_NRST_POSITION = "gpio2";
        public const uint DEVICE_NRST_ACTIVE_LOW = 1;
        public const string DEVICE_INTRN_KIND = "gpio-in";
        public const string DEVICE_INTRN_POSITION = "irq";
        public const uint DEVICE_INTRN_ACTIVE_LOW = 1;
        public const string DEVICE_PME_KIND = "gpio-in";
        public const string DEVICE_PME_POSITION = "gpio1";
        public const uint DEVICE_PME_ACTIVE_LOW = 1;
        public const string DEVICE_ETHERNET_KIND = "spi-device";
        public const string DEVICE_ETHERNET_BUS = "eth-spi";
        public const string DEVICE_ETHERNET_PART = "ksz8851snl";
    }
}
