//! GENERATED by lamella-bsp-gen from bsp/arduino-due/board.toml + csp/sam3x/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam3x

pub const BOARD_MODEL: u16 = 15;
pub const BOARD_VENDOR: &str = "Arduino";

/// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
/// role's `KIND` says what the application asked for -- a uart, an spi -- and two
/// peripherals of the same kind can share no register at all, so a consumer that selects a
/// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
/// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
/// name a driver; and a uart is a different register map on every family, so the kind does
/// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
pub const VCP_DRIVER_FAMILY: &str = "sam3x-uart";

pub const VCP_BASE: u32 = 0x400E0800;
pub const VCP_PID: u32 = 8;
pub const VCP_PMC_PCER_REG: u32 = 0x400E0610;
pub const VCP_PMC_PCER_MASK: u32 = 0x100;
pub const VCP_PIO_PDR_REG: u32 = 0x400E0E04;
pub const VCP_PIO_ABSR_REG: u32 = 0x400E0E70;
pub const VCP_PIO_MASK: u32 = 0x300;
pub const VCP_PIO_FUNC: u32 = 0;
pub const VCP_MCK_HZ: u32 = 84000000;
pub const VCP_BRGR_CD_115200_PLLA_84MHZ: u32 = 46;
