# GENERATED by lamella-bsp-gen from bsp/pico/board.toml + csp/rp2040/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040

BOARD = "pico"
BOARD_MODEL = 13

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
UART0 = "uart0"

CARRIER = {
    "kind": "uart",
    "role": "uart0",
}

# Per-role descriptor dicts: the same values the C# PicoBindings class carries as consts,
# under one mechanical renaming rule -- an UPPER_SNAKE const there is a lowercase key here,
# grouped by the role it belongs to.
FACTS = {
    "uart0": {
        "kind": "uart",
        "instance": "uart0",
        "base": 0x40034000,
        "reset_mask": 0x400120,
        "io_tx_ctrl": 0x40014004,
        "io_rx_ctrl": 0x4001400C,
        "funcsel": 2,
        "clk_peri_hz": 12000000,
        "ibrd_115200_xosc_12mhz": 6,
        "fbrd_115200_xosc_12mhz": 33,
    },
}

PLANS = {
    "xosc-12mhz": {"default": True, "source": "xosc", "xosc_hz": 12000000, "clk_peri_hz": 12000000},
    "pll-125-48": {"default": False, "source": "pll_sys + pll_usb", "xosc_hz": 12000000, "clk_sys_hz": 125000000, "pll_sys_fbdiv": 125, "pll_sys_postdiv1": 6, "pll_sys_postdiv2": 2, "clk_usb_hz": 48000000, "pll_usb_fbdiv": 100, "pll_usb_postdiv1": 5, "pll_usb_postdiv2": 5, "clk_peri_hz": 12000000},
}

# On-board devices + module control lines (the C# <NAME>_PORT_BASE/_PIN/_MASK/
# _ACTIVE_LOW consts, dict-shaped): PORT group base + pin index + mask + polarity.
DEVICES = {
}
