# GENERATED by lamella-bsp-gen from bsp/arduino-uno-q/board.toml + csp/stm32u585/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32u585

BOARD = "arduino-uno-q"
BOARD_MODEL = 36
BOARD_VENDOR = "Arduino"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.

CARRIER = {
    "kind": "",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Bases only: register offsets and bit encodings belong to the driver that knows the block.
INSTANCES = {
    "gpiog": {"block": "gpio", "base": 0x42021800, "rcc_en_off": 0x8C, "rcc_en_bit": 0x6},
    "gpioh": {"block": "gpio", "base": 0x42021C00, "rcc_en_off": 0x8C, "rcc_en_bit": 0x7},
    "spi3": {"block": "spi", "base": 0x46002000, "rcc_en_off": 0xA8, "rcc_en_bit": 0x5},
    "lpuart1": {"block": "lpuart", "base": 0x46002400, "rcc_en_off": 0xA8, "rcc_en_bit": 0x6},
    "rcc": {"block": "rcc", "base": 0x46020C00},
}

PLANS = {
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
    "led1_red": {"kind": "gpio-out", "port_base": 0x42021C00, "pin": 10, "mask": 0x400, "active_low": True},
    "led1_green": {"kind": "gpio-out", "port_base": 0x42021C00, "pin": 11, "mask": 0x800, "active_low": True},
    "led1_blue": {"kind": "gpio-out", "port_base": 0x42021C00, "pin": 12, "mask": 0x1000, "active_low": True},
    "led2_red": {"kind": "gpio-out", "port_base": 0x42021C00, "pin": 13, "mask": 0x2000, "active_low": True},
    "led2_green": {"kind": "gpio-out", "port_base": 0x42021C00, "pin": 14, "mask": 0x4000, "active_low": True},
    "led2_blue": {"kind": "gpio-out", "port_base": 0x42021C00, "pin": 15, "mask": 0x8000, "active_low": True},
}
