//! GENERATED by lamella-bsp-gen from ext/atio1-xpro/extension.toml + ext/standards/xplained-pro.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-ext . atio1-xpro
pub const EXTENSION: &str = "atio1-xpro";
pub const VENDOR: &str = "microchip";
pub const STANDARD: &str = "xplained-pro";

/// -- the kit identifier its identification chip carries, as the `nnnn` field of an
/// `nnnnrrssssssssss` serial. It is how a FITTED extension can be told from an assumed
/// one -- but on a kit with an embedded debugger the identification line reaches the
/// DEBUGGER rather than an MCU pad, so this is a host tool's reading and not a
/// program's --
pub const KIT_IDENTIFIER: u32 = 1775;

/// -- what this board needs a host socket to bring out. Each POSITION is the connector
/// standard's own name for a hole, never a pad: this file cannot name a pad, because it does
/// not know which host it is plugged into. A host's `CONNECTOR_<socket>_<POSITION>_*`
/// constants carry the pad behind each one, and the two are joined on the position name --
pub const POSITION_COUNT: u32 = 14;
pub const POSITION_SPI_SS_A_PIN: u32 = 15;
pub const POSITION_SPI_MOSI_PIN: u32 = 16;
pub const POSITION_SPI_MISO_PIN: u32 = 17;
pub const POSITION_SPI_SCK_PIN: u32 = 18;
pub const POSITION_I2C_SDA_PIN: u32 = 11;
pub const POSITION_I2C_SCL_PIN: u32 = 12;
pub const POSITION_PWM_P_PIN: u32 = 7;
pub const POSITION_SPI_SS_B_PIN: u32 = 10;
pub const POSITION_IRQ_PIN: u32 = 9;
pub const POSITION_ADC_P_PIN: u32 = 3;
pub const POSITION_ADC_N_PIN: u32 = 4;
pub const POSITION_PWM_N_PIN: u32 = 8;
pub const POSITION_GPIO1_PIN: u32 = 5;
pub const POSITION_GPIO2_PIN: u32 = 6;

/// -- the buses this board presents, each naming the socket positions it rides. A host
/// resolves them through the same socket constants; which of its controllers is behind
/// them is the HOST's fact and appears nowhere here --
pub const BUS_COUNT: u32 = 2;
pub const BUS_SD_SPI_KIND: &str = "spi";
pub const BUS_SD_SPI_SS: &str = "spi_ss_a";
pub const BUS_SD_SPI_MOSI: &str = "spi_mosi";
pub const BUS_SD_SPI_MISO: &str = "spi_miso";
pub const BUS_SD_SPI_SCK: &str = "spi_sck";
pub const BUS_SENSOR_I2C_KIND: &str = "i2c";
pub const BUS_SENSOR_I2C_SDA: &str = "i2c_sda";
pub const BUS_SENSOR_I2C_SCL: &str = "i2c_scl";

/// -- the devices a host reaches. A LINE-wired device names the socket position it sits on
/// and its active level; a BUS-wired one names the bus and, where a document states one, its
/// address. An active level of `unknown` is a document that does not say, recorded as such:
/// no polarity constant is emitted for it, so a program that assumed one fails to compile --
pub const DEVICE_COUNT: u32 = 11;
pub const DEVICE_TEMPERATURE_KIND: &str = "i2c-device";
pub const DEVICE_TEMPERATURE_BUS: &str = "sensor-i2c";
pub const DEVICE_TEMPERATURE_PART: &str = "at30tse758";
pub const DEVICE_TEMPERATURE_ADDRESS: u32 = 0x4F;
pub const DEVICE_EEPROM_KIND: &str = "i2c-device";
pub const DEVICE_EEPROM_BUS: &str = "sensor-i2c";
pub const DEVICE_EEPROM_PART: &str = "at30tse758";
pub const DEVICE_EEPROM_ADDRESS: u32 = 0x57;
pub const DEVICE_SDCARD_KIND: &str = "spi-device";
pub const DEVICE_SDCARD_BUS: &str = "sd-spi";
pub const DEVICE_SDCARD_PART: &str = "microsd-socket";
pub const DEVICE_LED_KIND: &str = "gpio-out";
pub const DEVICE_LED_POSITION: &str = "pwm_p";
pub const DEVICE_LED_ACTIVE_LOW: u32 = 1;
pub const DEVICE_SD_DETECT_KIND: &str = "gpio-in";
pub const DEVICE_SD_DETECT_POSITION: &str = "spi_ss_b";
pub const DEVICE_SD_DETECT_ACTIVE_LOW: u32 = 1;
pub const DEVICE_TEMP_ALERT_KIND: &str = "gpio-in";
pub const DEVICE_TEMP_ALERT_POSITION: &str = "irq";
pub const DEVICE_LIGHT_KIND: &str = "analog-in";
pub const DEVICE_LIGHT_POSITION: &str = "adc_p";
pub const DEVICE_FILTER_OUT_KIND: &str = "analog-in";
pub const DEVICE_FILTER_OUT_POSITION: &str = "adc_n";
pub const DEVICE_FILTER_IN_KIND: &str = "gpio-out";
pub const DEVICE_FILTER_IN_POSITION: &str = "pwm_n";
pub const DEVICE_GPIO1_KIND: &str = "gpio-out";
pub const DEVICE_GPIO1_POSITION: &str = "gpio1";
pub const DEVICE_GPIO2_KIND: &str = "gpio-out";
pub const DEVICE_GPIO2_POSITION: &str = "gpio2";
