// GENERATED by lamella-bsp-gen from csp/sam4l/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4l
//
// The sam4l instance map: where each block copy sits and its per-instance ids.
// Layout offsets live in the *Layout classes; wiring lives in the per-board *Bindings.
namespace Lamella.Generated
{
    public sealed class Sam4lInstances
    {
        private Sam4lInstances() { }

        public const uint GPIO_PORT2_BASE = 0x400E1400;
    }
}
