// GENERATED by lamella-bsp-gen from csp/sam4l/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Sam4lInstances
    {
        private Sam4lInstances() { }

        public const uint GPIO_PORT2_BASE = 0x400E1400;
    }
}
