// GENERATED by lamella-bsp-gen from bsp/nucleo-l476rg/board.toml + csp/stm32l476/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32l476
//
// The nucleo-l476rg board bindings as Swift constants, name/value-identical to NucleoL476rgBindings.g.cs:
// every value below is a generation-time literal derived from the strata. Board truth
// lives in board.toml, never here.

public enum NucleoL476rgBindings {
    // -- identity --
    public static let BOARD_MODEL: UInt16 = 8

    // -- VCP: an st-usart binding descriptor --
    public static let VCP_BASE: UInt32 = 0x40004400
    public static let VCP_RCC_EN_REG: UInt32 = 0x40021058
    public static let VCP_RCC_EN_MASK: UInt32 = 0x20000
    public static let VCP_PORT_RCC_EN_REG: UInt32 = 0x4002104C
    public static let VCP_PORT_RCC_EN_MASK: UInt32 = 0x1
    public static let VCP_MODER_REG: UInt32 = 0x48000000
    public static let VCP_MODER_MASK: UInt32 = 0xF0
    public static let VCP_MODER_VALUE: UInt32 = 0xA0
    public static let VCP_AFRL_REG: UInt32 = 0x48000020
    public static let VCP_AFRL_MASK: UInt32 = 0xFF00
    public static let VCP_AFRL_VALUE: UInt32 = 0x7700
    public static let VCP_PCLK1_HZ: UInt32 = 4000000
    public static let VCP_BRR_115200_MSI_4MHZ: UInt32 = 0x23
}
