// GENERATED by lamella-bsp-gen from bsp/nucleo-l476rg/board.toml + csp/stm32l476/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32l476
//
// The nucleo-l476rg board bindings as Swift constants, name/value-identical to NucleoL476rgBindings.g.cs:
// every value below is a generation-time literal derived from the strata. Board truth
// lives in board.toml, never here.

public enum NucleoL476rgBindings {
    // -- identity --
    public static let BOARD_MODEL: UInt16 = 8
    public static let BOARD_VENDOR: String = "St"

    /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
    /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
    /// peripherals of the same kind can share no register at all, so a consumer that selects a
    /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
    /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
    /// name a driver; and a uart is a different register map on every family, so the kind does
    /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
    public static let VCP_DRIVER_FAMILY: String = "stm32l476-usart"

    // -- VCP: an st-usart binding descriptor --
    public static let VCP_BASE: UInt32 = 0x40004400
    public static let VCP_RCC_EN_REG: UInt32 = 0x40021058
    public static let VCP_RCC_EN_MASK: UInt32 = 0x20000
    public static let VCP_TX_PORT_RCC_EN_REG: UInt32 = 0x4002104C
    public static let VCP_TX_PORT_RCC_EN_MASK: UInt32 = 0x1
    public static let VCP_TX_MODER_REG: UInt32 = 0x48000000
    public static let VCP_TX_MODER_MASK: UInt32 = 0x30
    public static let VCP_TX_MODER_VALUE: UInt32 = 0x20
    public static let VCP_TX_AFR_REG: UInt32 = 0x48000020
    public static let VCP_TX_AFR_MASK: UInt32 = 0xF00
    public static let VCP_TX_AFR_VALUE: UInt32 = 0x700
    public static let VCP_RX_PORT_RCC_EN_REG: UInt32 = 0x4002104C
    public static let VCP_RX_PORT_RCC_EN_MASK: UInt32 = 0x1
    public static let VCP_RX_MODER_REG: UInt32 = 0x48000000
    public static let VCP_RX_MODER_MASK: UInt32 = 0xC0
    public static let VCP_RX_MODER_VALUE: UInt32 = 0x80
    public static let VCP_RX_AFR_REG: UInt32 = 0x48000020
    public static let VCP_RX_AFR_MASK: UInt32 = 0xF000
    public static let VCP_RX_AFR_VALUE: UInt32 = 0x7000
    public static let VCP_PCLK_HZ: UInt32 = 4000000
    public static let VCP_BRR_115200_MSI_4MHZ: UInt32 = 0x23
}
