// GENERATED by lamella-bsp-gen from csp/samd10/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd10
//
// The samd10 instance map as Swift constants, name/value-identical to Samd10Instances.g.cs:
// where each block copy sits and its per-instance ids. Block-register offsets are not
// emitted for Swift: a firmware project states its block constants and reads this file
// for every placed-instance fact.

public enum Samd10Instances {
    public static let PM_BASE: UInt32 = 0x40000400
    public static let PM_IRQ: UInt32 = 0
    public static let GCLK_BASE: UInt32 = 0x40000C00
    public static let PORTA_BASE: UInt32 = 0x41004400
    public static let DSU_BASE: UInt32 = 0x41002000
    public static let NVMCTRL_BASE: UInt32 = 0x41004000
    public static let NVMCTRL_GCLK_CORE_ID: UInt32 = 13
    public static let NVMCTRL_IRQ: UInt32 = 5
    public static let SERCOM0_BASE: UInt32 = 0x42000800
    public static let SERCOM0_GCLK_CORE_ID: UInt32 = 14
    public static let SERCOM0_APBC_BIT: UInt32 = 2
    public static let SERCOM0_APBC_MASK: UInt32 = 0x4
    public static let SERCOM0_IRQ: UInt32 = 9
    public static let SERCOM1_BASE: UInt32 = 0x42000C00
    public static let SERCOM1_GCLK_CORE_ID: UInt32 = 15
    public static let SERCOM1_APBC_BIT: UInt32 = 3
    public static let SERCOM1_APBC_MASK: UInt32 = 0x8
    public static let SERCOM1_IRQ: UInt32 = 10
    public static let SERCOM2_BASE: UInt32 = 0x42001000
    public static let SERCOM2_GCLK_CORE_ID: UInt32 = 16
    public static let SERCOM2_APBC_BIT: UInt32 = 4
    public static let SERCOM2_APBC_MASK: UInt32 = 0x10
    public static let SERCOM2_IRQ: UInt32 = 11
}
