// GENERATED by lamella-bsp-gen from csp/samd10/blocks/gclk.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd10
//
// The samd10 gclk BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samd10Instances. Widths are access widths.

public enum Samd10GclkLayout {
    // -- register offsets (block-relative) + access widths --
    public static let CTRL_OFF: UInt32 = 0x0
    public static let CTRL_WIDTH: Int32 = 8
    public static let STATUS_OFF: UInt32 = 0x1
    public static let STATUS_WIDTH: Int32 = 8
    public static let CLKCTRL_OFF: UInt32 = 0x2
    public static let CLKCTRL_WIDTH: Int32 = 16
    public static let GENCTRL_OFF: UInt32 = 0x4
    public static let GENCTRL_WIDTH: Int32 = 32
    public static let GENDIV_OFF: UInt32 = 0x8
    public static let GENDIV_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let CTRL_SWRST: UInt32 = 0x1
    public static let CTRL_SWRST_LSB: UInt32 = 0
    public static let STATUS_SYNCBUSY: UInt32 = 0x80
    public static let STATUS_SYNCBUSY_LSB: UInt32 = 7
    public static let CLKCTRL_ID: UInt32 = 0x3F
    public static let CLKCTRL_ID_LSB: UInt32 = 0
    public static let CLKCTRL_GEN: UInt32 = 0xF00
    public static let CLKCTRL_GEN_LSB: UInt32 = 8
    public static let CLKCTRL_CLKEN: UInt32 = 0x4000
    public static let CLKCTRL_CLKEN_LSB: UInt32 = 14
    public static let CLKCTRL_WRTLOCK: UInt32 = 0x8000
    public static let CLKCTRL_WRTLOCK_LSB: UInt32 = 15
    public static let GENCTRL_ID: UInt32 = 0xF
    public static let GENCTRL_ID_LSB: UInt32 = 0
    public static let GENCTRL_SRC: UInt32 = 0x1F00
    public static let GENCTRL_SRC_LSB: UInt32 = 8
    public static let GENCTRL_GENEN: UInt32 = 0x10000
    public static let GENCTRL_GENEN_LSB: UInt32 = 16
    public static let GENDIV_ID: UInt32 = 0xF
    public static let GENDIV_ID_LSB: UInt32 = 0
    public static let GENDIV_DIV: UInt32 = 0xFFFF00
    public static let GENDIV_DIV_LSB: UInt32 = 8
}
