//! GENERATED by lamella-bsp-gen from bsp/arduino-giga-r1-wifi/board.toml + csp/stm32h7/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32h7

pub const BOARD_MODEL: u16 = 33;
pub const BOARD_VENDOR: &str = "Arduino";

pub const LED_RED_PORT_BASE: u32 = 0x58022000;
pub const LED_RED_PIN: u32 = 12;
pub const LED_RED_MASK: u32 = 0x1000;
pub const LED_RED_ACTIVE_LOW: u32 = 1;
pub const LED_GREEN_PORT_BASE: u32 = 0x58022400;
pub const LED_GREEN_PIN: u32 = 13;
pub const LED_GREEN_MASK: u32 = 0x2000;
pub const LED_GREEN_ACTIVE_LOW: u32 = 1;
pub const LED_BLUE_PORT_BASE: u32 = 0x58021000;
pub const LED_BLUE_PIN: u32 = 3;
pub const LED_BLUE_MASK: u32 = 0x8;
pub const LED_BLUE_ACTIVE_LOW: u32 = 1;
pub const BUTTON_PORT_BASE: u32 = 0x58020800;
pub const BUTTON_PIN: u32 = 13;
pub const BUTTON_MASK: u32 = 0x2000;
pub const BUTTON_ACTIVE_LOW: u32 = 0;
