// GENERATED by lamella-bsp-gen from bsp/samd20-xpro/board.toml + csp/samd20/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Samd20XproBindings
    {
        private Samd20XproBindings() { }

        public const int BOARD_MODEL = 48;
        public const string BOARD_VENDOR = "Microchip";
        public const uint CARRIER_USB_VID = 0x03EB;

        /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
        /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
        /// peripherals of the same kind can share no register at all, so a consumer that selects a
        /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
        /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
        /// name a driver; and a uart is a different register map on every family, so the kind does
        /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
        public const string VCP_DRIVER_FAMILY = "samd20-sercom";

        public const uint VCP_SERCOM_BASE = 0x42001400;
        public const uint VCP_IRQ = 10;
        public const uint VCP_GCLK_CLKCTRL_VALUE = 0x4010;
        public const uint VCP_APBC_MASK = 0x20;
        public const uint VCP_PMUX_REG = 0x4100443C;
        public const uint VCP_PMUX_PAIR = 0x22;
        public const uint VCP_PMUX_TX_REG = 0x4100443C;
        public const uint VCP_PMUX_TX_MASK = 0xF;
        public const uint VCP_PMUX_TX_VALUE = 0x2;
        public const uint VCP_PMUX_RX_REG = 0x4100443C;
        public const uint VCP_PMUX_RX_MASK = 0xF0;
        public const uint VCP_PMUX_RX_VALUE = 0x20;
        public const uint VCP_PINCFG_TX_REG = 0x41004458;
        public const uint VCP_PINCFG_RX_REG = 0x41004459;
        public const uint VCP_TXPO = 1;
        public const uint VCP_RXPO = 3;
        public const uint VCP_BAUD_115200_OSC8M_8MHZ = 0xC505;

        public const uint LED0_PORT_BASE = 0x41004400;
        public const uint LED0_PIN = 14;
        public const uint LED0_MASK = 0x4000;
        public const uint LED0_ACTIVE_LOW = 1;
        public const uint BUTTON0_PORT_BASE = 0x41004400;
        public const uint BUTTON0_PIN = 15;
        public const uint BUTTON0_MASK = 0x8000;
        public const uint BUTTON0_ACTIVE_LOW = 1;
    }
}
