//! GENERATED by lamella-bsp-gen from ext/atethernet1-xpro/extension.toml + ext/standards/xplained-pro.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-ext . atethernet1-xpro
pub const EXTENSION: &str = "atethernet1-xpro";
pub const VENDOR: &str = "microchip";
pub const STANDARD: &str = "xplained-pro";

/// -- the kit identifier its identification chip carries, as the `nnnn` field of an
/// `nnnnrrssssssssss` serial. It is how a FITTED extension can be told from an assumed
/// one -- but on a kit with an embedded debugger the identification line reaches the
/// DEBUGGER rather than an MCU pad, so this is a host tool's reading and not a
/// program's --
pub const KIT_IDENTIFIER: u32 = 2258;

/// -- what this board needs a host socket to bring out. Each POSITION is the connector
/// standard's own name for a hole, never a pad: this file cannot name a pad, because it does
/// not know which host it is plugged into. A host's `CONNECTOR_<socket>_<POSITION>_*`
/// constants carry the pad behind each one, and the two are joined on the position name --
pub const POSITION_COUNT: u32 = 7;
pub const POSITION_SPI_SS_A_PIN: u32 = 15;
pub const POSITION_SPI_MOSI_PIN: u32 = 16;
pub const POSITION_SPI_MISO_PIN: u32 = 17;
pub const POSITION_SPI_SCK_PIN: u32 = 18;
pub const POSITION_GPIO2_PIN: u32 = 6;
pub const POSITION_IRQ_PIN: u32 = 9;
pub const POSITION_GPIO1_PIN: u32 = 5;

/// -- the buses this board presents, each naming the socket positions it rides. A host
/// resolves them through the same socket constants; which of its controllers is behind
/// them is the HOST's fact and appears nowhere here --
pub const BUS_COUNT: u32 = 1;
pub const BUS_ETH_SPI_KIND: &str = "spi";
pub const BUS_ETH_SPI_SS: &str = "spi_ss_a";
pub const BUS_ETH_SPI_MOSI: &str = "spi_mosi";
pub const BUS_ETH_SPI_MISO: &str = "spi_miso";
pub const BUS_ETH_SPI_SCK: &str = "spi_sck";

/// -- the devices a host reaches. A LINE-wired device names the socket position it sits on
/// and its active level; a BUS-wired one names the bus and, where a document states one, its
/// address. An active level of `unknown` is a document that does not say, recorded as such:
/// no polarity constant is emitted for it, so a program that assumed one fails to compile --
pub const DEVICE_COUNT: u32 = 4;
pub const DEVICE_NRST_KIND: &str = "gpio-out";
pub const DEVICE_NRST_POSITION: &str = "gpio2";
pub const DEVICE_NRST_ACTIVE_LOW: u32 = 1;
pub const DEVICE_INTRN_KIND: &str = "gpio-in";
pub const DEVICE_INTRN_POSITION: &str = "irq";
pub const DEVICE_INTRN_ACTIVE_LOW: u32 = 1;
pub const DEVICE_PME_KIND: &str = "gpio-in";
pub const DEVICE_PME_POSITION: &str = "gpio1";
pub const DEVICE_PME_ACTIVE_LOW: u32 = 1;
pub const DEVICE_ETHERNET_KIND: &str = "spi-device";
pub const DEVICE_ETHERNET_BUS: &str = "eth-spi";
pub const DEVICE_ETHERNET_PART: &str = "ksz8851snl";
