// GENERATED by lamella-bsp-gen from csp/sam4s/blocks/flash.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Sam4sFlashLayout
    {
        private Sam4sFlashLayout() { }



        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 512;
    }
}
