// GENERATED by lamella-bsp-gen from csp/stm32l073/blocks/gpio.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32l073
//
// The stm32l073 gpio BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Stm32l073Instances. Widths are access widths.

public enum Stm32l073GpioLayout {
    // -- register offsets (block-relative) + access widths --
    public static let MODER_OFF: UInt32 = 0x0
    public static let MODER_WIDTH: Int32 = 32
    public static let OTYPER_OFF: UInt32 = 0x4
    public static let OTYPER_WIDTH: Int32 = 32
    public static let OSPEEDR_OFF: UInt32 = 0x8
    public static let OSPEEDR_WIDTH: Int32 = 32
    public static let PUPDR_OFF: UInt32 = 0xC
    public static let PUPDR_WIDTH: Int32 = 32
    public static let IDR_OFF: UInt32 = 0x10
    public static let IDR_WIDTH: Int32 = 32
    public static let ODR_OFF: UInt32 = 0x14
    public static let ODR_WIDTH: Int32 = 32
    public static let BSRR_OFF: UInt32 = 0x18
    public static let BSRR_WIDTH: Int32 = 32
    public static let AFRL_OFF: UInt32 = 0x20
    public static let AFRL_WIDTH: Int32 = 32
    public static let AFRH_OFF: UInt32 = 0x24
    public static let AFRH_WIDTH: Int32 = 32
    public static let BRR_OFF: UInt32 = 0x28
    public static let BRR_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let MODER_MODE2: UInt32 = 0x30
    public static let MODER_MODE2_LSB: UInt32 = 4
    public static let MODER_MODE3: UInt32 = 0xC0
    public static let MODER_MODE3_LSB: UInt32 = 6
    public static let MODER_MODE5: UInt32 = 0xC00
    public static let MODER_MODE5_LSB: UInt32 = 10
    public static let AFRL_AFSEL0: UInt32 = 0xF
    public static let AFRL_AFSEL0_LSB: UInt32 = 0
    public static let AFRL_AFSEL1: UInt32 = 0xF0
    public static let AFRL_AFSEL1_LSB: UInt32 = 4
    public static let AFRL_AFSEL2: UInt32 = 0xF00
    public static let AFRL_AFSEL2_LSB: UInt32 = 8
    public static let AFRL_AFSEL3: UInt32 = 0xF000
    public static let AFRL_AFSEL3_LSB: UInt32 = 12
    public static let AFRL_AFSEL4: UInt32 = 0xF0000
    public static let AFRL_AFSEL4_LSB: UInt32 = 16
    public static let AFRL_AFSEL5: UInt32 = 0xF00000
    public static let AFRL_AFSEL5_LSB: UInt32 = 20
    public static let AFRL_AFSEL6: UInt32 = 0xF000000
    public static let AFRL_AFSEL6_LSB: UInt32 = 24
    public static let AFRL_AFSEL7: UInt32 = 0xF0000000
    public static let AFRL_AFSEL7_LSB: UInt32 = 28
    public static let AFRH_AFSEL8: UInt32 = 0xF
    public static let AFRH_AFSEL8_LSB: UInt32 = 0
    public static let AFRH_AFSEL9: UInt32 = 0xF0
    public static let AFRH_AFSEL9_LSB: UInt32 = 4
    public static let AFRH_AFSEL10: UInt32 = 0xF00
    public static let AFRH_AFSEL10_LSB: UInt32 = 8
    public static let AFRH_AFSEL11: UInt32 = 0xF000
    public static let AFRH_AFSEL11_LSB: UInt32 = 12
    public static let AFRH_AFSEL12: UInt32 = 0xF0000
    public static let AFRH_AFSEL12_LSB: UInt32 = 16
    public static let AFRH_AFSEL13: UInt32 = 0xF00000
    public static let AFRH_AFSEL13_LSB: UInt32 = 20
    public static let AFRH_AFSEL14: UInt32 = 0xF000000
    public static let AFRH_AFSEL14_LSB: UInt32 = 24
    public static let AFRH_AFSEL15: UInt32 = 0xF0000000
    public static let AFRH_AFSEL15_LSB: UInt32 = 28

    // -- block constants --
    public static let MODER_MODE_INPUT: UInt32 = 0
    public static let MODER_MODE_OUTPUT: UInt32 = 1
    public static let MODER_MODE_AF: UInt32 = 2
    public static let MODER_MODE_ANALOG: UInt32 = 3
    public static let PUPD_NONE: UInt32 = 0
    public static let PUPD_UP: UInt32 = 1
    public static let PUPD_DOWN: UInt32 = 2
    public static let OTYPE_PUSH_PULL: UInt32 = 0
    public static let OTYPE_OPEN_DRAIN: UInt32 = 1
}
