//! GENERATED by lamella-bsp-gen from csp/stm32l4r5/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32l4r5
//!
//! The stm32l4r5 instance map as Rust consts: where each block copy sits and its per-instance ids.
//! Each block's layout is in its own layout module beside this file.

pub const GPIOA_BASE: u32 = 0x48000000;
pub const GPIOA_RCC_EN_OFF: u32 = 76;
pub const GPIOA_RCC_EN_BIT: u32 = 0;
pub const GPIOA_RCC_EN_MASK: u32 = 0x1;
pub const GPIOB_BASE: u32 = 0x48000400;
pub const GPIOB_RCC_EN_OFF: u32 = 76;
pub const GPIOB_RCC_EN_BIT: u32 = 1;
pub const GPIOB_RCC_EN_MASK: u32 = 0x2;
pub const GPIOC_BASE: u32 = 0x48000800;
pub const GPIOC_RCC_EN_OFF: u32 = 76;
pub const GPIOC_RCC_EN_BIT: u32 = 2;
pub const GPIOC_RCC_EN_MASK: u32 = 0x4;
pub const GPIOD_BASE: u32 = 0x48000C00;
pub const GPIOD_RCC_EN_OFF: u32 = 76;
pub const GPIOD_RCC_EN_BIT: u32 = 3;
pub const GPIOD_RCC_EN_MASK: u32 = 0x8;
pub const GPIOE_BASE: u32 = 0x48001000;
pub const GPIOE_RCC_EN_OFF: u32 = 76;
pub const GPIOE_RCC_EN_BIT: u32 = 4;
pub const GPIOE_RCC_EN_MASK: u32 = 0x10;
pub const GPIOF_BASE: u32 = 0x48001400;
pub const GPIOF_RCC_EN_OFF: u32 = 76;
pub const GPIOF_RCC_EN_BIT: u32 = 5;
pub const GPIOF_RCC_EN_MASK: u32 = 0x20;
pub const GPIOG_BASE: u32 = 0x48001800;
pub const GPIOG_RCC_EN_OFF: u32 = 76;
pub const GPIOG_RCC_EN_BIT: u32 = 6;
pub const GPIOG_RCC_EN_MASK: u32 = 0x40;
pub const GPIOH_BASE: u32 = 0x48001C00;
pub const GPIOH_RCC_EN_OFF: u32 = 76;
pub const GPIOH_RCC_EN_BIT: u32 = 7;
pub const GPIOH_RCC_EN_MASK: u32 = 0x80;
pub const GPIOI_BASE: u32 = 0x48002000;
pub const GPIOI_RCC_EN_OFF: u32 = 76;
pub const GPIOI_RCC_EN_BIT: u32 = 8;
pub const GPIOI_RCC_EN_MASK: u32 = 0x100;
pub const LPUART1_BASE: u32 = 0x40008000;
pub const LPUART1_RCC_EN_OFF: u32 = 92;
pub const LPUART1_RCC_EN_BIT: u32 = 0;
pub const LPUART1_RCC_EN_MASK: u32 = 0x1;
pub const PWR_BASE: u32 = 0x40007000;
pub const PWR_RCC_EN_OFF: u32 = 88;
pub const PWR_RCC_EN_BIT: u32 = 28;
pub const PWR_RCC_EN_MASK: u32 = 0x10000000;
pub const RCC_BASE: u32 = 0x40021000;
