// GENERATED by lamella-bsp-gen from bsp/microchip-sam4s-xpro/board.toml + csp/sam4s/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4s
//
// The microchip-sam4s-xpro board bindings (resolved against the sam4s chip strata): every value below is a
// generation-time literal derived from the strata -- role descriptors, module control
// lines, and the carrier identity. The board's facts are stated in board.toml.
namespace Lamella.Generated
{
    public sealed class MicrochipSam4sXproBindings
    {
        private MicrochipSam4sXproBindings() { }

        // -- identity --
        public const int BOARD_MODEL = 3;
        public const string BOARD_VENDOR = "Microchip";
        public const uint CARRIER_USB_VID = 0x03EB;
        public const uint CARRIER_USB_PID = 0x2111;
        public const uint DEVICE_COUNT = 0;
    }
}
