# GENERATED by lamella-bsp-gen from bsp/nucleo-u5a5zj-q/board.toml + csp/stm32u5a5/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32u5a5

BOARD = "nucleo-u5a5zj-q"
BOARD_MODEL = 40
BOARD_VENDOR = "St"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
VCP = "vcp"

CARRIER = {
    "kind": "stlink-vcp",
    "role": "vcp",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
    "vcp": {
        "kind": "uart",
        "driver_family": "stm32u5a5-usart",
        "instance": "usart1",
        "base": 0x40013800,
        "rcc_en_reg": 0x46020CA4,
        "rcc_en_mask": 0x4000,
        "pclk_hz": 4000000,
        "tx_port_rcc_en_reg": 0x46020C8C,
        "tx_port_rcc_en_mask": 0x1,
        "tx_moder_reg": 0x42020000,
        "tx_moder_mask": 0xC0000,
        "tx_moder_value": 0x80000,
        "tx_afr_reg": 0x42020024,
        "tx_afr_mask": 0xF0,
        "tx_afr_value": 0x70,
        "rx_port_rcc_en_reg": 0x46020C8C,
        "rx_port_rcc_en_mask": 0x1,
        "rx_moder_reg": 0x42020000,
        "rx_moder_mask": 0x300000,
        "rx_moder_value": 0x200000,
        "rx_afr_reg": 0x42020024,
        "rx_afr_mask": 0xF00,
        "rx_afr_value": 0x700,
        "brr_115200_msis_4mhz": 0x23,
    },
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Each row carries whatever this family's record declares -- a base always, and per-instance
# facts like a clock channel or a bus-enable bit where the family states them. Register offsets
# and bit encodings belong to the driver that knows the block, not here.
INSTANCES = {
    "gpioa": {"block": "gpio", "base": 0x42020000, "rcc_en_off": 0x8C, "rcc_en_bit": 0x0},
    "gpiob": {"block": "gpio", "base": 0x42020400, "rcc_en_off": 0x8C, "rcc_en_bit": 0x1},
    "gpioc": {"block": "gpio", "base": 0x42020800, "rcc_en_off": 0x8C, "rcc_en_bit": 0x2},
    "gpiod": {"block": "gpio", "base": 0x42020C00, "rcc_en_off": 0x8C, "rcc_en_bit": 0x3},
    "gpioe": {"block": "gpio", "base": 0x42021000, "rcc_en_off": 0x8C, "rcc_en_bit": 0x4},
    "gpiof": {"block": "gpio", "base": 0x42021400, "rcc_en_off": 0x8C, "rcc_en_bit": 0x5},
    "gpiog": {"block": "gpio", "base": 0x42021800, "rcc_en_off": 0x8C, "rcc_en_bit": 0x6},
    "gpioh": {"block": "gpio", "base": 0x42021C00, "rcc_en_off": 0x8C, "rcc_en_bit": 0x7},
    "gpioi": {"block": "gpio", "base": 0x42022000, "rcc_en_off": 0x8C, "rcc_en_bit": 0x8},
    "gpioj": {"block": "gpio", "base": 0x42022400, "rcc_en_off": 0x8C, "rcc_en_bit": 0x9},
    "usart1": {"block": "usart", "base": 0x40013800, "rcc_en_off": 0xA4, "rcc_en_bit": 0xE},
    "rcc": {"block": "rcc", "base": 0x46020C00},
}

PLANS = {
    "msis-4mhz": {"default": True, "source": "msis", "msis_hz": 4000000, "pclk_hz": 4000000},
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
}
