//! GENERATED by lamella-bsp-gen from bsp/p1am-100/board.toml + csp/samd21/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21

pub const BOARD_MODEL: u16 = 42;
pub const BOARD_VENDOR: &str = "AutomationDirect";

pub const LED_PORT_BASE: u32 = 0x41004480;
pub const LED_PIN: u32 = 8;
pub const LED_MASK: u32 = 0x100;
pub const LED_ACTIVE_LOW: u32 = 0;
pub const RUN_SWITCH_PORT_BASE: u32 = 0x41004400;
pub const RUN_SWITCH_PIN: u32 = 28;
pub const RUN_SWITCH_MASK: u32 = 0x10000000;
pub const RUN_SWITCH_ACTIVE_LOW: u32 = 1;
pub const BASE_ENABLE_PORT_BASE: u32 = 0x41004480;
pub const BASE_ENABLE_PIN: u32 = 9;
pub const BASE_ENABLE_MASK: u32 = 0x200;
pub const BASE_ENABLE_ACTIVE_LOW: u32 = 0;
pub const BASE_CS_PORT_BASE: u32 = 0x41004400;
pub const BASE_CS_PIN: u32 = 4;
pub const BASE_CS_MASK: u32 = 0x10;
pub const BASE_CS_ACTIVE_LOW: u32 = 1;
pub const BASE_READY_PORT_BASE: u32 = 0x41004400;
pub const BASE_READY_PIN: u32 = 5;
pub const BASE_READY_MASK: u32 = 0x20;
pub const BASE_READY_ACTIVE_LOW: u32 = 0;
pub const SD_CS_PORT_BASE: u32 = 0x41004400;
pub const SD_CS_PIN: u32 = 14;
pub const SD_CS_MASK: u32 = 0x4000;
