// GENERATED by lamella-bsp-gen -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Rp2350UartFacts
    {
        private Rp2350UartFacts() { }

        public const uint XOSC = 0x40048000;
        public const uint CLOCKS = 0x40010000;
        public const uint RESETS = 0x40020000;
        public const uint RESETS_CLR = 0x40023000;
        public const uint IO_BANK0 = 0x40028000;
        public const uint PADS_BANK0 = 0x40038000;
        public const uint UART0 = 0x40070000;

        public const uint XOSC_CTRL = 0x40048000;
        public const uint XOSC_STATUS = 0x40048004;
        public const uint XOSC_STARTUP = 0x4004800C;
        public const uint CLK_PERI_CTRL = 0x40010048;
        public const uint CLK_PERI_DIV = 0x4001004C;
        public const uint RESETS_RESET_CLR = 0x40023000;
        public const uint RESETS_RESET_DONE = 0x40020008;
        public const uint IO_BANK0_GPIO0_CTRL = 0x40028004;
        public const uint IO_BANK0_GPIO1_CTRL = 0x4002800C;
        public const uint PADS_BANK0_GPIO0 = 0x40038004;
        public const uint PADS_BANK0_GPIO1 = 0x40038008;
        public const uint UARTDR = 0x40070000;
        public const uint UARTFR = 0x40070018;
        public const uint UARTIBRD = 0x40070024;
        public const uint UARTFBRD = 0x40070028;
        public const uint UARTLCR_H = 0x4007002C;
        public const uint UARTCR = 0x40070030;

        public const uint XOSC_CTRL_ENABLE = 0xFFF000;
        public const uint XOSC_CTRL_ENABLE_LSB = 12;
        public const uint XOSC_CTRL_FREQ_RANGE = 0xFFF;
        public const uint XOSC_CTRL_FREQ_RANGE_LSB = 0;
        public const uint XOSC_STATUS_STABLE = 0x80000000;
        public const uint XOSC_STATUS_STABLE_LSB = 31;
        public const uint XOSC_STARTUP_DELAY = 0x3FFF;
        public const uint XOSC_STARTUP_DELAY_LSB = 0;
        public const uint CLK_PERI_CTRL_AUXSRC = 0xE0;
        public const uint CLK_PERI_CTRL_AUXSRC_LSB = 5;
        public const uint CLK_PERI_CTRL_ENABLE = 0x800;
        public const uint CLK_PERI_CTRL_ENABLE_LSB = 11;
        public const uint CLK_PERI_DIV_INT = 0x30000;
        public const uint CLK_PERI_DIV_INT_LSB = 16;
        public const uint RESETS_RESET_CLR_UART0 = 0x4000000;
        public const uint RESETS_RESET_CLR_UART0_LSB = 26;
        public const uint RESETS_RESET_CLR_PADS_BANK0 = 0x200;
        public const uint RESETS_RESET_CLR_PADS_BANK0_LSB = 9;
        public const uint RESETS_RESET_CLR_IO_BANK0 = 0x40;
        public const uint RESETS_RESET_CLR_IO_BANK0_LSB = 6;
        public const uint RESETS_RESET_DONE_UART0 = 0x4000000;
        public const uint RESETS_RESET_DONE_UART0_LSB = 26;
        public const uint RESETS_RESET_DONE_PADS_BANK0 = 0x200;
        public const uint RESETS_RESET_DONE_PADS_BANK0_LSB = 9;
        public const uint RESETS_RESET_DONE_IO_BANK0 = 0x40;
        public const uint RESETS_RESET_DONE_IO_BANK0_LSB = 6;
        public const uint IO_BANK0_GPIO0_CTRL_FUNCSEL = 0x1F;
        public const uint IO_BANK0_GPIO0_CTRL_FUNCSEL_LSB = 0;
        public const uint IO_BANK0_GPIO1_CTRL_FUNCSEL = 0x1F;
        public const uint IO_BANK0_GPIO1_CTRL_FUNCSEL_LSB = 0;
        public const uint PADS_BANK0_GPIO0_IE = 0x40;
        public const uint PADS_BANK0_GPIO0_IE_LSB = 6;
        public const uint PADS_BANK0_GPIO0_OD = 0x80;
        public const uint PADS_BANK0_GPIO0_OD_LSB = 7;
        public const uint PADS_BANK0_GPIO0_ISO = 0x100;
        public const uint PADS_BANK0_GPIO0_ISO_LSB = 8;
        public const uint PADS_BANK0_GPIO1_IE = 0x40;
        public const uint PADS_BANK0_GPIO1_IE_LSB = 6;
        public const uint PADS_BANK0_GPIO1_OD = 0x80;
        public const uint PADS_BANK0_GPIO1_OD_LSB = 7;
        public const uint PADS_BANK0_GPIO1_ISO = 0x100;
        public const uint PADS_BANK0_GPIO1_ISO_LSB = 8;
        public const uint UARTDR_DATA = 0xFF;
        public const uint UARTDR_DATA_LSB = 0;
        public const uint UARTFR_BUSY = 0x8;
        public const uint UARTFR_BUSY_LSB = 3;
        public const uint UARTFR_RXFE = 0x10;
        public const uint UARTFR_RXFE_LSB = 4;
        public const uint UARTFR_TXFF = 0x20;
        public const uint UARTFR_TXFF_LSB = 5;
        public const uint UARTFR_TXFE = 0x80;
        public const uint UARTFR_TXFE_LSB = 7;
        public const uint UARTIBRD_BAUD_DIVINT = 0xFFFF;
        public const uint UARTIBRD_BAUD_DIVINT_LSB = 0;
        public const uint UARTFBRD_BAUD_DIVFRAC = 0x3F;
        public const uint UARTFBRD_BAUD_DIVFRAC_LSB = 0;
        public const uint UARTLCR_H_FEN = 0x10;
        public const uint UARTLCR_H_FEN_LSB = 4;
        public const uint UARTLCR_H_WLEN = 0x60;
        public const uint UARTLCR_H_WLEN_LSB = 5;
        public const uint UARTLCR_H_STP2 = 0x8;
        public const uint UARTLCR_H_STP2_LSB = 3;
        public const uint UARTLCR_H_EPS = 0x4;
        public const uint UARTLCR_H_EPS_LSB = 2;
        public const uint UARTLCR_H_PEN = 0x2;
        public const uint UARTLCR_H_PEN_LSB = 1;
        public const uint UARTLCR_H_SPS = 0x80;
        public const uint UARTLCR_H_SPS_LSB = 7;
        public const uint UARTCR_UARTEN = 0x1;
        public const uint UARTCR_UARTEN_LSB = 0;
        public const uint UARTCR_LBE = 0x80;
        public const uint UARTCR_LBE_LSB = 7;
        public const uint UARTCR_TXE = 0x100;
        public const uint UARTCR_TXE_LSB = 8;
        public const uint UARTCR_RXE = 0x200;
        public const uint UARTCR_RXE_LSB = 9;

        public const uint FIFO_DEPTH = 32;
        public const uint XOSC_HZ = 12000000;
        public const uint FUNCSEL_UART = 2;
    }
}
