// GENERATED by lamella-bsp-gen from csp/saml22/blocks/mclk.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . saml22
//
// The saml22 mclk BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Saml22Instances. Widths are access widths.

public enum Saml22MclkLayout {
    // -- register offsets (block-relative) + access widths --
    public static let AHBMASK_OFF: UInt32 = 0x10
    public static let AHBMASK_WIDTH: Int32 = 32
    public static let APBAMASK_OFF: UInt32 = 0x14
    public static let APBAMASK_WIDTH: Int32 = 32
    public static let APBBMASK_OFF: UInt32 = 0x18
    public static let APBBMASK_WIDTH: Int32 = 32
    public static let APBCMASK_OFF: UInt32 = 0x1C
    public static let APBCMASK_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let APBBMASK_PORT: UInt32 = 0x8
    public static let APBBMASK_PORT_LSB: UInt32 = 3
    public static let APBCMASK_SERCOM0: UInt32 = 0x2
    public static let APBCMASK_SERCOM0_LSB: UInt32 = 1
    public static let APBCMASK_SERCOM1: UInt32 = 0x4
    public static let APBCMASK_SERCOM1_LSB: UInt32 = 2
    public static let APBCMASK_SERCOM2: UInt32 = 0x8
    public static let APBCMASK_SERCOM2_LSB: UInt32 = 3
    public static let APBCMASK_SERCOM3: UInt32 = 0x10
    public static let APBCMASK_SERCOM3_LSB: UInt32 = 4
    public static let APBCMASK_SERCOM4: UInt32 = 0x20
    public static let APBCMASK_SERCOM4_LSB: UInt32 = 5
    public static let APBCMASK_SERCOM5: UInt32 = 0x40
    public static let APBCMASK_SERCOM5_LSB: UInt32 = 6
}
