// GENERATED by lamella-bsp-gen from bsp/microchip-samd21-cnano/board.toml + csp/samd21/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The microchip-samd21-cnano board bindings (resolved against the samd21 chip strata): every value below is a
// generation-time literal derived from the strata -- role descriptors, module control
// lines, and the carrier identity. The board's facts are stated in board.toml.
namespace Lamella.Generated
{
    public sealed class MicrochipSamd21CnanoBindings
    {
        private MicrochipSamd21CnanoBindings() { }

        // -- identity --
        public const int BOARD_MODEL = 46;
        public const string BOARD_VENDOR = "Microchip";
        public const uint DEVICE_COUNT = 2;

        // -- on-board devices: PORT group base + pin index + mask --
        public const uint LED0_PORT_BASE = 0x41004480;
        public const uint LED0_PIN = 10;
        public const uint LED0_BANK = 0;
        public const uint LED0_MASK = 0x400;
        public const uint LED0_ACTIVE_LOW = 1;
        public const uint BUTTON0_PORT_BASE = 0x41004480;
        public const uint BUTTON0_PIN = 11;
        public const uint BUTTON0_BANK = 0;
        public const uint BUTTON0_MASK = 0x800;
        public const uint BUTTON0_ACTIVE_LOW = 1;
    }
}
