# GENERATED by lamella-bsp-gen from bsp/nucleo-f429zi/board.toml + csp/stm32f42x/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32f42x

BOARD = "nucleo-f429zi"
BOARD_MODEL = 28
BOARD_VENDOR = "St"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.

CARRIER = {
    "kind": "stlink-vcp",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Bases only: register offsets and bit encodings belong to the driver that knows the block.
INSTANCES = {
    "usart1": {"block": "usart", "base": 0x40011000, "rcc_en_off": 0x44, "rcc_en_bit": 0x4},
    "spi5": {"block": "spi", "base": 0x40015000, "rcc_en_off": 0x44, "rcc_en_bit": 0x14},
    "gpioa": {"block": "gpio", "base": 0x40020000, "rcc_en_off": 0x30, "rcc_en_bit": 0x0},
    "gpiob": {"block": "gpio", "base": 0x40020400, "rcc_en_off": 0x30, "rcc_en_bit": 0x1},
    "gpioc": {"block": "gpio", "base": 0x40020800, "rcc_en_off": 0x30, "rcc_en_bit": 0x2},
    "gpiod": {"block": "gpio", "base": 0x40020C00, "rcc_en_off": 0x30, "rcc_en_bit": 0x3},
    "gpioe": {"block": "gpio", "base": 0x40021000, "rcc_en_off": 0x30, "rcc_en_bit": 0x4},
    "gpiof": {"block": "gpio", "base": 0x40021400, "rcc_en_off": 0x30, "rcc_en_bit": 0x5},
    "gpiog": {"block": "gpio", "base": 0x40021800, "rcc_en_off": 0x30, "rcc_en_bit": 0x6},
    "rcc": {"block": "rcc", "base": 0x40023800},
    "usart2": {"block": "usart", "base": 0x40004400, "rcc_en_off": 0x40, "rcc_en_bit": 0x11},
    "otg_fs": {"block": "otg-fs", "base": 0x50000000, "rcc_en_off": 0x34, "rcc_en_bit": 0x7},
    "flash": {"block": "flash", "base": 0x40023C00},
    "fmc": {"block": "fmc", "base": 0xA0000000, "rcc_en_off": 0x38, "rcc_en_bit": 0x0},
}

PLANS = {
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
    "led0": {"kind": "gpio-out", "port_base": 0x40020400, "pin": 0, "mask": 0x1, "active_low": False},
    "led1": {"kind": "gpio-out", "port_base": 0x40020400, "pin": 7, "mask": 0x80, "active_low": False},
    "led2": {"kind": "gpio-out", "port_base": 0x40020400, "pin": 14, "mask": 0x4000, "active_low": False},
    "button0": {"kind": "gpio-in", "port_base": 0x40020800, "pin": 13, "mask": 0x2000, "active_low": False},
}
