//! GENERATED by lamella-bsp-gen from csp/samd21/blocks/sysctrl.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//!
//! The samd21 sysctrl block layout as Rust consts, name/value-identical to Samd21SysctrlLayout.g.cs:
//! offsets are instance-base-relative (`base + *_OFF`) and the instance bases live in
//! samd21_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const VREF_OFF: u32 = 0x40;
pub const VREF_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const VREF_TSEN: u32 = 0x2;
pub const VREF_TSEN_LSB: u32 = 1;
pub const VREF_BGOUTEN: u32 = 0x4;
pub const VREF_BGOUTEN_LSB: u32 = 2;
pub const VREF_CALIB: u32 = 0x7FF0000;
pub const VREF_CALIB_LSB: u32 = 16;
