//! GENERATED by lamella-bsp-gen from csp/samd21/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21

pub const SERCOM0_BASE: u32 = 0x42000800;
pub const SERCOM0_GCLK_CORE_ID: u32 = 20;
pub const SERCOM0_APBC_BIT: u32 = 2;
pub const SERCOM0_APBC_MASK: u32 = 0x4;
pub const SERCOM0_IRQ: u32 = 9;
pub const SERCOM1_BASE: u32 = 0x42000C00;
pub const SERCOM1_GCLK_CORE_ID: u32 = 21;
pub const SERCOM1_APBC_BIT: u32 = 3;
pub const SERCOM1_APBC_MASK: u32 = 0x8;
pub const SERCOM1_IRQ: u32 = 10;
pub const SERCOM2_BASE: u32 = 0x42001000;
pub const SERCOM2_GCLK_CORE_ID: u32 = 22;
pub const SERCOM2_APBC_BIT: u32 = 4;
pub const SERCOM2_APBC_MASK: u32 = 0x10;
pub const SERCOM2_IRQ: u32 = 11;
pub const SERCOM3_BASE: u32 = 0x42001400;
pub const SERCOM3_GCLK_CORE_ID: u32 = 23;
pub const SERCOM3_APBC_BIT: u32 = 5;
pub const SERCOM3_APBC_MASK: u32 = 0x20;
pub const SERCOM3_IRQ: u32 = 12;
pub const SERCOM4_BASE: u32 = 0x42001800;
pub const SERCOM4_GCLK_CORE_ID: u32 = 24;
pub const SERCOM4_APBC_BIT: u32 = 6;
pub const SERCOM4_APBC_MASK: u32 = 0x40;
pub const SERCOM4_IRQ: u32 = 13;
pub const SERCOM5_BASE: u32 = 0x42001C00;
pub const SERCOM5_GCLK_CORE_ID: u32 = 25;
pub const SERCOM5_APBC_BIT: u32 = 7;
pub const SERCOM5_APBC_MASK: u32 = 0x80;
pub const SERCOM5_IRQ: u32 = 14;
pub const PM_BASE: u32 = 0x40000400;
pub const GCLK_BASE: u32 = 0x40000C00;
pub const PORTA_BASE: u32 = 0x41004400;
pub const PORTB_BASE: u32 = 0x41004480;
