// GENERATED by lamella-bsp-gen from csp/ch32v003/blocks/gpio.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ch32v003
//
// The ch32v003 gpio BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Ch32v003Instances. Widths are access widths.

public enum Ch32v003GpioLayout {
    // -- register offsets (block-relative) + access widths --
    public static let CFGLR_OFF: UInt32 = 0x0
    public static let CFGLR_WIDTH: Int32 = 32
    public static let INDR_OFF: UInt32 = 0x8
    public static let INDR_WIDTH: Int32 = 32
    public static let OUTDR_OFF: UInt32 = 0xC
    public static let OUTDR_WIDTH: Int32 = 32
    public static let BSHR_OFF: UInt32 = 0x10
    public static let BSHR_WIDTH: Int32 = 32
    public static let BCR_OFF: UInt32 = 0x14
    public static let BCR_WIDTH: Int32 = 32
    public static let LCKR_OFF: UInt32 = 0x18
    public static let LCKR_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let CFGLR_MODE6: UInt32 = 0x3000000
    public static let CFGLR_MODE6_LSB: UInt32 = 24
    public static let CFGLR_CNF6: UInt32 = 0xC000000
    public static let CFGLR_CNF6_LSB: UInt32 = 26
    public static let BSHR_BS6: UInt32 = 0x40
    public static let BSHR_BS6_LSB: UInt32 = 6
    public static let BSHR_BR6: UInt32 = 0x400000
    public static let BSHR_BR6_LSB: UInt32 = 22
    public static let BCR_BR6: UInt32 = 0x40
    public static let BCR_BR6_LSB: UInt32 = 6

    // -- block constants --
    public static let CFGLR_MODE_INPUT: UInt32 = 0
    public static let CFGLR_MODE_OUTPUT_10MHZ: UInt32 = 1
    public static let CFGLR_MODE_OUTPUT_2MHZ: UInt32 = 2
    public static let CFGLR_MODE_OUTPUT_30MHZ: UInt32 = 3
    public static let CFGLR_CNF_OUTPUT_PUSH_PULL: UInt32 = 0
    public static let CFGLR_CNF_OUTPUT_OPEN_DRAIN: UInt32 = 1
    public static let CFGLR_CNF_OUTPUT_AF_PUSH_PULL: UInt32 = 2
    public static let CFGLR_CNF_OUTPUT_AF_OPEN_DRAIN: UInt32 = 3
    public static let CFGLR_CNF_INPUT_ANALOG: UInt32 = 0
    public static let CFGLR_CNF_INPUT_FLOATING: UInt32 = 1
    public static let CFGLR_CNF_INPUT_PULL: UInt32 = 2
    public static let CFGLR_RESET: UInt32 = 0x44444444
}
