# GENERATED by lamella-bsp-gen from bsp/portenta-h7/board.toml + csp/stm32h7/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32h7

BOARD = "portenta-h7"
BOARD_MODEL = 35
BOARD_VENDOR = "Arduino"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.

CARRIER = {
    "kind": "native-usb",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Bases only: register offsets and bit encodings belong to the driver that knows the block.
INSTANCES = {
    "usart3": {"block": "usart", "base": 0x40004800, "rcc_en_off": 0xE8, "rcc_en_bit": 0x12},
    "gpiob": {"block": "gpio", "base": 0x58020400, "rcc_en_off": 0xE0, "rcc_en_bit": 0x1},
    "gpioc": {"block": "gpio", "base": 0x58020800, "rcc_en_off": 0xE0, "rcc_en_bit": 0x2},
    "gpiod": {"block": "gpio", "base": 0x58020C00, "rcc_en_off": 0xE0, "rcc_en_bit": 0x3},
    "gpioe": {"block": "gpio", "base": 0x58021000, "rcc_en_off": 0xE0, "rcc_en_bit": 0x4},
    "gpioi": {"block": "gpio", "base": 0x58022000, "rcc_en_off": 0xE0, "rcc_en_bit": 0x8},
    "gpioj": {"block": "gpio", "base": 0x58022400, "rcc_en_off": 0xE0, "rcc_en_bit": 0x9},
    "gpiok": {"block": "gpio", "base": 0x58022800, "rcc_en_off": 0xE0, "rcc_en_bit": 0xA},
    "rcc": {"block": "rcc", "base": 0x58024400},
}

PLANS = {
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
    "led_red": {"kind": "gpio-out", "port_base": 0x58022800, "pin": 5, "mask": 0x20, "active_low": True},
    "led_green": {"kind": "gpio-out", "port_base": 0x58022800, "pin": 6, "mask": 0x40, "active_low": True},
    "led_blue": {"kind": "gpio-out", "port_base": 0x58022800, "pin": 7, "mask": 0x80, "active_low": True},
}
