// GENERATED by lamella-bsp-gen from bsp/nucleo-h755zi-q/board.toml + csp/stm32h7/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class NucleoH755ziQBindings
    {
        private NucleoH755ziQBindings() { }

        public const int BOARD_MODEL = 32;
        public const string BOARD_VENDOR = "St";

        /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
        /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
        /// peripherals of the same kind can share no register at all, so a consumer that selects a
        /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
        /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
        /// name a driver; and a uart is a different register map on every family, so the kind does
        /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
        public const string VCP_DRIVER_FAMILY = "stm32h7-usart";

        public const uint VCP_BASE = 0x40004800;
        public const uint VCP_RCC_EN_REG = 0x580244E8;
        public const uint VCP_RCC_EN_MASK = 0x40000;
        public const uint VCP_TX_PORT_RCC_EN_REG = 0x580244E0;
        public const uint VCP_TX_PORT_RCC_EN_MASK = 0x8;
        public const uint VCP_TX_MODER_REG = 0x58020C00;
        public const uint VCP_TX_MODER_MASK = 0x30000;
        public const uint VCP_TX_MODER_VALUE = 0x20000;
        public const uint VCP_TX_AFR_REG = 0x58020C24;
        public const uint VCP_TX_AFR_MASK = 0xF;
        public const uint VCP_TX_AFR_VALUE = 0x7;
        public const uint VCP_RX_PORT_RCC_EN_REG = 0x580244E0;
        public const uint VCP_RX_PORT_RCC_EN_MASK = 0x8;
        public const uint VCP_RX_MODER_REG = 0x58020C00;
        public const uint VCP_RX_MODER_MASK = 0xC0000;
        public const uint VCP_RX_MODER_VALUE = 0x80000;
        public const uint VCP_RX_AFR_REG = 0x58020C24;
        public const uint VCP_RX_AFR_MASK = 0xF0;
        public const uint VCP_RX_AFR_VALUE = 0x70;
        public const uint VCP_PCLK_HZ = 64000000;
        public const uint VCP_BRR_115200_HSI_64MHZ = 0x22C;

        public const uint LED0_PORT_BASE = 0x58020400;
        public const uint LED0_PIN = 0;
        public const uint LED0_MASK = 0x1;
        public const uint LED0_ACTIVE_LOW = 0;
        public const uint LED1_PORT_BASE = 0x58021000;
        public const uint LED1_PIN = 1;
        public const uint LED1_MASK = 0x2;
        public const uint LED1_ACTIVE_LOW = 0;
        public const uint LED2_PORT_BASE = 0x58020400;
        public const uint LED2_PIN = 14;
        public const uint LED2_MASK = 0x4000;
        public const uint LED2_ACTIVE_LOW = 0;
    }
}
