// GENERATED by lamella-bsp-gen from csp/nrf52833/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . nrf52833
//
// The nrf52833 instance map as Swift constants, name/value-identical to Nrf52833Instances.g.cs:
// where each block copy sits and its per-instance ids. Block-register offsets are not
// emitted for Swift: a firmware project states its block constants and reads this file
// for every placed-instance fact.

public enum Nrf52833Instances {
    public static let TWI0_BASE: UInt32 = 0x40003000
    public static let PORT0_BASE: UInt32 = 0x50000000
    public static let PORT1_BASE: UInt32 = 0x50000300
}
