// GENERATED by lamella-bsp-gen from bsp/pico/board.toml + csp/rp2040/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class PicoBindings
    {
        private PicoBindings() { }

        public const int BOARD_MODEL = 13;

        public const uint UART0_BASE = 0x40034000;
        public const uint UART0_RESET_MASK = 0x400120;
        public const uint UART0_IO_TX_CTRL = 0x40014004;
        public const uint UART0_IO_RX_CTRL = 0x4001400C;
        public const uint UART0_FUNCSEL = 2;
        public const uint UART0_CLK_PERI_HZ = 12000000;
        public const uint UART0_IBRD_115200_XOSC_12MHZ = 6;
        public const uint UART0_FBRD_115200_XOSC_12MHZ = 33;
    }
}
