// GENERATED by lamella-bsp-gen from csp/nrf51/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . nrf51
//
// The nrf51 flash BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Nrf51Instances. Widths are access widths.

public enum Nrf51FlashLayout {
    // -- register offsets (block-relative) + access widths --

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

    // -- block constants --
    public static let ERASED_VALUE: UInt32 = 0xFFFFFFFF
    public static let WRITE_UNIT: UInt32 = 4
}
