# GENERATED by lamella-bsp-gen from parts/bme68x/bme680.toml + parts/bme68x/bme688.toml + parts/bme68x/bme68x.toml -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-parts . bme68x
#
# The facts every bme68x member emits IDENTICALLY -- the family's INVARIANT subset,
# computed across bme680, bme688. A part family's driver base is shared code in every language, and
# this is what it may rely on. A fact is here only while EVERY member agrees on it, so the
# day one member states its own value the fact LEAVES this class and the shared code that
# used it stops compiling. Nothing here is inherited: each member's own table spells all
# of it too, flattened.
FAMILY = "bme68x"

# identity: the accepted values are a SET. A driver that accepts only one of them rejects a genuine part, and a rejected part reads as no part at all -- so on a mismatch, name the id received AND this set.
IDENTITY_REG = 0xD0
IDENTITY_WIDTH = 8
IDENTITY_VALUE_COUNT = 1
IDENTITY_VALUE_0 = 0x61

# address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
ADDRESS_BUS = "i2c"
ADDRESS_BASE = 0x76
ADDRESS_STRAP_COUNT = 1
ADDRESS_STRAP_SDO_BIT = 0
ADDRESS_STRAP_SDO_LOW = 0x76
ADDRESS_STRAP_SDO_HIGH = 0x77

# buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
BUS_COUNT = 2
BUS_I2C_KIND = "i2c"
BUS_I2C_REGISTER_READ_TRANSFORM = "identity"
BUS_I2C_REGISTER_WRITE_TRANSFORM = "identity"
BUS_I2C_READ_PROTOCOL = "write-register-then-repeated-start-read"
BUS_SPI_KIND = "spi"
BUS_SPI_REGISTER_READ_TRANSFORM = "set-bit7"
BUS_SPI_REGISTER_WRITE_TRANSFORM = "clear-bit7"
BUS_SPI_READ_PROTOCOL = "single-chip-select-address-then-clock-data"
BUS_SPI_MODE_COUNT = 2
BUS_SPI_MODE_0 = 0
BUS_SPI_MODE_1 = 3

# registers: `_REG` is the address written on the wire -- an operand, NOT an offset to add to an instance base. Fields carry the shifted mask and its shift.
ID_REG = 0xD0
ID_WIDTH = 8
ID_ACCESS = "read-only"
ID_CHIP_ID = 0xFF
ID_CHIP_ID_LSB = 0
RESET_REG = 0xE0
RESET_WIDTH = 8
RESET_ACCESS = "write-only"
RESET_RESET = 0xFF
RESET_RESET_LSB = 0
STATUS_REG = 0x73
STATUS_WIDTH = 8
STATUS_ACCESS = "read-write"
STATUS_SPI_MEM_PAGE = 0x10
STATUS_SPI_MEM_PAGE_LSB = 4
CTRL_HUM_REG = 0x72
CTRL_HUM_WIDTH = 8
CTRL_HUM_ACCESS = "read-write"
CTRL_HUM_OSRS_H = 0x7
CTRL_HUM_OSRS_H_LSB = 0
CTRL_HUM_SPI_3W_INT_EN = 0x40
CTRL_HUM_SPI_3W_INT_EN_LSB = 6
CTRL_MEAS_REG = 0x74
CTRL_MEAS_WIDTH = 8
CTRL_MEAS_ACCESS = "read-write"
CTRL_MEAS_MODE = 0x3
CTRL_MEAS_MODE_LSB = 0
CTRL_MEAS_OSRS_P = 0x1C
CTRL_MEAS_OSRS_P_LSB = 2
CTRL_MEAS_OSRS_T = 0xE0
CTRL_MEAS_OSRS_T_LSB = 5
CONFIG_REG = 0x75
CONFIG_WIDTH = 8
CONFIG_ACCESS = "read-write"
CONFIG_SPI_3W_EN = 0x1
CONFIG_SPI_3W_EN_LSB = 0
CONFIG_FILTER = 0x1C
CONFIG_FILTER_LSB = 2
CTRL_GAS_0_REG = 0x70
CTRL_GAS_0_WIDTH = 8
CTRL_GAS_0_ACCESS = "read-write"
CTRL_GAS_0_HEAT_OFF = 0x8
CTRL_GAS_0_HEAT_OFF_LSB = 3
CTRL_GAS_1_REG = 0x71
CTRL_GAS_1_WIDTH = 8
CTRL_GAS_1_ACCESS = "read-write"
CTRL_GAS_1_NB_CONV = 0xF
CTRL_GAS_1_NB_CONV_LSB = 0
IDAC_HEAT_0_REG = 0x50
IDAC_HEAT_0_WIDTH = 8
IDAC_HEAT_0_ACCESS = "read-write"
IDAC_HEAT_0_IDAC_HEAT = 0xFF
IDAC_HEAT_0_IDAC_HEAT_LSB = 0
RES_HEAT_0_REG = 0x5A
RES_HEAT_0_WIDTH = 8
RES_HEAT_0_ACCESS = "read-write"
RES_HEAT_0_RES_HEAT = 0xFF
RES_HEAT_0_RES_HEAT_LSB = 0
GAS_WAIT_0_REG = 0x64
GAS_WAIT_0_WIDTH = 8
GAS_WAIT_0_ACCESS = "read-write"
GAS_WAIT_0_GAS_WAIT = 0xFF
GAS_WAIT_0_GAS_WAIT_LSB = 0
MEAS_STATUS_0_REG = 0x1D
MEAS_STATUS_0_WIDTH = 8
MEAS_STATUS_0_ACCESS = "read-only"
MEAS_STATUS_0_MEASURING = 0x20
MEAS_STATUS_0_MEASURING_LSB = 5
MEAS_STATUS_0_GAS_MEASURING = 0x40
MEAS_STATUS_0_GAS_MEASURING_LSB = 6
PRESS_REG = 0x1F
PRESS_WIDTH = 24
PRESS_ACCESS = "read-only"
PRESS_PRESS_XLSB = 0xF0
PRESS_PRESS_XLSB_LSB = 4
PRESS_PRESS_LSB = 0xFF00
PRESS_PRESS_LSB_LSB = 8
PRESS_PRESS_MSB = 0xFF0000
PRESS_PRESS_MSB_LSB = 16
TEMP_REG = 0x22
TEMP_WIDTH = 24
TEMP_ACCESS = "read-only"
TEMP_TEMP_XLSB = 0xF0
TEMP_TEMP_XLSB_LSB = 4
TEMP_TEMP_LSB = 0xFF00
TEMP_TEMP_LSB_LSB = 8
TEMP_TEMP_MSB = 0xFF0000
TEMP_TEMP_MSB_LSB = 16
HUM_REG = 0x25
HUM_WIDTH = 16
HUM_ACCESS = "read-only"
HUM_HUM_LSB = 0xFF
HUM_HUM_LSB_LSB = 0
HUM_HUM_MSB = 0xFF00
HUM_HUM_MSB_LSB = 8
GAS_R_WIDTH = 16
GAS_R_ACCESS = "read-only"
GAS_R_GAS_RANGE_R = 0xF
GAS_R_GAS_RANGE_R_LSB = 0
GAS_R_HEAT_STAB_R = 0x10
GAS_R_HEAT_STAB_R_LSB = 4
GAS_R_GAS_VALID_R = 0x20
GAS_R_GAS_VALID_R_LSB = 5
GAS_R_GAS_R = 0xFFC0
GAS_R_GAS_R_LSB = 6

# encodings: the codes a field takes, as this part reads them.
OVERSAMPLING_SKIPPED = 0
OVERSAMPLING_X1 = 1
OVERSAMPLING_X2 = 2
OVERSAMPLING_X4 = 3
OVERSAMPLING_X8 = 4
OVERSAMPLING_X16 = 5
FILTER_COEFF_0 = 0
FILTER_COEFF_1 = 1
FILTER_COEFF_3 = 2
FILTER_COEFF_7 = 3
FILTER_COEFF_15 = 4
FILTER_COEFF_31 = 5
FILTER_COEFF_63 = 6
FILTER_COEFF_127 = 7
RESET_COMMAND_SOFT_RESET = 0xB6
MODE_SLEEP = 0
MODE_FORCED = 1
