//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/xosc.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350

/// -- register offsets (block-relative) + access widths --
pub const CTRL_OFF: u32 = 0x0;
pub const CTRL_WIDTH: i32 = 32;
pub const STATUS_OFF: u32 = 0x4;
pub const STATUS_WIDTH: i32 = 32;
pub const STARTUP_OFF: u32 = 0xC;
pub const STARTUP_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const CTRL_FREQ_RANGE: u32 = 0xFFF;
pub const CTRL_FREQ_RANGE_LSB: u32 = 0;
pub const CTRL_ENABLE: u32 = 0xFFF000;
pub const CTRL_ENABLE_LSB: u32 = 12;
pub const STATUS_STABLE: u32 = 0x80000000;
pub const STATUS_STABLE_LSB: u32 = 31;
pub const STARTUP_DELAY: u32 = 0x3FFF;
pub const STARTUP_DELAY_LSB: u32 = 0;

/// -- block constants --
pub const CTRL_ENABLE_MAGIC: u32 = 0xFAB;
pub const CTRL_FREQ_RANGE_1_15MHZ: u32 = 0xAA0;
pub const STARTUP_DELAY_1MS: u32 = 0xC4;
