//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/resets.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//!
//! The rp2350 resets block layout as Rust consts, name/value-identical to Rp2350ResetsLayout.g.cs:
//! offsets are instance-base-relative (`base + *_OFF`) and the instance bases live in
//! rp2350_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const RESET_OFF: u32 = 0x0;
pub const RESET_WIDTH: i32 = 32;
pub const RESET_SET_OFF: u32 = 0x2000;
pub const RESET_SET_WIDTH: i32 = 32;
pub const RESET_DONE_OFF: u32 = 0x8;
pub const RESET_DONE_WIDTH: i32 = 32;
