//! GENERATED by lamella-bsp-gen from csp/rp2350/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350

pub const XOSC_BASE: u32 = 0x40048000;
pub const CLOCKS_BASE: u32 = 0x40010000;
pub const RESETS_BASE: u32 = 0x40020000;
pub const RESETS_CLR_BASE: u32 = 0x40023000;
pub const IO_BANK0_BASE: u32 = 0x40028000;
pub const IO_BANK0_RESET_BIT: u32 = 6;
pub const IO_BANK0_RESET_MASK: u32 = 0x40;
pub const PADS_BANK0_BASE: u32 = 0x40038000;
pub const PADS_BANK0_RESET_BIT: u32 = 9;
pub const PADS_BANK0_RESET_MASK: u32 = 0x200;
pub const SIO_BASE: u32 = 0xD0000000;
pub const PLL_SYS_BASE: u32 = 0x40050000;
pub const PLL_SYS_RESET_BIT: u32 = 14;
pub const PLL_SYS_RESET_MASK: u32 = 0x4000;
pub const PLL_USB_BASE: u32 = 0x40058000;
pub const PLL_USB_RESET_BIT: u32 = 15;
pub const PLL_USB_RESET_MASK: u32 = 0x8000;
pub const UART0_BASE: u32 = 0x40070000;
pub const UART0_RESET_BIT: u32 = 26;
pub const UART0_RESET_MASK: u32 = 0x4000000;
pub const SPI0_BASE: u32 = 0x40080000;
pub const SPI0_RESET_BIT: u32 = 18;
pub const SPI0_RESET_MASK: u32 = 0x40000;
pub const I2C0_BASE: u32 = 0x40090000;
pub const I2C0_RESET_BIT: u32 = 4;
pub const I2C0_RESET_MASK: u32 = 0x10;
pub const ADC_BASE: u32 = 0x400A0000;
pub const ADC_RESET_BIT: u32 = 0;
pub const ADC_RESET_MASK: u32 = 0x1;
