//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/trng.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//!
//! The rp2350 trng block layout as Rust consts: offsets are instance-base-relative
//! (`base + *_OFF`) and the instance bases live in rp2350_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const RNG_ISR_OFF: u32 = 0x104;
pub const RNG_ISR_WIDTH: i32 = 32;
pub const RNG_ICR_OFF: u32 = 0x108;
pub const RNG_ICR_WIDTH: i32 = 32;
pub const TRNG_CONFIG_OFF: u32 = 0x10C;
pub const TRNG_CONFIG_WIDTH: i32 = 32;
pub const TRNG_VALID_OFF: u32 = 0x110;
pub const TRNG_VALID_WIDTH: i32 = 32;
pub const EHR_DATA0_OFF: u32 = 0x114;
pub const EHR_DATA0_WIDTH: i32 = 32;
pub const RND_SOURCE_ENABLE_OFF: u32 = 0x12C;
pub const RND_SOURCE_ENABLE_WIDTH: i32 = 32;
pub const SAMPLE_CNT1_OFF: u32 = 0x130;
pub const SAMPLE_CNT1_WIDTH: i32 = 32;
pub const TRNG_DEBUG_CONTROL_OFF: u32 = 0x138;
pub const TRNG_DEBUG_CONTROL_WIDTH: i32 = 32;
pub const TRNG_SW_RESET_OFF: u32 = 0x140;
pub const TRNG_SW_RESET_WIDTH: i32 = 32;
pub const TRNG_BUSY_OFF: u32 = 0x1B8;
pub const TRNG_BUSY_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const RNG_ISR_EHR_VALID: u32 = 0x1;
pub const RNG_ISR_EHR_VALID_LSB: u32 = 0;
pub const RNG_ISR_AUTOCORR_ERR: u32 = 0x2;
pub const RNG_ISR_AUTOCORR_ERR_LSB: u32 = 1;
pub const RNG_ISR_CRNGT_ERR: u32 = 0x4;
pub const RNG_ISR_CRNGT_ERR_LSB: u32 = 2;
pub const RNG_ISR_VN_ERR: u32 = 0x8;
pub const RNG_ISR_VN_ERR_LSB: u32 = 3;
pub const RNG_ICR_EHR_VALID: u32 = 0x1;
pub const RNG_ICR_EHR_VALID_LSB: u32 = 0;
pub const RNG_ICR_AUTOCORR_ERR: u32 = 0x2;
pub const RNG_ICR_AUTOCORR_ERR_LSB: u32 = 1;
pub const RNG_ICR_CRNGT_ERR: u32 = 0x4;
pub const RNG_ICR_CRNGT_ERR_LSB: u32 = 2;
pub const RNG_ICR_VN_ERR: u32 = 0x8;
pub const RNG_ICR_VN_ERR_LSB: u32 = 3;
pub const TRNG_CONFIG_RND_SRC_SEL: u32 = 0x3;
pub const TRNG_CONFIG_RND_SRC_SEL_LSB: u32 = 0;
pub const TRNG_VALID_EHR_VALID: u32 = 0x1;
pub const TRNG_VALID_EHR_VALID_LSB: u32 = 0;
pub const RND_SOURCE_ENABLE_RND_SRC_EN: u32 = 0x1;
pub const RND_SOURCE_ENABLE_RND_SRC_EN_LSB: u32 = 0;
pub const TRNG_DEBUG_CONTROL_VNC_BYPASS: u32 = 0x2;
pub const TRNG_DEBUG_CONTROL_VNC_BYPASS_LSB: u32 = 1;
pub const TRNG_DEBUG_CONTROL_TRNG_CRNGT_BYPASS: u32 = 0x4;
pub const TRNG_DEBUG_CONTROL_TRNG_CRNGT_BYPASS_LSB: u32 = 2;
pub const TRNG_DEBUG_CONTROL_AUTO_CORRELATE_BYPASS: u32 = 0x8;
pub const TRNG_DEBUG_CONTROL_AUTO_CORRELATE_BYPASS_LSB: u32 = 3;
pub const TRNG_SW_RESET_TRNG_SW_RESET: u32 = 0x1;
pub const TRNG_SW_RESET_TRNG_SW_RESET_LSB: u32 = 0;
pub const TRNG_BUSY_TRNG_BUSY: u32 = 0x1;
pub const TRNG_BUSY_TRNG_BUSY_LSB: u32 = 0;

/// -- block constants --
pub const EHR_WORDS: u32 = 6;
pub const EHR_STRIDE: u32 = 4;
