//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/sio.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350

/// -- register offsets (block-relative) + access widths --
pub const GPIO_IN_OFF: u32 = 0x4;
pub const GPIO_IN_WIDTH: i32 = 32;
pub const GPIO_OUT_SET_OFF: u32 = 0x18;
pub const GPIO_OUT_SET_WIDTH: i32 = 32;
pub const GPIO_OUT_CLR_OFF: u32 = 0x20;
pub const GPIO_OUT_CLR_WIDTH: i32 = 32;
pub const GPIO_OUT_XOR_OFF: u32 = 0x28;
pub const GPIO_OUT_XOR_WIDTH: i32 = 32;
pub const GPIO_OE_OFF: u32 = 0x30;
pub const GPIO_OE_WIDTH: i32 = 32;
pub const GPIO_OE_SET_OFF: u32 = 0x38;
pub const GPIO_OE_SET_WIDTH: i32 = 32;
pub const GPIO_OE_CLR_OFF: u32 = 0x40;
pub const GPIO_OE_CLR_WIDTH: i32 = 32;
