//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/clocks.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350

/// -- register offsets (block-relative) + access widths --
pub const CLK_REF_CTRL_OFF: u32 = 0x30;
pub const CLK_REF_CTRL_WIDTH: i32 = 32;
pub const CLK_REF_SELECTED_OFF: u32 = 0x38;
pub const CLK_REF_SELECTED_WIDTH: i32 = 32;
pub const CLK_SYS_CTRL_OFF: u32 = 0x3C;
pub const CLK_SYS_CTRL_WIDTH: i32 = 32;
pub const CLK_SYS_SELECTED_OFF: u32 = 0x44;
pub const CLK_SYS_SELECTED_WIDTH: i32 = 32;
pub const CLK_PERI_CTRL_OFF: u32 = 0x48;
pub const CLK_PERI_CTRL_WIDTH: i32 = 32;
pub const CLK_PERI_DIV_OFF: u32 = 0x4C;
pub const CLK_PERI_DIV_WIDTH: i32 = 32;
pub const CLK_USB_CTRL_OFF: u32 = 0x60;
pub const CLK_USB_CTRL_WIDTH: i32 = 32;
pub const CLK_ADC_CTRL_OFF: u32 = 0x6C;
pub const CLK_ADC_CTRL_WIDTH: i32 = 32;
pub const CLK_ADC_DIV_OFF: u32 = 0x70;
pub const CLK_ADC_DIV_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const CLK_REF_CTRL_SRC: u32 = 0x3;
pub const CLK_REF_CTRL_SRC_LSB: u32 = 0;
pub const CLK_SYS_CTRL_SRC: u32 = 0x1;
pub const CLK_SYS_CTRL_SRC_LSB: u32 = 0;
pub const CLK_SYS_CTRL_AUXSRC: u32 = 0xE0;
pub const CLK_SYS_CTRL_AUXSRC_LSB: u32 = 5;
pub const CLK_PERI_CTRL_AUXSRC: u32 = 0xE0;
pub const CLK_PERI_CTRL_AUXSRC_LSB: u32 = 5;
pub const CLK_PERI_CTRL_ENABLE: u32 = 0x800;
pub const CLK_PERI_CTRL_ENABLE_LSB: u32 = 11;
pub const CLK_PERI_DIV_INT: u32 = 0x30000;
pub const CLK_PERI_DIV_INT_LSB: u32 = 16;
pub const CLK_USB_CTRL_AUXSRC: u32 = 0xE0;
pub const CLK_USB_CTRL_AUXSRC_LSB: u32 = 5;
pub const CLK_USB_CTRL_ENABLE: u32 = 0x800;
pub const CLK_USB_CTRL_ENABLE_LSB: u32 = 11;
pub const CLK_ADC_CTRL_AUXSRC: u32 = 0xE0;
pub const CLK_ADC_CTRL_AUXSRC_LSB: u32 = 5;
pub const CLK_ADC_CTRL_KILL: u32 = 0x400;
pub const CLK_ADC_CTRL_KILL_LSB: u32 = 10;
pub const CLK_ADC_CTRL_ENABLE: u32 = 0x800;
pub const CLK_ADC_CTRL_ENABLE_LSB: u32 = 11;
pub const CLK_ADC_CTRL_PHASE: u32 = 0x30000;
pub const CLK_ADC_CTRL_PHASE_LSB: u32 = 16;
pub const CLK_ADC_CTRL_NUDGE: u32 = 0x100000;
pub const CLK_ADC_CTRL_NUDGE_LSB: u32 = 20;
pub const CLK_ADC_CTRL_ENABLED: u32 = 0x10000000;
pub const CLK_ADC_CTRL_ENABLED_LSB: u32 = 28;
pub const CLK_ADC_DIV_INT: u32 = 0xF0000;
pub const CLK_ADC_DIV_INT_LSB: u32 = 16;

/// -- block constants --
pub const CLK_REF_SRC_XOSC: u32 = 2;
pub const CLK_REF_XOSC_SELECTED: u32 = 0x4;
pub const CLK_SYS_SRC_AUX: u32 = 1;
pub const CLK_SYS_REF_SELECTED: u32 = 0x1;
pub const CLK_SYS_AUX_SELECTED: u32 = 0x2;
pub const CLK_PERI_AUXSRC_XOSC: u32 = 4;
pub const CLK_ADC_AUXSRC_PLL_USB: u32 = 0;
