//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/pwm.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//!
//! The rp2350 pwm block layout as Rust consts: offsets are instance-base-relative
//! (`base + *_OFF`) and the instance bases live in rp2350_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const CH0_CSR_OFF: u32 = 0x0;
pub const CH0_CSR_WIDTH: i32 = 32;
pub const CH0_DIV_OFF: u32 = 0x4;
pub const CH0_DIV_WIDTH: i32 = 32;
pub const CH0_CTR_OFF: u32 = 0x8;
pub const CH0_CTR_WIDTH: i32 = 32;
pub const CH0_CC_OFF: u32 = 0xC;
pub const CH0_CC_WIDTH: i32 = 32;
pub const CH0_TOP_OFF: u32 = 0x10;
pub const CH0_TOP_WIDTH: i32 = 32;
pub const EN_OFF: u32 = 0xF0;
pub const EN_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const CH0_CSR_EN: u32 = 0x1;
pub const CH0_CSR_EN_LSB: u32 = 0;
pub const CH0_CSR_PH_CORRECT: u32 = 0x2;
pub const CH0_CSR_PH_CORRECT_LSB: u32 = 1;
pub const CH0_CSR_A_INV: u32 = 0x4;
pub const CH0_CSR_A_INV_LSB: u32 = 2;
pub const CH0_CSR_B_INV: u32 = 0x8;
pub const CH0_CSR_B_INV_LSB: u32 = 3;
pub const CH0_CSR_DIVMODE: u32 = 0x30;
pub const CH0_CSR_DIVMODE_LSB: u32 = 4;
pub const CH0_CSR_PH_RET: u32 = 0x40;
pub const CH0_CSR_PH_RET_LSB: u32 = 6;
pub const CH0_CSR_PH_ADV: u32 = 0x80;
pub const CH0_CSR_PH_ADV_LSB: u32 = 7;
pub const CH0_DIV_FRAC: u32 = 0xF;
pub const CH0_DIV_FRAC_LSB: u32 = 0;
pub const CH0_DIV_INT: u32 = 0xFF0;
pub const CH0_DIV_INT_LSB: u32 = 4;
pub const CH0_CTR_CTR: u32 = 0xFFFF;
pub const CH0_CTR_CTR_LSB: u32 = 0;
pub const CH0_CC_A: u32 = 0xFFFF;
pub const CH0_CC_A_LSB: u32 = 0;
pub const CH0_CC_B: u32 = 0xFFFF0000;
pub const CH0_CC_B_LSB: u32 = 16;
pub const CH0_TOP_TOP: u32 = 0xFFFF;
pub const CH0_TOP_TOP_LSB: u32 = 0;

/// -- block constants --
pub const CH_STRIDE: u32 = 0x14;
pub const SLICE_COUNT: u32 = 12;
pub const DIVMODE_DIV: u32 = 0;
