//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/timer.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//!
//! The rp2350 timer block layout as Rust consts: offsets are instance-base-relative
//! (`base + *_OFF`) and the instance bases live in rp2350_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const TIMERAWH_OFF: u32 = 0x24;
pub const TIMERAWH_WIDTH: i32 = 32;
pub const TIMERAWL_OFF: u32 = 0x28;
pub const TIMERAWL_WIDTH: i32 = 32;
