//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/pll.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350

/// -- register offsets (block-relative) + access widths --
pub const CS_OFF: u32 = 0x0;
pub const CS_WIDTH: i32 = 32;
pub const PWR_OFF: u32 = 0x4;
pub const PWR_WIDTH: i32 = 32;
pub const PWR_CLR_OFF: u32 = 0x3004;
pub const PWR_CLR_WIDTH: i32 = 32;
pub const FBDIV_INT_OFF: u32 = 0x8;
pub const FBDIV_INT_WIDTH: i32 = 32;
pub const PRIM_OFF: u32 = 0xC;
pub const PRIM_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const CS_REFDIV: u32 = 0x3F;
pub const CS_REFDIV_LSB: u32 = 0;
pub const CS_LOCK: u32 = 0x80000000;
pub const CS_LOCK_LSB: u32 = 31;
pub const PWR_PD: u32 = 0x1;
pub const PWR_PD_LSB: u32 = 0;
pub const PWR_POSTDIVPD: u32 = 0x8;
pub const PWR_POSTDIVPD_LSB: u32 = 3;
pub const PWR_VCOPD: u32 = 0x20;
pub const PWR_VCOPD_LSB: u32 = 5;
pub const PRIM_POSTDIV2: u32 = 0x7000;
pub const PRIM_POSTDIV2_LSB: u32 = 12;
pub const PRIM_POSTDIV1: u32 = 0x70000;
pub const PRIM_POSTDIV1_LSB: u32 = 16;
