//! GENERATED by lamella-bsp-gen from csp/rp2350/blocks/io-bank0.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//!
//! The rp2350 io-bank0 block layout as Rust consts, name/value-identical to Rp2350IoBank0Layout.g.cs:
//! offsets are instance-base-relative (`base + *_OFF`) and the instance bases live in
//! rp2350_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const GPIO0_CTRL_OFF: u32 = 0x4;
pub const GPIO0_CTRL_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const GPIO0_CTRL_FUNCSEL: u32 = 0x1F;
pub const GPIO0_CTRL_FUNCSEL_LSB: u32 = 0;

/// -- block constants --
pub const GPIO_CTRL_STRIDE: u32 = 8;
pub const FUNCSEL_SPI: u32 = 1;
pub const FUNCSEL_UART: u32 = 2;
pub const FUNCSEL_I2C: u32 = 3;
pub const FUNCSEL_SIO: u32 = 5;
pub const FUNCSEL_NULL: u32 = 0x1F;
