//! GENERATED by lamella-bsp-gen from csp/stm32u5a5/blocks/pwr.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32u5a5
//!
//! The stm32u5a5 pwr block layout as Rust consts: offsets are instance-base-relative
//! (`base + *_OFF`) and the instance bases live in stm32u5a5_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const SVMCR_OFF: u32 = 0x10;
pub const SVMCR_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const SVMCR_IO2SV: u32 = 0x20000000;
pub const SVMCR_IO2SV_LSB: u32 = 29;
