# GENERATED by lamella-bsp-gen from bsp/pico2-w/board.toml + csp/rp2350/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350

BOARD = "pico2-w"
BOARD_MODEL = 10

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
UART0 = "uart0"
SPI0 = "spi0"
I2C0 = "i2c0"
ADC = "adc"

CARRIER = {
    "kind": "native-usb",
}

# Per-role descriptor dicts: the same values the C# Pico2WBindings class carries as consts,
# under one mechanical renaming rule -- an UPPER_SNAKE const there is a lowercase key here,
# grouped by the role it belongs to.
FACTS = {
    "uart0": {
        "kind": "uart",
        "instance": "uart0",
        "base": 0x40070000,
        "reset_mask": 0x4000240,
        "io_tx_ctrl": 0x40028004,
        "io_rx_ctrl": 0x4002800C,
        "pads_tx": 0x40038004,
        "pads_rx": 0x40038008,
        "funcsel": 2,
        "clk_peri_hz": 12000000,
        "ibrd_115200_pll_150_48": 6,
        "fbrd_115200_pll_150_48": 33,
    },
    "spi0": {
        "kind": "spi",
        "instance": "spi0",
        "base": 0x40080000,
        "reset_mask": 0x40240,
        "io_miso_ctrl": 0x40028084,
        "pads_miso": 0x40038044,
        "io_cs_ctrl": 0x4002808C,
        "pads_cs": 0x40038048,
        "io_sck_ctrl": 0x40028094,
        "pads_sck": 0x4003804C,
        "io_mosi_ctrl": 0x4002809C,
        "pads_mosi": 0x40038050,
        "funcsel": 1,
        "sspclk_hz": 12000000,
    },
    "i2c0": {
        "kind": "i2c",
        "instance": "i2c0",
        "base": 0x40090000,
        "reset_mask": 0x250,
        "io_sda_ctrl": 0x40028024,
        "io_scl_ctrl": 0x4002802C,
        "pads_sda": 0x40038014,
        "pads_scl": 0x40038018,
        "funcsel": 3,
        "ic_clk_hz": 150000000,
    },
    "adc": {
        "kind": "adc",
        "instance": "adc",
        "base": 0x400A0000,
        "reset_mask": 0x1,
        "reference_uv": 3300000,
    },
}

PLANS = {
    "pll-150-48": {"default": True, "source": "xosc", "xosc_hz": 12000000, "clk_peri_hz": 12000000, "clk_sys_hz": 150000000, "clk_usb_hz": 48000000, "clk_adc_hz": 48000000, "pll_sys_fbdiv": 125, "pll_sys_postdiv1": 5, "pll_sys_postdiv2": 2, "pll_usb_fbdiv": 100, "pll_usb_postdiv1": 5, "pll_usb_postdiv2": 5},
}

# On-board devices + module control lines (the C# <NAME>_PORT_BASE/_PIN/_MASK/
# _ACTIVE_LOW consts, dict-shaped): PORT group base + pin index + mask + polarity.
DEVICES = {
    "cyw43439-wl-reg-on": {"port_base": 0xD0000000, "pin": 23, "mask": 0x800000, "active_low": False},
    "cyw43439-data": {"port_base": 0xD0000000, "pin": 24, "mask": 0x1000000, "active_low": False},
    "cyw43439-cs": {"port_base": 0xD0000000, "pin": 25, "mask": 0x2000000, "active_low": True},
    "cyw43439-clk": {"port_base": 0xD0000000, "pin": 29, "mask": 0x20000000, "active_low": False},
}
