// GENERATED by lamella-bsp-gen from csp/nrf52833/blocks/flash.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Nrf52833FlashLayout
    {
        private Nrf52833FlashLayout() { }



        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 4;
    }
}
