// GENERATED by lamella-bsp-gen from csp/nrf52833/blocks/gpio.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Nrf52833GpioLayout
    {
        private Nrf52833GpioLayout() { }

        public const uint OUT_OFF = 0x504;
        public const int OUT_WIDTH = 32;
        public const uint OUTSET_OFF = 0x508;
        public const int OUTSET_WIDTH = 32;
        public const uint OUTCLR_OFF = 0x50C;
        public const int OUTCLR_WIDTH = 32;
        public const uint IN_OFF = 0x510;
        public const int IN_WIDTH = 32;
        public const uint DIR_OFF = 0x514;
        public const int DIR_WIDTH = 32;
        public const uint DIRSET_OFF = 0x518;
        public const int DIRSET_WIDTH = 32;
        public const uint DIRCLR_OFF = 0x51C;
        public const int DIRCLR_WIDTH = 32;
        public const uint PIN_CNF0_OFF = 0x700;
        public const int PIN_CNF0_WIDTH = 32;

        public const uint PIN_CNF0_DIR = 0x1;
        public const uint PIN_CNF0_DIR_LSB = 0;
        public const uint PIN_CNF0_INPUT = 0x2;
        public const uint PIN_CNF0_INPUT_LSB = 1;
        public const uint PIN_CNF0_PULL = 0xC;
        public const uint PIN_CNF0_PULL_LSB = 2;
        public const uint PIN_CNF0_DRIVE = 0x700;
        public const uint PIN_CNF0_DRIVE_LSB = 8;
        public const uint PIN_CNF0_SENSE = 0x30000;
        public const uint PIN_CNF0_SENSE_LSB = 16;

        public const uint PIN_CNF_STRIDE = 4;
    }
}
