// GENERATED by lamella-bsp-gen from csp/ra4m1/blocks/flash.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Ra4m1FlashLayout
    {
        private Ra4m1FlashLayout() { }



        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 8;
    }
}
