// GENERATED by lamella-bsp-gen from csp/ra4m1/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ra4m1
//
// The ra4m1 flash block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Ra4m1Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Ra4m1FlashLayout
    {
        private Ra4m1FlashLayout() { }

        // -- register offsets (block-relative) + access widths --

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

        // -- block constants --
        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 8;
    }
}
