// GENERATED by lamella-bsp-gen from csp/stm32f091/blocks/gpio.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32f091GpioLayout
    {
        private Stm32f091GpioLayout() { }

        public const uint MODER_OFF = 0x0;
        public const int MODER_WIDTH = 32;
        public const uint AFRL_OFF = 0x20;
        public const int AFRL_WIDTH = 32;

        public const uint MODER_MODER2 = 0x30;
        public const uint MODER_MODER2_LSB = 4;
        public const uint MODER_MODER3 = 0xC0;
        public const uint MODER_MODER3_LSB = 6;
        public const uint AFRL_AFSEL2 = 0xF00;
        public const uint AFRL_AFSEL2_LSB = 8;
        public const uint AFRL_AFSEL3 = 0xF000;
        public const uint AFRL_AFSEL3_LSB = 12;

        public const uint MODER_MODE_AF = 2;
    }
}
