// GENERATED by lamella-bsp-gen from csp/samd10/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd10
//
// The samd10 flash block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samd10Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Samd10FlashLayout
    {
        private Samd10FlashLayout() { }

        // -- register offsets (block-relative) + access widths --

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

        // -- block constants --
        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 64;
    }
}
