// GENERATED by lamella-bsp-gen from csp/samd11/blocks/port.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd11
//
// The samd11 port BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samd11Instances. Widths are access widths.

public enum Samd11PortLayout {
    // -- register offsets (block-relative) + access widths --
    public static let DIR_OFF: UInt32 = 0x0
    public static let DIR_WIDTH: Int32 = 32
    public static let DIRCLR_OFF: UInt32 = 0x4
    public static let DIRCLR_WIDTH: Int32 = 32
    public static let DIRSET_OFF: UInt32 = 0x8
    public static let DIRSET_WIDTH: Int32 = 32
    public static let DIRTGL_OFF: UInt32 = 0xC
    public static let DIRTGL_WIDTH: Int32 = 32
    public static let OUT_OFF: UInt32 = 0x10
    public static let OUT_WIDTH: Int32 = 32
    public static let OUTCLR_OFF: UInt32 = 0x14
    public static let OUTCLR_WIDTH: Int32 = 32
    public static let OUTSET_OFF: UInt32 = 0x18
    public static let OUTSET_WIDTH: Int32 = 32
    public static let OUTTGL_OFF: UInt32 = 0x1C
    public static let OUTTGL_WIDTH: Int32 = 32
    public static let IN_OFF: UInt32 = 0x20
    public static let IN_WIDTH: Int32 = 32
    public static let PMUX0_OFF: UInt32 = 0x30
    public static let PMUX0_WIDTH: Int32 = 8
    public static let PINCFG0_OFF: UInt32 = 0x40
    public static let PINCFG0_WIDTH: Int32 = 8

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let DIR_DIR: UInt32 = 0xFFFFFFFF
    public static let DIR_DIR_LSB: UInt32 = 0
    public static let DIRCLR_DIRCLR: UInt32 = 0xFFFFFFFF
    public static let DIRCLR_DIRCLR_LSB: UInt32 = 0
    public static let DIRSET_DIRSET: UInt32 = 0xFFFFFFFF
    public static let DIRSET_DIRSET_LSB: UInt32 = 0
    public static let DIRTGL_DIRTGL: UInt32 = 0xFFFFFFFF
    public static let DIRTGL_DIRTGL_LSB: UInt32 = 0
    public static let OUT_OUT: UInt32 = 0xFFFFFFFF
    public static let OUT_OUT_LSB: UInt32 = 0
    public static let OUTCLR_OUTCLR: UInt32 = 0xFFFFFFFF
    public static let OUTCLR_OUTCLR_LSB: UInt32 = 0
    public static let OUTSET_OUTSET: UInt32 = 0xFFFFFFFF
    public static let OUTSET_OUTSET_LSB: UInt32 = 0
    public static let OUTTGL_OUTTGL: UInt32 = 0xFFFFFFFF
    public static let OUTTGL_OUTTGL_LSB: UInt32 = 0
    public static let IN_IN: UInt32 = 0xFFFFFFFF
    public static let IN_IN_LSB: UInt32 = 0
    public static let PMUX0_PMUXE: UInt32 = 0xF
    public static let PMUX0_PMUXE_LSB: UInt32 = 0
    public static let PMUX0_PMUXO: UInt32 = 0xF0
    public static let PMUX0_PMUXO_LSB: UInt32 = 4
    public static let PINCFG0_PMUXEN: UInt32 = 0x1
    public static let PINCFG0_PMUXEN_LSB: UInt32 = 0
    public static let PINCFG0_INEN: UInt32 = 0x2
    public static let PINCFG0_INEN_LSB: UInt32 = 1
    public static let PINCFG0_PULLEN: UInt32 = 0x4
    public static let PINCFG0_PULLEN_LSB: UInt32 = 2
    public static let PINCFG0_DRVSTR: UInt32 = 0x40
    public static let PINCFG0_DRVSTR_LSB: UInt32 = 6

    // -- block constants --
    public static let FUNC_A: UInt32 = 0
    public static let FUNC_B: UInt32 = 1
    public static let FUNC_C: UInt32 = 2
    public static let FUNC_D: UInt32 = 3
    public static let FUNC_E: UInt32 = 4
    public static let FUNC_F: UInt32 = 5
    public static let FUNC_G: UInt32 = 6
    public static let FUNC_H: UInt32 = 7
}
