//! GENERATED by lamella-bsp-gen from bsp/same54-xpro/board.toml + csp/same54/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . same54

pub const BOARD_MODEL: u16 = 4;
pub const BOARD_VENDOR: &str = "Microchip";
