# GENERATED by lamella-bsp-gen from bsp/samd21-xpro/board.toml + csp/samd21/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21

BOARD = "samd21-xpro"
BOARD_MODEL = 5
BOARD_VENDOR = "Microchip"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
VCP = "vcp"

CARRIER = {
    "kind": "edbg-vcp",
    "usb_vid": 0x03EB,
    "usb_pid": 0x2169,
    "role": "vcp",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
FACTS = {
    "vcp": {
        "kind": "uart",
        "instance": "sercom3",
        "sercom_base": 0x42001400,
        "irq": 12,
        "gclk_clkctrl_value": 0x4017,
        "apbc_mask": 0x20,
        "pmux_reg": 0x4100443B,
        "pmux_pair": 0x22,
        "pincfg_tx_reg": 0x41004456,
        "pincfg_rx_reg": 0x41004457,
        "txpo": 0,
        "rxpo": 1,
        "baud_115200_osc8m_8mhz": 0xC505,
    },
}

PLANS = {
    "osc8m-8mhz": {"default": True, "source": "osc8m", "gclk0_hz": 8000000},
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
}
