// GENERATED by lamella-bsp-gen from bsp/samd21-cnano/board.toml + csp/samd21/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The samd21-cnano board bindings as Swift constants, name/value-identical to Samd21CnanoBindings.g.cs:
// every value below is a generation-time literal derived from the strata. Board truth
// lives in board.toml, never here.

public enum Samd21CnanoBindings {
    // -- identity --
    public static let BOARD_MODEL: UInt16 = 46
    public static let BOARD_VENDOR: String = "Microchip"

    // -- on-board devices: PORT group base + pin index + mask --
    public static let LED0_PORT_BASE: UInt32 = 0x41004480
    public static let LED0_PIN: UInt32 = 10
    public static let LED0_MASK: UInt32 = 0x400
    public static let LED0_ACTIVE_LOW: UInt32 = 1
    public static let BUTTON0_PORT_BASE: UInt32 = 0x41004480
    public static let BUTTON0_PIN: UInt32 = 11
    public static let BUTTON0_MASK: UInt32 = 0x800
    public static let BUTTON0_ACTIVE_LOW: UInt32 = 1
}
