// GENERATED by lamella-bsp-gen from bsp/st-nucleo-f439zi/board.toml + csp/stm32f42x/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32f42x
//
// The st-nucleo-f439zi board bindings (resolved against the stm32f42x chip strata): every value below is a
// generation-time literal derived from the strata -- role descriptors, module control
// lines, and the carrier identity. The board's facts are stated in board.toml.
namespace Lamella.Generated
{
    public sealed class StNucleoF439ziBindings
    {
        private StNucleoF439ziBindings() { }

        // -- identity --
        public const int BOARD_MODEL = 29;
        public const string BOARD_VENDOR = "St";
        public const uint DEVICE_COUNT = 4;

        // -- on-board devices: PORT group base + pin index + mask --
        public const uint LED0_PORT_BASE = 0x40020400;
        public const uint LED0_PIN = 0;
        public const uint LED0_MASK = 0x1;
        public const uint LED0_ACTIVE_LOW = 0;
        public const uint LED1_PORT_BASE = 0x40020400;
        public const uint LED1_PIN = 7;
        public const uint LED1_MASK = 0x80;
        public const uint LED1_ACTIVE_LOW = 0;
        public const uint LED2_PORT_BASE = 0x40020400;
        public const uint LED2_PIN = 14;
        public const uint LED2_MASK = 0x4000;
        public const uint LED2_ACTIVE_LOW = 0;
        public const uint BUTTON0_PORT_BASE = 0x40020800;
        public const uint BUTTON0_PIN = 13;
        public const uint BUTTON0_MASK = 0x2000;
        public const uint BUTTON0_ACTIVE_LOW = 0;
    }
}
