//! GENERATED by lamella-bsp-gen from csp/stm32u585/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32u585
//!
//! The stm32u585 instance map as Rust consts, name/value-identical to Stm32u585Instances.g.cs:
//! where each block copy sits and its per-instance ids. Each block's layout is in its own
//! layout module beside this file.

pub const GPIOG_BASE: u32 = 0x42021800;
pub const GPIOG_RCC_EN_OFF: u32 = 140;
pub const GPIOG_RCC_EN_BIT: u32 = 6;
pub const GPIOG_RCC_EN_MASK: u32 = 0x40;
pub const GPIOH_BASE: u32 = 0x42021C00;
pub const GPIOH_RCC_EN_OFF: u32 = 140;
pub const GPIOH_RCC_EN_BIT: u32 = 7;
pub const GPIOH_RCC_EN_MASK: u32 = 0x80;
pub const SPI3_BASE: u32 = 0x46002000;
pub const SPI3_RCC_EN_OFF: u32 = 168;
pub const SPI3_RCC_EN_BIT: u32 = 5;
pub const SPI3_RCC_EN_MASK: u32 = 0x20;
pub const LPUART1_BASE: u32 = 0x46002400;
pub const LPUART1_RCC_EN_OFF: u32 = 168;
pub const LPUART1_RCC_EN_BIT: u32 = 6;
pub const LPUART1_RCC_EN_MASK: u32 = 0x40;
pub const RCC_BASE: u32 = 0x46020C00;
