// GENERATED by lamella-bsp-gen from csp/samd21/blocks/flash.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Samd21FlashLayout
    {
        private Samd21FlashLayout() { }



        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 64;
    }
}
