// GENERATED by lamella-bsp-gen from csp/samd21/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The samd21 flash block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samd21Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Samd21FlashLayout
    {
        private Samd21FlashLayout() { }

        // -- register offsets (block-relative) + access widths --

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

        // -- block constants --
        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 64;
    }
}
