// GENERATED by lamella-bsp-gen from csp/samd21/blocks/adc.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The samd21 adc block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samd21Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Samd21AdcLayout
    {
        private Samd21AdcLayout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint CTRLA_OFF = 0x0;
        public const int CTRLA_WIDTH = 8;
        public const uint REFCTRL_OFF = 0x1;
        public const int REFCTRL_WIDTH = 8;
        public const uint AVGCTRL_OFF = 0x2;
        public const int AVGCTRL_WIDTH = 8;
        public const uint SAMPCTRL_OFF = 0x3;
        public const int SAMPCTRL_WIDTH = 8;
        public const uint CTRLB_OFF = 0x4;
        public const int CTRLB_WIDTH = 16;
        public const uint WINCTRL_OFF = 0x8;
        public const int WINCTRL_WIDTH = 8;
        public const uint SWTRIG_OFF = 0xC;
        public const int SWTRIG_WIDTH = 8;
        public const uint INPUTCTRL_OFF = 0x10;
        public const int INPUTCTRL_WIDTH = 32;
        public const uint EVCTRL_OFF = 0x14;
        public const int EVCTRL_WIDTH = 8;
        public const uint INTENCLR_OFF = 0x16;
        public const int INTENCLR_WIDTH = 8;
        public const uint INTENSET_OFF = 0x17;
        public const int INTENSET_WIDTH = 8;
        public const uint INTFLAG_OFF = 0x18;
        public const int INTFLAG_WIDTH = 8;
        public const uint STATUS_OFF = 0x19;
        public const int STATUS_WIDTH = 8;
        public const uint RESULT_OFF = 0x1A;
        public const int RESULT_WIDTH = 16;
        public const uint WINLT_OFF = 0x1C;
        public const int WINLT_WIDTH = 16;
        public const uint WINUT_OFF = 0x20;
        public const int WINUT_WIDTH = 16;
        public const uint GAINCORR_OFF = 0x24;
        public const int GAINCORR_WIDTH = 16;
        public const uint OFFSETCORR_OFF = 0x26;
        public const int OFFSETCORR_WIDTH = 16;
        public const uint CALIB_OFF = 0x28;
        public const int CALIB_WIDTH = 16;
        public const uint DBGCTRL_OFF = 0x2A;
        public const int DBGCTRL_WIDTH = 8;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
        public const uint CTRLA_SWRST = 0x1;
        public const uint CTRLA_SWRST_LSB = 0;
        public const uint CTRLA_ENABLE = 0x2;
        public const uint CTRLA_ENABLE_LSB = 1;
        public const uint CTRLA_RUNSTDBY = 0x4;
        public const uint CTRLA_RUNSTDBY_LSB = 2;
        public const uint REFCTRL_REFSEL = 0xF;
        public const uint REFCTRL_REFSEL_LSB = 0;
        public const uint REFCTRL_REFCOMP = 0x80;
        public const uint REFCTRL_REFCOMP_LSB = 7;
        public const uint AVGCTRL_SAMPLENUM = 0xF;
        public const uint AVGCTRL_SAMPLENUM_LSB = 0;
        public const uint AVGCTRL_ADJRES = 0x70;
        public const uint AVGCTRL_ADJRES_LSB = 4;
        public const uint SAMPCTRL_SAMPLEN = 0x3F;
        public const uint SAMPCTRL_SAMPLEN_LSB = 0;
        public const uint CTRLB_DIFFMODE = 0x1;
        public const uint CTRLB_DIFFMODE_LSB = 0;
        public const uint CTRLB_LEFTADJ = 0x2;
        public const uint CTRLB_LEFTADJ_LSB = 1;
        public const uint CTRLB_FREERUN = 0x4;
        public const uint CTRLB_FREERUN_LSB = 2;
        public const uint CTRLB_CORREN = 0x8;
        public const uint CTRLB_CORREN_LSB = 3;
        public const uint CTRLB_RESSEL = 0x30;
        public const uint CTRLB_RESSEL_LSB = 4;
        public const uint CTRLB_PRESCALER = 0x700;
        public const uint CTRLB_PRESCALER_LSB = 8;
        public const uint WINCTRL_WINMODE = 0x7;
        public const uint WINCTRL_WINMODE_LSB = 0;
        public const uint SWTRIG_FLUSH = 0x1;
        public const uint SWTRIG_FLUSH_LSB = 0;
        public const uint SWTRIG_START = 0x2;
        public const uint SWTRIG_START_LSB = 1;
        public const uint INPUTCTRL_MUXPOS = 0x1F;
        public const uint INPUTCTRL_MUXPOS_LSB = 0;
        public const uint INPUTCTRL_MUXNEG = 0x1F00;
        public const uint INPUTCTRL_MUXNEG_LSB = 8;
        public const uint INPUTCTRL_INPUTSCAN = 0xF0000;
        public const uint INPUTCTRL_INPUTSCAN_LSB = 16;
        public const uint INPUTCTRL_INPUTOFFSET = 0xF00000;
        public const uint INPUTCTRL_INPUTOFFSET_LSB = 20;
        public const uint INPUTCTRL_GAIN = 0xF000000;
        public const uint INPUTCTRL_GAIN_LSB = 24;
        public const uint EVCTRL_STARTEI = 0x1;
        public const uint EVCTRL_STARTEI_LSB = 0;
        public const uint EVCTRL_SYNCEI = 0x2;
        public const uint EVCTRL_SYNCEI_LSB = 1;
        public const uint EVCTRL_RESRDYEO = 0x10;
        public const uint EVCTRL_RESRDYEO_LSB = 4;
        public const uint EVCTRL_WINMONEO = 0x20;
        public const uint EVCTRL_WINMONEO_LSB = 5;
        public const uint INTENCLR_RESRDY = 0x1;
        public const uint INTENCLR_RESRDY_LSB = 0;
        public const uint INTENCLR_OVERRUN = 0x2;
        public const uint INTENCLR_OVERRUN_LSB = 1;
        public const uint INTENCLR_WINMON = 0x4;
        public const uint INTENCLR_WINMON_LSB = 2;
        public const uint INTENCLR_SYNCRDY = 0x8;
        public const uint INTENCLR_SYNCRDY_LSB = 3;
        public const uint INTENSET_RESRDY = 0x1;
        public const uint INTENSET_RESRDY_LSB = 0;
        public const uint INTENSET_OVERRUN = 0x2;
        public const uint INTENSET_OVERRUN_LSB = 1;
        public const uint INTENSET_WINMON = 0x4;
        public const uint INTENSET_WINMON_LSB = 2;
        public const uint INTENSET_SYNCRDY = 0x8;
        public const uint INTENSET_SYNCRDY_LSB = 3;
        public const uint INTFLAG_RESRDY = 0x1;
        public const uint INTFLAG_RESRDY_LSB = 0;
        public const uint INTFLAG_OVERRUN = 0x2;
        public const uint INTFLAG_OVERRUN_LSB = 1;
        public const uint INTFLAG_WINMON = 0x4;
        public const uint INTFLAG_WINMON_LSB = 2;
        public const uint INTFLAG_SYNCRDY = 0x8;
        public const uint INTFLAG_SYNCRDY_LSB = 3;
        public const uint STATUS_SYNCBUSY = 0x80;
        public const uint STATUS_SYNCBUSY_LSB = 7;
        public const uint RESULT_RESULT = 0xFFFF;
        public const uint RESULT_RESULT_LSB = 0;
        public const uint WINLT_WINLT = 0xFFFF;
        public const uint WINLT_WINLT_LSB = 0;
        public const uint WINUT_WINUT = 0xFFFF;
        public const uint WINUT_WINUT_LSB = 0;
        public const uint GAINCORR_GAINCORR = 0xFFF;
        public const uint GAINCORR_GAINCORR_LSB = 0;
        public const uint OFFSETCORR_OFFSETCORR = 0xFFF;
        public const uint OFFSETCORR_OFFSETCORR_LSB = 0;
        public const uint CALIB_LINEARITY_CAL = 0xFF;
        public const uint CALIB_LINEARITY_CAL_LSB = 0;
        public const uint CALIB_BIAS_CAL = 0x700;
        public const uint CALIB_BIAS_CAL_LSB = 8;
        public const uint DBGCTRL_DBGRUN = 0x1;
        public const uint DBGCTRL_DBGRUN_LSB = 0;

        // -- block constants --
        public const uint REFSEL_INT1V = 0;
        public const uint REFSEL_INTVCC0 = 1;
        public const uint REFSEL_INTVCC1 = 2;
        public const uint REFSEL_VREFA = 3;
        public const uint REFSEL_VREFB = 4;
        public const uint RESSEL_12BIT = 0;
        public const uint RESSEL_16BIT = 1;
        public const uint RESSEL_10BIT = 2;
        public const uint RESSEL_8BIT = 3;
        public const uint PRESCALER_DIV4 = 0;
        public const uint PRESCALER_DIV8 = 1;
        public const uint PRESCALER_DIV16 = 2;
        public const uint PRESCALER_DIV32 = 3;
        public const uint PRESCALER_DIV64 = 4;
        public const uint PRESCALER_DIV128 = 5;
        public const uint PRESCALER_DIV256 = 6;
        public const uint PRESCALER_DIV512 = 7;
        public const uint GAIN_1X = 0;
        public const uint GAIN_DIV2 = 15;
        public const uint MUXNEG_GND = 24;
        public const uint MUXNEG_IOGND = 25;
        public const uint NVM_CALIBRATION_AREA = 0x806020;
        public const uint NVM_LINEARITY_LSB = 27;
        public const uint NVM_LINEARITY_WIDTH = 8;
        public const uint NVM_BIASCAL_LSB = 35;
        public const uint NVM_BIASCAL_WIDTH = 3;

        /// <summary>The division PRESCALER code <paramref name="code"/> selects, from the
        /// PRESCALER_DIV constants above, or 0 for a code none of them names.</summary>
        public static uint PrescalerDivisor(uint code)
        {
            switch (code)
            {
                case 0: return 4;
                case 1: return 8;
                case 2: return 16;
                case 3: return 32;
                case 4: return 64;
                case 5: return 128;
                case 6: return 256;
                case 7: return 512;
            }
            return 0;
        }

        // -- facts as data (chip/electrical facts conversions read) --
        public const uint ResolutionBits = 12;
        public const uint MinValue = 0;
        public const uint MaxValue = 4095;
        public const uint GclkAdcMaxHz = 48000000;
        public const uint ClkAdcMinHz = 30000;
        public const uint ClkAdcMaxHz = 2100000;

        // -- channel map: Channel_<source> = the mux/AINSEL index; Channel<i>_Pin = the
        // GPIO index a pin-fed channel taps (the inverse, so no driver carries a pin
        // literal); ChannelCount = how many rows the map has; IsChannel = whether an
        // index is one of them --
        public const int Channel_AIN0 = 0;
        public const int Channel_AIN1 = 1;
        public const int Channel_AIN2 = 2;
        public const int Channel_AIN3 = 3;
        public const int Channel_AIN4 = 4;
        public const int Channel_AIN5 = 5;
        public const int Channel_AIN6 = 6;
        public const int Channel_AIN7 = 7;
        public const int Channel_AIN8 = 8;
        public const int Channel_AIN9 = 9;
        public const int Channel_AIN10 = 10;
        public const int Channel_AIN11 = 11;
        public const int Channel_AIN12 = 12;
        public const int Channel_AIN13 = 13;
        public const int Channel_AIN14 = 14;
        public const int Channel_AIN15 = 15;
        public const int Channel_AIN16 = 16;
        public const int Channel_AIN17 = 17;
        public const int Channel_AIN18 = 18;
        public const int Channel_AIN19 = 19;
        public const int Channel_Bandgap = 25;
        public const int Channel_ScaledCoreSupply = 26;
        public const int Channel_ScaledIoSupply = 27;
        public const int ChannelCount = 23;

        /// <summary>Whether <paramref name="channel"/> is the index of a row in the
        /// channel map above. The indexes need not run without gaps, so ChannelCount alone
        /// does not answer this.</summary>
        public static bool IsChannel(int channel)
        {
            switch (channel)
            {
                case 0: return true;
                case 1: return true;
                case 2: return true;
                case 3: return true;
                case 4: return true;
                case 5: return true;
                case 6: return true;
                case 7: return true;
                case 8: return true;
                case 9: return true;
                case 10: return true;
                case 11: return true;
                case 12: return true;
                case 13: return true;
                case 14: return true;
                case 15: return true;
                case 16: return true;
                case 17: return true;
                case 18: return true;
                case 19: return true;
                case 25: return true;
                case 26: return true;
                case 27: return true;
            }
            return false;
        }
    }
}
