//! GENERATED by lamella-bsp-gen from csp/ch32v003/blocks/gpio.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ch32v003

/// -- register offsets (block-relative) + access widths --
pub const CFGLR_OFF: u32 = 0x0;
pub const CFGLR_WIDTH: i32 = 32;
pub const INDR_OFF: u32 = 0x8;
pub const INDR_WIDTH: i32 = 32;
pub const OUTDR_OFF: u32 = 0xC;
pub const OUTDR_WIDTH: i32 = 32;
pub const BSHR_OFF: u32 = 0x10;
pub const BSHR_WIDTH: i32 = 32;
pub const BCR_OFF: u32 = 0x14;
pub const BCR_WIDTH: i32 = 32;
pub const LCKR_OFF: u32 = 0x18;
pub const LCKR_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const CFGLR_MODE6: u32 = 0x3000000;
pub const CFGLR_MODE6_LSB: u32 = 24;
pub const CFGLR_CNF6: u32 = 0xC000000;
pub const CFGLR_CNF6_LSB: u32 = 26;
pub const BSHR_BS6: u32 = 0x40;
pub const BSHR_BS6_LSB: u32 = 6;
pub const BSHR_BR6: u32 = 0x400000;
pub const BSHR_BR6_LSB: u32 = 22;
pub const BCR_BR6: u32 = 0x40;
pub const BCR_BR6_LSB: u32 = 6;

/// -- block constants --
pub const CFGLR_MODE_INPUT: u32 = 0;
pub const CFGLR_MODE_OUTPUT_10MHZ: u32 = 1;
pub const CFGLR_MODE_OUTPUT_2MHZ: u32 = 2;
pub const CFGLR_MODE_OUTPUT_30MHZ: u32 = 3;
pub const CFGLR_CNF_OUTPUT_PUSH_PULL: u32 = 0;
pub const CFGLR_CNF_OUTPUT_OPEN_DRAIN: u32 = 1;
pub const CFGLR_CNF_OUTPUT_AF_PUSH_PULL: u32 = 2;
pub const CFGLR_CNF_OUTPUT_AF_OPEN_DRAIN: u32 = 3;
pub const CFGLR_CNF_INPUT_ANALOG: u32 = 0;
pub const CFGLR_CNF_INPUT_FLOATING: u32 = 1;
pub const CFGLR_CNF_INPUT_PULL: u32 = 2;
pub const CFGLR_RESET: u32 = 0x44444444;
