//! GENERATED by lamella-bsp-gen from bsp/samg55-xpro/board.toml + csp/samg55/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samg55

pub const BOARD_MODEL: u16 = 60;
pub const BOARD_VENDOR: &str = "Microchip";
pub const CARRIER_USB_VID: u16 = 0x03EB;

pub const LED0_PORT_BASE: u32 = 0x400E0E00;
pub const LED0_PIN: u32 = 6;
pub const LED0_MASK: u32 = 0x40;
pub const LED0_ACTIVE_LOW: u32 = 1;
pub const BUTTON0_PORT_BASE: u32 = 0x400E0E00;
pub const BUTTON0_PIN: u32 = 2;
pub const BUTTON0_MASK: u32 = 0x4;
pub const BUTTON0_ACTIVE_LOW: u32 = 1;
