//! GENERATED by lamella-bsp-gen from csp/sam4l/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4l
//!
//! The sam4l instance map as Rust consts, name/value-identical to Sam4lInstances.g.cs:
//! where each block copy sits and its per-instance ids. Each block's layout is in its own
//! layout module beside this file.

pub const GPIO_PORT2_BASE: u32 = 0x400E1400;
