//! GENERATED by lamella-bsp-gen from csp/sam4l/blocks/flash.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4l
//!
//! The sam4l flash block layout as Rust consts, name/value-identical to Sam4lFlashLayout.g.cs:
//! offsets are instance-base-relative (`base + *_OFF`) and the instance bases live in
//! sam4l_instances.rs. Widths are access widths.

/// -- block constants --
pub const ERASED_VALUE: u32 = 0xFFFFFFFF;
pub const WRITE_UNIT: u32 = 512;
