//! GENERATED by lamella-bsp-gen from csp/sam4l/blocks/flash.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4l

/// -- block constants --
pub const ERASED_VALUE: u32 = 0xFFFFFFFF;
pub const WRITE_UNIT: u32 = 512;
