// GENERATED by lamella-bsp-gen from csp/stm32l073/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32l073
//
// The stm32l073 flash block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Stm32l073Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Stm32l073FlashLayout
    {
        private Stm32l073FlashLayout() { }

        // -- register offsets (block-relative) + access widths --

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

        // -- block constants --
        public const uint ERASED_VALUE = 0x0;
        public const uint WRITE_UNIT = 4;
    }
}
