// GENERATED by lamella-bsp-gen from bsp/esp32c6-devkitc/board.toml + csp/esp32c6/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Esp32c6DevkitcBindings
    {
        private Esp32c6DevkitcBindings() { }

        public const int BOARD_MODEL = 14;
        public const string BOARD_VENDOR = "Espressif";

        /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
        /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
        /// peripherals of the same kind can share no register at all, so a consumer that selects a
        /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
        /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
        /// name a driver; and a uart is a different register map on every family, so the kind does
        /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
        public const string UART0_DRIVER_FAMILY = "esp32c6-uart";

        public const uint UART0_BASE = 0x60000000;
        public const uint UART0_PCR_CONF = 0x60096000;
        public const uint UART0_PCR_SCLK_CONF = 0x60096004;
        public const uint UART0_IO_MUX_TX = 0x60090044;
        public const uint UART0_IO_MUX_RX = 0x60090048;
        public const uint UART0_MCU_SEL = 0;
        public const uint UART0_SCLK_HZ = 40000000;
    }
}
