// GENERATED by lamella-bsp-gen from csp/samg55/blocks/pmc.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samg55
//
// The samg55 pmc block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samg55Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Samg55PmcLayout
    {
        private Samg55PmcLayout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint PCER0_OFF = 0x10;
        public const int PCER0_WIDTH = 32;
        public const uint PCDR0_OFF = 0x14;
        public const int PCDR0_WIDTH = 32;
        public const uint PCSR0_OFF = 0x18;
        public const int PCSR0_WIDTH = 32;
        public const uint PCER1_OFF = 0x100;
        public const int PCER1_WIDTH = 32;
        public const uint PCDR1_OFF = 0x104;
        public const int PCDR1_WIDTH = 32;
        public const uint PCSR1_OFF = 0x108;
        public const int PCSR1_WIDTH = 32;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
        public const uint PCER0_PCER0 = 0xFFFFFFFF;
        public const uint PCER0_PCER0_LSB = 0;
        public const uint PCDR0_PCDR0 = 0xFFFFFFFF;
        public const uint PCDR0_PCDR0_LSB = 0;
        public const uint PCSR0_PCSR0 = 0xFFFFFFFF;
        public const uint PCSR0_PCSR0_LSB = 0;
        public const uint PCER1_PCER1 = 0xFFFFFFFF;
        public const uint PCER1_PCER1_LSB = 0;
        public const uint PCDR1_PCDR1 = 0xFFFFFFFF;
        public const uint PCDR1_PCDR1_LSB = 0;
        public const uint PCSR1_PCSR1 = 0xFFFFFFFF;
        public const uint PCSR1_PCSR1_LSB = 0;
    }
}
