// GENERATED by lamella-bsp-gen from csp/samg55/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Samg55Instances
    {
        private Samg55Instances() { }

        public const uint PIOA_BASE = 0x400E0E00;
        public const uint PIOA_PID = 11;
        public const uint PIOB_BASE = 0x400E1000;
        public const uint PIOB_PID = 12;
        public const uint PMC_BASE = 0x400E0400;
        public const uint PMC_PID = 5;
        public const uint FLEXCOM0_BASE = 0x4000C000;
        public const uint FLEXCOM1_BASE = 0x40020000;
        public const uint FLEXCOM2_BASE = 0x40024000;
        public const uint FLEXCOM3_BASE = 0x40018000;
        public const uint FLEXCOM4_BASE = 0x4001C000;
        public const uint FLEXCOM5_BASE = 0x40008000;
        public const uint FLEXCOM6_BASE = 0x40040000;
        public const uint FLEXCOM7_BASE = 0x40034000;
    }
}
