//! GENERATED by lamella-bsp-gen from bsp/sam4l8-xpro/board.toml + csp/sam4l/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4l

pub const BOARD_MODEL: u16 = 27;
pub const BOARD_VENDOR: &str = "Atmel";

pub const LED0_PORT_BASE: u32 = 0x400E1400;
pub const LED0_PIN: u32 = 7;
pub const LED0_MASK: u32 = 0x80;
pub const LED0_ACTIVE_LOW: u32 = 1;
pub const BUTTON0_PORT_BASE: u32 = 0x400E1400;
pub const BUTTON0_PIN: u32 = 24;
pub const BUTTON0_MASK: u32 = 0x1000000;
pub const BUTTON0_ACTIVE_LOW: u32 = 1;
