// GENERATED by lamella-bsp-gen from parts/bmx280/bme280.toml + parts/bmx280/bmx280.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-parts . bmx280
//
// The bme280 part table, FLATTENED: every value it inherited is spelled out here, because a
// value that is only ever inherited is pinned in no emitted artifact and so cannot be
// checked for drift between languages. A part is something we talk TO rather than a chip
// we run on -- a board states which buses exist, this table states the part's identity,
// and a probe joins the two at run time.

public enum Bme280Part {
    public static let PART: StaticString = "bme280"
    public static let FAMILY: StaticString = "bmx280"

    // identity: the accepted values are a SET. A driver that accepts only one of them rejects a genuine part, and a rejected part reads as no part at all -- so on a mismatch, name the id received AND this set.
    public static let IDENTITY_REG: UInt32 = 0xD0
    public static let IDENTITY_WIDTH: UInt32 = 8
    public static let IDENTITY_VALUE_COUNT: UInt32 = 1
    public static let IDENTITY_VALUE_0: UInt32 = 0x60

    // address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
    public static let ADDRESS_BUS: StaticString = "i2c"
    public static let ADDRESS_BASE: UInt32 = 0x76
    public static let ADDRESS_STRAP_COUNT: UInt32 = 1
    public static let ADDRESS_STRAP_SDO_BIT: UInt32 = 0
    public static let ADDRESS_STRAP_SDO_LOW: UInt32 = 0x76
    public static let ADDRESS_STRAP_SDO_HIGH: UInt32 = 0x77

    // buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
    public static let BUS_COUNT: UInt32 = 2
    public static let BUS_I2C_KIND: StaticString = "i2c"
    public static let BUS_I2C_REGISTER_READ_TRANSFORM: StaticString = "identity"
    public static let BUS_I2C_REGISTER_WRITE_TRANSFORM: StaticString = "identity"
    public static let BUS_I2C_READ_PROTOCOL: StaticString = "write-register-then-repeated-start-read"
    public static let BUS_SPI_KIND: StaticString = "spi"
    public static let BUS_SPI_REGISTER_READ_TRANSFORM: StaticString = "set-bit7"
    public static let BUS_SPI_REGISTER_WRITE_TRANSFORM: StaticString = "clear-bit7"
    public static let BUS_SPI_READ_PROTOCOL: StaticString = "single-chip-select-address-then-clock-data"
    public static let BUS_SPI_MODE_COUNT: UInt32 = 2
    public static let BUS_SPI_MODE_0: UInt32 = 0
    public static let BUS_SPI_MODE_1: UInt32 = 3

    // registers: `_REG` is the address written on the wire -- an operand, NOT an offset to add to an instance base. Fields carry the shifted mask and its shift.
    public static let ID_REG: UInt32 = 0xD0
    public static let ID_WIDTH: UInt32 = 8
    public static let ID_ACCESS: StaticString = "read-only"
    public static let ID_CHIP_ID: UInt32 = 0xFF
    public static let ID_CHIP_ID_LSB: UInt32 = 0
    public static let RESET_REG: UInt32 = 0xE0
    public static let RESET_WIDTH: UInt32 = 8
    public static let RESET_ACCESS: StaticString = "write-only"
    public static let RESET_RESET: UInt32 = 0xFF
    public static let RESET_RESET_LSB: UInt32 = 0
    public static let STATUS_REG: UInt32 = 0xF3
    public static let STATUS_WIDTH: UInt32 = 8
    public static let STATUS_ACCESS: StaticString = "read-only"
    public static let STATUS_IM_UPDATE: UInt32 = 0x1
    public static let STATUS_IM_UPDATE_LSB: UInt32 = 0
    public static let STATUS_MEASURING: UInt32 = 0x8
    public static let STATUS_MEASURING_LSB: UInt32 = 3
    public static let CTRL_MEAS_REG: UInt32 = 0xF4
    public static let CTRL_MEAS_WIDTH: UInt32 = 8
    public static let CTRL_MEAS_ACCESS: StaticString = "read-write"
    public static let CTRL_MEAS_MODE: UInt32 = 0x3
    public static let CTRL_MEAS_MODE_LSB: UInt32 = 0
    public static let CTRL_MEAS_OSRS_P: UInt32 = 0x1C
    public static let CTRL_MEAS_OSRS_P_LSB: UInt32 = 2
    public static let CTRL_MEAS_OSRS_T: UInt32 = 0xE0
    public static let CTRL_MEAS_OSRS_T_LSB: UInt32 = 5
    public static let CONFIG_REG: UInt32 = 0xF5
    public static let CONFIG_WIDTH: UInt32 = 8
    public static let CONFIG_ACCESS: StaticString = "read-write"
    public static let CONFIG_SPI3W_EN: UInt32 = 0x1
    public static let CONFIG_SPI3W_EN_LSB: UInt32 = 0
    public static let CONFIG_FILTER: UInt32 = 0x1C
    public static let CONFIG_FILTER_LSB: UInt32 = 2
    public static let CONFIG_T_SB: UInt32 = 0xE0
    public static let CONFIG_T_SB_LSB: UInt32 = 5
    public static let PRESS_REG: UInt32 = 0xF7
    public static let PRESS_WIDTH: UInt32 = 24
    public static let PRESS_ACCESS: StaticString = "read-only"
    public static let PRESS_PRESS_MSB: UInt32 = 0xFF0000
    public static let PRESS_PRESS_MSB_LSB: UInt32 = 16
    public static let PRESS_PRESS_LSB: UInt32 = 0xFF00
    public static let PRESS_PRESS_LSB_LSB: UInt32 = 8
    public static let PRESS_PRESS_XLSB: UInt32 = 0xF0
    public static let PRESS_PRESS_XLSB_LSB: UInt32 = 4
    public static let TEMP_REG: UInt32 = 0xFA
    public static let TEMP_WIDTH: UInt32 = 24
    public static let TEMP_ACCESS: StaticString = "read-only"
    public static let TEMP_TEMP_MSB: UInt32 = 0xFF0000
    public static let TEMP_TEMP_MSB_LSB: UInt32 = 16
    public static let TEMP_TEMP_LSB: UInt32 = 0xFF00
    public static let TEMP_TEMP_LSB_LSB: UInt32 = 8
    public static let TEMP_TEMP_XLSB: UInt32 = 0xF0
    public static let TEMP_TEMP_XLSB_LSB: UInt32 = 4
    public static let CTRL_HUM_REG: UInt32 = 0xF2
    public static let CTRL_HUM_WIDTH: UInt32 = 8
    public static let CTRL_HUM_ACCESS: StaticString = "read-write"
    public static let CTRL_HUM_OSRS_H: UInt32 = 0x7
    public static let CTRL_HUM_OSRS_H_LSB: UInt32 = 0
    public static let HUM_REG: UInt32 = 0xFD
    public static let HUM_WIDTH: UInt32 = 16
    public static let HUM_ACCESS: StaticString = "read-only"
    public static let HUM_HUM_MSB: UInt32 = 0xFF00
    public static let HUM_HUM_MSB_LSB: UInt32 = 8
    public static let HUM_HUM_LSB: UInt32 = 0xFF
    public static let HUM_HUM_LSB_LSB: UInt32 = 0

    // encodings: the codes a field takes, as this part reads them.
    public static let OVERSAMPLING_SKIPPED: UInt32 = 0
    public static let OVERSAMPLING_X1: UInt32 = 1
    public static let OVERSAMPLING_X2: UInt32 = 2
    public static let OVERSAMPLING_X4: UInt32 = 3
    public static let OVERSAMPLING_X8: UInt32 = 4
    public static let OVERSAMPLING_X16: UInt32 = 5
    public static let MODE_SLEEP: UInt32 = 0
    public static let MODE_FORCED: UInt32 = 1
    public static let MODE_NORMAL: UInt32 = 3
    public static let FILTER_OFF: UInt32 = 0
    public static let FILTER_X2: UInt32 = 1
    public static let FILTER_X4: UInt32 = 2
    public static let FILTER_X8: UInt32 = 3
    public static let FILTER_X16: UInt32 = 4
    public static let RESET_COMMAND_SOFT_RESET: UInt32 = 0xB6
    public static let STANDBY_US_0: UInt32 = 500
    public static let STANDBY_US_1: UInt32 = 62500
    public static let STANDBY_US_2: UInt32 = 125000
    public static let STANDBY_US_3: UInt32 = 250000
    public static let STANDBY_US_4: UInt32 = 500000
    public static let STANDBY_US_5: UInt32 = 1000000
    public static let STANDBY_US_6: UInt32 = 10000
    public static let STANDBY_US_7: UInt32 = 20000

    // measurement: the part holds a whole data block steady for the duration of one burst, so a byte-at-a-time read can mix two conversions.
    public static let BURST_LENGTH: UInt32 = 8

    // calibration 'temperature': these parameters are READ from the part and are per-device -- they are not constants and must not be baked into a driver. `_FORM` selects hand-written per-language arithmetic; signedness is not uniform, and reading it backwards yields a plausible wrong answer rather than an error.
    public static let TEMPERATURE_FORM: StaticString = "bmx280-t-int32"
    public static let TEMPERATURE_BYTE_ORDER: StaticString = "little"
    public static let TEMPERATURE_OUTPUT_SCALE: StaticString = "centi-degrees-celsius"
    public static let TEMPERATURE_READ_COUNT: UInt32 = 3
    public static let TEMPERATURE_DIG_T1_REG: UInt32 = 0x88
    public static let TEMPERATURE_DIG_T1_WIDTH: UInt32 = 16
    public static let TEMPERATURE_DIG_T1_SIGNED: UInt32 = 0
    public static let TEMPERATURE_DIG_T2_REG: UInt32 = 0x8A
    public static let TEMPERATURE_DIG_T2_WIDTH: UInt32 = 16
    public static let TEMPERATURE_DIG_T2_SIGNED: UInt32 = 1
    public static let TEMPERATURE_DIG_T3_REG: UInt32 = 0x8C
    public static let TEMPERATURE_DIG_T3_WIDTH: UInt32 = 16
    public static let TEMPERATURE_DIG_T3_SIGNED: UInt32 = 1

    // calibration 'pressure': these parameters are READ from the part and are per-device -- they are not constants and must not be baked into a driver. `_FORM` selects hand-written per-language arithmetic; signedness is not uniform, and reading it backwards yields a plausible wrong answer rather than an error.
    public static let PRESSURE_FORM: StaticString = "bmx280-p-int64"
    public static let PRESSURE_BYTE_ORDER: StaticString = "little"
    public static let PRESSURE_OUTPUT_SCALE: StaticString = "q24.8-pascals"
    public static let PRESSURE_DEPENDS_ON_COUNT: UInt32 = 1
    public static let PRESSURE_DEPENDS_ON_0: StaticString = "temperature"
    public static let PRESSURE_READ_COUNT: UInt32 = 9
    public static let PRESSURE_DIG_P1_REG: UInt32 = 0x8E
    public static let PRESSURE_DIG_P1_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P1_SIGNED: UInt32 = 0
    public static let PRESSURE_DIG_P2_REG: UInt32 = 0x90
    public static let PRESSURE_DIG_P2_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P2_SIGNED: UInt32 = 1
    public static let PRESSURE_DIG_P3_REG: UInt32 = 0x92
    public static let PRESSURE_DIG_P3_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P3_SIGNED: UInt32 = 1
    public static let PRESSURE_DIG_P4_REG: UInt32 = 0x94
    public static let PRESSURE_DIG_P4_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P4_SIGNED: UInt32 = 1
    public static let PRESSURE_DIG_P5_REG: UInt32 = 0x96
    public static let PRESSURE_DIG_P5_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P5_SIGNED: UInt32 = 1
    public static let PRESSURE_DIG_P6_REG: UInt32 = 0x98
    public static let PRESSURE_DIG_P6_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P6_SIGNED: UInt32 = 1
    public static let PRESSURE_DIG_P7_REG: UInt32 = 0x9A
    public static let PRESSURE_DIG_P7_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P7_SIGNED: UInt32 = 1
    public static let PRESSURE_DIG_P8_REG: UInt32 = 0x9C
    public static let PRESSURE_DIG_P8_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P8_SIGNED: UInt32 = 1
    public static let PRESSURE_DIG_P9_REG: UInt32 = 0x9E
    public static let PRESSURE_DIG_P9_WIDTH: UInt32 = 16
    public static let PRESSURE_DIG_P9_SIGNED: UInt32 = 1

    // calibration 'humidity': these parameters are READ from the part and are per-device -- they are not constants and must not be baked into a driver. `_FORM` selects hand-written per-language arithmetic; signedness is not uniform, and reading it backwards yields a plausible wrong answer rather than an error.
    public static let HUMIDITY_FORM: StaticString = "bmx280-h-int32"
    public static let HUMIDITY_BYTE_ORDER: StaticString = "little"
    public static let HUMIDITY_OUTPUT_SCALE: StaticString = "q22.10-percent-relative-humidity"
    public static let HUMIDITY_DEPENDS_ON_COUNT: UInt32 = 1
    public static let HUMIDITY_DEPENDS_ON_0: StaticString = "temperature"
    public static let HUMIDITY_READ_COUNT: UInt32 = 6
    public static let HUMIDITY_DIG_H1_REG: UInt32 = 0xA1
    public static let HUMIDITY_DIG_H1_WIDTH: UInt32 = 8
    public static let HUMIDITY_DIG_H1_SIGNED: UInt32 = 0
    public static let HUMIDITY_DIG_H2_REG: UInt32 = 0xE1
    public static let HUMIDITY_DIG_H2_WIDTH: UInt32 = 16
    public static let HUMIDITY_DIG_H2_SIGNED: UInt32 = 1
    public static let HUMIDITY_DIG_H3_REG: UInt32 = 0xE3
    public static let HUMIDITY_DIG_H3_WIDTH: UInt32 = 8
    public static let HUMIDITY_DIG_H3_SIGNED: UInt32 = 0
    public static let HUMIDITY_DIG_H4_REG: UInt32 = 0xE4
    public static let HUMIDITY_DIG_H4_WIDTH: UInt32 = 12
    public static let HUMIDITY_DIG_H4_SIGNED: UInt32 = 1
    public static let HUMIDITY_DIG_H4_PACKING: StaticString = "high8-at-0xE4-low4-in-low-nibble-of-0xE5"
    public static let HUMIDITY_DIG_H5_REG: UInt32 = 0xE6
    public static let HUMIDITY_DIG_H5_WIDTH: UInt32 = 12
    public static let HUMIDITY_DIG_H5_SIGNED: UInt32 = 1
    public static let HUMIDITY_DIG_H5_PACKING: StaticString = "high8-at-0xE6-low4-in-high-nibble-of-0xE5"
    public static let HUMIDITY_DIG_H6_REG: UInt32 = 0xE7
    public static let HUMIDITY_DIG_H6_WIDTH: UInt32 = 8
    public static let HUMIDITY_DIG_H6_SIGNED: UInt32 = 1

    // sequence 'forced_measurement': declarative steps, resolved here so a step carries its own register and mask. The description is transport agnostic -- one step list describes an I2C transaction, an SPI one, and a call through a host import alike.
    public static let FORCED_MEASUREMENT_STEP_COUNT: UInt32 = 3
    public static let FORCED_MEASUREMENT_STEP_0_OP: StaticString = "write-field"
    public static let FORCED_MEASUREMENT_STEP_0_TARGET: StaticString = "ctrl_meas.mode"
    public static let FORCED_MEASUREMENT_STEP_0_REG: UInt32 = 0xF4
    public static let FORCED_MEASUREMENT_STEP_0_MASK: UInt32 = 0x3
    public static let FORCED_MEASUREMENT_STEP_0_LSB: UInt32 = 0
    public static let FORCED_MEASUREMENT_STEP_0_VALUE: UInt32 = 1
    public static let FORCED_MEASUREMENT_STEP_0_BOUNDED: UInt32 = 0
    public static let FORCED_MEASUREMENT_STEP_1_OP: StaticString = "poll-field-until"
    public static let FORCED_MEASUREMENT_STEP_1_TARGET: StaticString = "status.measuring"
    public static let FORCED_MEASUREMENT_STEP_1_REG: UInt32 = 0xF3
    public static let FORCED_MEASUREMENT_STEP_1_MASK: UInt32 = 0x8
    public static let FORCED_MEASUREMENT_STEP_1_LSB: UInt32 = 3
    public static let FORCED_MEASUREMENT_STEP_1_VALUE: UInt32 = 0
    public static let FORCED_MEASUREMENT_STEP_1_BOUNDED: UInt32 = 1
    public static let FORCED_MEASUREMENT_STEP_2_OP: StaticString = "burst-read"
    public static let FORCED_MEASUREMENT_STEP_2_TARGET: StaticString = "press"
    public static let FORCED_MEASUREMENT_STEP_2_REG: UInt32 = 0xF7
    public static let FORCED_MEASUREMENT_STEP_2_LENGTH: UInt32 = 8
    public static let FORCED_MEASUREMENT_STEP_2_BOUNDED: UInt32 = 0
}
