// GENERATED by lamella-bsp-gen from bsp/opta-wifi/board.toml + csp/stm32h7/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class OptaWifiBindings
    {
        private OptaWifiBindings() { }

        public const int BOARD_MODEL = 43;
        public const string BOARD_VENDOR = "Arduino";

        public const uint RELAY_1_PORT_BASE = 0x58022000;
        public const uint RELAY_1_PIN = 6;
        public const uint RELAY_1_MASK = 0x40;
        public const uint RELAY_1_ACTIVE_LOW = 0;
        public const uint RELAY_2_PORT_BASE = 0x58022000;
        public const uint RELAY_2_PIN = 5;
        public const uint RELAY_2_MASK = 0x20;
        public const uint RELAY_2_ACTIVE_LOW = 0;
        public const uint RELAY_3_PORT_BASE = 0x58022000;
        public const uint RELAY_3_PIN = 7;
        public const uint RELAY_3_MASK = 0x80;
        public const uint RELAY_3_ACTIVE_LOW = 0;
        public const uint RELAY_4_PORT_BASE = 0x58022000;
        public const uint RELAY_4_PIN = 4;
        public const uint RELAY_4_MASK = 0x10;
        public const uint RELAY_4_ACTIVE_LOW = 0;
        public const uint USER_BUTTON_PORT_BASE = 0x58021000;
        public const uint USER_BUTTON_PIN = 4;
        public const uint USER_BUTTON_MASK = 0x10;
        public const uint USER_BUTTON_ACTIVE_LOW = 1;
        public const uint USER_LED_PORT_BASE = 0x58021000;
        public const uint USER_LED_PIN = 5;
        public const uint USER_LED_MASK = 0x20;
    }
}
