//! GENERATED by lamella-bsp-gen from csp/samg55/blocks/pio.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samg55

/// -- register offsets (block-relative) + access widths --
pub const PER_OFF: u32 = 0x0;
pub const PER_WIDTH: i32 = 32;
pub const PDR_OFF: u32 = 0x4;
pub const PDR_WIDTH: i32 = 32;
pub const PSR_OFF: u32 = 0x8;
pub const PSR_WIDTH: i32 = 32;
pub const OER_OFF: u32 = 0x10;
pub const OER_WIDTH: i32 = 32;
pub const ODR_OFF: u32 = 0x14;
pub const ODR_WIDTH: i32 = 32;
pub const OSR_OFF: u32 = 0x18;
pub const OSR_WIDTH: i32 = 32;
pub const SODR_OFF: u32 = 0x30;
pub const SODR_WIDTH: i32 = 32;
pub const CODR_OFF: u32 = 0x34;
pub const CODR_WIDTH: i32 = 32;
pub const ODSR_OFF: u32 = 0x38;
pub const ODSR_WIDTH: i32 = 32;
pub const PDSR_OFF: u32 = 0x3C;
pub const PDSR_WIDTH: i32 = 32;
pub const PUDR_OFF: u32 = 0x60;
pub const PUDR_WIDTH: i32 = 32;
pub const PUER_OFF: u32 = 0x64;
pub const PUER_WIDTH: i32 = 32;
pub const PUSR_OFF: u32 = 0x68;
pub const PUSR_WIDTH: i32 = 32;
pub const ABCDSR1_OFF: u32 = 0x70;
pub const ABCDSR1_WIDTH: i32 = 32;
pub const ABCDSR2_OFF: u32 = 0x74;
pub const ABCDSR2_WIDTH: i32 = 32;
pub const PPDDR_OFF: u32 = 0x90;
pub const PPDDR_WIDTH: i32 = 32;
pub const PPDER_OFF: u32 = 0x94;
pub const PPDER_WIDTH: i32 = 32;
pub const PPDSR_OFF: u32 = 0x98;
pub const PPDSR_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const PER_PER: u32 = 0xFFFFFFFF;
pub const PER_PER_LSB: u32 = 0;
pub const PDR_PDR: u32 = 0xFFFFFFFF;
pub const PDR_PDR_LSB: u32 = 0;
pub const PSR_PSR: u32 = 0xFFFFFFFF;
pub const PSR_PSR_LSB: u32 = 0;
pub const OER_OER: u32 = 0xFFFFFFFF;
pub const OER_OER_LSB: u32 = 0;
pub const ODR_ODR: u32 = 0xFFFFFFFF;
pub const ODR_ODR_LSB: u32 = 0;
pub const OSR_OSR: u32 = 0xFFFFFFFF;
pub const OSR_OSR_LSB: u32 = 0;
pub const SODR_SODR: u32 = 0xFFFFFFFF;
pub const SODR_SODR_LSB: u32 = 0;
pub const CODR_CODR: u32 = 0xFFFFFFFF;
pub const CODR_CODR_LSB: u32 = 0;
pub const ODSR_ODSR: u32 = 0xFFFFFFFF;
pub const ODSR_ODSR_LSB: u32 = 0;
pub const PDSR_PDSR: u32 = 0xFFFFFFFF;
pub const PDSR_PDSR_LSB: u32 = 0;
pub const PUDR_PUDR: u32 = 0xFFFFFFFF;
pub const PUDR_PUDR_LSB: u32 = 0;
pub const PUER_PUER: u32 = 0xFFFFFFFF;
pub const PUER_PUER_LSB: u32 = 0;
pub const PUSR_PUSR: u32 = 0xFFFFFFFF;
pub const PUSR_PUSR_LSB: u32 = 0;
pub const ABCDSR1_ABCDSR1: u32 = 0xFFFFFFFF;
pub const ABCDSR1_ABCDSR1_LSB: u32 = 0;
pub const ABCDSR2_ABCDSR2: u32 = 0xFFFFFFFF;
pub const ABCDSR2_ABCDSR2_LSB: u32 = 0;
pub const PPDDR_PPDDR: u32 = 0xFFFFFFFF;
pub const PPDDR_PPDDR_LSB: u32 = 0;
pub const PPDER_PPDER: u32 = 0xFFFFFFFF;
pub const PPDER_PPDER_LSB: u32 = 0;
pub const PPDSR_PPDSR: u32 = 0xFFFFFFFF;
pub const PPDSR_PPDSR_LSB: u32 = 0;

/// -- block constants --
pub const FUNC_A: u32 = 0;
pub const FUNC_B: u32 = 1;
pub const FUNC_C: u32 = 2;
pub const FUNC_D: u32 = 3;
