//! GENERATED by lamella-bsp-gen from csp/stm32c0/blocks/flash.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32c0

/// -- block constants --
pub const ERASED_VALUE: u32 = 0xFFFFFFFF;
pub const WRITE_UNIT: u32 = 8;
