//! GENERATED by lamella-bsp-gen from csp/stm32c0/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32c0
//!
//! The stm32c0 instance map as Rust consts, name/value-identical to Stm32c0Instances.g.cs:
//! where each block copy sits and its per-instance ids. Each block's layout is in its own
//! layout module beside this file.

pub const FLASH_BASE: u32 = 0x40022000;
