// GENERATED by lamella-bsp-gen from csp/sam3x/blocks/pio.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Sam3xPioLayout
    {
        private Sam3xPioLayout() { }

        public const uint PER_OFF = 0x0;
        public const int PER_WIDTH = 32;
        public const uint PDR_OFF = 0x4;
        public const int PDR_WIDTH = 32;
        public const uint PSR_OFF = 0x8;
        public const int PSR_WIDTH = 32;
        public const uint ABSR_OFF = 0x70;
        public const int ABSR_WIDTH = 32;

        public const uint PER_PER = 0xFFFFFFFF;
        public const uint PER_PER_LSB = 0;
        public const uint PDR_PDR = 0xFFFFFFFF;
        public const uint PDR_PDR_LSB = 0;
        public const uint PSR_PSR = 0xFFFFFFFF;
        public const uint PSR_PSR_LSB = 0;
        public const uint ABSR_ABSR = 0xFFFFFFFF;
        public const uint ABSR_ABSR_LSB = 0;

        public const uint FUNC_A = 0;
        public const uint FUNC_B = 1;
    }
}
