// GENERATED by lamella-bsp-gen from csp/sam3x/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam3x
//
// The sam3x flash block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Sam3xInstances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Sam3xFlashLayout
    {
        private Sam3xFlashLayout() { }

        // -- register offsets (block-relative) + access widths --

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

        // -- block constants --
        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 256;
    }
}
