//! GENERATED by lamella-bsp-gen from bsp/esp32c6-devkitc/board.toml + csp/esp32c6/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . esp32c6

pub const BOARD_MODEL: u16 = 14;
pub const BOARD_VENDOR: &str = "Espressif";

/// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
/// role's `KIND` says what the application asked for -- a uart, an spi -- and two
/// peripherals of the same kind can share no register at all, so a consumer that selects a
/// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
/// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
/// name a driver; and a uart is a different register map on every family, so the kind does
/// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
pub const UART0_DRIVER_FAMILY: &str = "esp32c6-uart";

pub const UART0_BASE: u32 = 0x60000000;
pub const UART0_PCR_CONF: u32 = 0x60096000;
pub const UART0_PCR_SCLK_CONF: u32 = 0x60096004;
pub const UART0_IO_MUX_TX: u32 = 0x60090044;
pub const UART0_IO_MUX_RX: u32 = 0x60090048;
pub const UART0_MCU_SEL: u32 = 0;
pub const UART0_SCLK_HZ: u32 = 40000000;
