//! GENERATED by lamella-bsp-gen from csp/sam3x/blocks/pio.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam3x

/// -- register offsets (block-relative) + access widths --
pub const PER_OFF: u32 = 0x0;
pub const PER_WIDTH: i32 = 32;
pub const PDR_OFF: u32 = 0x4;
pub const PDR_WIDTH: i32 = 32;
pub const PSR_OFF: u32 = 0x8;
pub const PSR_WIDTH: i32 = 32;
pub const ABSR_OFF: u32 = 0x70;
pub const ABSR_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const PER_PER: u32 = 0xFFFFFFFF;
pub const PER_PER_LSB: u32 = 0;
pub const PDR_PDR: u32 = 0xFFFFFFFF;
pub const PDR_PDR_LSB: u32 = 0;
pub const PSR_PSR: u32 = 0xFFFFFFFF;
pub const PSR_PSR_LSB: u32 = 0;
pub const ABSR_ABSR: u32 = 0xFFFFFFFF;
pub const ABSR_ABSR_LSB: u32 = 0;

/// -- block constants --
pub const FUNC_A: u32 = 0;
pub const FUNC_B: u32 = 1;
