// GENERATED by lamella-bsp-gen from csp/samr21/blocks/pm.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samr21
//
// The samr21 pm block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samr21Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Samr21PmLayout
    {
        private Samr21PmLayout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint APBCMASK_OFF = 0x20;
        public const int APBCMASK_WIDTH = 32;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
        public const uint APBCMASK_SERCOM0 = 0x4;
        public const uint APBCMASK_SERCOM0_LSB = 2;
        public const uint APBCMASK_SERCOM1 = 0x8;
        public const uint APBCMASK_SERCOM1_LSB = 3;
        public const uint APBCMASK_SERCOM2 = 0x10;
        public const uint APBCMASK_SERCOM2_LSB = 4;
        public const uint APBCMASK_SERCOM3 = 0x20;
        public const uint APBCMASK_SERCOM3_LSB = 5;
        public const uint APBCMASK_SERCOM4 = 0x40;
        public const uint APBCMASK_SERCOM4_LSB = 6;
        public const uint APBCMASK_SERCOM5 = 0x80;
        public const uint APBCMASK_SERCOM5_LSB = 7;
        public const uint APBCMASK_RFCTRL = 0x200000;
        public const uint APBCMASK_RFCTRL_LSB = 21;
    }
}
