// GENERATED by lamella-bsp-gen from csp/samr21/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Samr21Instances
    {
        private Samr21Instances() { }

        public const uint SERCOM0_BASE = 0x42000800;
        public const uint SERCOM0_GCLK_CORE_ID = 20;
        public const uint SERCOM0_APBC_BIT = 2;
        public const uint SERCOM0_APBC_MASK = 0x4;
        public const uint SERCOM0_IRQ = 9;
        public const uint SERCOM1_BASE = 0x42000C00;
        public const uint SERCOM1_GCLK_CORE_ID = 21;
        public const uint SERCOM1_APBC_BIT = 3;
        public const uint SERCOM1_APBC_MASK = 0x8;
        public const uint SERCOM1_IRQ = 10;
        public const uint SERCOM2_BASE = 0x42001000;
        public const uint SERCOM2_GCLK_CORE_ID = 22;
        public const uint SERCOM2_APBC_BIT = 4;
        public const uint SERCOM2_APBC_MASK = 0x10;
        public const uint SERCOM2_IRQ = 11;
        public const uint SERCOM3_BASE = 0x42001400;
        public const uint SERCOM3_GCLK_CORE_ID = 23;
        public const uint SERCOM3_APBC_BIT = 5;
        public const uint SERCOM3_APBC_MASK = 0x20;
        public const uint SERCOM3_IRQ = 12;
        public const uint SERCOM4_BASE = 0x42001800;
        public const uint SERCOM4_GCLK_CORE_ID = 24;
        public const uint SERCOM4_APBC_BIT = 6;
        public const uint SERCOM4_APBC_MASK = 0x40;
        public const uint SERCOM4_IRQ = 13;
        public const uint SERCOM5_BASE = 0x42001C00;
        public const uint SERCOM5_GCLK_CORE_ID = 25;
        public const uint SERCOM5_APBC_BIT = 7;
        public const uint SERCOM5_APBC_MASK = 0x80;
        public const uint SERCOM5_IRQ = 14;
        public const uint PM_BASE = 0x40000400;
        public const uint GCLK_BASE = 0x40000C00;
        public const uint PORTA_BASE = 0x41004400;
        public const uint PORTB_BASE = 0x41004480;
        public const uint PORTC_BASE = 0x41004500;
    }
}
