// GENERATED by lamella-bsp-gen from parts/lsm303agr/lsm303agr-mag.toml + parts/lsm303agr/lsm303agr-xl.toml + parts/lsm303agr/lsm303agr.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-parts . lsm303agr
//
// The facts every lsm303agr member emits IDENTICALLY -- the family's INVARIANT subset,
// computed across lsm303agr-mag, lsm303agr-xl. A part family's driver base is shared code in every language, and
// this is what it may rely on. A fact is here only while EVERY member agrees on it, so the
// day one member states its own value the fact LEAVES this class and the shared code that
// used it stops compiling. Nothing here is inherited: each member's own table spells all
// of it too, flattened.

public enum Lsm303agrCommon {
    public static let FAMILY: StaticString = "lsm303agr"
    public static let IDENTITY_WIDTH: UInt32 = 8
    public static let IDENTITY_VALUE_COUNT: UInt32 = 1

    // address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
    public static let ADDRESS_BUS: StaticString = "i2c"
    public static let ADDRESS_STRAP_COUNT: UInt32 = 0

    // buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
    public static let BUS_COUNT: UInt32 = 2
    public static let BUS_I2C_KIND: StaticString = "i2c"
    public static let BUS_I2C_REGISTER_READ_TRANSFORM: StaticString = "identity"
    public static let BUS_I2C_REGISTER_WRITE_TRANSFORM: StaticString = "identity"
    public static let BUS_I2C_READ_PROTOCOL: StaticString = "write-register-then-repeated-start-read"
    public static let BUS_SPI_KIND: StaticString = "spi"
    public static let BUS_SPI_REGISTER_READ_TRANSFORM: StaticString = "set-bit7"
    public static let BUS_SPI_REGISTER_WRITE_TRANSFORM: StaticString = "clear-bit7"
    public static let BUS_SPI_READ_PROTOCOL: StaticString = "single-chip-select-address-then-clock-data"

    // measurement: the part holds a whole data block steady for the duration of one burst, so a byte-at-a-time read can mix two conversions.
    public static let BURST_LENGTH: UInt32 = 6
}
