// GENERATED by lamella-bsp-gen from csp/stm32f42x/blocks/gpio.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32f42xGpioLayout
    {
        private Stm32f42xGpioLayout() { }

        public const uint MODER_OFF = 0x0;
        public const int MODER_WIDTH = 32;
        public const uint OTYPER_OFF = 0x4;
        public const int OTYPER_WIDTH = 32;
        public const uint OSPEEDR_OFF = 0x8;
        public const int OSPEEDR_WIDTH = 32;
        public const uint PUPDR_OFF = 0xC;
        public const int PUPDR_WIDTH = 32;
        public const uint IDR_OFF = 0x10;
        public const int IDR_WIDTH = 32;
        public const uint ODR_OFF = 0x14;
        public const int ODR_WIDTH = 32;
        public const uint BSRR_OFF = 0x18;
        public const int BSRR_WIDTH = 32;
        public const uint LCKR_OFF = 0x1C;
        public const int LCKR_WIDTH = 32;
        public const uint AFRL_OFF = 0x20;
        public const int AFRL_WIDTH = 32;
        public const uint AFRH_OFF = 0x24;
        public const int AFRH_WIDTH = 32;

        public const uint MODER_MODER9 = 0xC0000;
        public const uint MODER_MODER9_LSB = 18;
        public const uint MODER_MODER10 = 0x300000;
        public const uint MODER_MODER10_LSB = 20;
        public const uint AFRH_AFSEL9 = 0xF0;
        public const uint AFRH_AFSEL9_LSB = 4;
        public const uint AFRH_AFSEL10 = 0xF00;
        public const uint AFRH_AFSEL10_LSB = 8;

        public const uint MODER_MODE_AF = 2;
        public const uint MODER_MODE_OUTPUT = 1;
        public const uint MODER_MODE_INPUT = 0;
        public const uint MODER_MODE_ANALOG = 3;
        public const uint OTYPER_OPEN_DRAIN = 1;
        public const uint OSPEEDR_VERY_HIGH = 3;
        public const uint PUPDR_PULL_UP = 1;
        public const uint PUPDR_NONE = 0;
        public const uint PUPDR_PULL_DOWN = 2;
    }
}
