//! GENERATED by lamella-bsp-gen from ext/click-shield-for-pi-pico/extension.toml + ext/standards/pico-header.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-ext . click-shield-for-pi-pico
//!
//! The click-shield-for-pi-pico extension board, resolved against the pico-header connector standard: what it needs a host
//! socket to bring out, and what a host reaches through it. No host pad appears here: an
//! extension binds to any host that offers a socket of this standard.
pub const EXTENSION: &str = "click-shield-for-pi-pico";
pub const VENDOR: &str = "mikroe";
pub const STANDARD: &str = "pico-header";

/// -- what this board needs a host socket to bring out. Each POSITION is the connector
/// standard's own name for a hole, never a pad: this file cannot name a pad, because it does
/// not know which host it is plugged into. A host's `CONNECTOR_<socket>_<POSITION>_*`
/// constants carry the pad behind each one, and the two are joined on the position name --
pub const POSITION_COUNT: u32 = 19;
pub const POSITION_GP26_PIN: u32 = 31;
pub const POSITION_GP6_PIN: u32 = 9;
pub const POSITION_GP17_PIN: u32 = 22;
pub const POSITION_GP18_PIN: u32 = 24;
pub const POSITION_GP16_PIN: u32 = 21;
pub const POSITION_GP19_PIN: u32 = 25;
pub const POSITION_GP2_PIN: u32 = 4;
pub const POSITION_GP3_PIN: u32 = 5;
pub const POSITION_GP1_PIN: u32 = 2;
pub const POSITION_GP0_PIN: u32 = 1;
pub const POSITION_GP5_PIN: u32 = 7;
pub const POSITION_GP4_PIN: u32 = 6;
pub const POSITION_GP27_PIN: u32 = 32;
pub const POSITION_GP20_PIN: u32 = 26;
pub const POSITION_GP13_PIN: u32 = 17;
pub const POSITION_GP7_PIN: u32 = 10;
pub const POSITION_GP21_PIN: u32 = 27;
pub const POSITION_GP9_PIN: u32 = 12;
pub const POSITION_GP8_PIN: u32 = 11;
