// GENERATED by lamella-bsp-gen from csp/stm32c0/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32c0
//
// The stm32c0 instance map: where each block copy sits and its per-instance ids.
// Layout offsets live in the *Layout classes; wiring lives in the per-board *Bindings.
namespace Lamella.Generated
{
    public sealed class Stm32c0Instances
    {
        private Stm32c0Instances() { }

        public const uint FLASH_BASE = 0x40022000;
    }
}
