// GENERATED by lamella-bsp-gen from csp/stm32c0/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32c0Instances
    {
        private Stm32c0Instances() { }

        public const uint FLASH_BASE = 0x40022000;
    }
}
