// GENERATED by lamella-bsp-gen from csp/stm32c0/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32c0
//
// The stm32c0 flash block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Stm32c0Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Stm32c0FlashLayout
    {
        private Stm32c0FlashLayout() { }

        // -- register offsets (block-relative) + access widths --

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

        // -- block constants --
        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 8;
    }
}
