// GENERATED by lamella-bsp-gen from csp/saml22/blocks/gclk.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . saml22
//
// The saml22 gclk block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Saml22Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Saml22GclkLayout
    {
        private Saml22GclkLayout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint PCHCTRL0_OFF = 0x80;
        public const int PCHCTRL0_WIDTH = 32;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
        public const uint PCHCTRL0_GEN = 0xF;
        public const uint PCHCTRL0_GEN_LSB = 0;
        public const uint PCHCTRL0_CHEN = 0x40;
        public const uint PCHCTRL0_CHEN_LSB = 6;
        public const uint PCHCTRL0_WRTLOCK = 0x80;
        public const uint PCHCTRL0_WRTLOCK_LSB = 7;
    }
}
