// GENERATED by lamella-bsp-gen from csp/saml22/blocks/mclk.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Saml22MclkLayout
    {
        private Saml22MclkLayout() { }

        public const uint AHBMASK_OFF = 0x10;
        public const int AHBMASK_WIDTH = 32;
        public const uint APBAMASK_OFF = 0x14;
        public const int APBAMASK_WIDTH = 32;
        public const uint APBBMASK_OFF = 0x18;
        public const int APBBMASK_WIDTH = 32;
        public const uint APBCMASK_OFF = 0x1C;
        public const int APBCMASK_WIDTH = 32;

        public const uint APBBMASK_PORT = 0x8;
        public const uint APBBMASK_PORT_LSB = 3;
        public const uint APBCMASK_SERCOM0 = 0x2;
        public const uint APBCMASK_SERCOM0_LSB = 1;
        public const uint APBCMASK_SERCOM1 = 0x4;
        public const uint APBCMASK_SERCOM1_LSB = 2;
        public const uint APBCMASK_SERCOM2 = 0x8;
        public const uint APBCMASK_SERCOM2_LSB = 3;
        public const uint APBCMASK_SERCOM3 = 0x10;
        public const uint APBCMASK_SERCOM3_LSB = 4;
        public const uint APBCMASK_SERCOM4 = 0x20;
        public const uint APBCMASK_SERCOM4_LSB = 5;
        public const uint APBCMASK_SERCOM5 = 0x40;
        public const uint APBCMASK_SERCOM5_LSB = 6;
    }
}
