// GENERATED by lamella-bsp-gen from bsp/arduino-due/board.toml + csp/sam3x/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class DueBindings
    {
        private DueBindings() { }

        public const int BOARD_MODEL = 15;
        public const string BOARD_VENDOR = "Arduino";

        public const uint VCP_BASE = 0x400E0800;
        public const uint VCP_PID = 8;
        public const uint VCP_PMC_PCER_REG = 0x400E0610;
        public const uint VCP_PMC_PCER_MASK = 0x100;
        public const uint VCP_PIO_PDR_REG = 0x400E0E04;
        public const uint VCP_PIO_ABSR_REG = 0x400E0E70;
        public const uint VCP_PIO_MASK = 0x300;
        public const uint VCP_PIO_FUNC = 0;
        public const uint VCP_MCK_HZ = 84000000;
        public const uint VCP_BRGR_CD_115200_PLLA_84MHZ = 46;
    }
}
