//! GENERATED by lamella-bsp-gen from bsp/bbc-micro-bit-v1/board.toml + csp/nrf51/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . nrf51
//!
//! The bbc-micro-bit-v1 board bindings as Rust consts, name/value-identical to BbcMicroBitV1Bindings.g.cs:
//! every value below is a generation-time literal derived from the strata.
//! The board's facts are stated in board.toml.

// -- identity --
pub const BOARD_MODEL: u16 = 1;
pub const BOARD_VENDOR: &str = "Bbc";

/// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
/// role's `KIND` says what the application asked for -- a uart, an spi -- and two
/// peripherals of the same kind can share no register at all, so a consumer that selects a
/// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
/// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
/// name a driver; and a uart is a different register map on every family, so the kind does
/// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
pub const I2C_DRIVER_FAMILY: &str = "nrf51-twi";
pub const VCP_DRIVER_FAMILY: &str = "nrf51-uart";
pub const SPI_DRIVER_FAMILY: &str = "nrf51-spi";

// -- I2C: an nrf-twi binding descriptor --
pub const I2C_TWI_BASE: u32 = 0x40003000;
pub const I2C_PSEL_SCL: u32 = 0x0;
pub const I2C_PSEL_SDA: u32 = 0x1E;
pub const I2C_PIN_CNF_SCL_REG: u32 = 0x50000700;
pub const I2C_PIN_CNF_SDA_REG: u32 = 0x50000778;

// -- SPI: an nrf-spi binding descriptor --
pub const SPI_SPI_BASE: u32 = 0x40004000;
pub const SPI_PSEL_SCK: u32 = 0x17;
pub const SPI_PSEL_MOSI: u32 = 0x15;
pub const SPI_PSEL_MISO: u32 = 0x16;
pub const SPI_PIN_CNF_SCK_REG: u32 = 0x5000075C;
pub const SPI_PIN_CNF_MOSI_REG: u32 = 0x50000754;
pub const SPI_PIN_CNF_MISO_REG: u32 = 0x50000758;

// -- VCP: an nrf-uart binding descriptor --
pub const VCP_UART_BASE: u32 = 0x40002000;
pub const VCP_PSEL_TXD: u32 = 0x18;
pub const VCP_PSEL_RXD: u32 = 0x19;
pub const VCP_PIN_CNF_TXD_REG: u32 = 0x50000760;
pub const VCP_PIN_CNF_RXD_REG: u32 = 0x50000764;
pub const VCP_BAUDRATE_115200_XTAL_16MHZ: u32 = 0x1D7E000;
pub const DEVICE_COUNT: u32 = 12;

// -- on-board devices: PORT group base + pin index + mask --
pub const DISPLAY_ROW1_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_ROW1_PIN: u32 = 13;
pub const DISPLAY_ROW1_BANK: u32 = 0;
pub const DISPLAY_ROW1_MASK: u32 = 0x2000;
pub const DISPLAY_ROW1_ACTIVE_LOW: u32 = 0;
pub const DISPLAY_ROW2_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_ROW2_PIN: u32 = 14;
pub const DISPLAY_ROW2_BANK: u32 = 0;
pub const DISPLAY_ROW2_MASK: u32 = 0x4000;
pub const DISPLAY_ROW2_ACTIVE_LOW: u32 = 0;
pub const DISPLAY_ROW3_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_ROW3_PIN: u32 = 15;
pub const DISPLAY_ROW3_BANK: u32 = 0;
pub const DISPLAY_ROW3_MASK: u32 = 0x8000;
pub const DISPLAY_ROW3_ACTIVE_LOW: u32 = 0;
pub const DISPLAY_COL1_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL1_PIN: u32 = 4;
pub const DISPLAY_COL1_BANK: u32 = 0;
pub const DISPLAY_COL1_MASK: u32 = 0x10;
pub const DISPLAY_COL1_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL2_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL2_PIN: u32 = 5;
pub const DISPLAY_COL2_BANK: u32 = 0;
pub const DISPLAY_COL2_MASK: u32 = 0x20;
pub const DISPLAY_COL2_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL3_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL3_PIN: u32 = 6;
pub const DISPLAY_COL3_BANK: u32 = 0;
pub const DISPLAY_COL3_MASK: u32 = 0x40;
pub const DISPLAY_COL3_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL4_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL4_PIN: u32 = 7;
pub const DISPLAY_COL4_BANK: u32 = 0;
pub const DISPLAY_COL4_MASK: u32 = 0x80;
pub const DISPLAY_COL4_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL5_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL5_PIN: u32 = 8;
pub const DISPLAY_COL5_BANK: u32 = 0;
pub const DISPLAY_COL5_MASK: u32 = 0x100;
pub const DISPLAY_COL5_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL6_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL6_PIN: u32 = 9;
pub const DISPLAY_COL6_BANK: u32 = 0;
pub const DISPLAY_COL6_MASK: u32 = 0x200;
pub const DISPLAY_COL6_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL7_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL7_PIN: u32 = 10;
pub const DISPLAY_COL7_BANK: u32 = 0;
pub const DISPLAY_COL7_MASK: u32 = 0x400;
pub const DISPLAY_COL7_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL8_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL8_PIN: u32 = 11;
pub const DISPLAY_COL8_BANK: u32 = 0;
pub const DISPLAY_COL8_MASK: u32 = 0x800;
pub const DISPLAY_COL8_ACTIVE_LOW: u32 = 1;
pub const DISPLAY_COL9_PORT_BASE: u32 = 0x50000000;
pub const DISPLAY_COL9_PIN: u32 = 12;
pub const DISPLAY_COL9_BANK: u32 = 0;
pub const DISPLAY_COL9_MASK: u32 = 0x1000;
pub const DISPLAY_COL9_ACTIVE_LOW: u32 = 1;
