//! GENERATED by lamella-bsp-gen from csp/saml1x/blocks/mclk.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . saml1x
//!
//! The saml1x mclk block layout as Rust consts, name/value-identical to Saml1xMclkLayout.g.cs:
//! offsets are instance-base-relative (`base + *_OFF`) and the instance bases live in
//! saml1x_instances.rs. Widths are access widths.

/// -- register offsets (block-relative) + access widths --
pub const AHBMASK_OFF: u32 = 0x10;
pub const AHBMASK_WIDTH: i32 = 32;
pub const APBAMASK_OFF: u32 = 0x14;
pub const APBAMASK_WIDTH: i32 = 32;
pub const APBBMASK_OFF: u32 = 0x18;
pub const APBBMASK_WIDTH: i32 = 32;
pub const APBCMASK_OFF: u32 = 0x1C;
pub const APBCMASK_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const APBAMASK_PORT: u32 = 0x1000;
pub const APBAMASK_PORT_LSB: u32 = 12;
pub const APBCMASK_SERCOM0: u32 = 0x2;
pub const APBCMASK_SERCOM0_LSB: u32 = 1;
pub const APBCMASK_SERCOM1: u32 = 0x4;
pub const APBCMASK_SERCOM1_LSB: u32 = 2;
pub const APBCMASK_SERCOM2: u32 = 0x8;
pub const APBCMASK_SERCOM2_LSB: u32 = 3;
