//! GENERATED by lamella-bsp-gen from csp/saml1x/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . saml1x

pub const SERCOM0_BASE: u32 = 0x42000400;
pub const SERCOM0_GCLK_CORE_ID: u32 = 11;
pub const SERCOM0_APB_MASK_OFFSET: u32 = 28;
pub const SERCOM0_APB_BIT: u32 = 1;
pub const SERCOM0_APB_MASK: u32 = 0x2;
pub const SERCOM1_BASE: u32 = 0x42000800;
pub const SERCOM1_GCLK_CORE_ID: u32 = 12;
pub const SERCOM1_APB_MASK_OFFSET: u32 = 28;
pub const SERCOM1_APB_BIT: u32 = 2;
pub const SERCOM1_APB_MASK: u32 = 0x4;
pub const SERCOM2_BASE: u32 = 0x42000C00;
pub const SERCOM2_GCLK_CORE_ID: u32 = 13;
pub const SERCOM2_APB_MASK_OFFSET: u32 = 28;
pub const SERCOM2_APB_BIT: u32 = 3;
pub const SERCOM2_APB_MASK: u32 = 0x8;
pub const MCLK_BASE: u32 = 0x40000800;
pub const GCLK_BASE: u32 = 0x40001C00;
pub const PORTA_BASE: u32 = 0x40003000;
pub const PORTA_APB_MASK_OFFSET: u32 = 20;
pub const PORTA_APB_BIT: u32 = 12;
pub const PORTA_APB_MASK: u32 = 0x1000;
