// GENERATED by lamella-bsp-gen from bsp/st-nucleo-l4r5zi/board.toml + csp/stm32l4r5/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32l4r5
//
// The st-nucleo-l4r5zi board bindings (resolved against the stm32l4r5 chip strata): every value below is a
// generation-time literal derived from the strata -- role descriptors, module control
// lines, and the carrier identity. The board's facts are stated in board.toml.
namespace Lamella.Generated
{
    public sealed class StNucleoL4r5ziBindings
    {
        private StNucleoL4r5ziBindings() { }

        // -- identity --
        public const int BOARD_MODEL = 63;
        public const string BOARD_VENDOR = "St";
        public const uint DEVICE_COUNT = 4;

        // -- on-board devices: PORT group base + pin index + mask --
        public const uint LED0_PORT_BASE = 0x48000800;
        public const uint LED0_PIN = 7;
        public const uint LED0_BANK = 0;
        public const uint LED0_MASK = 0x80;
        public const uint LED0_ACTIVE_LOW = 0;
        public const uint LED1_PORT_BASE = 0x48000400;
        public const uint LED1_PIN = 7;
        public const uint LED1_BANK = 0;
        public const uint LED1_MASK = 0x80;
        public const uint LED1_ACTIVE_LOW = 0;
        public const uint LED2_PORT_BASE = 0x48000400;
        public const uint LED2_PIN = 14;
        public const uint LED2_BANK = 0;
        public const uint LED2_MASK = 0x4000;
        public const uint LED2_ACTIVE_LOW = 0;
        public const uint BUTTON0_PORT_BASE = 0x48000800;
        public const uint BUTTON0_PIN = 13;
        public const uint BUTTON0_BANK = 0;
        public const uint BUTTON0_MASK = 0x2000;
        public const uint BUTTON0_ACTIVE_LOW = 0;
    }
}
