// GENERATED by lamella-bsp-gen from ext/atio1-xpro/extension.toml + ext/standards/xplained-pro.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Atio1XproExtension
    {
        private Atio1XproExtension() { }
        public const string EXTENSION = "atio1-xpro";
        public const string VENDOR = "microchip";
        public const string STANDARD = "xplained-pro";

        /// -- the kit identifier its identification chip carries, as the `nnnn` field of an
        /// `nnnnrrssssssssss` serial. It is how a FITTED extension can be told from an assumed
        /// one -- but on a kit with an embedded debugger the identification line reaches the
        /// DEBUGGER rather than an MCU pad, so this is a host tool's reading and not a
        /// program's --
        public const uint KIT_IDENTIFIER = 1775;

        /// -- what this board needs a host socket to bring out. Each POSITION is the connector
        /// standard's own name for a hole, never a pad: this file cannot name a pad, because it does
        /// not know which host it is plugged into. A host's `CONNECTOR_<socket>_<POSITION>_*`
        /// constants carry the pad behind each one, and the two are joined on the position name --
        public const uint POSITION_COUNT = 14;
        public const uint POSITION_SPI_SS_A_PIN = 15;
        public const uint POSITION_SPI_MOSI_PIN = 16;
        public const uint POSITION_SPI_MISO_PIN = 17;
        public const uint POSITION_SPI_SCK_PIN = 18;
        public const uint POSITION_I2C_SDA_PIN = 11;
        public const uint POSITION_I2C_SCL_PIN = 12;
        public const uint POSITION_PWM_P_PIN = 7;
        public const uint POSITION_SPI_SS_B_PIN = 10;
        public const uint POSITION_IRQ_PIN = 9;
        public const uint POSITION_ADC_P_PIN = 3;
        public const uint POSITION_ADC_N_PIN = 4;
        public const uint POSITION_PWM_N_PIN = 8;
        public const uint POSITION_GPIO1_PIN = 5;
        public const uint POSITION_GPIO2_PIN = 6;

        /// -- the buses this board presents, each naming the socket positions it rides. A host
        /// resolves them through the same socket constants; which of its controllers is behind
        /// them is the HOST's fact and appears nowhere here --
        public const uint BUS_COUNT = 2;
        public const string BUS_SD_SPI_KIND = "spi";
        public const string BUS_SD_SPI_SS = "spi_ss_a";
        public const string BUS_SD_SPI_MOSI = "spi_mosi";
        public const string BUS_SD_SPI_MISO = "spi_miso";
        public const string BUS_SD_SPI_SCK = "spi_sck";
        public const string BUS_SENSOR_I2C_KIND = "i2c";
        public const string BUS_SENSOR_I2C_SDA = "i2c_sda";
        public const string BUS_SENSOR_I2C_SCL = "i2c_scl";

        /// -- the devices a host reaches. A LINE-wired device names the socket position it sits on
        /// and its active level; a BUS-wired one names the bus and, where a document states one, its
        /// address. An active level of `unknown` is a document that does not say, recorded as such:
        /// no polarity constant is emitted for it, so a program that assumed one fails to compile --
        public const uint DEVICE_COUNT = 11;
        public const string DEVICE_TEMPERATURE_KIND = "i2c-device";
        public const string DEVICE_TEMPERATURE_BUS = "sensor-i2c";
        public const string DEVICE_TEMPERATURE_PART = "at30tse758";
        public const uint DEVICE_TEMPERATURE_ADDRESS = 0x4F;
        public const string DEVICE_EEPROM_KIND = "i2c-device";
        public const string DEVICE_EEPROM_BUS = "sensor-i2c";
        public const string DEVICE_EEPROM_PART = "at30tse758";
        public const uint DEVICE_EEPROM_ADDRESS = 0x57;
        public const string DEVICE_SDCARD_KIND = "spi-device";
        public const string DEVICE_SDCARD_BUS = "sd-spi";
        public const string DEVICE_SDCARD_PART = "microsd-socket";
        public const string DEVICE_LED_KIND = "gpio-out";
        public const string DEVICE_LED_POSITION = "pwm_p";
        public const uint DEVICE_LED_ACTIVE_LOW = 1;
        public const string DEVICE_SD_DETECT_KIND = "gpio-in";
        public const string DEVICE_SD_DETECT_POSITION = "spi_ss_b";
        public const uint DEVICE_SD_DETECT_ACTIVE_LOW = 1;
        public const string DEVICE_TEMP_ALERT_KIND = "gpio-in";
        public const string DEVICE_TEMP_ALERT_POSITION = "irq";
        public const string DEVICE_LIGHT_KIND = "analog-in";
        public const string DEVICE_LIGHT_POSITION = "adc_p";
        public const string DEVICE_FILTER_OUT_KIND = "analog-in";
        public const string DEVICE_FILTER_OUT_POSITION = "adc_n";
        public const string DEVICE_FILTER_IN_KIND = "gpio-out";
        public const string DEVICE_FILTER_IN_POSITION = "pwm_n";
        public const string DEVICE_GPIO1_KIND = "gpio-out";
        public const string DEVICE_GPIO1_POSITION = "gpio1";
        public const string DEVICE_GPIO2_KIND = "gpio-out";
        public const string DEVICE_GPIO2_POSITION = "gpio2";
    }
}
