// GENERATED by lamella-bsp-gen from parts/modulino/joystick.toml + parts/modulino/modulino.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class JoystickPart
    {
        private JoystickPart() { }
        public const string PART = "joystick";
        public const string FAMILY = "modulino";

        /// sourcing: how far this part is established, on two INDEPENDENT axes -- a part can be strong on one and absent on the other, which is why they are not one rank. FACTS is `primary` (read from the part's own datasheet) or `secondary` (a primary vendor statement about this part carried by another document, named by DERIVED_FROM). VALIDATION is `none` (no physical part of this type has been made to answer), `identified` (one answered its identity register, against a negative control that tells the part from the wire) or `exercised` (one produced measurements a driver decoded). Anything above `none` states what was observed in EVIDENCE.
        public const string SOURCING_FACTS = "primary";
        public const string SOURCING_VALIDATION = "none";

        /// identity: THIS PART HAS NONE, and that is a fact about the part rather than a gap in this table. There is no register to read, so nothing can confirm which part answered an address -- the `identified` validation rung is unreachable for it by construction, and confidence has to be earned by exercising it instead.
        public const string IDENTITY_ABSENT = "These nodes run vendor firmware as an I2C target and Arduino's manuals document no identity register for any of them: no WHO_AM_I, no device id, no part id. Nothing on the bus can confirm WHICH node answered an address -- and because every address here is software-assignable, an address is not evidence of type either. Presence and type can be established only by exercising the node.";

        /// address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
        public const string ADDRESS_BUS = "i2c";
        public const uint ADDRESS_BASE = 0x20;
        public const uint ADDRESS_STRAP_COUNT = 0;

        /// buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
        public const uint BUS_COUNT = 1;
        public const string BUS_I2C_KIND = "i2c";
        public const string BUS_I2C_REGISTER_READ_TRANSFORM = "identity";
        public const string BUS_I2C_REGISTER_WRITE_TRANSFORM = "identity";
        public const string BUS_I2C_READ_PROTOCOL = "";
    }
}
