// GENERATED by lamella-bsp-gen from bsp/microbit-v1/board.toml + csp/nrf51/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class MicrobitV1Bindings
    {
        private MicrobitV1Bindings() { }

        public const int BOARD_MODEL = 1;

        public const uint I2C_TWI_BASE = 0x40003000;
        public const uint I2C_PSEL_SCL = 0x0;
        public const uint I2C_PSEL_SDA = 0x1E;
        public const uint I2C_PIN_CNF_SCL_REG = 0x50000700;
        public const uint I2C_PIN_CNF_SDA_REG = 0x50000778;

        public const uint DISPLAY_ROW1_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW1_PIN = 13;
        public const uint DISPLAY_ROW1_MASK = 0x2000;
        public const uint DISPLAY_ROW1_ACTIVE_LOW = 0;
        public const uint DISPLAY_ROW2_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW2_PIN = 14;
        public const uint DISPLAY_ROW2_MASK = 0x4000;
        public const uint DISPLAY_ROW2_ACTIVE_LOW = 0;
        public const uint DISPLAY_ROW3_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW3_PIN = 15;
        public const uint DISPLAY_ROW3_MASK = 0x8000;
        public const uint DISPLAY_ROW3_ACTIVE_LOW = 0;
        public const uint DISPLAY_COL1_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL1_PIN = 4;
        public const uint DISPLAY_COL1_MASK = 0x10;
        public const uint DISPLAY_COL1_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL2_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL2_PIN = 5;
        public const uint DISPLAY_COL2_MASK = 0x20;
        public const uint DISPLAY_COL2_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL3_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL3_PIN = 6;
        public const uint DISPLAY_COL3_MASK = 0x40;
        public const uint DISPLAY_COL3_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL4_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL4_PIN = 7;
        public const uint DISPLAY_COL4_MASK = 0x80;
        public const uint DISPLAY_COL4_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL5_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL5_PIN = 8;
        public const uint DISPLAY_COL5_MASK = 0x100;
        public const uint DISPLAY_COL5_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL6_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL6_PIN = 9;
        public const uint DISPLAY_COL6_MASK = 0x200;
        public const uint DISPLAY_COL6_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL7_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL7_PIN = 10;
        public const uint DISPLAY_COL7_MASK = 0x400;
        public const uint DISPLAY_COL7_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL8_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL8_PIN = 11;
        public const uint DISPLAY_COL8_MASK = 0x800;
        public const uint DISPLAY_COL8_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL9_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL9_PIN = 12;
        public const uint DISPLAY_COL9_MASK = 0x1000;
        public const uint DISPLAY_COL9_ACTIVE_LOW = 1;
    }
}
