// GENERATED by lamella-bsp-gen from csp/stm32l476/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32l476Instances
    {
        private Stm32l476Instances() { }

        public const uint USART2_BASE = 0x40004400;
        public const uint USART2_RCC_EN_OFF = 88;
        public const uint USART2_RCC_EN_BIT = 17;
        public const uint USART2_RCC_EN_MASK = 0x20000;
        public const uint GPIOA_BASE = 0x48000000;
        public const uint GPIOA_RCC_EN_OFF = 76;
        public const uint GPIOA_RCC_EN_BIT = 0;
        public const uint GPIOA_RCC_EN_MASK = 0x1;
        public const uint RCC_BASE = 0x40021000;
    }
}
