//! GENERATED by lamella-bsp-gen from bsp/samd21-xpro/board.toml + csp/samd21/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21

pub const BOARD_MODEL: u16 = 5;
pub const BOARD_VENDOR: &str = "Microchip";
pub const CARRIER_USB_VID: u16 = 0x03EB;
pub const CARRIER_USB_PID: u16 = 0x2169;

/// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
/// role's `KIND` says what the application asked for -- a uart, an spi -- and two
/// peripherals of the same kind can share no register at all, so a consumer that selects a
/// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
/// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
/// name a driver; and a uart is a different register map on every family, so the kind does
/// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
pub const VCP_DRIVER_FAMILY: &str = "samd21-sercom";

pub const VCP_SERCOM_BASE: u32 = 0x42001400;
pub const VCP_IRQ: u32 = 12;
pub const VCP_GCLK_CLKCTRL_VALUE: u32 = 0x4017;
pub const VCP_APBC_MASK: u32 = 0x20;
pub const VCP_PMUX_REG: u32 = 0x4100443B;
pub const VCP_PMUX_PAIR: u32 = 0x22;
pub const VCP_PMUX_TX_REG: u32 = 0x4100443B;
pub const VCP_PMUX_TX_MASK: u32 = 0xF;
pub const VCP_PMUX_TX_VALUE: u32 = 0x2;
pub const VCP_PMUX_RX_REG: u32 = 0x4100443B;
pub const VCP_PMUX_RX_MASK: u32 = 0xF0;
pub const VCP_PMUX_RX_VALUE: u32 = 0x20;
pub const VCP_PINCFG_TX_REG: u32 = 0x41004456;
pub const VCP_PINCFG_RX_REG: u32 = 0x41004457;
pub const VCP_TXPO: u32 = 0;
pub const VCP_RXPO: u32 = 1;
pub const VCP_BAUD_115200_OSC8M_8MHZ: u32 = 0xC505;

pub const LED0_PORT_BASE: u32 = 0x41004480;
pub const LED0_PIN: u32 = 30;
pub const LED0_MASK: u32 = 0x40000000;
pub const LED0_ACTIVE_LOW: u32 = 1;
pub const BUTTON0_PORT_BASE: u32 = 0x41004400;
pub const BUTTON0_PIN: u32 = 15;
pub const BUTTON0_MASK: u32 = 0x8000;
pub const BUTTON0_ACTIVE_LOW: u32 = 1;
