# GENERATED by lamella-bsp-gen from bsp/p1am-100/board.toml + csp/samd21/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21

BOARD = "p1am-100"
BOARD_MODEL = 42
BOARD_VENDOR = "AutomationDirect"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.

CARRIER = {
    "kind": "native-usb",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Each row carries whatever this family's record declares -- a base always, and per-instance
# facts like a clock channel or a bus-enable bit where the family states them. Register offsets
# and bit encodings belong to the driver that knows the block, not here.
INSTANCES = {
    "sercom0": {"block": "sercom", "base": 0x42000800, "gclk_core_id": 0x14, "apbc_bit": 0x2, "irq": 0x9},
    "sercom1": {"block": "sercom", "base": 0x42000C00, "gclk_core_id": 0x15, "apbc_bit": 0x3, "irq": 0xA},
    "sercom2": {"block": "sercom", "base": 0x42001000, "gclk_core_id": 0x16, "apbc_bit": 0x4, "irq": 0xB},
    "sercom3": {"block": "sercom", "base": 0x42001400, "gclk_core_id": 0x17, "apbc_bit": 0x5, "irq": 0xC},
    "sercom4": {"block": "sercom", "base": 0x42001800, "gclk_core_id": 0x18, "apbc_bit": 0x6, "irq": 0xD},
    "sercom5": {"block": "sercom", "base": 0x42001C00, "gclk_core_id": 0x19, "apbc_bit": 0x7, "irq": 0xE},
    "pm": {"block": "pm", "base": 0x40000400},
    "gclk": {"block": "gclk", "base": 0x40000C00},
    "porta": {"block": "port", "base": 0x41004400},
    "portb": {"block": "port", "base": 0x41004480},
}

PLANS = {
    "osc8m-8mhz": {"default": True, "source": "osc8m", "gclk0_hz": 8000000},
    "usb-48mhz": {"default": False, "source": "dfll48m-usb-recovery", "gclk1_hz": 48000000},
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
    "led": {"kind": "gpio-out", "port_base": 0x41004480, "pin": 8, "mask": 0x100, "active_low": False},
    "run-switch": {"kind": "gpio-in", "port_base": 0x41004400, "pin": 28, "mask": 0x10000000, "active_low": True},
    "base-enable": {"kind": "gpio-out", "port_base": 0x41004480, "pin": 9, "mask": 0x200, "active_low": False},
    "base-cs": {"kind": "gpio-out", "port_base": 0x41004400, "pin": 4, "mask": 0x10, "active_low": True},
    "base-ready": {"kind": "gpio-in", "port_base": 0x41004400, "pin": 5, "mask": 0x20, "active_low": False},
    "sd-cs": {"kind": "gpio-out", "port_base": 0x41004400, "pin": 14, "mask": 0x4000},
}
