//! GENERATED by lamella-bsp-gen from bsp/microchip-sam4e-xpro/board.toml + csp/sam4e/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4e
//!
//! The microchip-sam4e-xpro board bindings as Rust consts, name/value-identical to MicrochipSam4eXproBindings.g.cs:
//! every value below is a generation-time literal derived from the strata.
//! The board's facts are stated in board.toml.

// -- identity --
pub const BOARD_MODEL: u16 = 26;
pub const BOARD_VENDOR: &str = "Microchip";
pub const CARRIER_USB_VID: u16 = 0x03EB;
pub const CARRIER_USB_PID: u16 = 0x2111;
pub const DEVICE_COUNT: u32 = 2;

// -- on-board devices: PORT group base + pin index + mask --
pub const LED0_PORT_BASE: u32 = 0x400E1400;
pub const LED0_PIN: u32 = 22;
pub const LED0_MASK: u32 = 0x400000;
pub const LED0_ACTIVE_LOW: u32 = 1;
pub const BUTTON0_PORT_BASE: u32 = 0x400E0E00;
pub const BUTTON0_PIN: u32 = 2;
pub const BUTTON0_MASK: u32 = 0x4;
pub const BUTTON0_ACTIVE_LOW: u32 = 1;
