// GENERATED by lamella-bsp-gen from bsp/samd21-xpro/board.toml + csp/samd21/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Samd21XproBindings
    {
        private Samd21XproBindings() { }

        public const int BOARD_MODEL = 5;
        public const uint CARRIER_USB_VID = 0x03EB;
        public const uint CARRIER_USB_PID = 0x2169;

        public const uint VCP_SERCOM_BASE = 0x42001400;
        public const uint VCP_IRQ = 12;
        public const uint VCP_GCLK_CLKCTRL_VALUE = 0x4017;
        public const uint VCP_APBC_MASK = 0x20;
        public const uint VCP_PMUX_REG = 0x4100443B;
        public const uint VCP_PMUX_PAIR = 0x22;
        public const uint VCP_PINCFG_TX_REG = 0x41004456;
        public const uint VCP_PINCFG_RX_REG = 0x41004457;
        public const uint VCP_TXPO = 0;
        public const uint VCP_RXPO = 1;
        public const uint VCP_BAUD_115200_OSC8M_8MHZ = 0xC505;
    }
}
