// GENERATED by lamella-bsp-gen from bsp/rpi-pico/board.toml + csp/rp2040/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040
//
// The pico board bindings as Swift constants, name/value-identical to PicoBindings.g.cs:
// every value below is a generation-time literal derived from the strata. Board truth
// lives in board.toml, never here.

public enum PicoBindings {
    // -- identity --
    public static let BOARD_MODEL: UInt16 = 13
    public static let BOARD_VENDOR: String = "RaspberryPi"

    // -- UART0: a pl011 uart binding descriptor --
    public static let UART0_BASE: UInt32 = 0x40034000
    public static let UART0_RESET_MASK: UInt32 = 0x400120
    public static let UART0_IO_TX_CTRL: UInt32 = 0x40014004
    public static let UART0_IO_RX_CTRL: UInt32 = 0x4001400C
    public static let UART0_FUNCSEL: UInt32 = 2
    public static let UART0_CLK_PERI_HZ: UInt32 = 12000000
    public static let UART0_IBRD_115200_XOSC_12MHZ: UInt32 = 6
    public static let UART0_FBRD_115200_XOSC_12MHZ: UInt32 = 33

    // -- the clock plan (state-and-verify: the plan states the chosen PLL
    // values AND the resulting rates; generation verified hz == xosc * fbdiv /
    // (postdiv1 * postdiv2) and composed each PRIM word from the pll block fields).
    // Every const carries the plan name as a suffix, the default plan included, so a
    // name states which operating point it means -- a board may declare several --
    public static let XOSC_HZ_PLL_125_48: UInt32 = 12000000
    public static let CLK_SYS_HZ_PLL_125_48: UInt32 = 125000000
    public static let CLK_USB_HZ_PLL_125_48: UInt32 = 48000000
    public static let PLL_SYS_FBDIV_PLL_125_48: UInt32 = 125
    public static let PLL_SYS_PRIM_PLL_125_48: UInt32 = 0x62000
    public static let PLL_USB_FBDIV_PLL_125_48: UInt32 = 100
    public static let PLL_USB_PRIM_PLL_125_48: UInt32 = 0x55000

    // -- memory regions the board fits: SIZE is what a program may reach, which a device's own
    // size may exceed; a region with a CONTROLLER does not exist until that instance is brought
    // up, and touching it first is a bus fault rather than a wrong value --
    public static let MEMORY_REGION_COUNT: UInt32 = 1
    public static let MEMORY_FLASH_KIND: StaticString = "flash"
    public static let MEMORY_FLASH_SIZE: UInt32 = 0x200000
    public static let MEMORY_FLASH_OPTIONAL: UInt32 = 0
}
