//! GENERATED by lamella-bsp-gen from bsp/nucleo-u5a5zj-q/board.toml + csp/stm32u5a5/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32u5a5

pub const BOARD_MODEL: u16 = 40;
pub const BOARD_VENDOR: &str = "St";

/// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
/// role's `KIND` says what the application asked for -- a uart, an spi -- and two
/// peripherals of the same kind can share no register at all, so a consumer that selects a
/// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
/// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
/// name a driver; and a uart is a different register map on every family, so the kind does
/// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
pub const VCP_DRIVER_FAMILY: &str = "stm32u5a5-usart";

pub const VCP_BASE: u32 = 0x40013800;
pub const VCP_RCC_EN_REG: u32 = 0x46020CA4;
pub const VCP_RCC_EN_MASK: u32 = 0x4000;
pub const VCP_TX_PORT_RCC_EN_REG: u32 = 0x46020C8C;
pub const VCP_TX_PORT_RCC_EN_MASK: u32 = 0x1;
pub const VCP_TX_MODER_REG: u32 = 0x42020000;
pub const VCP_TX_MODER_MASK: u32 = 0xC0000;
pub const VCP_TX_MODER_VALUE: u32 = 0x80000;
pub const VCP_TX_AFR_REG: u32 = 0x42020024;
pub const VCP_TX_AFR_MASK: u32 = 0xF0;
pub const VCP_TX_AFR_VALUE: u32 = 0x70;
pub const VCP_RX_PORT_RCC_EN_REG: u32 = 0x46020C8C;
pub const VCP_RX_PORT_RCC_EN_MASK: u32 = 0x1;
pub const VCP_RX_MODER_REG: u32 = 0x42020000;
pub const VCP_RX_MODER_MASK: u32 = 0x300000;
pub const VCP_RX_MODER_VALUE: u32 = 0x200000;
pub const VCP_RX_AFR_REG: u32 = 0x42020024;
pub const VCP_RX_AFR_MASK: u32 = 0xF00;
pub const VCP_RX_AFR_VALUE: u32 = 0x700;
pub const VCP_PCLK_HZ: u32 = 4000000;
pub const VCP_BRR_115200_MSIS_4MHZ: u32 = 0x23;
