//! GENERATED by lamella-bsp-gen from csp/stm32f091/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32f091
//!
//! The stm32f091 instance map as Rust consts, name/value-identical to Stm32f091Instances.g.cs:
//! where each block copy sits and its per-instance ids. Each block's layout is in its own
//! layout module beside this file.

pub const USART2_BASE: u32 = 0x40004400;
pub const USART2_RCC_EN_OFF: u32 = 28;
pub const USART2_RCC_EN_BIT: u32 = 17;
pub const USART2_RCC_EN_MASK: u32 = 0x20000;
pub const GPIOA_BASE: u32 = 0x48000000;
pub const GPIOA_RCC_EN_OFF: u32 = 20;
pub const GPIOA_RCC_EN_BIT: u32 = 17;
pub const GPIOA_RCC_EN_MASK: u32 = 0x20000;
pub const RCC_BASE: u32 = 0x40021000;
pub const GPIOC_BASE: u32 = 0x48000800;
pub const GPIOC_RCC_EN_OFF: u32 = 20;
pub const GPIOC_RCC_EN_BIT: u32 = 19;
pub const GPIOC_RCC_EN_MASK: u32 = 0x80000;
pub const GPIOD_BASE: u32 = 0x48000C00;
pub const GPIOD_RCC_EN_OFF: u32 = 20;
pub const GPIOD_RCC_EN_BIT: u32 = 20;
pub const GPIOD_RCC_EN_MASK: u32 = 0x100000;
pub const GPIOE_BASE: u32 = 0x48001000;
pub const GPIOE_RCC_EN_OFF: u32 = 20;
pub const GPIOE_RCC_EN_BIT: u32 = 21;
pub const GPIOE_RCC_EN_MASK: u32 = 0x200000;
pub const GPIOF_BASE: u32 = 0x48001400;
pub const GPIOF_RCC_EN_OFF: u32 = 20;
pub const GPIOF_RCC_EN_BIT: u32 = 22;
pub const GPIOF_RCC_EN_MASK: u32 = 0x400000;
