//! GENERATED by lamella-bsp-gen from bsp/rpi-pico/board.toml + csp/rp2040/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040

pub const BOARD_MODEL: u16 = 13;
pub const BOARD_VENDOR: &str = "RaspberryPi";

pub const UART0_BASE: u32 = 0x40034000;
pub const UART0_RESET_MASK: u32 = 0x400120;
pub const UART0_IO_TX_CTRL: u32 = 0x40014004;
pub const UART0_IO_RX_CTRL: u32 = 0x4001400C;
pub const UART0_FUNCSEL: u32 = 2;
pub const UART0_CLK_PERI_HZ: u32 = 12000000;
pub const UART0_IBRD_115200_XOSC_12MHZ: u32 = 6;
pub const UART0_FBRD_115200_XOSC_12MHZ: u32 = 33;

pub const XOSC_HZ_PLL_125_48: u32 = 12000000;
pub const CLK_SYS_HZ_PLL_125_48: u32 = 125000000;
pub const CLK_USB_HZ_PLL_125_48: u32 = 48000000;
pub const PLL_SYS_FBDIV_PLL_125_48: u32 = 125;
pub const PLL_SYS_PRIM_PLL_125_48: u32 = 0x62000;
pub const PLL_USB_FBDIV_PLL_125_48: u32 = 100;
pub const PLL_USB_PRIM_PLL_125_48: u32 = 0x55000;

/// -- memory regions the board fits: SIZE is what a program may reach, which a device's own
/// size may exceed; a region with a CONTROLLER does not exist until that instance is brought
/// up, and touching it first is a bus fault rather than a wrong value --
pub const MEMORY_REGION_COUNT: u32 = 1;
pub const MEMORY_FLASH_KIND: &str = "flash";
pub const MEMORY_FLASH_SIZE: u32 = 0x200000;
pub const MEMORY_FLASH_OPTIONAL: u32 = 0;
