// GENERATED by lamella-bsp-gen from parts/mag3110/mag3110.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Mag3110Part
    {
        private Mag3110Part() { }
        public const string PART = "mag3110";
        public const string FAMILY = "mag3110";

        /// sourcing: how far this part is established, on two INDEPENDENT axes -- a part can be strong on one and absent on the other, which is why they are not one rank. FACTS is `primary` (read from the part's own datasheet) or `secondary` (a primary vendor statement about this part carried by another document, named by DERIVED_FROM). VALIDATION is `none` (no physical part of this type has been made to answer), `identified` (one answered its identity register, against a negative control that tells the part from the wire) or `exercised` (one produced measurements a driver decoded). Anything above `none` states what was observed in EVIDENCE.
        public const string SOURCING_FACTS = "primary";
        public const string SOURCING_VALIDATION = "identified";
        public const string SOURCING_EVIDENCE = "A physical part answered the identity register on a micro:bit v1.3B, over the nRF51's TWI0 at 100 kHz on the board's internal bus: register 0x07 read 0xC4 at address 0x0E, the single value this table accepts at the single address it states, repeated across eight consecutive passes with 0 faulted of 112 addresses walked in each. THE NEGATIVE CONTROL RAN IN TWO PARTS. First, on that same bus in those same passes, reads of other parts' identity registers at addresses where nothing was fitted ABORTED every time, so this bus reports an absence as an abort rather than as a byte. Second, the identical read of the identical register at the identical address, 0x07 at 0x0E, was run on a micro:bit v2 -- a board that does not fit this part -- and ABORTED across ten consecutive passes; that arm is on a different controller of the same family, which is stated because it is what makes it a second arm rather than a repetition of the first. THE REGISTER IS THE POINT OF THIS ONE: two other parts from this vendor in this catalogue answer their identity at 0x0D, and this part answers at 0x07 while holding writable offset configuration at 0x0D -- so an instrument that assumed a vendor convention would have read this part's user Z offset and compared it against a device id. It was asked at its own register and answered. EVERY NUMBER IN THE CHECK -- the address, the register and the accepted value -- was taken from this table's own emitted artifact by a bench program that includes it.";

        /// identity: the accepted values are a SET. A driver that accepts only one of them rejects a genuine part, and a rejected part reads as no part at all -- so on a mismatch, name the id received AND this set.
        public const uint IDENTITY_REG = 0x7;
        public const uint IDENTITY_WIDTH = 8;
        public const uint IDENTITY_VALUE_COUNT = 1;
        public const uint IDENTITY_VALUE_0 = 0xC4;

        /// address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
        public const string ADDRESS_BUS = "i2c";
        public const uint ADDRESS_BASE = 0xE;
        public const uint ADDRESS_STRAP_COUNT = 0;

        /// buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
        public const uint BUS_COUNT = 1;
        public const string BUS_I2C_KIND = "i2c";
        public const string BUS_I2C_REGISTER_READ_TRANSFORM = "identity";
        public const string BUS_I2C_REGISTER_WRITE_TRANSFORM = "identity";
        public const string BUS_I2C_READ_PROTOCOL = "write-register-then-repeated-start-read";

        /// registers: `_REG` is the address written on the wire -- an operand, NOT an offset to add to an instance base. Fields carry the shifted mask and its shift.
        public const uint DR_STATUS_REG = 0x0;
        public const uint DR_STATUS_WIDTH = 8;
        public const string DR_STATUS_ACCESS = "read-only";
        public const uint OUT_X_REG = 0x1;
        public const uint OUT_X_WIDTH = 16;
        public const string OUT_X_ACCESS = "read-only";
        public const uint OUT_X_OUT_X_LSB = 0xFF;
        public const uint OUT_X_OUT_X_LSB_LSB = 0;
        public const uint OUT_X_OUT_X_MSB = 0xFF00;
        public const uint OUT_X_OUT_X_MSB_LSB = 8;
        public const uint OUT_Y_REG = 0x3;
        public const uint OUT_Y_WIDTH = 16;
        public const string OUT_Y_ACCESS = "read-only";
        public const uint OUT_Y_OUT_Y_LSB = 0xFF;
        public const uint OUT_Y_OUT_Y_LSB_LSB = 0;
        public const uint OUT_Y_OUT_Y_MSB = 0xFF00;
        public const uint OUT_Y_OUT_Y_MSB_LSB = 8;
        public const uint OUT_Z_REG = 0x5;
        public const uint OUT_Z_WIDTH = 16;
        public const string OUT_Z_ACCESS = "read-only";
        public const uint OUT_Z_OUT_Z_LSB = 0xFF;
        public const uint OUT_Z_OUT_Z_LSB_LSB = 0;
        public const uint OUT_Z_OUT_Z_MSB = 0xFF00;
        public const uint OUT_Z_OUT_Z_MSB_LSB = 8;
        public const uint WHO_AM_I_REG = 0x7;
        public const uint WHO_AM_I_WIDTH = 8;
        public const string WHO_AM_I_ACCESS = "read-only";
        public const uint WHO_AM_I_WHO_AM_I = 0xFF;
        public const uint WHO_AM_I_WHO_AM_I_LSB = 0;
        public const uint SYSMOD_REG = 0x8;
        public const uint SYSMOD_WIDTH = 8;
        public const string SYSMOD_ACCESS = "read-only";
        public const uint OFF_X_REG = 0x9;
        public const uint OFF_X_WIDTH = 16;
        public const string OFF_X_ACCESS = "read-write";
        public const uint OFF_X_OFF_X_LSB = 0xFF;
        public const uint OFF_X_OFF_X_LSB_LSB = 0;
        public const uint OFF_X_OFF_X_MSB = 0xFF00;
        public const uint OFF_X_OFF_X_MSB_LSB = 8;
        public const uint OFF_Y_REG = 0xB;
        public const uint OFF_Y_WIDTH = 16;
        public const string OFF_Y_ACCESS = "read-write";
        public const uint OFF_Y_OFF_Y_LSB = 0xFF;
        public const uint OFF_Y_OFF_Y_LSB_LSB = 0;
        public const uint OFF_Y_OFF_Y_MSB = 0xFF00;
        public const uint OFF_Y_OFF_Y_MSB_LSB = 8;
        public const uint OFF_Z_REG = 0xD;
        public const uint OFF_Z_WIDTH = 16;
        public const string OFF_Z_ACCESS = "read-write";
        public const uint OFF_Z_OFF_Z_LSB = 0xFF;
        public const uint OFF_Z_OFF_Z_LSB_LSB = 0;
        public const uint OFF_Z_OFF_Z_MSB = 0xFF00;
        public const uint OFF_Z_OFF_Z_MSB_LSB = 8;
        public const uint DIE_TEMP_REG = 0xF;
        public const uint DIE_TEMP_WIDTH = 8;
        public const string DIE_TEMP_ACCESS = "read-only";
        public const uint CTRL_REG1_REG = 0x10;
        public const uint CTRL_REG1_WIDTH = 8;
        public const string CTRL_REG1_ACCESS = "read-write";
        public const uint CTRL_REG2_REG = 0x11;
        public const uint CTRL_REG2_WIDTH = 8;
        public const string CTRL_REG2_ACCESS = "read-write";

        /// measurement: the part holds a whole data block steady for the duration of one burst, so a byte-at-a-time read can mix two conversions.
        public const uint BURST_LENGTH = 6;
    }
}
