// GENERATED by lamella-bsp-gen from bsp/feather-rp2040-adalogger/board.toml + csp/rp2040/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class FeatherRp2040AdaloggerBindings
    {
        private FeatherRp2040AdaloggerBindings() { }

        public const int BOARD_MODEL = 18;

        public const uint UART0_BASE = 0x40034000;
        public const uint UART0_RESET_MASK = 0x400120;
        public const uint UART0_IO_TX_CTRL = 0x40014004;
        public const uint UART0_IO_RX_CTRL = 0x4001400C;
        public const uint UART0_FUNCSEL = 2;
        public const uint UART0_CLK_PERI_HZ = 12000000;

        public const uint LED_PORT_BASE = 0xD0000000;
        public const uint LED_PIN = 13;
        public const uint LED_MASK = 0x2000;
        public const uint LED_ACTIVE_LOW = 0;
        public const uint NEOPIXEL_PORT_BASE = 0xD0000000;
        public const uint NEOPIXEL_PIN = 17;
        public const uint NEOPIXEL_MASK = 0x20000;
        public const uint NEOPIXEL_ACTIVE_LOW = 0;
        public const uint BUTTON_PORT_BASE = 0xD0000000;
        public const uint BUTTON_PIN = 7;
        public const uint BUTTON_MASK = 0x80;
        public const uint BUTTON_ACTIVE_LOW = 1;
        public const uint SD_CARD_DETECT_PORT_BASE = 0xD0000000;
        public const uint SD_CARD_DETECT_PIN = 16;
        public const uint SD_CARD_DETECT_MASK = 0x10000;
        public const uint SD_CARD_DETECT_ACTIVE_LOW = 1;
    }
}
