# GENERATED by lamella-bsp-gen from parts/lsm303agr/lsm303agr-mag.toml + parts/lsm303agr/lsm303agr.toml -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-parts . lsm303agr
#
# The lsm303agr-mag part table, FLATTENED: every value it inherited is spelled out here, because a
# value that is only ever inherited is pinned in no emitted artifact and so cannot be
# checked for drift between languages. A part is something we talk TO rather than a chip
# we run on -- a board states which buses exist, this table states the part's identity,
# and a probe joins the two at run time.
PART = "lsm303agr-mag"
FAMILY = "lsm303agr"

# sourcing: how far this part is established, on two INDEPENDENT axes -- a part can be strong on one and absent on the other, which is why they are not one rank. FACTS is `primary` (read from the part's own datasheet) or `secondary` (a primary vendor statement about this part carried by another document, named by DERIVED_FROM). VALIDATION is `none` (no physical part of this type has been made to answer), `identified` (one answered its identity register, against a negative control that tells the part from the wire) or `exercised` (one produced measurements a driver decoded). Anything above `none` states what was observed in EVIDENCE.
SOURCING_FACTS = "primary"
SOURCING_VALIDATION = "identified"
SOURCING_EVIDENCE = "A physical part answered the identity register on a Raspberry Pi Pico 2, over I2C0 at 100 kHz, on a breakout reached through a four-wire cable: register 0x4F read 0x40 at address 0x1E, the single value this table accepts at the single address it states, repeated across five consecutive passes with 0 faulted of 112 addresses walked in each. THE NEGATIVE CONTROL RAN AT THE SAME ADDRESS ON THE SAME REGISTER: with the module unplugged, the identical read ABORTED in four consecutive passes, during which nothing answered anywhere on the bus and 0 of 112 addresses were faulted. A SECOND CONTROL CAME FREE AND IT TESTS THIS FAMILY'S WHOLE MODEL: the accelerometer half of the same package was checked in the same passes at ITS address and ITS register, 0x0F at 0x19, and answered its own value and not this one -- so the two halves are separated by different registers at different addresses on silicon and not merely on paper, which is the claim that made this package two parts rather than one with a plural address. EVERY NUMBER IN THE CHECK -- the address, the register and the accepted value -- was taken from this table's own emitted artifact by a bench program that includes it, so what was tested is the row that ships and not a copy of it."

# identity: the accepted values are a SET. A driver that accepts only one of them rejects a genuine part, and a rejected part reads as no part at all -- so on a mismatch, name the id received AND this set.
IDENTITY_REG = 0x4F
IDENTITY_WIDTH = 8
IDENTITY_VALUE_COUNT = 1
IDENTITY_VALUE_0 = 0x40

# address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
ADDRESS_BUS = "i2c"
ADDRESS_BASE = 0x1E
ADDRESS_STRAP_COUNT = 0

# buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
BUS_COUNT = 2
BUS_I2C_KIND = "i2c"
BUS_I2C_REGISTER_READ_TRANSFORM = "identity"
BUS_I2C_REGISTER_WRITE_TRANSFORM = "identity"
BUS_I2C_READ_PROTOCOL = "write-register-then-repeated-start-read"
BUS_SPI_KIND = "spi"
BUS_SPI_REGISTER_READ_TRANSFORM = "set-bit7"
BUS_SPI_REGISTER_WRITE_TRANSFORM = "clear-bit7"
BUS_SPI_READ_PROTOCOL = "single-chip-select-address-then-clock-data"

# registers: `_REG` is the address written on the wire -- an operand, NOT an offset to add to an instance base. Fields carry the shifted mask and its shift.
WHO_AM_I_M_REG = 0x4F
WHO_AM_I_M_WIDTH = 8
WHO_AM_I_M_ACCESS = "read-only"
WHO_AM_I_M_WHO_AM_I = 0xFF
WHO_AM_I_M_WHO_AM_I_LSB = 0
OFFSET_X_M_REG = 0x45
OFFSET_X_M_WIDTH = 16
OFFSET_X_M_ACCESS = "read-write"
OFFSET_X_M_OFFSET_X_L = 0xFF
OFFSET_X_M_OFFSET_X_L_LSB = 0
OFFSET_X_M_OFFSET_X_H = 0xFF00
OFFSET_X_M_OFFSET_X_H_LSB = 8
OFFSET_Y_M_REG = 0x47
OFFSET_Y_M_WIDTH = 16
OFFSET_Y_M_ACCESS = "read-write"
OFFSET_Y_M_OFFSET_Y_L = 0xFF
OFFSET_Y_M_OFFSET_Y_L_LSB = 0
OFFSET_Y_M_OFFSET_Y_H = 0xFF00
OFFSET_Y_M_OFFSET_Y_H_LSB = 8
OFFSET_Z_M_REG = 0x49
OFFSET_Z_M_WIDTH = 16
OFFSET_Z_M_ACCESS = "read-write"
OFFSET_Z_M_OFFSET_Z_L = 0xFF
OFFSET_Z_M_OFFSET_Z_L_LSB = 0
OFFSET_Z_M_OFFSET_Z_H = 0xFF00
OFFSET_Z_M_OFFSET_Z_H_LSB = 8
CFG_REG_A_M_REG = 0x60
CFG_REG_A_M_WIDTH = 8
CFG_REG_A_M_ACCESS = "read-write"
CFG_REG_B_M_REG = 0x61
CFG_REG_B_M_WIDTH = 8
CFG_REG_B_M_ACCESS = "read-write"
CFG_REG_C_M_REG = 0x62
CFG_REG_C_M_WIDTH = 8
CFG_REG_C_M_ACCESS = "read-write"
INT_CTRL_REG_M_REG = 0x63
INT_CTRL_REG_M_WIDTH = 8
INT_CTRL_REG_M_ACCESS = "read-write"
INT_SOURCE_REG_M_REG = 0x64
INT_SOURCE_REG_M_WIDTH = 8
INT_SOURCE_REG_M_ACCESS = "read-only"
INT_THS_M_REG = 0x65
INT_THS_M_WIDTH = 16
INT_THS_M_ACCESS = "read-write"
INT_THS_M_INT_THS_L = 0xFF
INT_THS_M_INT_THS_L_LSB = 0
INT_THS_M_INT_THS_H = 0xFF00
INT_THS_M_INT_THS_H_LSB = 8
STATUS_REG_M_REG = 0x67
STATUS_REG_M_WIDTH = 8
STATUS_REG_M_ACCESS = "read-only"
OUTX_M_REG = 0x68
OUTX_M_WIDTH = 16
OUTX_M_ACCESS = "read-only"
OUTX_M_OUTX_L = 0xFF
OUTX_M_OUTX_L_LSB = 0
OUTX_M_OUTX_H = 0xFF00
OUTX_M_OUTX_H_LSB = 8
OUTY_M_REG = 0x6A
OUTY_M_WIDTH = 16
OUTY_M_ACCESS = "read-only"
OUTY_M_OUTY_L = 0xFF
OUTY_M_OUTY_L_LSB = 0
OUTY_M_OUTY_H = 0xFF00
OUTY_M_OUTY_H_LSB = 8
OUTZ_M_REG = 0x6C
OUTZ_M_WIDTH = 16
OUTZ_M_ACCESS = "read-only"
OUTZ_M_OUTZ_L = 0xFF
OUTZ_M_OUTZ_L_LSB = 0
OUTZ_M_OUTZ_H = 0xFF00
OUTZ_M_OUTZ_H_LSB = 8

# measurement: the part holds a whole data block steady for the duration of one burst, so a byte-at-a-time read can mix two conversions.
BURST_LENGTH = 6
