// GENERATED by lamella-bsp-gen from csp/stm32f769/blocks/exti.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32f769ExtiLayout
    {
        private Stm32f769ExtiLayout() { }

        public const uint IMR_OFF = 0x0;
        public const int IMR_WIDTH = 32;
        public const uint EMR_OFF = 0x4;
        public const int EMR_WIDTH = 32;
        public const uint RTSR_OFF = 0x8;
        public const int RTSR_WIDTH = 32;
        public const uint FTSR_OFF = 0xC;
        public const int FTSR_WIDTH = 32;
        public const uint SWIER_OFF = 0x10;
        public const int SWIER_WIDTH = 32;
        public const uint PR_OFF = 0x14;
        public const int PR_WIDTH = 32;

        public const uint IMR_MR = 0x1FFFFFF;
        public const uint IMR_MR_LSB = 0;
        public const uint EMR_MR = 0x1FFFFFF;
        public const uint EMR_MR_LSB = 0;
        public const uint RTSR_TR = 0x1FFFFFF;
        public const uint RTSR_TR_LSB = 0;
        public const uint FTSR_TR = 0x1FFFFFF;
        public const uint FTSR_TR_LSB = 0;
        public const uint SWIER_SWIER = 0x1FFFFFF;
        public const uint SWIER_SWIER_LSB = 0;
        public const uint PR_PR = 0x1FFFFFF;
        public const uint PR_PR_LSB = 0;
    }
}
