// GENERATED by lamella-bsp-gen from bsp/microchip-sam4n-xpro/board.toml + csp/sam4n/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4n
//
// The microchip-sam4n-xpro board bindings (resolved against the sam4n chip strata): every value below is a
// generation-time literal derived from the strata -- role descriptors, module control
// lines, and the carrier identity. The board's facts are stated in board.toml.
namespace Lamella.Generated
{
    public sealed class MicrochipSam4nXproBindings
    {
        private MicrochipSam4nXproBindings() { }

        // -- identity --
        public const int BOARD_MODEL = 25;
        public const string BOARD_VENDOR = "Microchip";
        public const uint CARRIER_USB_VID = 0x03EB;
        public const uint CARRIER_USB_PID = 0x2111;
        public const uint DEVICE_COUNT = 2;

        // -- on-board devices: PORT group base + pin index + mask --
        public const uint LED0_PORT_BASE = 0x400E1000;
        public const uint LED0_PIN = 14;
        public const uint LED0_BANK = 0;
        public const uint LED0_MASK = 0x4000;
        public const uint LED0_ACTIVE_LOW = 1;
        public const uint BUTTON0_PORT_BASE = 0x400E0E00;
        public const uint BUTTON0_PIN = 30;
        public const uint BUTTON0_BANK = 0;
        public const uint BUTTON0_MASK = 0x40000000;
        public const uint BUTTON0_ACTIVE_LOW = 1;
    }
}
