// GENERATED by lamella-bsp-gen from bsp/rpi-pico-w/board.toml + csp/rp2040/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class PicoWBindings
    {
        private PicoWBindings() { }

        public const int BOARD_MODEL = 22;
        public const string BOARD_VENDOR = "RaspberryPi";

        /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
        /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
        /// peripherals of the same kind can share no register at all, so a consumer that selects a
        /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
        /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
        /// name a driver; and a uart is a different register map on every family, so the kind does
        /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
        public const string UART0_DRIVER_FAMILY = "rp2040-uart";

        public const uint UART0_BASE = 0x40034000;
        public const uint UART0_RESET_MASK = 0x400120;
        public const uint UART0_IO_TX_CTRL = 0x40014004;
        public const uint UART0_IO_RX_CTRL = 0x4001400C;
        public const uint UART0_FUNCSEL = 2;
        public const uint UART0_CLK_PERI_HZ = 12000000;
        public const uint UART0_IBRD_115200_XOSC_12MHZ = 6;
        public const uint UART0_FBRD_115200_XOSC_12MHZ = 33;

        public const uint XOSC_HZ_PLL_125_48 = 12000000;
        public const uint CLK_SYS_HZ_PLL_125_48 = 125000000;
        public const uint CLK_USB_HZ_PLL_125_48 = 48000000;
        public const uint PLL_SYS_FBDIV_PLL_125_48 = 125;
        public const uint PLL_SYS_PRIM_PLL_125_48 = 0x62000;
        public const uint PLL_USB_FBDIV_PLL_125_48 = 100;
        public const uint PLL_USB_PRIM_PLL_125_48 = 0x55000;

        public const uint CYW43439_WL_REG_ON_PORT_BASE = 0xD0000000;
        public const uint CYW43439_WL_REG_ON_PIN = 23;
        public const uint CYW43439_WL_REG_ON_MASK = 0x800000;
        public const uint CYW43439_WL_REG_ON_ACTIVE_LOW = 0;
        public const uint CYW43439_DATA_PORT_BASE = 0xD0000000;
        public const uint CYW43439_DATA_PIN = 24;
        public const uint CYW43439_DATA_MASK = 0x1000000;
        public const uint CYW43439_CS_PORT_BASE = 0xD0000000;
        public const uint CYW43439_CS_PIN = 25;
        public const uint CYW43439_CS_MASK = 0x2000000;
        public const uint CYW43439_CS_ACTIVE_LOW = 1;
        public const uint CYW43439_CLK_PORT_BASE = 0xD0000000;
        public const uint CYW43439_CLK_PIN = 29;
        public const uint CYW43439_CLK_MASK = 0x20000000;

        /// -- memory regions the board fits: SIZE is what a program may reach, which a device's own
        /// size may exceed; a region with a CONTROLLER does not exist until that instance is brought
        /// up, and touching it first is a bus fault rather than a wrong value --
        public const uint MEMORY_REGION_COUNT = 1;
        public const string MEMORY_FLASH_KIND = "flash";
        public const uint MEMORY_FLASH_SIZE = 0x200000;
        public const uint MEMORY_FLASH_OPTIONAL = 0;
    }
}
