// GENERATED by lamella-bsp-gen from bsp/atsamd10-xmini/board.toml + csp/samd10/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Atsamd10XminiBindings
    {
        private Atsamd10XminiBindings() { }

        public const int BOARD_MODEL = 38;
        public const string BOARD_VENDOR = "Microchip";
        public const uint CARRIER_USB_VID = 0x03EB;
        public const uint CARRIER_USB_PID = 0x2145;

        /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
        /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
        /// peripherals of the same kind can share no register at all, so a consumer that selects a
        /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
        /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
        /// name a driver; and a uart is a different register map on every family, so the kind does
        /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
        public const string VCP_DRIVER_FAMILY = "samd10-sercom";

        public const uint VCP_SERCOM_BASE = 0x42000800;
        public const uint VCP_IRQ = 9;
        public const uint VCP_GCLK_CLKCTRL_VALUE = 0x400E;
        public const uint VCP_APBC_MASK = 0x4;
        public const uint VCP_PMUX_REG = 0x41004435;
        public const uint VCP_PMUX_PAIR = 0x22;
        public const uint VCP_PINCFG_TX_REG = 0x4100444A;
        public const uint VCP_PINCFG_RX_REG = 0x4100444B;
        public const uint VCP_TXPO = 1;
        public const uint VCP_RXPO = 3;
        public const uint VCP_BAUD_115200_OSC8M_8MHZ = 0xC505;
    }
}
