//! GENERATED by lamella-bsp-gen from bsp/sam4s-xpro/board.toml + csp/sam4s/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4s

pub const BOARD_MODEL: u16 = 3;
pub const BOARD_VENDOR: &str = "Microchip";
