# GENERATED by lamella-bsp-gen from bsp/mkr1000/board.toml + csp/atsamw25/module.toml + csp/samd21/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21

BOARD = "mkr1000"
BOARD_MODEL = 9

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
WINC_SPI = "winc-spi"

CARRIER = {
    "kind": "native-usb",
}

# Per-role descriptor dicts: the same values the C# Mkr1000Bindings class carries as consts,
# under one mechanical renaming rule -- an UPPER_SNAKE const there is a lowercase key here,
# grouped by the role it belongs to.
FACTS = {
    "winc-spi": {
        "kind": "spi",
        "instance": "sercom2",
        "sercom_base": 0x42001000,
        "irq": 11,
        "apbc_mask": 0x10,
        "gclk_core_id": 22,
        "pmux_mosi_reg": 0x41004436,
        "pmux_mosi_shift": 0,
        "pincfg_mosi_reg": 0x4100444C,
        "pmux_sck_reg": 0x41004436,
        "pmux_sck_shift": 4,
        "pincfg_sck_reg": 0x4100444D,
        "pmux_miso_reg": 0x41004437,
        "pmux_miso_shift": 4,
        "pincfg_miso_reg": 0x4100444F,
        "pmux_func": 2,
        "dopo": 0,
        "dipo": 3,
        "cs_port_base": 0x41004400,
        "cs_pin": 14,
        "cs_mask": 0x4000,
    },
}

PLANS = {
    "osc8m-8mhz": {"default": True, "source": "osc8m", "gclk0_hz": 8000000},
    "usb-48mhz": {"default": False, "source": "dfll48m-usb-recovery", "gclk1_hz": 48000000},
}

# On-board devices + module control lines (the C# <NAME>_PORT_BASE/_PIN/_MASK/
# _ACTIVE_LOW consts, dict-shaped): PORT group base + pin index + mask + polarity.
DEVICES = {
    "winc-reset_n": {"port_base": 0x41004400, "pin": 27, "mask": 0x8000000, "active_low": True},
    "winc-chip_en": {"port_base": 0x41004400, "pin": 28, "mask": 0x10000000, "active_low": False},
    "winc-irqn": {"port_base": 0x41004480, "pin": 9, "mask": 0x200, "active_low": True},
}
