// GENERATED by lamella-bsp-gen from csp/stm32f7/blocks/gpio.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32f7
//
// The stm32f7 gpio BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Stm32f7Instances. Widths are access widths.

public enum Stm32f7GpioLayout {
    // -- register offsets (block-relative) + access widths --
    public static let MODER_OFF: UInt32 = 0x0
    public static let MODER_WIDTH: Int32 = 32
    public static let OTYPER_OFF: UInt32 = 0x4
    public static let OTYPER_WIDTH: Int32 = 32
    public static let OSPEEDR_OFF: UInt32 = 0x8
    public static let OSPEEDR_WIDTH: Int32 = 32
    public static let PUPDR_OFF: UInt32 = 0xC
    public static let PUPDR_WIDTH: Int32 = 32
    public static let AFRL_OFF: UInt32 = 0x20
    public static let AFRL_WIDTH: Int32 = 32
    public static let AFRH_OFF: UInt32 = 0x24
    public static let AFRH_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let MODER_MODER7: UInt32 = 0xC000
    public static let MODER_MODER7_LSB: UInt32 = 14
    public static let MODER_MODER9: UInt32 = 0xC0000
    public static let MODER_MODER9_LSB: UInt32 = 18
    public static let AFRL_AFSEL7: UInt32 = 0xF0000000
    public static let AFRL_AFSEL7_LSB: UInt32 = 28
    public static let AFRH_AFSEL9: UInt32 = 0xF0
    public static let AFRH_AFSEL9_LSB: UInt32 = 4

    // -- block constants --
    public static let MODER_MODE_AF: UInt32 = 2
    public static let OTYPER_OPEN_DRAIN: UInt32 = 1
    public static let OSPEEDR_VERY_HIGH: UInt32 = 3
    public static let PUPDR_PULL_UP: UInt32 = 1
}
