//! GENERATED by lamella-bsp-gen from csp/sam4n/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4n
//!
//! The sam4n instance map as Rust consts, name/value-identical to Sam4nInstances.g.cs:
//! where each block copy sits and its per-instance ids. Each block's layout is in its own
//! layout module beside this file.

pub const EEFC0_BASE: u32 = 0x400E0A00;
pub const PIOA_BASE: u32 = 0x400E0E00;
pub const PIOA_PID: u32 = 11;
pub const PIOB_BASE: u32 = 0x400E1000;
pub const PIOB_PID: u32 = 12;
