//! GENERATED by lamella-bsp-gen from csp/same54/blocks/flash.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . same54
//!
//! The same54 flash block layout as Rust consts, name/value-identical to Same54FlashLayout.g.cs:
//! offsets are instance-base-relative (`base + *_OFF`) and the instance bases live in
//! same54_instances.rs. Widths are access widths.

/// -- block constants --
pub const ERASED_VALUE: u32 = 0xFFFFFFFF;
pub const WRITE_UNIT: u32 = 16;
