//! GENERATED by lamella-bsp-gen from csp/same54/blocks/gclk.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . same54

/// -- register offsets (block-relative) + access widths --
pub const CTRLA_OFF: u32 = 0x0;
pub const CTRLA_WIDTH: i32 = 8;
pub const SYNCBUSY_OFF: u32 = 0x4;
pub const SYNCBUSY_WIDTH: i32 = 32;
pub const GENCTRL0_OFF: u32 = 0x20;
pub const GENCTRL0_WIDTH: i32 = 32;
pub const PCHCTRL0_OFF: u32 = 0x80;
pub const PCHCTRL0_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const CTRLA_SWRST: u32 = 0x1;
pub const CTRLA_SWRST_LSB: u32 = 0;
pub const SYNCBUSY_SWRST: u32 = 0x1;
pub const SYNCBUSY_SWRST_LSB: u32 = 0;
pub const SYNCBUSY_GENCTRL: u32 = 0x3FFC;
pub const SYNCBUSY_GENCTRL_LSB: u32 = 2;
pub const GENCTRL0_SRC: u32 = 0x1F;
pub const GENCTRL0_SRC_LSB: u32 = 0;
pub const GENCTRL0_GENEN: u32 = 0x100;
pub const GENCTRL0_GENEN_LSB: u32 = 8;
pub const GENCTRL0_IDC: u32 = 0x200;
pub const GENCTRL0_IDC_LSB: u32 = 9;
pub const GENCTRL0_OOV: u32 = 0x400;
pub const GENCTRL0_OOV_LSB: u32 = 10;
pub const GENCTRL0_OE: u32 = 0x800;
pub const GENCTRL0_OE_LSB: u32 = 11;
pub const GENCTRL0_DIVSEL: u32 = 0x1000;
pub const GENCTRL0_DIVSEL_LSB: u32 = 12;
pub const GENCTRL0_RUNSTDBY: u32 = 0x2000;
pub const GENCTRL0_RUNSTDBY_LSB: u32 = 13;
pub const GENCTRL0_DIV: u32 = 0xFFFF0000;
pub const GENCTRL0_DIV_LSB: u32 = 16;
pub const PCHCTRL0_GEN: u32 = 0xF;
pub const PCHCTRL0_GEN_LSB: u32 = 0;
pub const PCHCTRL0_CHEN: u32 = 0x40;
pub const PCHCTRL0_CHEN_LSB: u32 = 6;
pub const PCHCTRL0_WRTLOCK: u32 = 0x80;
pub const PCHCTRL0_WRTLOCK_LSB: u32 = 7;
