// GENERATED by lamella-bsp-gen from csp/samd21/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The samd21 instance map as Swift constants, name/value-identical to Samd21Instances.g.cs:
// where each block copy sits and its per-instance ids. Block-register offsets are not
// emitted for Swift: a firmware project states its block constants and reads this file
// for every placed-instance fact.

public enum Samd21Instances {
    public static let SERCOM0_BASE: UInt32 = 0x42000800
    public static let SERCOM0_GCLK_CORE_ID: UInt32 = 20
    public static let SERCOM0_APBC_BIT: UInt32 = 2
    public static let SERCOM0_APBC_MASK: UInt32 = 0x4
    public static let SERCOM0_IRQ: UInt32 = 9
    public static let SERCOM1_BASE: UInt32 = 0x42000C00
    public static let SERCOM1_GCLK_CORE_ID: UInt32 = 21
    public static let SERCOM1_APBC_BIT: UInt32 = 3
    public static let SERCOM1_APBC_MASK: UInt32 = 0x8
    public static let SERCOM1_IRQ: UInt32 = 10
    public static let SERCOM2_BASE: UInt32 = 0x42001000
    public static let SERCOM2_GCLK_CORE_ID: UInt32 = 22
    public static let SERCOM2_APBC_BIT: UInt32 = 4
    public static let SERCOM2_APBC_MASK: UInt32 = 0x10
    public static let SERCOM2_IRQ: UInt32 = 11
    public static let SERCOM3_BASE: UInt32 = 0x42001400
    public static let SERCOM3_GCLK_CORE_ID: UInt32 = 23
    public static let SERCOM3_APBC_BIT: UInt32 = 5
    public static let SERCOM3_APBC_MASK: UInt32 = 0x20
    public static let SERCOM3_IRQ: UInt32 = 12
    public static let SERCOM4_BASE: UInt32 = 0x42001800
    public static let SERCOM4_GCLK_CORE_ID: UInt32 = 24
    public static let SERCOM4_APBC_BIT: UInt32 = 6
    public static let SERCOM4_APBC_MASK: UInt32 = 0x40
    public static let SERCOM4_IRQ: UInt32 = 13
    public static let SERCOM5_BASE: UInt32 = 0x42001C00
    public static let SERCOM5_GCLK_CORE_ID: UInt32 = 25
    public static let SERCOM5_APBC_BIT: UInt32 = 7
    public static let SERCOM5_APBC_MASK: UInt32 = 0x80
    public static let SERCOM5_IRQ: UInt32 = 14
    public static let PM_BASE: UInt32 = 0x40000400
    public static let GCLK_BASE: UInt32 = 0x40000C00
    public static let PORTA_BASE: UInt32 = 0x41004400
    public static let PORTB_BASE: UInt32 = 0x41004480
}
