// GENERATED by lamella-bsp-gen from csp/samd21/blocks/flash.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The samd21 flash BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samd21Instances. Widths are access widths.

public enum Samd21FlashLayout {
    // -- register offsets (block-relative) + access widths --

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --

    // -- block constants --
    public static let ERASED_VALUE: UInt32 = 0xFFFFFFFF
    public static let WRITE_UNIT: UInt32 = 64
}
