// GENERATED by lamella-bsp-gen from csp/samd21/blocks/tc-count8.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The samd21 tc-count8 block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Samd21Instances. Widths are access widths.

public enum Samd21TcCount8Layout {
    // -- register offsets (block-relative) + access widths --
    public static let CTRLA_OFF: UInt32 = 0x0
    public static let CTRLA_WIDTH: Int32 = 16
    public static let READREQ_OFF: UInt32 = 0x2
    public static let READREQ_WIDTH: Int32 = 16
    public static let CTRLBCLR_OFF: UInt32 = 0x4
    public static let CTRLBCLR_WIDTH: Int32 = 8
    public static let CTRLBSET_OFF: UInt32 = 0x5
    public static let CTRLBSET_WIDTH: Int32 = 8
    public static let CTRLC_OFF: UInt32 = 0x6
    public static let CTRLC_WIDTH: Int32 = 8
    public static let DBGCTRL_OFF: UInt32 = 0x8
    public static let DBGCTRL_WIDTH: Int32 = 8
    public static let INTFLAG_OFF: UInt32 = 0xE
    public static let INTFLAG_WIDTH: Int32 = 8
    public static let STATUS_OFF: UInt32 = 0xF
    public static let STATUS_WIDTH: Int32 = 8
    public static let COUNT_OFF: UInt32 = 0x10
    public static let COUNT_WIDTH: Int32 = 8
    public static let PER_OFF: UInt32 = 0x14
    public static let PER_WIDTH: Int32 = 8
    public static let CC0_OFF: UInt32 = 0x18
    public static let CC0_WIDTH: Int32 = 8
    public static let CC1_OFF: UInt32 = 0x19
    public static let CC1_WIDTH: Int32 = 8

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let CTRLA_SWRST: UInt32 = 0x1
    public static let CTRLA_SWRST_LSB: UInt32 = 0
    public static let CTRLA_ENABLE: UInt32 = 0x2
    public static let CTRLA_ENABLE_LSB: UInt32 = 1
    public static let CTRLA_MODE: UInt32 = 0xC
    public static let CTRLA_MODE_LSB: UInt32 = 2
    public static let CTRLA_WAVEGEN: UInt32 = 0x60
    public static let CTRLA_WAVEGEN_LSB: UInt32 = 5
    public static let CTRLA_PRESCALER: UInt32 = 0x700
    public static let CTRLA_PRESCALER_LSB: UInt32 = 8
    public static let CTRLA_RUNSTDBY: UInt32 = 0x800
    public static let CTRLA_RUNSTDBY_LSB: UInt32 = 11
    public static let CTRLA_PRESCSYNC: UInt32 = 0x3000
    public static let CTRLA_PRESCSYNC_LSB: UInt32 = 12
    public static let READREQ_ADDR: UInt32 = 0x1F
    public static let READREQ_ADDR_LSB: UInt32 = 0
    public static let READREQ_RCONT: UInt32 = 0x4000
    public static let READREQ_RCONT_LSB: UInt32 = 14
    public static let READREQ_RREQ: UInt32 = 0x8000
    public static let READREQ_RREQ_LSB: UInt32 = 15
    public static let CTRLBCLR_DIR: UInt32 = 0x1
    public static let CTRLBCLR_DIR_LSB: UInt32 = 0
    public static let CTRLBCLR_ONESHOT: UInt32 = 0x4
    public static let CTRLBCLR_ONESHOT_LSB: UInt32 = 2
    public static let CTRLBCLR_CMD: UInt32 = 0xC0
    public static let CTRLBCLR_CMD_LSB: UInt32 = 6
    public static let CTRLBSET_DIR: UInt32 = 0x1
    public static let CTRLBSET_DIR_LSB: UInt32 = 0
    public static let CTRLBSET_ONESHOT: UInt32 = 0x4
    public static let CTRLBSET_ONESHOT_LSB: UInt32 = 2
    public static let CTRLBSET_CMD: UInt32 = 0xC0
    public static let CTRLBSET_CMD_LSB: UInt32 = 6
    public static let CTRLC_INVEN0: UInt32 = 0x1
    public static let CTRLC_INVEN0_LSB: UInt32 = 0
    public static let CTRLC_INVEN1: UInt32 = 0x2
    public static let CTRLC_INVEN1_LSB: UInt32 = 1
    public static let CTRLC_CPTEN0: UInt32 = 0x10
    public static let CTRLC_CPTEN0_LSB: UInt32 = 4
    public static let CTRLC_CPTEN1: UInt32 = 0x20
    public static let CTRLC_CPTEN1_LSB: UInt32 = 5
    public static let DBGCTRL_DBGRUN: UInt32 = 0x1
    public static let DBGCTRL_DBGRUN_LSB: UInt32 = 0
    public static let INTFLAG_OVF: UInt32 = 0x1
    public static let INTFLAG_OVF_LSB: UInt32 = 0
    public static let INTFLAG_ERR: UInt32 = 0x2
    public static let INTFLAG_ERR_LSB: UInt32 = 1
    public static let INTFLAG_SYNCRDY: UInt32 = 0x8
    public static let INTFLAG_SYNCRDY_LSB: UInt32 = 3
    public static let INTFLAG_MC0: UInt32 = 0x10
    public static let INTFLAG_MC0_LSB: UInt32 = 4
    public static let INTFLAG_MC1: UInt32 = 0x20
    public static let INTFLAG_MC1_LSB: UInt32 = 5
    public static let STATUS_STOP: UInt32 = 0x8
    public static let STATUS_STOP_LSB: UInt32 = 3
    public static let STATUS_SLAVE: UInt32 = 0x10
    public static let STATUS_SLAVE_LSB: UInt32 = 4
    public static let STATUS_SYNCBUSY: UInt32 = 0x80
    public static let STATUS_SYNCBUSY_LSB: UInt32 = 7
    public static let COUNT_COUNT: UInt32 = 0xFF
    public static let COUNT_COUNT_LSB: UInt32 = 0
    public static let PER_PER: UInt32 = 0xFF
    public static let PER_PER_LSB: UInt32 = 0
    public static let CC0_CC: UInt32 = 0xFF
    public static let CC0_CC_LSB: UInt32 = 0
    public static let CC1_CC: UInt32 = 0xFF
    public static let CC1_CC_LSB: UInt32 = 0

    // -- block constants --
    public static let MODE_COUNT16: UInt32 = 0
    public static let MODE_COUNT8: UInt32 = 1
    public static let MODE_COUNT32: UInt32 = 2
    public static let WAVEGEN_NFRQ: UInt32 = 0
    public static let WAVEGEN_MFRQ: UInt32 = 1
    public static let WAVEGEN_NPWM: UInt32 = 2
    public static let WAVEGEN_MPWM: UInt32 = 3
    public static let PRESCALER_DIV1: UInt32 = 0
    public static let PRESCALER_DIV2: UInt32 = 1
    public static let PRESCALER_DIV4: UInt32 = 2
    public static let PRESCALER_DIV8: UInt32 = 3
    public static let PRESCALER_DIV16: UInt32 = 4
    public static let PRESCALER_DIV64: UInt32 = 5
    public static let PRESCALER_DIV256: UInt32 = 6
    public static let PRESCALER_DIV1024: UInt32 = 7
    public static let PRESCSYNC_GCLK: UInt32 = 0
    public static let PRESCSYNC_PRESC: UInt32 = 1
    public static let PRESCSYNC_RESYNC: UInt32 = 2
    public static let CMD_NONE: UInt32 = 0
    public static let CMD_RETRIGGER: UInt32 = 1
    public static let CMD_STOP: UInt32 = 2
    public static let CC_STRIDE: UInt32 = 1

    /// The division PRESCALER code `code` selects, from the PRESCALER_DIV constants above, or 0
    /// for a code none of them names.
    public static func prescalerDivisor(_ code: UInt32) -> UInt32 {
        switch code {
        case 0: return 1
        case 1: return 2
        case 2: return 4
        case 3: return 8
        case 4: return 16
        case 5: return 64
        case 6: return 256
        case 7: return 1024
        default: return 0
        }
    }

    // -- facts as data (chip/electrical facts conversions read) --
    public static let CounterBits: UInt32 = 8
}
