# GENERATED by lamella-bsp-gen from bsp/arduino-due/board.toml + csp/sam3x/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam3x

BOARD = "due"
BOARD_MODEL = 15
BOARD_VENDOR = "Arduino"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
VCP = "vcp"

CARRIER = {
    "kind": "uart",
    "role": "vcp",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
    "vcp": {
        "kind": "uart",
        "driver_family": "sam3x-uart",
        "instance": "uart",
        "base": 0x400E0800,
        "pid": 8,
        "pmc_pcer_reg": 0x400E0610,
        "pmc_pcer_mask": 0x100,
        "pio_pdr_reg": 0x400E0E04,
        "pio_absr_reg": 0x400E0E70,
        "pio_mask": 0x300,
        "pio_func": 0,
        "mck_hz": 84000000,
        "brgr_cd_115200_plla_84mhz": 46,
    },
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Bases only: register offsets and bit encodings belong to the driver that knows the block.
INSTANCES = {
    "uart": {"block": "uart", "base": 0x400E0800, "pid": 0x8},
    "pmc": {"block": "pmc", "base": 0x400E0600},
    "pioa": {"block": "pio", "base": 0x400E0E00, "pid": 0xB},
}

PLANS = {
    "plla-84mhz": {"default": True, "source": "xtal", "xtal_hz": 12000000, "mck_hz": 84000000},
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
}
