# GENERATED by lamella-bsp-gen from bsp/arduino-due/board.toml + csp/sam3x/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam3x

BOARD = "due"
BOARD_MODEL = 15
BOARD_VENDOR = "Arduino"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.
VCP = "vcp"

CARRIER = {
    "kind": "uart",
    "role": "vcp",
}

# Per-role descriptor dicts: the same values the C# DueBindings class carries as consts,
# under one mechanical renaming rule -- an UPPER_SNAKE const there is a lowercase key here,
# grouped by the role it belongs to.
FACTS = {
    "vcp": {
        "kind": "uart",
        "instance": "uart",
        "base": 0x400E0800,
        "pid": 8,
        "pmc_pcer_reg": 0x400E0610,
        "pmc_pcer_mask": 0x100,
        "pio_pdr_reg": 0x400E0E04,
        "pio_absr_reg": 0x400E0E70,
        "pio_mask": 0x300,
        "pio_func": 0,
        "mck_hz": 84000000,
        "brgr_cd_115200_plla_84mhz": 46,
    },
}

PLANS = {
    "plla-84mhz": {"default": True, "source": "xtal", "xtal_hz": 12000000, "mck_hz": 84000000},
}

# On-board devices + module control lines (the C# <NAME>_PORT_BASE/_PIN/_MASK/
# _ACTIVE_LOW consts, dict-shaped): PORT group base + pin index + mask + polarity.
DEVICES = {
}
