//! GENERATED by lamella-bsp-gen from bsp/stm32f429i-disco/board.toml + csp/stm32f42x/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32f42x

pub const BOARD_MODEL: u16 = 21;
pub const BOARD_VENDOR: &str = "St";

/// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
/// role's `KIND` says what the application asked for -- a uart, an spi -- and two
/// peripherals of the same kind can share no register at all, so a consumer that selects a
/// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
/// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
/// name a driver; and a uart is a different register map on every family, so the kind does
/// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
pub const VCP_DRIVER_FAMILY: &str = "stm32f42x-usart";
pub const MEMS_SPI_DRIVER_FAMILY: &str = "stm32f42x-spi";

pub const VCP_BASE: u32 = 0x40011000;
pub const VCP_RCC_EN_REG: u32 = 0x40023844;
pub const VCP_RCC_EN_MASK: u32 = 0x10;
pub const VCP_TX_PORT_RCC_EN_REG: u32 = 0x40023830;
pub const VCP_TX_PORT_RCC_EN_MASK: u32 = 0x1;
pub const VCP_TX_MODER_REG: u32 = 0x40020000;
pub const VCP_TX_MODER_MASK: u32 = 0xC0000;
pub const VCP_TX_MODER_VALUE: u32 = 0x80000;
pub const VCP_TX_AFR_REG: u32 = 0x40020024;
pub const VCP_TX_AFR_MASK: u32 = 0xF0;
pub const VCP_TX_AFR_VALUE: u32 = 0x70;
pub const VCP_RX_PORT_RCC_EN_REG: u32 = 0x40023830;
pub const VCP_RX_PORT_RCC_EN_MASK: u32 = 0x1;
pub const VCP_RX_MODER_REG: u32 = 0x40020000;
pub const VCP_RX_MODER_MASK: u32 = 0x300000;
pub const VCP_RX_MODER_VALUE: u32 = 0x200000;
pub const VCP_RX_AFR_REG: u32 = 0x40020024;
pub const VCP_RX_AFR_MASK: u32 = 0xF00;
pub const VCP_RX_AFR_VALUE: u32 = 0x700;
pub const VCP_PCLK_HZ: u32 = 16000000;
pub const VCP_BRR_115200_HSI_16MHZ: u32 = 0x8B;

pub const MEMS_SPI_BASE: u32 = 0x40015000;
pub const MEMS_SPI_RCC_EN_REG: u32 = 0x40023844;
pub const MEMS_SPI_RCC_EN_MASK: u32 = 0x100000;
pub const MEMS_SPI_SCK_PORT_RCC_EN_REG: u32 = 0x40023830;
pub const MEMS_SPI_SCK_PORT_RCC_EN_MASK: u32 = 0x20;
pub const MEMS_SPI_SCK_MODER_REG: u32 = 0x40021400;
pub const MEMS_SPI_SCK_MODER_MASK: u32 = 0xC000;
pub const MEMS_SPI_SCK_MODER_VALUE: u32 = 0x8000;
pub const MEMS_SPI_SCK_AFR_REG: u32 = 0x40021420;
pub const MEMS_SPI_SCK_AFR_MASK: u32 = 0xF0000000;
pub const MEMS_SPI_SCK_AFR_VALUE: u32 = 0x50000000;
pub const MEMS_SPI_MISO_PORT_RCC_EN_REG: u32 = 0x40023830;
pub const MEMS_SPI_MISO_PORT_RCC_EN_MASK: u32 = 0x20;
pub const MEMS_SPI_MISO_MODER_REG: u32 = 0x40021400;
pub const MEMS_SPI_MISO_MODER_MASK: u32 = 0x30000;
pub const MEMS_SPI_MISO_MODER_VALUE: u32 = 0x20000;
pub const MEMS_SPI_MISO_AFR_REG: u32 = 0x40021424;
pub const MEMS_SPI_MISO_AFR_MASK: u32 = 0xF;
pub const MEMS_SPI_MISO_AFR_VALUE: u32 = 0x5;
pub const MEMS_SPI_MOSI_PORT_RCC_EN_REG: u32 = 0x40023830;
pub const MEMS_SPI_MOSI_PORT_RCC_EN_MASK: u32 = 0x20;
pub const MEMS_SPI_MOSI_MODER_REG: u32 = 0x40021400;
pub const MEMS_SPI_MOSI_MODER_MASK: u32 = 0xC0000;
pub const MEMS_SPI_MOSI_MODER_VALUE: u32 = 0x80000;
pub const MEMS_SPI_MOSI_AFR_REG: u32 = 0x40021424;
pub const MEMS_SPI_MOSI_AFR_MASK: u32 = 0xF0;
pub const MEMS_SPI_MOSI_AFR_VALUE: u32 = 0x50;
pub const MEMS_SPI_CS_PORT_RCC_EN_REG: u32 = 0x40023830;
pub const MEMS_SPI_CS_PORT_RCC_EN_MASK: u32 = 0x4;
pub const MEMS_SPI_CS_MODER_REG: u32 = 0x40020800;
pub const MEMS_SPI_CS_MODER_MASK: u32 = 0xC;
pub const MEMS_SPI_CS_MODER_VALUE: u32 = 0x4;
pub const MEMS_SPI_CS_BSRR_REG: u32 = 0x40020818;
pub const MEMS_SPI_CS_BSRR_SET: u32 = 0x2;
pub const MEMS_SPI_CS_BSRR_CLEAR: u32 = 0x20000;
pub const MEMS_SPI_PCLK_HZ: u32 = 16000000;

pub const LED_GREEN_PORT_BASE: u32 = 0x40021800;
pub const LED_GREEN_PIN: u32 = 13;
pub const LED_GREEN_MASK: u32 = 0x2000;
pub const LED_GREEN_ACTIVE_LOW: u32 = 0;
pub const LED_RED_PORT_BASE: u32 = 0x40021800;
pub const LED_RED_PIN: u32 = 14;
pub const LED_RED_MASK: u32 = 0x4000;
pub const LED_RED_ACTIVE_LOW: u32 = 0;
pub const BUTTON_PORT_BASE: u32 = 0x40020000;
pub const BUTTON_PIN: u32 = 0;
pub const BUTTON_MASK: u32 = 0x1;
pub const BUTTON_ACTIVE_LOW: u32 = 0;

/// -- memory regions the board fits: SIZE is what a program may reach, which a device's own
/// size may exceed; a region with a CONTROLLER does not exist until that instance is brought
/// up, and touching it first is a bus fault rather than a wrong value --
pub const MEMORY_REGION_COUNT: u32 = 1;
pub const MEMORY_SDRAM_KIND: &str = "ram";
pub const MEMORY_SDRAM_BASE: u32 = 0xD0000000;
pub const MEMORY_SDRAM_SIZE: u32 = 0x800000;
pub const MEMORY_SDRAM_CONTROLLER: &str = "fmc";
pub const MEMORY_SDRAM_OPTIONAL: u32 = 1;

/// -- the SDRAM fitted to 'sdram': the shape its controller has to be told. The geometry and
/// the two sizes above are one fact stated twice and are checked against each other --
/// rows x columns x banks x width IS the size, and a column count off by one halves the
/// memory, aliases every address above the first row, and passes a write-then-read --
pub const MEMORY_SDRAM_BANK: u32 = 2;
pub const MEMORY_SDRAM_SDCR1: u32 = 0x1800;
pub const MEMORY_SDRAM_SDCR2: u32 = 0x154;
pub const MEMORY_SDRAM_SDCMR_CLOCK_ENABLE: u32 = 0x9;
pub const MEMORY_SDRAM_SDCMR_PRECHARGE_ALL: u32 = 0xA;
pub const MEMORY_SDRAM_SDCMR_AUTO_REFRESH: u32 = 0xEB;
pub const MEMORY_SDRAM_SDCMR_LOAD_MODE: u32 = 0x4400C;
pub const MEMORY_SDRAM_SETTLE_US: u32 = 100;

/// -- and the numbers that are NOT constants of anything. Each is derived from a formula
/// that is the CHIP's, a specification that is the DEVICE's, and a clock that is this PLAN's
/// -- write any one of the three down and it is wrong at the other two's next value. They
/// carry the plan's name for that reason. The timings round UP, because a timing is a floor:
/// a cycle short is a violation and a cycle long is only throughput --
pub const MEMORY_SDRAM_SDCLK_HZ_HSI_16MHZ: u32 = 8000000;
pub const MEMORY_SDRAM_REFRESH_COUNT_HSI_16MHZ: u32 = 105;
pub const MEMORY_SDRAM_SDRTR_HSI_16MHZ: u32 = 0xD2;
pub const MEMORY_SDRAM_SDTR1_HSI_16MHZ: u32 = 0x106000;
pub const MEMORY_SDRAM_SDTR2_HSI_16MHZ: u32 = 0x1020361;
