//! GENERATED by lamella-bsp-gen from bsp/arduino-opta-wifi/board.toml + csp/stm32h7/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . stm32h7
//!
//! The arduino-opta-wifi board bindings as Rust consts, name/value-identical to ArduinoOptaWifiBindings.g.cs:
//! every value below is a generation-time literal derived from the strata.
//! The board's facts are stated in board.toml.

// -- identity --
pub const BOARD_MODEL: u16 = 43;
pub const BOARD_VENDOR: &str = "Arduino";
pub const DEVICE_COUNT: u32 = 6;

// -- on-board devices: PORT group base + pin index + mask --
pub const RELAY_1_PORT_BASE: u32 = 0x58022000;
pub const RELAY_1_PIN: u32 = 6;
pub const RELAY_1_MASK: u32 = 0x40;
pub const RELAY_1_ACTIVE_LOW: u32 = 0;
pub const RELAY_2_PORT_BASE: u32 = 0x58022000;
pub const RELAY_2_PIN: u32 = 5;
pub const RELAY_2_MASK: u32 = 0x20;
pub const RELAY_2_ACTIVE_LOW: u32 = 0;
pub const RELAY_3_PORT_BASE: u32 = 0x58022000;
pub const RELAY_3_PIN: u32 = 7;
pub const RELAY_3_MASK: u32 = 0x80;
pub const RELAY_3_ACTIVE_LOW: u32 = 0;
pub const RELAY_4_PORT_BASE: u32 = 0x58022000;
pub const RELAY_4_PIN: u32 = 4;
pub const RELAY_4_MASK: u32 = 0x10;
pub const RELAY_4_ACTIVE_LOW: u32 = 0;
pub const USER_BUTTON_PORT_BASE: u32 = 0x58021000;
pub const USER_BUTTON_PIN: u32 = 4;
pub const USER_BUTTON_MASK: u32 = 0x10;
pub const USER_BUTTON_ACTIVE_LOW: u32 = 1;
pub const USER_LED_PORT_BASE: u32 = 0x58021000;
pub const USER_LED_PIN: u32 = 5;
pub const USER_LED_MASK: u32 = 0x20;
