// GENERATED by lamella-bsp-gen from csp/rp2350/blocks/io-bank0.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//
// The rp2350 io-bank0 block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2350Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Rp2350IoBank0Layout
    {
        private Rp2350IoBank0Layout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint GPIO0_CTRL_OFF = 0x4;
        public const int GPIO0_CTRL_WIDTH = 32;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
        public const uint GPIO0_CTRL_FUNCSEL = 0x1F;
        public const uint GPIO0_CTRL_FUNCSEL_LSB = 0;

        // -- block constants --
        public const uint GPIO_CTRL_STRIDE = 8;
        public const uint FUNCSEL_SPI = 1;
        public const uint FUNCSEL_UART = 2;
        public const uint FUNCSEL_I2C = 3;
        public const uint FUNCSEL_SIO = 5;
        public const uint FUNCSEL_NULL = 0x1F;
    }
}
