// GENERATED by lamella-bsp-gen from csp/rp2350/blocks/ticks.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//
// The rp2350 ticks block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2350Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Rp2350TicksLayout
    {
        private Rp2350TicksLayout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint TIMER0_CTRL_OFF = 0x18;
        public const int TIMER0_CTRL_WIDTH = 32;
        public const uint TIMER0_CYCLES_OFF = 0x1C;
        public const int TIMER0_CYCLES_WIDTH = 32;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
        public const uint TIMER0_CTRL_ENABLE = 0x1;
        public const uint TIMER0_CTRL_ENABLE_LSB = 0;
        public const uint TIMER0_CTRL_RUNNING = 0x2;
        public const uint TIMER0_CTRL_RUNNING_LSB = 1;
        public const uint TIMER0_CYCLES_CYCLES = 0x1FF;
        public const uint TIMER0_CYCLES_CYCLES_LSB = 0;
    }
}
