// GENERATED by lamella-bsp-gen from csp/rp2350/blocks/timer.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//
// The rp2350 timer block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2350Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Rp2350TimerLayout
    {
        private Rp2350TimerLayout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint TIMERAWH_OFF = 0x24;
        public const int TIMERAWH_WIDTH = 32;
        public const uint TIMERAWL_OFF = 0x28;
        public const int TIMERAWL_WIDTH = 32;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    }
}
