//! GENERATED by lamella-bsp-gen from csp/nrf51/blocks/gpio.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . nrf51

/// -- register offsets (block-relative) + access widths --
pub const OUT_OFF: u32 = 0x504;
pub const OUT_WIDTH: i32 = 32;
pub const OUTSET_OFF: u32 = 0x508;
pub const OUTSET_WIDTH: i32 = 32;
pub const OUTCLR_OFF: u32 = 0x50C;
pub const OUTCLR_WIDTH: i32 = 32;
pub const IN_OFF: u32 = 0x510;
pub const IN_WIDTH: i32 = 32;
pub const DIR_OFF: u32 = 0x514;
pub const DIR_WIDTH: i32 = 32;
pub const DIRSET_OFF: u32 = 0x518;
pub const DIRSET_WIDTH: i32 = 32;
pub const DIRCLR_OFF: u32 = 0x51C;
pub const DIRCLR_WIDTH: i32 = 32;
pub const PIN_CNF0_OFF: u32 = 0x700;
pub const PIN_CNF0_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const PIN_CNF0_DIR: u32 = 0x1;
pub const PIN_CNF0_DIR_LSB: u32 = 0;
pub const PIN_CNF0_INPUT: u32 = 0x2;
pub const PIN_CNF0_INPUT_LSB: u32 = 1;
pub const PIN_CNF0_PULL: u32 = 0xC;
pub const PIN_CNF0_PULL_LSB: u32 = 2;
pub const PIN_CNF0_DRIVE: u32 = 0x700;
pub const PIN_CNF0_DRIVE_LSB: u32 = 8;
pub const PIN_CNF0_SENSE: u32 = 0x30000;
pub const PIN_CNF0_SENSE_LSB: u32 = 16;

/// -- block constants --
pub const PIN_CNF_STRIDE: u32 = 4;
