//! GENERATED by lamella-bsp-gen from csp/nrf51/blocks/clock.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . nrf51
//!
//! The nrf51 clock block layout as Rust consts: offsets are instance-base-relative
//! (`base + *_OFF`) and the instance bases live in nrf51_instances.rs. Widths are access widths.
//! Its block table's `emit` list leaves C# out, so no C# layout of it exists.

/// -- register offsets (block-relative) + access widths --
pub const TASKS_HFCLKSTART_OFF: u32 = 0x0;
pub const TASKS_HFCLKSTART_WIDTH: i32 = 32;
pub const TASKS_HFCLKSTOP_OFF: u32 = 0x4;
pub const TASKS_HFCLKSTOP_WIDTH: i32 = 32;
pub const TASKS_LFCLKSTART_OFF: u32 = 0x8;
pub const TASKS_LFCLKSTART_WIDTH: i32 = 32;
pub const TASKS_LFCLKSTOP_OFF: u32 = 0xC;
pub const TASKS_LFCLKSTOP_WIDTH: i32 = 32;
pub const TASKS_CAL_OFF: u32 = 0x10;
pub const TASKS_CAL_WIDTH: i32 = 32;
pub const TASKS_CTSTART_OFF: u32 = 0x14;
pub const TASKS_CTSTART_WIDTH: i32 = 32;
pub const TASKS_CTSTOP_OFF: u32 = 0x18;
pub const TASKS_CTSTOP_WIDTH: i32 = 32;
pub const EVENTS_HFCLKSTARTED_OFF: u32 = 0x100;
pub const EVENTS_HFCLKSTARTED_WIDTH: i32 = 32;
pub const EVENTS_LFCLKSTARTED_OFF: u32 = 0x104;
pub const EVENTS_LFCLKSTARTED_WIDTH: i32 = 32;
pub const EVENTS_DONE_OFF: u32 = 0x10C;
pub const EVENTS_DONE_WIDTH: i32 = 32;
pub const EVENTS_CTTO_OFF: u32 = 0x110;
pub const EVENTS_CTTO_WIDTH: i32 = 32;
pub const INTENSET_OFF: u32 = 0x304;
pub const INTENSET_WIDTH: i32 = 32;
pub const INTENCLR_OFF: u32 = 0x308;
pub const INTENCLR_WIDTH: i32 = 32;
pub const HFCLKRUN_OFF: u32 = 0x408;
pub const HFCLKRUN_WIDTH: i32 = 32;
pub const HFCLKSTAT_OFF: u32 = 0x40C;
pub const HFCLKSTAT_WIDTH: i32 = 32;
pub const LFCLKRUN_OFF: u32 = 0x414;
pub const LFCLKRUN_WIDTH: i32 = 32;
pub const LFCLKSTAT_OFF: u32 = 0x418;
pub const LFCLKSTAT_WIDTH: i32 = 32;
pub const LFCLKSRCCOPY_OFF: u32 = 0x41C;
pub const LFCLKSRCCOPY_WIDTH: i32 = 32;
pub const LFCLKSRC_OFF: u32 = 0x518;
pub const LFCLKSRC_WIDTH: i32 = 32;
pub const CTIV_OFF: u32 = 0x538;
pub const CTIV_WIDTH: i32 = 32;
pub const XTALFREQ_OFF: u32 = 0x550;
pub const XTALFREQ_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const TASKS_HFCLKSTART_TASKS_HFCLKSTART: u32 = 0x1;
pub const TASKS_HFCLKSTART_TASKS_HFCLKSTART_LSB: u32 = 0;
pub const TASKS_HFCLKSTOP_TASKS_HFCLKSTOP: u32 = 0x1;
pub const TASKS_HFCLKSTOP_TASKS_HFCLKSTOP_LSB: u32 = 0;
pub const TASKS_LFCLKSTART_TASKS_LFCLKSTART: u32 = 0x1;
pub const TASKS_LFCLKSTART_TASKS_LFCLKSTART_LSB: u32 = 0;
pub const TASKS_LFCLKSTOP_TASKS_LFCLKSTOP: u32 = 0x1;
pub const TASKS_LFCLKSTOP_TASKS_LFCLKSTOP_LSB: u32 = 0;
pub const TASKS_CAL_TASKS_CAL: u32 = 0x1;
pub const TASKS_CAL_TASKS_CAL_LSB: u32 = 0;
pub const TASKS_CTSTART_TASKS_CTSTART: u32 = 0x1;
pub const TASKS_CTSTART_TASKS_CTSTART_LSB: u32 = 0;
pub const TASKS_CTSTOP_TASKS_CTSTOP: u32 = 0x1;
pub const TASKS_CTSTOP_TASKS_CTSTOP_LSB: u32 = 0;
pub const EVENTS_HFCLKSTARTED_EVENTS_HFCLKSTARTED: u32 = 0x1;
pub const EVENTS_HFCLKSTARTED_EVENTS_HFCLKSTARTED_LSB: u32 = 0;
pub const EVENTS_LFCLKSTARTED_EVENTS_LFCLKSTARTED: u32 = 0x1;
pub const EVENTS_LFCLKSTARTED_EVENTS_LFCLKSTARTED_LSB: u32 = 0;
pub const EVENTS_DONE_EVENTS_DONE: u32 = 0x1;
pub const EVENTS_DONE_EVENTS_DONE_LSB: u32 = 0;
pub const EVENTS_CTTO_EVENTS_CTTO: u32 = 0x1;
pub const EVENTS_CTTO_EVENTS_CTTO_LSB: u32 = 0;
pub const INTENSET_HFCLKSTARTED: u32 = 0x1;
pub const INTENSET_HFCLKSTARTED_LSB: u32 = 0;
pub const INTENSET_LFCLKSTARTED: u32 = 0x2;
pub const INTENSET_LFCLKSTARTED_LSB: u32 = 1;
pub const INTENSET_DONE: u32 = 0x8;
pub const INTENSET_DONE_LSB: u32 = 3;
pub const INTENSET_CTTO: u32 = 0x10;
pub const INTENSET_CTTO_LSB: u32 = 4;
pub const INTENCLR_HFCLKSTARTED: u32 = 0x1;
pub const INTENCLR_HFCLKSTARTED_LSB: u32 = 0;
pub const INTENCLR_LFCLKSTARTED: u32 = 0x2;
pub const INTENCLR_LFCLKSTARTED_LSB: u32 = 1;
pub const INTENCLR_DONE: u32 = 0x8;
pub const INTENCLR_DONE_LSB: u32 = 3;
pub const INTENCLR_CTTO: u32 = 0x10;
pub const INTENCLR_CTTO_LSB: u32 = 4;
pub const HFCLKRUN_STATUS: u32 = 0x1;
pub const HFCLKRUN_STATUS_LSB: u32 = 0;
pub const HFCLKSTAT_SRC: u32 = 0x1;
pub const HFCLKSTAT_SRC_LSB: u32 = 0;
pub const HFCLKSTAT_STATE: u32 = 0x10000;
pub const HFCLKSTAT_STATE_LSB: u32 = 16;
pub const LFCLKRUN_STATUS: u32 = 0x1;
pub const LFCLKRUN_STATUS_LSB: u32 = 0;
pub const LFCLKSTAT_SRC: u32 = 0x3;
pub const LFCLKSTAT_SRC_LSB: u32 = 0;
pub const LFCLKSTAT_STATE: u32 = 0x10000;
pub const LFCLKSTAT_STATE_LSB: u32 = 16;
pub const LFCLKSRCCOPY_SRC: u32 = 0x3;
pub const LFCLKSRCCOPY_SRC_LSB: u32 = 0;
pub const LFCLKSRC_SRC: u32 = 0x3;
pub const LFCLKSRC_SRC_LSB: u32 = 0;
pub const CTIV_CTIV: u32 = 0x7F;
pub const CTIV_CTIV_LSB: u32 = 0;
pub const XTALFREQ_XTALFREQ: u32 = 0xFF;
pub const XTALFREQ_XTALFREQ_LSB: u32 = 0;

/// -- block constants --
pub const HFCLKSTAT_SRC_RC: u32 = 0;
pub const HFCLKSTAT_SRC_XTAL: u32 = 1;
pub const LFCLKSRC_RC: u32 = 0;
pub const LFCLKSRC_XTAL: u32 = 1;
pub const LFCLKSRC_SYNTH: u32 = 2;
pub const XTALFREQ_16MHZ: u32 = 0xFF;
pub const XTALFREQ_32MHZ: u32 = 0x0;
pub const HCLK_HZ: u32 = 16000000;
