//! GENERATED by lamella-bsp-gen from csp/ra4m1/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ra4m1
//!
//! The ra4m1 instance map as Rust consts, name/value-identical to Ra4m1Instances.g.cs:
//! where each block copy sits and its per-instance ids. Each block's layout is in its own
//! layout module beside this file.

pub const PORT0_BASE: u32 = 0x40040000;
pub const PORT1_BASE: u32 = 0x40040020;
