//! GENERATED by lamella-bsp-gen from csp/ra4m1/instances.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ra4m1

pub const PORT0_BASE: u32 = 0x40040000;
pub const PORT1_BASE: u32 = 0x40040020;
