//! GENERATED by lamella-bsp-gen from csp/ra4m1/blocks/port.toml -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ra4m1

/// -- register offsets (block-relative) + access widths --
pub const PCNTR1_OFF: u32 = 0x0;
pub const PCNTR1_WIDTH: i32 = 32;
pub const PCNTR2_OFF: u32 = 0x4;
pub const PCNTR2_WIDTH: i32 = 32;
pub const PCNTR3_OFF: u32 = 0x8;
pub const PCNTR3_WIDTH: i32 = 32;
pub const PCNTR4_OFF: u32 = 0xC;
pub const PCNTR4_WIDTH: i32 = 32;

/// -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
pub const PCNTR1_PDR11: u32 = 0x800;
pub const PCNTR1_PDR11_LSB: u32 = 11;
pub const PCNTR1_PDR12: u32 = 0x1000;
pub const PCNTR1_PDR12_LSB: u32 = 12;
pub const PCNTR1_PDR13: u32 = 0x2000;
pub const PCNTR1_PDR13_LSB: u32 = 13;
pub const PCNTR1_PODR11: u32 = 0x8000000;
pub const PCNTR1_PODR11_LSB: u32 = 27;
pub const PCNTR1_PODR12: u32 = 0x10000000;
pub const PCNTR1_PODR12_LSB: u32 = 28;
pub const PCNTR1_PODR13: u32 = 0x20000000;
pub const PCNTR1_PODR13_LSB: u32 = 29;
pub const PCNTR3_POSR11: u32 = 0x800;
pub const PCNTR3_POSR11_LSB: u32 = 11;
pub const PCNTR3_POSR12: u32 = 0x1000;
pub const PCNTR3_POSR12_LSB: u32 = 12;
pub const PCNTR3_POSR13: u32 = 0x2000;
pub const PCNTR3_POSR13_LSB: u32 = 13;
pub const PCNTR3_PORR11: u32 = 0x8000000;
pub const PCNTR3_PORR11_LSB: u32 = 27;
pub const PCNTR3_PORR12: u32 = 0x10000000;
pub const PCNTR3_PORR12_LSB: u32 = 28;
pub const PCNTR3_PORR13: u32 = 0x20000000;
pub const PCNTR3_PORR13_LSB: u32 = 29;

/// -- block constants --
pub const PDR_OUTPUT: u32 = 1;
pub const PODR_HIGH: u32 = 1;
