// GENERATED by lamella-bsp-gen from bsp/arduino-uno-r4-minima/board.toml + csp/ra4m1/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class ArduinoUnoR4MinimaBindings
    {
        private ArduinoUnoR4MinimaBindings() { }

        public const int BOARD_MODEL = 34;
        public const string BOARD_VENDOR = "Arduino";

        public const uint LED0_PORT_BASE = 0x40040020;
        public const uint LED0_PIN = 11;
        public const uint LED0_MASK = 0x800;
        public const uint LED0_ACTIVE_LOW = 0;
        public const uint LED_TX_PORT_BASE = 0x40040000;
        public const uint LED_TX_PIN = 12;
        public const uint LED_TX_MASK = 0x1000;
        public const uint LED_TX_ACTIVE_LOW = 1;
        public const uint LED_RX_PORT_BASE = 0x40040000;
        public const uint LED_RX_PIN = 13;
        public const uint LED_RX_MASK = 0x2000;
        public const uint LED_RX_ACTIVE_LOW = 1;
    }
}
