// GENERATED by lamella-bsp-gen from bsp/microbit-v2/board.toml + csp/nrf52833/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class MicrobitV2Bindings
    {
        private MicrobitV2Bindings() { }

        public const int BOARD_MODEL = 11;

        public const uint INTERNAL_I2C_TWI_BASE = 0x40003000;
        public const uint INTERNAL_I2C_PSEL_SCL = 0x8;
        public const uint INTERNAL_I2C_PSEL_SDA = 0x10;
        public const uint INTERNAL_I2C_PIN_CNF_SCL_REG = 0x50000720;
        public const uint INTERNAL_I2C_PIN_CNF_SDA_REG = 0x50000740;

        public const uint LSM303AGR_ADDRESS = 0x19;
        public const uint LSM303AGR_MAG_ADDRESS = 0x1E;
        public const uint DISPLAY_ROW1_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW1_PIN = 21;
        public const uint DISPLAY_ROW1_MASK = 0x200000;
        public const uint DISPLAY_ROW1_ACTIVE_LOW = 0;
        public const uint DISPLAY_ROW2_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW2_PIN = 22;
        public const uint DISPLAY_ROW2_MASK = 0x400000;
        public const uint DISPLAY_ROW2_ACTIVE_LOW = 0;
        public const uint DISPLAY_ROW3_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW3_PIN = 15;
        public const uint DISPLAY_ROW3_MASK = 0x8000;
        public const uint DISPLAY_ROW3_ACTIVE_LOW = 0;
        public const uint DISPLAY_ROW4_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW4_PIN = 24;
        public const uint DISPLAY_ROW4_MASK = 0x1000000;
        public const uint DISPLAY_ROW4_ACTIVE_LOW = 0;
        public const uint DISPLAY_ROW5_PORT_BASE = 0x50000000;
        public const uint DISPLAY_ROW5_PIN = 19;
        public const uint DISPLAY_ROW5_MASK = 0x80000;
        public const uint DISPLAY_ROW5_ACTIVE_LOW = 0;
        public const uint DISPLAY_COL1_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL1_PIN = 28;
        public const uint DISPLAY_COL1_MASK = 0x10000000;
        public const uint DISPLAY_COL1_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL2_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL2_PIN = 11;
        public const uint DISPLAY_COL2_MASK = 0x800;
        public const uint DISPLAY_COL2_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL3_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL3_PIN = 31;
        public const uint DISPLAY_COL3_MASK = 0x80000000;
        public const uint DISPLAY_COL3_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL4_PORT_BASE = 0x50000300;
        public const uint DISPLAY_COL4_PIN = 5;
        public const uint DISPLAY_COL4_MASK = 0x20;
        public const uint DISPLAY_COL4_ACTIVE_LOW = 1;
        public const uint DISPLAY_COL5_PORT_BASE = 0x50000000;
        public const uint DISPLAY_COL5_PIN = 30;
        public const uint DISPLAY_COL5_MASK = 0x40000000;
        public const uint DISPLAY_COL5_ACTIVE_LOW = 1;
    }
}
