// GENERATED by lamella-bsp-gen from csp/same54/pins.toml + csp/same54/blocks/port.toml + csp/same54/blocks/eic.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . same54
//
// The same54 external interrupt line each pad raises, with the same constants as Same54Pins.g.cs and
// the lookup spelled `extIntLine`. A pad raises its line only while its multiplexer selects the
// EIC function.

public enum Same54Pins {
    /// Returned by `extIntLine` for a pad that raises no external interrupt.
    public static let EXTINT_NONE: Int32 = -1
    /// Returned by `extIntLine` for the pad whose EIC function is the non-maskable interrupt,
    /// which is not one of the external interrupt lines.
    public static let EXTINT_NMI: Int32 = -2
    /// The PMUX function value that selects the EIC on every pad `extIntLine` answers for.
    public static let EXTINT_FUNCTION: UInt32 = 0

    /// The external interrupt line a pad raises while its PMUX selects `EXTINT_FUNCTION`: a line
    /// below `Same54EicLayout.LINE_COUNT`, `EXTINT_NMI`, or `EXTINT_NONE`. `group` is the PORT group,
    /// 0 for PA, 1 for PB, 2 for PC, 3 for PD; `index` is the pad's index within its group.
    public static func extIntLine(group: UInt32, index: UInt32) -> Int32 {
        switch (group, index) {
        case (0, 0): return 0
        case (0, 1): return 1
        case (0, 2): return 2
        case (0, 3): return 3
        case (0, 4): return 4
        case (0, 5): return 5
        case (0, 6): return 6
        case (0, 7): return 7
        case (0, 8): return EXTINT_NMI
        case (0, 9): return 9
        case (0, 10): return 10
        case (0, 11): return 11
        case (0, 12): return 12
        case (0, 13): return 13
        case (0, 14): return 14
        case (0, 15): return 15
        case (0, 16): return 0
        case (0, 17): return 1
        case (0, 18): return 2
        case (0, 19): return 3
        case (0, 20): return 4
        case (0, 21): return 5
        case (0, 22): return 6
        case (0, 23): return 7
        case (0, 24): return 8
        case (0, 25): return 9
        case (0, 27): return 11
        case (0, 30): return 14
        case (0, 31): return 15
        case (1, 0): return 0
        case (1, 1): return 1
        case (1, 2): return 2
        case (1, 3): return 3
        case (1, 4): return 4
        case (1, 5): return 5
        case (1, 6): return 6
        case (1, 7): return 7
        case (1, 8): return 8
        case (1, 9): return 9
        case (1, 10): return 10
        case (1, 11): return 11
        case (1, 12): return 12
        case (1, 13): return 13
        case (1, 14): return 14
        case (1, 15): return 15
        case (1, 16): return 0
        case (1, 17): return 1
        case (1, 18): return 2
        case (1, 19): return 3
        case (1, 20): return 4
        case (1, 21): return 5
        case (1, 22): return 6
        case (1, 23): return 7
        case (1, 24): return 8
        case (1, 25): return 9
        case (1, 26): return 12
        case (1, 27): return 13
        case (1, 28): return 14
        case (1, 29): return 15
        case (1, 30): return 14
        case (1, 31): return 15
        case (2, 0): return 0
        case (2, 1): return 1
        case (2, 2): return 2
        case (2, 3): return 3
        case (2, 4): return 4
        case (2, 5): return 5
        case (2, 6): return 6
        case (2, 7): return 9
        case (2, 10): return 10
        case (2, 11): return 11
        case (2, 12): return 12
        case (2, 13): return 13
        case (2, 14): return 14
        case (2, 15): return 15
        case (2, 16): return 0
        case (2, 17): return 1
        case (2, 18): return 2
        case (2, 19): return 3
        case (2, 20): return 4
        case (2, 21): return 5
        case (2, 22): return 6
        case (2, 23): return 7
        case (2, 24): return 8
        case (2, 25): return 9
        case (2, 26): return 10
        case (2, 27): return 11
        case (2, 28): return 12
        case (2, 30): return 14
        case (2, 31): return 15
        case (3, 0): return 0
        case (3, 1): return 1
        case (3, 8): return 3
        case (3, 9): return 4
        case (3, 10): return 5
        case (3, 11): return 6
        case (3, 12): return 7
        case (3, 20): return 10
        case (3, 21): return 11
        default: return EXTINT_NONE
        }
    }
}
