// GENERATED by lamella-bsp-gen from csp/same54/blocks/mclk.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . same54
//
// The same54 mclk block layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Same54Instances. Widths are access widths.
namespace Lamella.Generated
{
    public sealed class Same54MclkLayout
    {
        private Same54MclkLayout() { }

        // -- register offsets (block-relative) + access widths --
        public const uint INTENCLR_OFF = 0x1;
        public const int INTENCLR_WIDTH = 8;
        public const uint INTENSET_OFF = 0x2;
        public const int INTENSET_WIDTH = 8;
        public const uint INTFLAG_OFF = 0x3;
        public const int INTFLAG_WIDTH = 8;
        public const uint HSDIV_OFF = 0x4;
        public const int HSDIV_WIDTH = 8;
        public const uint CPUDIV_OFF = 0x5;
        public const int CPUDIV_WIDTH = 8;
        public const uint AHBMASK_OFF = 0x10;
        public const int AHBMASK_WIDTH = 32;
        public const uint APBAMASK_OFF = 0x14;
        public const int APBAMASK_WIDTH = 32;
        public const uint APBBMASK_OFF = 0x18;
        public const int APBBMASK_WIDTH = 32;
        public const uint APBCMASK_OFF = 0x1C;
        public const int APBCMASK_WIDTH = 32;
        public const uint APBDMASK_OFF = 0x20;
        public const int APBDMASK_WIDTH = 32;

        // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
        public const uint INTENCLR_CKRDY = 0x1;
        public const uint INTENCLR_CKRDY_LSB = 0;
        public const uint INTENSET_CKRDY = 0x1;
        public const uint INTENSET_CKRDY_LSB = 0;
        public const uint INTFLAG_CKRDY = 0x1;
        public const uint INTFLAG_CKRDY_LSB = 0;
        public const uint HSDIV_DIV = 0xFF;
        public const uint HSDIV_DIV_LSB = 0;
        public const uint CPUDIV_DIV = 0xFF;
        public const uint CPUDIV_DIV_LSB = 0;
    }
}
