// GENERATED by lamella-bsp-gen from csp/stm32l0/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32l0Instances
    {
        private Stm32l0Instances() { }

        public const uint GPIOA_BASE = 0x50000000;
        public const uint GPIOA_RCC_EN_OFF = 44;
        public const uint GPIOA_RCC_EN_BIT = 0;
        public const uint GPIOA_RCC_EN_MASK = 0x1;
        public const uint GPIOB_BASE = 0x50000400;
        public const uint GPIOB_RCC_EN_OFF = 44;
        public const uint GPIOB_RCC_EN_BIT = 1;
        public const uint GPIOB_RCC_EN_MASK = 0x2;
        public const uint GPIOC_BASE = 0x50000800;
        public const uint GPIOC_RCC_EN_OFF = 44;
        public const uint GPIOC_RCC_EN_BIT = 2;
        public const uint GPIOC_RCC_EN_MASK = 0x4;
        public const uint USART2_BASE = 0x40004400;
        public const uint USART2_RCC_EN_OFF = 56;
        public const uint USART2_RCC_EN_BIT = 17;
        public const uint USART2_RCC_EN_MASK = 0x20000;
        public const uint LPUART1_BASE = 0x40004800;
        public const uint LPUART1_RCC_EN_OFF = 56;
        public const uint LPUART1_RCC_EN_BIT = 18;
        public const uint LPUART1_RCC_EN_MASK = 0x40000;
        public const uint SPI1_BASE = 0x40013000;
        public const uint SPI1_RCC_EN_OFF = 52;
        public const uint SPI1_RCC_EN_BIT = 12;
        public const uint SPI1_RCC_EN_MASK = 0x1000;
        public const uint RCC_BASE = 0x40021000;
    }
}
