// GENERATED by lamella-bsp-gen from bsp/arduino-mkr1000/board.toml + csp/samw25/module.toml + csp/samd21/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Mkr1000Bindings
    {
        private Mkr1000Bindings() { }

        public const int BOARD_MODEL = 9;
        public const string BOARD_VENDOR = "Arduino";

        /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
        /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
        /// peripherals of the same kind can share no register at all, so a consumer that selects a
        /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
        /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
        /// name a driver; and a uart is a different register map on every family, so the kind does
        /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
        public const string WINC_SPI_DRIVER_FAMILY = "samd21-sercom";

        public const uint WINC_SPI_SERCOM_BASE = 0x42001000;
        public const uint WINC_SPI_IRQ = 11;
        public const uint WINC_SPI_APBC_MASK = 0x10;
        public const uint WINC_SPI_GCLK_CORE_ID = 22;
        public const uint WINC_SPI_PMUX_MOSI_REG = 0x41004436;
        public const uint WINC_SPI_PMUX_MOSI_SHIFT = 0;
        public const uint WINC_SPI_PINCFG_MOSI_REG = 0x4100444C;
        public const uint WINC_SPI_PMUX_SCK_REG = 0x41004436;
        public const uint WINC_SPI_PMUX_SCK_SHIFT = 4;
        public const uint WINC_SPI_PINCFG_SCK_REG = 0x4100444D;
        public const uint WINC_SPI_PMUX_MISO_REG = 0x41004437;
        public const uint WINC_SPI_PMUX_MISO_SHIFT = 4;
        public const uint WINC_SPI_PINCFG_MISO_REG = 0x4100444F;
        public const uint WINC_SPI_PMUX_FUNC = 2;
        public const uint WINC_SPI_DOPO = 0;
        public const uint WINC_SPI_DIPO = 3;
        public const uint WINC_SPI_CS_PORT_BASE = 0x41004400;
        public const uint WINC_SPI_CS_PIN = 14;
        public const uint WINC_SPI_CS_MASK = 0x4000;

        public const uint WINC_RESET_N_PORT_BASE = 0x41004400;
        public const uint WINC_RESET_N_PIN = 27;
        public const uint WINC_RESET_N_MASK = 0x8000000;
        public const uint WINC_RESET_N_ACTIVE_LOW = 1;
        public const uint WINC_CHIP_EN_PORT_BASE = 0x41004400;
        public const uint WINC_CHIP_EN_PIN = 28;
        public const uint WINC_CHIP_EN_MASK = 0x10000000;
        public const uint WINC_CHIP_EN_ACTIVE_LOW = 0;
        public const uint WINC_IRQN_PORT_BASE = 0x41004480;
        public const uint WINC_IRQN_PIN = 9;
        public const uint WINC_IRQN_MASK = 0x200;
        public const uint WINC_IRQN_ACTIVE_LOW = 1;
    }
}
