//! GENERATED by lamella-bsp-gen from bsp/arduino-uno-r4-minima/board.toml + csp/ra4m1/ strata -- DO NOT EDIT.
//! Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ra4m1

pub const BOARD_MODEL: u16 = 34;
pub const BOARD_VENDOR: &str = "Arduino";

pub const LED0_PORT_BASE: u32 = 0x40040020;
pub const LED0_PIN: u32 = 11;
pub const LED0_MASK: u32 = 0x800;
pub const LED0_ACTIVE_LOW: u32 = 0;
pub const LED_TX_PORT_BASE: u32 = 0x40040000;
pub const LED_TX_PIN: u32 = 12;
pub const LED_TX_MASK: u32 = 0x1000;
pub const LED_TX_ACTIVE_LOW: u32 = 1;
pub const LED_RX_PORT_BASE: u32 = 0x40040000;
pub const LED_RX_PIN: u32 = 13;
pub const LED_RX_MASK: u32 = 0x2000;
pub const LED_RX_ACTIVE_LOW: u32 = 1;
