// GENERATED by lamella-bsp-gen from csp/rp2040/blocks/pads-bank0.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040
//
// The rp2040 pads-bank0 BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2040Instances. Widths are access widths.

public enum Rp2040PadsBank0Layout {
    // -- register offsets (block-relative) + access widths --
    public static let GPIO0_OFF: UInt32 = 0x4
    public static let GPIO0_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let GPIO0_SLEWFAST: UInt32 = 0x1
    public static let GPIO0_SLEWFAST_LSB: UInt32 = 0
    public static let GPIO0_SCHMITT: UInt32 = 0x2
    public static let GPIO0_SCHMITT_LSB: UInt32 = 1
    public static let GPIO0_PDE: UInt32 = 0x4
    public static let GPIO0_PDE_LSB: UInt32 = 2
    public static let GPIO0_PUE: UInt32 = 0x8
    public static let GPIO0_PUE_LSB: UInt32 = 3
    public static let GPIO0_DRIVE: UInt32 = 0x30
    public static let GPIO0_DRIVE_LSB: UInt32 = 4
    public static let GPIO0_IE: UInt32 = 0x40
    public static let GPIO0_IE_LSB: UInt32 = 6
    public static let GPIO0_OD: UInt32 = 0x80
    public static let GPIO0_OD_LSB: UInt32 = 7

    // -- block constants --
    public static let GPIO_STRIDE: UInt32 = 4
}
