// GENERATED by lamella-bsp-gen from csp/rp2040/blocks/resets.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040
//
// The rp2040 resets BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2040Instances. Widths are access widths.

public enum Rp2040ResetsLayout {
    // -- register offsets (block-relative) + access widths --
    public static let RESET_OFF: UInt32 = 0x0
    public static let RESET_WIDTH: Int32 = 32
    public static let RESET_DONE_OFF: UInt32 = 0x8
    public static let RESET_DONE_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
}
