// GENERATED by lamella-bsp-gen from csp/rp2040/blocks/io-bank0.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2040
//
// The rp2040 io-bank0 BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2040Instances. Widths are access widths.

public enum Rp2040IoBank0Layout {
    // -- register offsets (block-relative) + access widths --
    public static let GPIO0_CTRL_OFF: UInt32 = 0x4
    public static let GPIO0_CTRL_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let GPIO0_CTRL_FUNCSEL: UInt32 = 0x1F
    public static let GPIO0_CTRL_FUNCSEL_LSB: UInt32 = 0

    // -- block constants --
    public static let GPIO_CTRL_STRIDE: UInt32 = 8
    public static let FUNCSEL_UART: UInt32 = 2
}
