// GENERATED by lamella-bsp-gen from bsp/sam4e-xpro/board.toml + csp/sam4e/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Sam4eXproBindings
    {
        private Sam4eXproBindings() { }

        public const int BOARD_MODEL = 26;
        public const string BOARD_VENDOR = "Atmel";

        public const uint LED0_PORT_BASE = 0x400E1400;
        public const uint LED0_PIN = 22;
        public const uint LED0_MASK = 0x400000;
        public const uint LED0_ACTIVE_LOW = 1;
        public const uint BUTTON0_PORT_BASE = 0x400E0E00;
        public const uint BUTTON0_PIN = 2;
        public const uint BUTTON0_MASK = 0x4;
        public const uint BUTTON0_ACTIVE_LOW = 1;
    }
}
