// GENERATED by lamella-bsp-gen from bsp/adafruit-feather-m0-express/board.toml + csp/samd21/ strata -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . samd21
//
// The adafruit-feather-m0-express board bindings as Swift constants, name/value-identical to AdafruitFeatherM0ExpressBindings.g.cs:
// every value below is a generation-time literal derived from the strata. The board's
// facts are stated in board.toml.

public enum AdafruitFeatherM0ExpressBindings {
    // -- identity --
    public static let BOARD_MODEL: UInt16 = 16
    public static let BOARD_VENDOR: String = "Adafruit"
    public static let DEVICE_COUNT: UInt32 = 2

    // -- on-board devices: PORT group base + pin index + mask --
    public static let LED_PORT_BASE: UInt32 = 0x41004400
    public static let LED_PIN: UInt32 = 17
    public static let LED_BANK: UInt32 = 0
    public static let LED_MASK: UInt32 = 0x20000
    public static let LED_ACTIVE_LOW: UInt32 = 0
    public static let NEOPIXEL_PORT_BASE: UInt32 = 0x41004400
    public static let NEOPIXEL_PIN: UInt32 = 6
    public static let NEOPIXEL_BANK: UInt32 = 0
    public static let NEOPIXEL_MASK: UInt32 = 0x40
    public static let NEOPIXEL_ACTIVE_LOW: UInt32 = 0
}
