// GENERATED by lamella-bsp-gen from csp/ch32v003/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . ch32v003
//
// The ch32v003 instance map: where each block copy sits and its per-instance ids.
// Layout offsets live in the *Layout classes; wiring lives in the per-board *Bindings.
namespace Lamella.Generated
{
    public sealed class Ch32v003Instances
    {
        private Ch32v003Instances() { }

        public const uint RCC_BASE = 0x40021000;
        public const uint GPIOA_BASE = 0x40010800;
        public const uint GPIOC_BASE = 0x40011000;
        public const uint GPIOD_BASE = 0x40011400;
    }
}
