// GENERATED by lamella-bsp-gen from csp/ch32v003/blocks/flash.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Ch32v003FlashLayout
    {
        private Ch32v003FlashLayout() { }



        public const uint ERASED_VALUE = 0xFFFFFFFF;
        public const uint WRITE_UNIT = 64;
    }
}
