# GENERATED by lamella-bsp-gen from bsp/sam4s-xpro/board.toml + csp/sam4s/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4s

BOARD = "sam4s-xpro"
BOARD_MODEL = 3
BOARD_VENDOR = "Microchip"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.

CARRIER = {
    "kind": "edbg-vcp",
}

# Per-role descriptor dicts, grouped by the role each belongs to.
# Emitted from this board's facts, like every other language's support for it:
# an UPPER_SNAKE name in the shared facts is a lowercase key here.
#
# "kind" and "driver_family" are read TOGETHER and neither answers alone: kind is what the
# application asked for -- a uart, an spi -- and driver_family is which REGISTER MAP is behind
# it, as <chip family>-<block>. One SERCOM block serves uart, spi and i2c, so the block does not
# name a driver; a uart is a different register map on every family, so the kind does not either.
FACTS = {
}

# The chip's instance map: every block this family places, with its base address and
# the block layout it follows. A role descriptor above states a PERIPHERAL; a bring-up also
# touches blocks that belong to the chip rather than to any one role -- an oscillator, a clock
# controller, a reset controller -- and those are one per chip, so they are stated once here.
# Bases only: register offsets and bit encodings belong to the driver that knows the block.
INSTANCES = {
    "uart1": {"block": "uart", "base": 0x400E0800, "pid": 0x9},
    "pmc": {"block": "pmc", "base": 0x400E0400},
    "pioa": {"block": "pio", "base": 0x400E0E00, "pid": 0xB},
    "piob": {"block": "pio", "base": 0x400E1000, "pid": 0xC},
    "pioc": {"block": "pio", "base": 0x400E1200, "pid": 0xD},
    "eefc0": {"block": "eefc", "base": 0x400E0A00},
    "eefc1": {"block": "eefc", "base": 0x400E0C00},
}

PLANS = {
}

# On-board devices + module control lines: PORT group base + pin index + mask + polarity.
# Emitted from this board's facts; each supported language states the same set in its
# own idiom.
DEVICES = {
}
