# GENERATED by lamella-bsp-gen from bsp/sam4s-xpro/board.toml + csp/sam4s/ strata -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-family . sam4s

BOARD = "sam4s-xpro"
BOARD_MODEL = 3
BOARD_VENDOR = "Microchip"

# Role handles: the ONLY peripheral names an app sees. The value of a
# role handle is its role-id string; the runtime resolves role -> facts through FACTS
# below, never through a surface-private enum.

CARRIER = {
    "kind": "edbg-vcp",
}

# Per-role descriptor dicts: the same values the C# Sam4sXproBindings class carries as consts,
# under one mechanical renaming rule -- an UPPER_SNAKE const there is a lowercase key here,
# grouped by the role it belongs to.
FACTS = {
}

PLANS = {
}

# On-board devices + module control lines (the C# <NAME>_PORT_BASE/_PIN/_MASK/
# _ACTIVE_LOW consts, dict-shaped): PORT group base + pin index + mask + polarity.
DEVICES = {
}
