// GENERATED by lamella-bsp-gen from csp/samc21/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Samc21Instances
    {
        private Samc21Instances() { }

        public const uint SERCOM0_BASE = 0x42000400;
        public const uint SERCOM0_GCLK_CORE_ID = 19;
        public const uint SERCOM0_APB_MASK_OFFSET = 28;
        public const uint SERCOM0_APB_BIT = 1;
        public const uint SERCOM0_APB_MASK = 0x2;
        public const uint SERCOM0_IRQ = 9;
        public const uint SERCOM1_BASE = 0x42000800;
        public const uint SERCOM1_GCLK_CORE_ID = 20;
        public const uint SERCOM1_APB_MASK_OFFSET = 28;
        public const uint SERCOM1_APB_BIT = 2;
        public const uint SERCOM1_APB_MASK = 0x4;
        public const uint SERCOM1_IRQ = 10;
        public const uint SERCOM2_BASE = 0x42000C00;
        public const uint SERCOM2_GCLK_CORE_ID = 21;
        public const uint SERCOM2_APB_MASK_OFFSET = 28;
        public const uint SERCOM2_APB_BIT = 3;
        public const uint SERCOM2_APB_MASK = 0x8;
        public const uint SERCOM2_IRQ = 11;
        public const uint SERCOM3_BASE = 0x42001000;
        public const uint SERCOM3_GCLK_CORE_ID = 22;
        public const uint SERCOM3_APB_MASK_OFFSET = 28;
        public const uint SERCOM3_APB_BIT = 4;
        public const uint SERCOM3_APB_MASK = 0x10;
        public const uint SERCOM3_IRQ = 12;
        public const uint SERCOM4_BASE = 0x42001400;
        public const uint SERCOM4_GCLK_CORE_ID = 23;
        public const uint SERCOM4_APB_MASK_OFFSET = 28;
        public const uint SERCOM4_APB_BIT = 5;
        public const uint SERCOM4_APB_MASK = 0x20;
        public const uint SERCOM4_IRQ = 13;
        public const uint SERCOM5_BASE = 0x42001800;
        public const uint SERCOM5_GCLK_CORE_ID = 25;
        public const uint SERCOM5_APB_MASK_OFFSET = 28;
        public const uint SERCOM5_APB_BIT = 6;
        public const uint SERCOM5_APB_MASK = 0x40;
        public const uint SERCOM5_IRQ = 14;
        public const uint SERCOM6_BASE = 0x43000000;
        public const uint SERCOM6_GCLK_CORE_ID = 41;
        public const uint SERCOM6_APB_MASK_OFFSET = 32;
        public const uint SERCOM6_APB_BIT = 0;
        public const uint SERCOM6_APB_MASK = 0x1;
        public const uint SERCOM6_IRQ = 9;
        public const uint SERCOM7_BASE = 0x43000400;
        public const uint SERCOM7_GCLK_CORE_ID = 42;
        public const uint SERCOM7_APB_MASK_OFFSET = 32;
        public const uint SERCOM7_APB_BIT = 1;
        public const uint SERCOM7_APB_MASK = 0x2;
        public const uint SERCOM7_IRQ = 10;
        public const uint MCLK_BASE = 0x40000800;
        public const uint GCLK_BASE = 0x40001C00;
        public const uint PORTA_BASE = 0x41000000;
        public const uint PORTB_BASE = 0x41000080;
        public const uint PORTC_BASE = 0x41000100;
    }
}
