// GENERATED by lamella-bsp-gen from csp/stm32f7/instances.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32f7Instances
    {
        private Stm32f7Instances() { }

        public const uint USART1_BASE = 0x40011000;
        public const uint USART1_RCC_EN_OFF = 68;
        public const uint USART1_RCC_EN_BIT = 4;
        public const uint USART1_RCC_EN_MASK = 0x10;
        public const uint GPIOA_BASE = 0x40020000;
        public const uint GPIOA_RCC_EN_OFF = 48;
        public const uint GPIOA_RCC_EN_BIT = 0;
        public const uint GPIOA_RCC_EN_MASK = 0x1;
        public const uint GPIOB_BASE = 0x40020400;
        public const uint GPIOB_RCC_EN_OFF = 48;
        public const uint GPIOB_RCC_EN_BIT = 1;
        public const uint GPIOB_RCC_EN_MASK = 0x2;
        public const uint GPIOC_BASE = 0x40020800;
        public const uint GPIOC_RCC_EN_OFF = 48;
        public const uint GPIOC_RCC_EN_BIT = 2;
        public const uint GPIOC_RCC_EN_MASK = 0x4;
        public const uint GPIOD_BASE = 0x40020C00;
        public const uint GPIOD_RCC_EN_OFF = 48;
        public const uint GPIOD_RCC_EN_BIT = 3;
        public const uint GPIOD_RCC_EN_MASK = 0x8;
        public const uint GPIOE_BASE = 0x40021000;
        public const uint GPIOE_RCC_EN_OFF = 48;
        public const uint GPIOE_RCC_EN_BIT = 4;
        public const uint GPIOE_RCC_EN_MASK = 0x10;
        public const uint GPIOF_BASE = 0x40021400;
        public const uint GPIOF_RCC_EN_OFF = 48;
        public const uint GPIOF_RCC_EN_BIT = 5;
        public const uint GPIOF_RCC_EN_MASK = 0x20;
        public const uint GPIOG_BASE = 0x40021800;
        public const uint GPIOG_RCC_EN_OFF = 48;
        public const uint GPIOG_RCC_EN_BIT = 6;
        public const uint GPIOG_RCC_EN_MASK = 0x40;
        public const uint GPIOH_BASE = 0x40021C00;
        public const uint GPIOH_RCC_EN_OFF = 48;
        public const uint GPIOH_RCC_EN_BIT = 7;
        public const uint GPIOH_RCC_EN_MASK = 0x80;
        public const uint RCC_BASE = 0x40023800;
        public const uint I2C1_BASE = 0x40005400;
        public const uint I2C1_RCC_EN_OFF = 64;
        public const uint I2C1_RCC_EN_BIT = 21;
        public const uint I2C1_RCC_EN_MASK = 0x200000;
        public const uint I2C3_BASE = 0x40005C00;
        public const uint I2C3_RCC_EN_OFF = 64;
        public const uint I2C3_RCC_EN_BIT = 23;
        public const uint I2C3_RCC_EN_MASK = 0x800000;
        public const uint FMC_BASE = 0xA0000000;
        public const uint FMC_RCC_EN_OFF = 56;
        public const uint FMC_RCC_EN_BIT = 0;
        public const uint FMC_RCC_EN_MASK = 0x1;
        public const uint QUADSPI_BASE = 0xA0001000;
        public const uint QUADSPI_RCC_EN_OFF = 56;
        public const uint QUADSPI_RCC_EN_BIT = 1;
        public const uint QUADSPI_RCC_EN_MASK = 0x2;
    }
}
