// GENERATED by lamella-bsp-gen from csp/stm32f7/blocks/usart.toml -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class Stm32f7UsartLayout
    {
        private Stm32f7UsartLayout() { }

        public const uint CR1_OFF = 0x0;
        public const int CR1_WIDTH = 32;
        public const uint CR2_OFF = 0x4;
        public const int CR2_WIDTH = 32;
        public const uint CR3_OFF = 0x8;
        public const int CR3_WIDTH = 32;
        public const uint BRR_OFF = 0xC;
        public const int BRR_WIDTH = 32;
        public const uint ISR_OFF = 0x1C;
        public const int ISR_WIDTH = 32;
        public const uint ICR_OFF = 0x20;
        public const int ICR_WIDTH = 32;
        public const uint RDR_OFF = 0x24;
        public const int RDR_WIDTH = 32;
        public const uint TDR_OFF = 0x28;
        public const int TDR_WIDTH = 32;

        public const uint CR1_UE = 0x1;
        public const uint CR1_UE_LSB = 0;
        public const uint CR1_RE = 0x4;
        public const uint CR1_RE_LSB = 2;
        public const uint CR1_TE = 0x8;
        public const uint CR1_TE_LSB = 3;
        public const uint CR1_IDLEIE = 0x10;
        public const uint CR1_IDLEIE_LSB = 4;
        public const uint CR1_RXNEIE = 0x20;
        public const uint CR1_RXNEIE_LSB = 5;
        public const uint CR1_TCIE = 0x40;
        public const uint CR1_TCIE_LSB = 6;
        public const uint CR1_TXEIE = 0x80;
        public const uint CR1_TXEIE_LSB = 7;
        public const uint CR1_PEIE = 0x100;
        public const uint CR1_PEIE_LSB = 8;
        public const uint CR1_PS = 0x200;
        public const uint CR1_PS_LSB = 9;
        public const uint CR1_PCE = 0x400;
        public const uint CR1_PCE_LSB = 10;
        public const uint CR1_WAKE = 0x800;
        public const uint CR1_WAKE_LSB = 11;
        public const uint CR1_M0 = 0x1000;
        public const uint CR1_M0_LSB = 12;
        public const uint CR1_OVER8 = 0x8000;
        public const uint CR1_OVER8_LSB = 15;
        public const uint CR1_M1 = 0x10000000;
        public const uint CR1_M1_LSB = 28;
        public const uint CR2_STOP = 0x3000;
        public const uint CR2_STOP_LSB = 12;
        public const uint CR3_EIE = 0x1;
        public const uint CR3_EIE_LSB = 0;
        public const uint CR3_HDSEL = 0x8;
        public const uint CR3_HDSEL_LSB = 3;
        public const uint CR3_DMAR = 0x40;
        public const uint CR3_DMAR_LSB = 6;
        public const uint CR3_DMAT = 0x80;
        public const uint CR3_DMAT_LSB = 7;
        public const uint CR3_RTSE = 0x100;
        public const uint CR3_RTSE_LSB = 8;
        public const uint CR3_CTSE = 0x200;
        public const uint CR3_CTSE_LSB = 9;
        public const uint BRR_BRR = 0xFFFF;
        public const uint BRR_BRR_LSB = 0;
        public const uint ISR_PE = 0x1;
        public const uint ISR_PE_LSB = 0;
        public const uint ISR_FE = 0x2;
        public const uint ISR_FE_LSB = 1;
        public const uint ISR_NF = 0x4;
        public const uint ISR_NF_LSB = 2;
        public const uint ISR_ORE = 0x8;
        public const uint ISR_ORE_LSB = 3;
        public const uint ISR_IDLE = 0x10;
        public const uint ISR_IDLE_LSB = 4;
        public const uint ISR_RXNE = 0x20;
        public const uint ISR_RXNE_LSB = 5;
        public const uint ISR_TC = 0x40;
        public const uint ISR_TC_LSB = 6;
        public const uint ISR_TXE = 0x80;
        public const uint ISR_TXE_LSB = 7;
        public const uint ISR_BUSY = 0x10000;
        public const uint ISR_BUSY_LSB = 16;
        public const uint ISR_TEACK = 0x200000;
        public const uint ISR_TEACK_LSB = 21;
        public const uint ISR_REACK = 0x400000;
        public const uint ISR_REACK_LSB = 22;
        public const uint ICR_PECF = 0x1;
        public const uint ICR_PECF_LSB = 0;
        public const uint ICR_FECF = 0x2;
        public const uint ICR_FECF_LSB = 1;
        public const uint ICR_NCF = 0x4;
        public const uint ICR_NCF_LSB = 2;
        public const uint ICR_ORECF = 0x8;
        public const uint ICR_ORECF_LSB = 3;
        public const uint ICR_IDLECF = 0x10;
        public const uint ICR_IDLECF_LSB = 4;
        public const uint ICR_TCCF = 0x40;
        public const uint ICR_TCCF_LSB = 6;
        public const uint RDR_RDR = 0x1FF;
        public const uint RDR_RDR_LSB = 0;
        public const uint TDR_TDR = 0x1FF;
        public const uint TDR_TDR_LSB = 0;
    }
}
