# GENERATED by lamella-bsp-gen from parts/bmx280/bmp280.toml + parts/bmx280/bmx280.toml -- DO NOT EDIT.
# Regenerate: cargo run -p lamella-bsp-gen -- gen-parts . bmx280
#
# The bmp280 part table, FLATTENED: every value it inherited is spelled out here, because a
# value that is only ever inherited is pinned in no emitted artifact and so cannot be
# checked for drift between languages. A part is something we talk TO rather than a chip
# we run on -- a board states which buses exist, this table states the part's identity,
# and a probe joins the two at run time.
PART = "bmp280"
FAMILY = "bmx280"

# identity: the accepted values are a SET. A driver that accepts only one of them rejects a genuine part, and a rejected part reads as no part at all -- so on a mismatch, name the id received AND this set.
IDENTITY_REG = 0xD0
IDENTITY_WIDTH = 8
IDENTITY_VALUE_COUNT = 3
IDENTITY_VALUE_0 = 0x56
IDENTITY_VALUE_1 = 0x57
IDENTITY_VALUE_2 = 0x58

# address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
ADDRESS_BUS = "i2c"
ADDRESS_BASE = 0x76
ADDRESS_STRAP_COUNT = 1
ADDRESS_STRAP_SDO_BIT = 0
ADDRESS_STRAP_SDO_LOW = 0x76
ADDRESS_STRAP_SDO_HIGH = 0x77

# buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
BUS_COUNT = 2
BUS_I2C_KIND = "i2c"
BUS_I2C_REGISTER_READ_TRANSFORM = "identity"
BUS_I2C_REGISTER_WRITE_TRANSFORM = "identity"
BUS_I2C_READ_PROTOCOL = "write-register-then-repeated-start-read"
BUS_SPI_KIND = "spi"
BUS_SPI_REGISTER_READ_TRANSFORM = "set-bit7"
BUS_SPI_REGISTER_WRITE_TRANSFORM = "clear-bit7"
BUS_SPI_READ_PROTOCOL = "single-chip-select-address-then-clock-data"
BUS_SPI_MODE_COUNT = 2
BUS_SPI_MODE_0 = 0
BUS_SPI_MODE_1 = 3

# registers: `_REG` is the address written on the wire -- an operand, NOT an offset to add to an instance base. Fields carry the shifted mask and its shift.
ID_REG = 0xD0
ID_WIDTH = 8
ID_ACCESS = "read-only"
ID_CHIP_ID = 0xFF
ID_CHIP_ID_LSB = 0
RESET_REG = 0xE0
RESET_WIDTH = 8
RESET_ACCESS = "write-only"
RESET_RESET = 0xFF
RESET_RESET_LSB = 0
STATUS_REG = 0xF3
STATUS_WIDTH = 8
STATUS_ACCESS = "read-only"
STATUS_IM_UPDATE = 0x1
STATUS_IM_UPDATE_LSB = 0
STATUS_MEASURING = 0x8
STATUS_MEASURING_LSB = 3
CTRL_MEAS_REG = 0xF4
CTRL_MEAS_WIDTH = 8
CTRL_MEAS_ACCESS = "read-write"
CTRL_MEAS_MODE = 0x3
CTRL_MEAS_MODE_LSB = 0
CTRL_MEAS_OSRS_P = 0x1C
CTRL_MEAS_OSRS_P_LSB = 2
CTRL_MEAS_OSRS_T = 0xE0
CTRL_MEAS_OSRS_T_LSB = 5
CONFIG_REG = 0xF5
CONFIG_WIDTH = 8
CONFIG_ACCESS = "read-write"
CONFIG_SPI3W_EN = 0x1
CONFIG_SPI3W_EN_LSB = 0
CONFIG_FILTER = 0x1C
CONFIG_FILTER_LSB = 2
CONFIG_T_SB = 0xE0
CONFIG_T_SB_LSB = 5
PRESS_REG = 0xF7
PRESS_WIDTH = 24
PRESS_ACCESS = "read-only"
PRESS_PRESS_MSB = 0xFF0000
PRESS_PRESS_MSB_LSB = 16
PRESS_PRESS_LSB = 0xFF00
PRESS_PRESS_LSB_LSB = 8
PRESS_PRESS_XLSB = 0xF0
PRESS_PRESS_XLSB_LSB = 4
TEMP_REG = 0xFA
TEMP_WIDTH = 24
TEMP_ACCESS = "read-only"
TEMP_TEMP_MSB = 0xFF0000
TEMP_TEMP_MSB_LSB = 16
TEMP_TEMP_LSB = 0xFF00
TEMP_TEMP_LSB_LSB = 8
TEMP_TEMP_XLSB = 0xF0
TEMP_TEMP_XLSB_LSB = 4

# encodings: the codes a field takes, as this part reads them.
OVERSAMPLING_SKIPPED = 0
OVERSAMPLING_X1 = 1
OVERSAMPLING_X2 = 2
OVERSAMPLING_X4 = 3
OVERSAMPLING_X8 = 4
OVERSAMPLING_X16 = 5
MODE_SLEEP = 0
MODE_FORCED = 1
MODE_NORMAL = 3
FILTER_OFF = 0
FILTER_X2 = 1
FILTER_X4 = 2
FILTER_X8 = 3
FILTER_X16 = 4
RESET_COMMAND_SOFT_RESET = 0xB6
STANDBY_US_0 = 500
STANDBY_US_1 = 62500
STANDBY_US_2 = 125000
STANDBY_US_3 = 250000
STANDBY_US_4 = 500000
STANDBY_US_5 = 1000000
STANDBY_US_6 = 2000000
STANDBY_US_7 = 4000000

# measurement: the part holds a whole data block steady for the duration of one burst, so a byte-at-a-time read can mix two conversions.
BURST_LENGTH = 6

# calibration 'temperature': these parameters are READ from the part and are per-device -- they are not constants and must not be baked into a driver. `_FORM` selects hand-written per-language arithmetic; signedness is not uniform, and reading it backwards yields a plausible wrong answer rather than an error.
TEMPERATURE_FORM = "bmx280-t-int32"
TEMPERATURE_BYTE_ORDER = "little"
TEMPERATURE_OUTPUT_SCALE = "centi-degrees-celsius"
TEMPERATURE_READ_COUNT = 3
TEMPERATURE_DIG_T1_REG = 0x88
TEMPERATURE_DIG_T1_WIDTH = 16
TEMPERATURE_DIG_T1_SIGNED = 0
TEMPERATURE_DIG_T2_REG = 0x8A
TEMPERATURE_DIG_T2_WIDTH = 16
TEMPERATURE_DIG_T2_SIGNED = 1
TEMPERATURE_DIG_T3_REG = 0x8C
TEMPERATURE_DIG_T3_WIDTH = 16
TEMPERATURE_DIG_T3_SIGNED = 1

# calibration 'pressure': these parameters are READ from the part and are per-device -- they are not constants and must not be baked into a driver. `_FORM` selects hand-written per-language arithmetic; signedness is not uniform, and reading it backwards yields a plausible wrong answer rather than an error.
PRESSURE_FORM = "bmx280-p-int64"
PRESSURE_BYTE_ORDER = "little"
PRESSURE_OUTPUT_SCALE = "q24.8-pascals"
PRESSURE_DEPENDS_ON_COUNT = 1
PRESSURE_DEPENDS_ON_0 = "temperature"
PRESSURE_READ_COUNT = 9
PRESSURE_DIG_P1_REG = 0x8E
PRESSURE_DIG_P1_WIDTH = 16
PRESSURE_DIG_P1_SIGNED = 0
PRESSURE_DIG_P2_REG = 0x90
PRESSURE_DIG_P2_WIDTH = 16
PRESSURE_DIG_P2_SIGNED = 1
PRESSURE_DIG_P3_REG = 0x92
PRESSURE_DIG_P3_WIDTH = 16
PRESSURE_DIG_P3_SIGNED = 1
PRESSURE_DIG_P4_REG = 0x94
PRESSURE_DIG_P4_WIDTH = 16
PRESSURE_DIG_P4_SIGNED = 1
PRESSURE_DIG_P5_REG = 0x96
PRESSURE_DIG_P5_WIDTH = 16
PRESSURE_DIG_P5_SIGNED = 1
PRESSURE_DIG_P6_REG = 0x98
PRESSURE_DIG_P6_WIDTH = 16
PRESSURE_DIG_P6_SIGNED = 1
PRESSURE_DIG_P7_REG = 0x9A
PRESSURE_DIG_P7_WIDTH = 16
PRESSURE_DIG_P7_SIGNED = 1
PRESSURE_DIG_P8_REG = 0x9C
PRESSURE_DIG_P8_WIDTH = 16
PRESSURE_DIG_P8_SIGNED = 1
PRESSURE_DIG_P9_REG = 0x9E
PRESSURE_DIG_P9_WIDTH = 16
PRESSURE_DIG_P9_SIGNED = 1

# sequence 'forced_measurement': declarative steps, resolved here so a step carries its own register and mask. The description is transport agnostic -- one step list describes an I2C transaction, an SPI one, and a call through a host import alike.
FORCED_MEASUREMENT_STEP_COUNT = 3
FORCED_MEASUREMENT_STEP_0_OP = "write-field"
FORCED_MEASUREMENT_STEP_0_TARGET = "ctrl_meas.mode"
FORCED_MEASUREMENT_STEP_0_REG = 0xF4
FORCED_MEASUREMENT_STEP_0_MASK = 0x3
FORCED_MEASUREMENT_STEP_0_LSB = 0
FORCED_MEASUREMENT_STEP_0_VALUE = 1
FORCED_MEASUREMENT_STEP_0_BOUNDED = 0
FORCED_MEASUREMENT_STEP_1_OP = "poll-field-until"
FORCED_MEASUREMENT_STEP_1_TARGET = "status.measuring"
FORCED_MEASUREMENT_STEP_1_REG = 0xF3
FORCED_MEASUREMENT_STEP_1_MASK = 0x8
FORCED_MEASUREMENT_STEP_1_LSB = 3
FORCED_MEASUREMENT_STEP_1_VALUE = 0
FORCED_MEASUREMENT_STEP_1_BOUNDED = 1
FORCED_MEASUREMENT_STEP_2_OP = "burst-read"
FORCED_MEASUREMENT_STEP_2_TARGET = "press"
FORCED_MEASUREMENT_STEP_2_REG = 0xF7
FORCED_MEASUREMENT_STEP_2_LENGTH = 6
FORCED_MEASUREMENT_STEP_2_BOUNDED = 0
