// GENERATED by lamella-bsp-gen from bsp/feather-m0-express/board.toml + csp/samd21/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class FeatherM0ExpressBindings
    {
        private FeatherM0ExpressBindings() { }

        public const int BOARD_MODEL = 16;

        public const uint LED_PORT_BASE = 0x41004400;
        public const uint LED_PIN = 17;
        public const uint LED_MASK = 0x20000;
        public const uint LED_ACTIVE_LOW = 0;
        public const uint NEOPIXEL_PORT_BASE = 0x41004400;
        public const uint NEOPIXEL_PIN = 6;
        public const uint NEOPIXEL_MASK = 0x40;
        public const uint NEOPIXEL_ACTIVE_LOW = 0;
    }
}
