// GENERATED by lamella-bsp-gen from bsp/adafruit-feather-m0-wifi/board.toml + csp/samd21/ strata -- DO NOT EDIT.
namespace Lamella.Generated
{
    public sealed class FeatherM0WifiBindings
    {
        private FeatherM0WifiBindings() { }

        public const int BOARD_MODEL = 17;
        public const string BOARD_VENDOR = "Adafruit";

        /// driver family: which REGISTER MAP is behind a role, as `<chip family>-<block>`. The
        /// role's `KIND` says what the application asked for -- a uart, an spi -- and two
        /// peripherals of the same kind can share no register at all, so a consumer that selects a
        /// driver at run time needs both: KIND is what was asked for, this is what the silicon is.
        /// Neither alone is enough. One SERCOM block serves uart, spi and i2c, so the block does not
        /// name a driver; and a uart is a different register map on every family, so the kind does
        /// not either. Derived from the bound instance's block, so it cannot be transcribed wrongly.
        public const string WINC_SPI_DRIVER_FAMILY = "samd21-sercom";

        public const uint WINC_SPI_SERCOM_BASE = 0x42001800;
        public const uint WINC_SPI_IRQ = 13;
        public const uint WINC_SPI_APBC_MASK = 0x40;
        public const uint WINC_SPI_GCLK_CORE_ID = 24;
        public const uint WINC_SPI_PMUX_MOSI_REG = 0x410044B5;
        public const uint WINC_SPI_PMUX_MOSI_SHIFT = 0;
        public const uint WINC_SPI_PINCFG_MOSI_REG = 0x410044CA;
        public const uint WINC_SPI_PMUX_SCK_REG = 0x410044B5;
        public const uint WINC_SPI_PMUX_SCK_SHIFT = 4;
        public const uint WINC_SPI_PINCFG_SCK_REG = 0x410044CB;
        public const uint WINC_SPI_PMUX_MISO_REG = 0x41004436;
        public const uint WINC_SPI_PMUX_MISO_SHIFT = 0;
        public const uint WINC_SPI_PINCFG_MISO_REG = 0x4100444C;
        public const uint WINC_SPI_PMUX_FUNC = 3;
        public const uint WINC_SPI_DOPO = 1;
        public const uint WINC_SPI_DIPO = 0;
        public const uint WINC_SPI_CS_PORT_BASE = 0x41004400;
        public const uint WINC_SPI_CS_PIN = 6;
        public const uint WINC_SPI_CS_MASK = 0x40;

        public const uint WINC_RESET_N_PORT_BASE = 0x41004400;
        public const uint WINC_RESET_N_PIN = 8;
        public const uint WINC_RESET_N_MASK = 0x100;
        public const uint WINC_RESET_N_ACTIVE_LOW = 1;
        public const uint WINC_CHIP_EN_PORT_BASE = 0x41004400;
        public const uint WINC_CHIP_EN_PIN = 14;
        public const uint WINC_CHIP_EN_MASK = 0x4000;
        public const uint WINC_CHIP_EN_ACTIVE_LOW = 0;
        public const uint WINC_IRQN_PORT_BASE = 0x41004400;
        public const uint WINC_IRQN_PIN = 21;
        public const uint WINC_IRQN_MASK = 0x200000;
        public const uint WINC_IRQN_ACTIVE_LOW = 1;
        public const uint LED_PORT_BASE = 0x41004400;
        public const uint LED_PIN = 17;
        public const uint LED_MASK = 0x20000;
        public const uint LED_ACTIVE_LOW = 0;
    }
}
