// GENERATED by lamella-bsp-gen from parts/bme68x/bme680.toml + parts/bme68x/bme68x.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-parts . bme68x
//
// The bme680 part table, FLATTENED: every value it inherited is spelled out here, because a
// value that is only ever inherited is pinned in no emitted artifact and so cannot be
// checked for drift between languages. A part is something we talk TO rather than a chip
// we run on -- a board states which buses exist, this table states the part's identity,
// and a probe joins the two at run time.

public enum Bme680Part {
    public static let PART: StaticString = "bme680"
    public static let FAMILY: StaticString = "bme68x"

    // sourcing: how far this part is established, on two INDEPENDENT axes -- a part can be strong on one and absent on the other, which is why they are not one rank. FACTS is `primary` (read from the part's own datasheet) or `secondary` (a primary vendor statement about this part carried by another document, named by DERIVED_FROM). VALIDATION is `none` (no physical part of this type has been made to answer), `identified` (one answered its identity register, against a negative control that tells the part from the wire) or `exercised` (one produced measurements a driver decoded). Anything above `none` states what was observed in EVIDENCE.
    public static let SOURCING_FACTS: StaticString = "primary"
    public static let SOURCING_VALIDATION: StaticString = "none"

    // identity: the accepted values are a SET. A driver that accepts only one of them rejects a genuine part, and a rejected part reads as no part at all -- so on a mismatch, name the id received AND this set.
    public static let IDENTITY_REG: UInt32 = 0xD0
    public static let IDENTITY_WIDTH: UInt32 = 8
    public static let IDENTITY_VALUE_COUNT: UInt32 = 1
    public static let IDENTITY_VALUE_0: UInt32 = 0x61

    // address: a base plus which pin contributes which bit. The part states the range; a carrier fixes the straps, so no strap is defaulted here.
    public static let ADDRESS_BUS: StaticString = "i2c"
    public static let ADDRESS_BASE: UInt32 = 0x76
    public static let ADDRESS_STRAP_COUNT: UInt32 = 1
    public static let ADDRESS_STRAP_SDO_BIT: UInt32 = 0
    public static let ADDRESS_STRAP_SDO_LOW: UInt32 = 0x76
    public static let ADDRESS_STRAP_SDO_HIGH: UInt32 = 0x77

    // buses: the register MAP is shared between a part's buses; the ADDRESS TRANSFORM is not, so each states its own as a named dispatch. A path that took the wrong one is wrong by a fixed bit, and on one direction only.
    public static let BUS_COUNT: UInt32 = 2
    public static let BUS_I2C_KIND: StaticString = "i2c"
    public static let BUS_I2C_REGISTER_READ_TRANSFORM: StaticString = "identity"
    public static let BUS_I2C_REGISTER_WRITE_TRANSFORM: StaticString = "identity"
    public static let BUS_I2C_READ_PROTOCOL: StaticString = "write-register-then-repeated-start-read"
    public static let BUS_SPI_KIND: StaticString = "spi"
    public static let BUS_SPI_REGISTER_READ_TRANSFORM: StaticString = "set-bit7"
    public static let BUS_SPI_REGISTER_WRITE_TRANSFORM: StaticString = "clear-bit7"
    public static let BUS_SPI_READ_PROTOCOL: StaticString = "single-chip-select-address-then-clock-data"
    public static let BUS_SPI_MODE_COUNT: UInt32 = 2
    public static let BUS_SPI_MODE_0: UInt32 = 0
    public static let BUS_SPI_MODE_1: UInt32 = 3

    // registers: `_REG` is the address written on the wire -- an operand, NOT an offset to add to an instance base. Fields carry the shifted mask and its shift.
    public static let ID_REG: UInt32 = 0xD0
    public static let ID_WIDTH: UInt32 = 8
    public static let ID_ACCESS: StaticString = "read-only"
    public static let ID_CHIP_ID: UInt32 = 0xFF
    public static let ID_CHIP_ID_LSB: UInt32 = 0
    public static let RESET_REG: UInt32 = 0xE0
    public static let RESET_WIDTH: UInt32 = 8
    public static let RESET_ACCESS: StaticString = "write-only"
    public static let RESET_RESET: UInt32 = 0xFF
    public static let RESET_RESET_LSB: UInt32 = 0
    public static let STATUS_REG: UInt32 = 0x73
    public static let STATUS_WIDTH: UInt32 = 8
    public static let STATUS_ACCESS: StaticString = "read-write"
    public static let STATUS_SPI_MEM_PAGE: UInt32 = 0x10
    public static let STATUS_SPI_MEM_PAGE_LSB: UInt32 = 4
    public static let CTRL_HUM_REG: UInt32 = 0x72
    public static let CTRL_HUM_WIDTH: UInt32 = 8
    public static let CTRL_HUM_ACCESS: StaticString = "read-write"
    public static let CTRL_HUM_OSRS_H: UInt32 = 0x7
    public static let CTRL_HUM_OSRS_H_LSB: UInt32 = 0
    public static let CTRL_HUM_SPI_3W_INT_EN: UInt32 = 0x40
    public static let CTRL_HUM_SPI_3W_INT_EN_LSB: UInt32 = 6
    public static let CTRL_MEAS_REG: UInt32 = 0x74
    public static let CTRL_MEAS_WIDTH: UInt32 = 8
    public static let CTRL_MEAS_ACCESS: StaticString = "read-write"
    public static let CTRL_MEAS_MODE: UInt32 = 0x3
    public static let CTRL_MEAS_MODE_LSB: UInt32 = 0
    public static let CTRL_MEAS_OSRS_P: UInt32 = 0x1C
    public static let CTRL_MEAS_OSRS_P_LSB: UInt32 = 2
    public static let CTRL_MEAS_OSRS_T: UInt32 = 0xE0
    public static let CTRL_MEAS_OSRS_T_LSB: UInt32 = 5
    public static let CONFIG_REG: UInt32 = 0x75
    public static let CONFIG_WIDTH: UInt32 = 8
    public static let CONFIG_ACCESS: StaticString = "read-write"
    public static let CONFIG_SPI_3W_EN: UInt32 = 0x1
    public static let CONFIG_SPI_3W_EN_LSB: UInt32 = 0
    public static let CONFIG_FILTER: UInt32 = 0x1C
    public static let CONFIG_FILTER_LSB: UInt32 = 2
    public static let CTRL_GAS_0_REG: UInt32 = 0x70
    public static let CTRL_GAS_0_WIDTH: UInt32 = 8
    public static let CTRL_GAS_0_ACCESS: StaticString = "read-write"
    public static let CTRL_GAS_0_HEAT_OFF: UInt32 = 0x8
    public static let CTRL_GAS_0_HEAT_OFF_LSB: UInt32 = 3
    public static let CTRL_GAS_1_REG: UInt32 = 0x71
    public static let CTRL_GAS_1_WIDTH: UInt32 = 8
    public static let CTRL_GAS_1_ACCESS: StaticString = "read-write"
    public static let CTRL_GAS_1_NB_CONV: UInt32 = 0xF
    public static let CTRL_GAS_1_NB_CONV_LSB: UInt32 = 0
    public static let CTRL_GAS_1_RUN_GAS: UInt32 = 0x10
    public static let CTRL_GAS_1_RUN_GAS_LSB: UInt32 = 4
    public static let IDAC_HEAT_0_REG: UInt32 = 0x50
    public static let IDAC_HEAT_0_WIDTH: UInt32 = 8
    public static let IDAC_HEAT_0_ACCESS: StaticString = "read-write"
    public static let IDAC_HEAT_0_IDAC_HEAT: UInt32 = 0xFF
    public static let IDAC_HEAT_0_IDAC_HEAT_LSB: UInt32 = 0
    public static let RES_HEAT_0_REG: UInt32 = 0x5A
    public static let RES_HEAT_0_WIDTH: UInt32 = 8
    public static let RES_HEAT_0_ACCESS: StaticString = "read-write"
    public static let RES_HEAT_0_RES_HEAT: UInt32 = 0xFF
    public static let RES_HEAT_0_RES_HEAT_LSB: UInt32 = 0
    public static let GAS_WAIT_0_REG: UInt32 = 0x64
    public static let GAS_WAIT_0_WIDTH: UInt32 = 8
    public static let GAS_WAIT_0_ACCESS: StaticString = "read-write"
    public static let GAS_WAIT_0_GAS_WAIT: UInt32 = 0xFF
    public static let GAS_WAIT_0_GAS_WAIT_LSB: UInt32 = 0
    public static let MEAS_STATUS_0_REG: UInt32 = 0x1D
    public static let MEAS_STATUS_0_WIDTH: UInt32 = 8
    public static let MEAS_STATUS_0_ACCESS: StaticString = "read-only"
    public static let MEAS_STATUS_0_GAS_MEAS_INDEX_0: UInt32 = 0xF
    public static let MEAS_STATUS_0_GAS_MEAS_INDEX_0_LSB: UInt32 = 0
    public static let MEAS_STATUS_0_MEASURING: UInt32 = 0x20
    public static let MEAS_STATUS_0_MEASURING_LSB: UInt32 = 5
    public static let MEAS_STATUS_0_GAS_MEASURING: UInt32 = 0x40
    public static let MEAS_STATUS_0_GAS_MEASURING_LSB: UInt32 = 6
    public static let MEAS_STATUS_0_NEW_DATA_0: UInt32 = 0x80
    public static let MEAS_STATUS_0_NEW_DATA_0_LSB: UInt32 = 7
    public static let PRESS_REG: UInt32 = 0x1F
    public static let PRESS_WIDTH: UInt32 = 24
    public static let PRESS_ACCESS: StaticString = "read-only"
    public static let PRESS_PRESS_XLSB: UInt32 = 0xF0
    public static let PRESS_PRESS_XLSB_LSB: UInt32 = 4
    public static let PRESS_PRESS_LSB: UInt32 = 0xFF00
    public static let PRESS_PRESS_LSB_LSB: UInt32 = 8
    public static let PRESS_PRESS_MSB: UInt32 = 0xFF0000
    public static let PRESS_PRESS_MSB_LSB: UInt32 = 16
    public static let TEMP_REG: UInt32 = 0x22
    public static let TEMP_WIDTH: UInt32 = 24
    public static let TEMP_ACCESS: StaticString = "read-only"
    public static let TEMP_TEMP_XLSB: UInt32 = 0xF0
    public static let TEMP_TEMP_XLSB_LSB: UInt32 = 4
    public static let TEMP_TEMP_LSB: UInt32 = 0xFF00
    public static let TEMP_TEMP_LSB_LSB: UInt32 = 8
    public static let TEMP_TEMP_MSB: UInt32 = 0xFF0000
    public static let TEMP_TEMP_MSB_LSB: UInt32 = 16
    public static let HUM_REG: UInt32 = 0x25
    public static let HUM_WIDTH: UInt32 = 16
    public static let HUM_ACCESS: StaticString = "read-only"
    public static let HUM_HUM_LSB: UInt32 = 0xFF
    public static let HUM_HUM_LSB_LSB: UInt32 = 0
    public static let HUM_HUM_MSB: UInt32 = 0xFF00
    public static let HUM_HUM_MSB_LSB: UInt32 = 8
    public static let GAS_R_REG: UInt32 = 0x2A
    public static let GAS_R_WIDTH: UInt32 = 16
    public static let GAS_R_ACCESS: StaticString = "read-only"
    public static let GAS_R_GAS_RANGE_R: UInt32 = 0xF
    public static let GAS_R_GAS_RANGE_R_LSB: UInt32 = 0
    public static let GAS_R_HEAT_STAB_R: UInt32 = 0x10
    public static let GAS_R_HEAT_STAB_R_LSB: UInt32 = 4
    public static let GAS_R_GAS_VALID_R: UInt32 = 0x20
    public static let GAS_R_GAS_VALID_R_LSB: UInt32 = 5
    public static let GAS_R_GAS_R: UInt32 = 0xFFC0
    public static let GAS_R_GAS_R_LSB: UInt32 = 6

    // encodings: the codes a field takes, as this part reads them.
    public static let OVERSAMPLING_SKIPPED: UInt32 = 0
    public static let OVERSAMPLING_X1: UInt32 = 1
    public static let OVERSAMPLING_X2: UInt32 = 2
    public static let OVERSAMPLING_X4: UInt32 = 3
    public static let OVERSAMPLING_X8: UInt32 = 4
    public static let OVERSAMPLING_X16: UInt32 = 5
    public static let FILTER_COEFF_0: UInt32 = 0
    public static let FILTER_COEFF_1: UInt32 = 1
    public static let FILTER_COEFF_3: UInt32 = 2
    public static let FILTER_COEFF_7: UInt32 = 3
    public static let FILTER_COEFF_15: UInt32 = 4
    public static let FILTER_COEFF_31: UInt32 = 5
    public static let FILTER_COEFF_63: UInt32 = 6
    public static let FILTER_COEFF_127: UInt32 = 7
    public static let RESET_COMMAND_SOFT_RESET: UInt32 = 0xB6
    public static let MODE_SLEEP: UInt32 = 0
    public static let MODE_FORCED: UInt32 = 1

    // measurement: the part holds a whole data block steady for the duration of one burst, so a byte-at-a-time read can mix two conversions.
    public static let BURST_LENGTH: UInt32 = 15
}
