// GENERATED by lamella-bsp-gen from csp/rp2350/blocks/uart.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//
// The rp2350 uart BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2350Instances. Widths are access widths.

public enum Rp2350UartLayout {
    // -- register offsets (block-relative) + access widths --
    public static let UARTDR_OFF: UInt32 = 0x0
    public static let UARTDR_WIDTH: Int32 = 32
    public static let UARTFR_OFF: UInt32 = 0x18
    public static let UARTFR_WIDTH: Int32 = 32
    public static let UARTIBRD_OFF: UInt32 = 0x24
    public static let UARTIBRD_WIDTH: Int32 = 32
    public static let UARTFBRD_OFF: UInt32 = 0x28
    public static let UARTFBRD_WIDTH: Int32 = 32
    public static let UARTLCR_H_OFF: UInt32 = 0x2C
    public static let UARTLCR_H_WIDTH: Int32 = 32
    public static let UARTCR_OFF: UInt32 = 0x30
    public static let UARTCR_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let UARTDR_DATA: UInt32 = 0xFF
    public static let UARTDR_DATA_LSB: UInt32 = 0
    public static let UARTFR_BUSY: UInt32 = 0x8
    public static let UARTFR_BUSY_LSB: UInt32 = 3
    public static let UARTFR_RXFE: UInt32 = 0x10
    public static let UARTFR_RXFE_LSB: UInt32 = 4
    public static let UARTFR_TXFF: UInt32 = 0x20
    public static let UARTFR_TXFF_LSB: UInt32 = 5
    public static let UARTFR_TXFE: UInt32 = 0x80
    public static let UARTFR_TXFE_LSB: UInt32 = 7
    public static let UARTIBRD_BAUD_DIVINT: UInt32 = 0xFFFF
    public static let UARTIBRD_BAUD_DIVINT_LSB: UInt32 = 0
    public static let UARTFBRD_BAUD_DIVFRAC: UInt32 = 0x3F
    public static let UARTFBRD_BAUD_DIVFRAC_LSB: UInt32 = 0
    public static let UARTLCR_H_FEN: UInt32 = 0x10
    public static let UARTLCR_H_FEN_LSB: UInt32 = 4
    public static let UARTLCR_H_WLEN: UInt32 = 0x60
    public static let UARTLCR_H_WLEN_LSB: UInt32 = 5
    public static let UARTLCR_H_STP2: UInt32 = 0x8
    public static let UARTLCR_H_STP2_LSB: UInt32 = 3
    public static let UARTLCR_H_EPS: UInt32 = 0x4
    public static let UARTLCR_H_EPS_LSB: UInt32 = 2
    public static let UARTLCR_H_PEN: UInt32 = 0x2
    public static let UARTLCR_H_PEN_LSB: UInt32 = 1
    public static let UARTLCR_H_SPS: UInt32 = 0x80
    public static let UARTLCR_H_SPS_LSB: UInt32 = 7
    public static let UARTCR_UARTEN: UInt32 = 0x1
    public static let UARTCR_UARTEN_LSB: UInt32 = 0
    public static let UARTCR_LBE: UInt32 = 0x80
    public static let UARTCR_LBE_LSB: UInt32 = 7
    public static let UARTCR_TXE: UInt32 = 0x100
    public static let UARTCR_TXE_LSB: UInt32 = 8
    public static let UARTCR_RXE: UInt32 = 0x200
    public static let UARTCR_RXE_LSB: UInt32 = 9

    // -- block constants --
    public static let FIFO_DEPTH: UInt32 = 32
    public static let WLEN_8BIT: UInt32 = 3
}
