// GENERATED by lamella-bsp-gen from csp/rp2350/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//
// The rp2350 instance map as Swift constants: where each block copy sits and its per-instance ids.

public enum Rp2350Instances {
    public static let XOSC_BASE: UInt32 = 0x40048000
    public static let CLOCKS_BASE: UInt32 = 0x40010000
    public static let RESETS_BASE: UInt32 = 0x40020000
    public static let RESETS_CLR_BASE: UInt32 = 0x40023000
    public static let IO_BANK0_BASE: UInt32 = 0x40028000
    public static let IO_BANK0_RESET_BIT: UInt32 = 6
    public static let IO_BANK0_RESET_MASK: UInt32 = 0x40
    public static let PADS_BANK0_BASE: UInt32 = 0x40038000
    public static let PADS_BANK0_RESET_BIT: UInt32 = 9
    public static let PADS_BANK0_RESET_MASK: UInt32 = 0x200
    public static let SIO_BASE: UInt32 = 0xD0000000
    public static let PLL_SYS_BASE: UInt32 = 0x40050000
    public static let PLL_SYS_RESET_BIT: UInt32 = 14
    public static let PLL_SYS_RESET_MASK: UInt32 = 0x4000
    public static let PLL_USB_BASE: UInt32 = 0x40058000
    public static let PLL_USB_RESET_BIT: UInt32 = 15
    public static let PLL_USB_RESET_MASK: UInt32 = 0x8000
    public static let UART0_BASE: UInt32 = 0x40070000
    public static let UART0_RESET_BIT: UInt32 = 26
    public static let UART0_RESET_MASK: UInt32 = 0x4000000
    public static let UART1_BASE: UInt32 = 0x40078000
    public static let UART1_RESET_BIT: UInt32 = 27
    public static let UART1_RESET_MASK: UInt32 = 0x8000000
    public static let SPI0_BASE: UInt32 = 0x40080000
    public static let SPI0_RESET_BIT: UInt32 = 18
    public static let SPI0_RESET_MASK: UInt32 = 0x40000
    public static let I2C0_BASE: UInt32 = 0x40090000
    public static let I2C0_RESET_BIT: UInt32 = 4
    public static let I2C0_RESET_MASK: UInt32 = 0x10
    public static let ADC_BASE: UInt32 = 0x400A0000
    public static let ADC_RESET_BIT: UInt32 = 0
    public static let ADC_RESET_MASK: UInt32 = 0x1
    public static let TIMER0_BASE: UInt32 = 0x400B0000
    public static let TIMER0_RESET_BIT: UInt32 = 23
    public static let TIMER0_RESET_MASK: UInt32 = 0x800000
    public static let TICKS_BASE: UInt32 = 0x40108000
    public static let TRNG_BASE: UInt32 = 0x400F0000
    public static let TRNG_RESET_BIT: UInt32 = 25
    public static let TRNG_RESET_MASK: UInt32 = 0x2000000
    public static let PWM_BASE: UInt32 = 0x400A8000
    public static let PWM_RESET_BIT: UInt32 = 16
    public static let PWM_RESET_MASK: UInt32 = 0x10000
}
