// GENERATED by lamella-bsp-gen from csp/rp2350/blocks/xosc.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . rp2350
//
// The rp2350 xosc BLOCK layout: offsets are instance-base-relative (`base + *_OFF`);
// instance bases live in Rp2350Instances. Widths are access widths.

public enum Rp2350XoscLayout {
    // -- register offsets (block-relative) + access widths --
    public static let CTRL_OFF: UInt32 = 0x0
    public static let CTRL_WIDTH: Int32 = 32
    public static let STATUS_OFF: UInt32 = 0x4
    public static let STATUS_WIDTH: Int32 = 32
    public static let STARTUP_OFF: UInt32 = 0xC
    public static let STARTUP_WIDTH: Int32 = 32

    // -- fields: <REG>_<FIELD> = the shifted mask; _LSB = the shift --
    public static let CTRL_FREQ_RANGE: UInt32 = 0xFFF
    public static let CTRL_FREQ_RANGE_LSB: UInt32 = 0
    public static let CTRL_ENABLE: UInt32 = 0xFFF000
    public static let CTRL_ENABLE_LSB: UInt32 = 12
    public static let STATUS_STABLE: UInt32 = 0x80000000
    public static let STATUS_STABLE_LSB: UInt32 = 31
    public static let STARTUP_DELAY: UInt32 = 0x3FFF
    public static let STARTUP_DELAY_LSB: UInt32 = 0

    // -- block constants --
    public static let CTRL_ENABLE_MAGIC: UInt32 = 0xFAB
    public static let CTRL_FREQ_RANGE_1_15MHZ: UInt32 = 0xAA0
    public static let STARTUP_DELAY_1MS: UInt32 = 0xC4
}
