// GENERATED by lamella-bsp-gen from csp/esp32c6/instances.toml -- DO NOT EDIT.
// Regenerate: cargo run -p lamella-bsp-gen -- gen-family . esp32c6
//
// The esp32c6 instance map: where each block copy sits and its per-instance ids.
// Layout offsets live in the *Layout classes; wiring lives in the per-board *Bindings.
namespace Lamella.Generated
{
    public sealed class Esp32c6Instances
    {
        private Esp32c6Instances() { }

        public const uint UART0_BASE = 0x60000000;
        public const uint PCR_BASE = 0x60096000;
        public const uint IO_MUX_BASE = 0x60090000;
    }
}
